OSHUN: Array4D_cmplx< T > Class Template Reference
Array4D_cmplx< T > Class Template Reference
#include <lib-array.h>
Public Member Functions
Array4D_cmplx (size_t x, size_t y, size_t z, size_t w)
Array4D_cmplx (const Array4D_cmplx &other)
~Array4D_cmplx ()
size_t dim () const
size_t dim1 () const
size_t dim2 () const
size_t dim3 () const
size_t dim4 () const
valarray< T > & array () const
T & operator[] (size_t i)
T operator[] (size_t i) const
T & real (size_t i, size_t j, size_t k, size_t l)
T real (size_t i, size_t j, size_t k, size_t l) const
T & imag (size_t i, size_t j, size_t k, size_t l)
T imag (size_t i, size_t j, size_t k, size_t l) const
GSlice_iter< T > d1c (size_t b, size_t e)
GSlice_iter< T > d2c (size_t b, size_t e)
GSlice_iter< T > d3c (size_t b, size_t e)
GSlice_iter< T > d4c (size_t b, size_t e)
GSlice_iter< T > SubArray4D (size_t st, size_t nx, size_t ny, size_t nz, size_t nw)
CGSlice_iter< T > d1c (size_t b, size_t e) const
CGSlice_iter< T > d2c (size_t b, size_t e) const
CGSlice_iter< T > d3c (size_t b, size_t e) const
CGSlice_iter< T > d4c (size_t b, size_t e) const
CGSlice_iter< T > SubArray4D (size_t st, size_t nx, size_t ny, size_t nz, size_t nw) const
Array4D_cmplx & operator= (const T &d)
Array4D_cmplx & operator= (const complex< T > &c)
Array4D_cmplx & operator= (const Array4D< T > &other)
Array4D_cmplx & operator= (const Array4D_cmplx &other)
Array4D_cmplx & operator*= (const T &d)
Array4D_cmplx & operator*= (const complex< T > &c)
Array4D_cmplx & operator*= (const Array4D< T > &vmulti)
Array4D_cmplx & operator*= (const Array4D_cmplx &vmulti)
Array4D_cmplx & operator+= (const T &d)
Array4D_cmplx & operator+= (const complex< T > &c)
Array4D_cmplx & operator+= (const Array4D< T > &vadd)
Array4D_cmplx & operator+= (const Array4D_cmplx &vadd)
Array4D_cmplx & operator-= (const T &d)
Array4D_cmplx & operator-= (const complex< T > &c)
Array4D_cmplx & operator-= (const Array4D< T > &vmin)
Array4D_cmplx & operator-= (const Array4D_cmplx &vmin)
Array4D_cmplx & multid1 (const valarray< T > &vmulti)
Array4D_cmplx & multid1 (const valarray< complex< T > > &vmulti)
Array4D_cmplx & multid2 (const valarray< T > &vmulti)
Array4D_cmplx & multid2 (const valarray< complex< T > > &vmulti)
Array4D_cmplx & multid3 (const valarray< T > &vmulti)
Array4D_cmplx & multid3 (const valarray< complex< T > > &vmulti)
Array4D_cmplx & multid4 (const valarray< T > &vmulti)
Array4D_cmplx & multid4 (const valarray< complex< T > > &vmulti)
Array4D_cmplx & multid2d3d4 (const Array3D< T > &vd2d3d4)
Array4D_cmplx & multid2d3d4 (const Array3D_cmplx< T > &vd2d3d4)
Array4D_cmplx & Dd1 ()
Array4D_cmplx & Dd2 ()
Array4D_cmplx & Dd3 ()
Array4D_cmplx & Dd4 ()
Array4D_cmplx & Filterd1 (size_t N)
Private Attributes
valarray< T > * v
size_t d1
size_t d2
size_t d3
size_t d4
size_t td1
size_t td1d2
size_t td1d2d3
Detailed Description
template<class T>
class Array4D_cmplx< T >
Definition at line 2288 of file lib-array.h.
Constructor & Destructor Documentation
Array4D_cmplx() [1/2]
template<class T > Array4D_cmplx< T >::Array4D_cmplx (size_t x, size_t y, size_t z, size_t w)
Definition at line 2387 of file lib-array.h.
References Array4D_cmplx< T >::d1, Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
Referenced by Array4D_cmplx< T >::array().
                                                    : d1(x), d2(y), d3(z), d4(w) {
     v = new valarray<T>(2*d1*d2*d3*d4);
     td1 = 2*d1;
     td1d2 = 2*d1*d2;
     td1d2d3 = 2*d1*d2*d3;
 }
Array4D_cmplx() [2/2]
template<class T > Array4D_cmplx< T >::Array4D_cmplx (const Array4D_cmplx< T > & other)
Definition at line 2394 of file lib-array.h.
References Array4D_cmplx< T >::array(), Array4D_cmplx< T >::d1, Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::dim1(), Array4D_cmplx< T >::dim2(), Array4D_cmplx< T >::dim3(), Array4D_cmplx< T >::dim4(), Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     d1  = other.dim1();
     d2  = other.dim2();
     d3  = other.dim3();
     d4  = other.dim4();
     td1 = 2*d1;
     td1d2 = 2*d1*d2;
     td1d2d3 = 2*d1*d2*d3;
     v = new valarray<T>(2*d1*d2*d3*d4);
     (*v) = other.array();
 }
~Array4D_cmplx()
template<class T > Array4D_cmplx< T >::~Array4D_cmplx ()
Definition at line 2406 of file lib-array.h.
References Array4D_cmplx< T >::v.
{
     delete v;
 }
Member Function Documentation
array()
template<class T > valarray<T>& Array4D_cmplx< T >::array () const inline
Definition at line 2312 of file lib-array.h.
References Array4D_cmplx< T >::Array4D_cmplx(), Array4D< T >::d1c(), Array4D< T >::d2c(), Array4D< T >::d3c(), Array4D< T >::d4c(), Array4D< T >::Dd1(), Array4D< T >::Dd2(), Array4D< T >::Dd3(), Array4D< T >::Dd4(), Array4D< T >::Filterd1(), Array4D< T >::multid1(), Array4D< T >::multid2(), Array4D< T >::multid2d3d4(), Array4D< T >::multid3(), Array4D< T >::multid4(), Array4D< T >::operator*=(), Array4D< T >::operator+=(), Array4D< T >::operator-=(), Array4D< T >::operator=(), Array4D< T >::SubArray4D(), and Array4D< T >::v.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator+=(), Array4D_cmplx< T >::operator-=(), and Array4D_cmplx< T >::operator=().
 {return *v;};
d1c() [1/2]
template<class T > GSlice_iter< T > Array4D_cmplx< T >::d1c (size_t b, size_t e) inline
Definition at line 2443 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(5), str(5);
     str[4] = 1, str[3] = td1; str[2] = td1d2; str[1] = td1d2d3; str[0] = 2;
     sz[4] = 2,  sz[3]  = d2;  sz[2]  = d3;    sz[1]  = d4;       sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(2*b,sz,str));
 }
d1c() [2/2]
template<class T > CGSlice_iter< T > Array4D_cmplx< T >::d1c (size_t b, size_t e) const inline
Definition at line 2451 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(5), str(5);
     str[4] = 1, str[3] = td1; str[2] = td1d2; str[1] = td1d2d3; str[0] = 2;
     sz[4] = 2,  sz[3]  = d2;  sz[2]  = d3;    sz[1]  = d4;       sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(2*b,sz,str));
 }
d2c() [1/2]
template<class T > GSlice_iter< T > Array4D_cmplx< T >::d2c (size_t b, size_t e) inline
Definition at line 2459 of file lib-array.h.
References Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(4), str(4);
     str[3] = 1;  str[2] = td1d2; str[1] = td1d2d3; str[0] = td1;
     sz[3]  = td1; sz[2]  = d3;   sz[1] = d4; sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(b*td1,sz,str));
 }
d2c() [2/2]
template<class T > CGSlice_iter< T > Array4D_cmplx< T >::d2c (size_t b, size_t e) const inline
Definition at line 2467 of file lib-array.h.
References Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(4), str(4);
     str[3] = 1;  str[2] = td1d2; str[1] = td1d2d3; str[0] = td1;
     sz[3]  = td1; sz[2] = d3;    sz[1]  = d4;       sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(b*td1,sz,str));
 }
d3c() [1/2]
template<class T > GSlice_iter< T > Array4D_cmplx< T >::d3c (size_t b, size_t e) inline
Definition at line 2475 of file lib-array.h.
References Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;     str[1] = td1d2d3; str[0] = td1d2;
     sz[2]  = td1d2; sz[1]  = d4;      sz[0]  = e-b+1;
     return GSlice_iter<T>(v,gslice(b*td1d2,sz,str));
 }
d3c() [2/2]
template<class T > CGSlice_iter< T > Array4D_cmplx< T >::d3c (size_t b, size_t e) const inline
Definition at line 2483 of file lib-array.h.
References Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;     str[1] = td1d2d3; str[0] = td1d2;
     sz[2]  = td1d2; sz[1]  = d4;      sz[0]  = e-b+1;
     return CGSlice_iter<T>(v,gslice(b*td1d2,sz,str));
 }
d4c() [1/2]
template<class T > GSlice_iter< T > Array4D_cmplx< T >::d4c (size_t b, size_t e) inline
Definition at line 2491 of file lib-array.h.
References Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1;       str[0] = td1d2d3;
     sz[1]  = td1d2d3; sz[0]  = e-b+1;
     return GSlice_iter<T>(v,gslice(b*td1d2d3,sz,str));
 }
d4c() [2/2]
template<class T > CGSlice_iter< T > Array4D_cmplx< T >::d4c (size_t b, size_t e) const inline
Definition at line 2499 of file lib-array.h.
References Array4D_cmplx< T >::SubArray4D(), Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1;       str[0] = td1d2d3;
     sz[1]  = td1d2d3; sz[0]  = e-b+1;
     return CGSlice_iter<T>(v,gslice(b*td1d2d3,sz,str));
 }
Dd1()
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::Dd1 ()
Definition at line 2789 of file lib-array.h.
References Array4D_cmplx< T >::dim().
{
     for(long i(0); i< 2*dim()-4; ++i) {
         (*v)[i] -= (*v)[i+4];
     }
     for(long i(2*dim()-5); i>-1; --i) {
         (*v)[i+2] = (*v)[i];
     }
     return *this;
 }
Dd2()
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::Dd2 ()
Definition at line 2800 of file lib-array.h.
References Array4D_cmplx< T >::dim(), and Array4D_cmplx< T >::td1.
{
     long twotd1 = 2*td1;
     for(long i(0); i< 2*dim()-twotd1; ++i) {
         (*v)[i] -= (*v)[i+twotd1];
     }
     for(long i(2*dim()-twotd1-1); i>-1; --i) {
         (*v)[i+td1] = (*v)[i];
     }
     return *this;
 }
Dd3()
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::Dd3 ()
Definition at line 2812 of file lib-array.h.
References Array4D_cmplx< T >::dim(), and Array4D_cmplx< T >::td1d2.
{
     long twotd1d2 = 2*td1d2;
     for(long i(0); i< 2*dim()-twotd1d2; ++i) {
         (*v)[i] -= (*v)[i+twotd1d2];
     }
     for(long i(2*dim()-twotd1d2-1); i>-1; --i) {
         (*v)[i+td1d2] = (*v)[i];
     }
     return *this;
 }
Dd4()
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::Dd4 ()
Definition at line 2824 of file lib-array.h.
References Array4D_cmplx< T >::dim(), and Array4D_cmplx< T >::td1d2d3.
{
     long twotd1d2d3 = 2*td1d2d3;
     for(long i(0); i< long(2*dim())-twotd1d2d3; ++i) {
         (*v)[i] -= (*v)[i+twotd1d2d3];
     }
     for(long i(2*dim()-twotd1d2d3-1); i>-1; --i) {
         (*v)[i+td1d2d3] = (*v)[i];
     }
     return *this;
 }
dim()
template<class T > size_t Array4D_cmplx< T >::dim () const inline
Definition at line 2307 of file lib-array.h.
References Array4D< T >::d4.
Referenced by Array4D_cmplx< T >::Dd1(), Array4D_cmplx< T >::Dd2(), Array4D_cmplx< T >::Dd3(), Array4D_cmplx< T >::Dd4(), Array4D_cmplx< T >::multid1(), Array4D_cmplx< T >::multid2(), and Array4D_cmplx< T >::multid3().
 {return d1*d2*d3*d4;}
dim1()
template<class T > size_t Array4D_cmplx< T >::dim1 () const inline
Definition at line 2308 of file lib-array.h.
References Array4D< T >::d1.
Referenced by Array4D_cmplx< T >::Array4D_cmplx().
 {return d1;}
dim2()
template<class T > size_t Array4D_cmplx< T >::dim2 () const inline
Definition at line 2309 of file lib-array.h.
References Array4D< T >::d2.
Referenced by Array4D_cmplx< T >::Array4D_cmplx().
 {return d2;}
dim3()
template<class T > size_t Array4D_cmplx< T >::dim3 () const inline
Definition at line 2310 of file lib-array.h.
References Array4D< T >::d3.
Referenced by Array4D_cmplx< T >::Array4D_cmplx().
 {return d3;}
dim4()
template<class T > size_t Array4D_cmplx< T >::dim4 () const inline
Definition at line 2311 of file lib-array.h.
References Array4D< T >::d4.
Referenced by Array4D_cmplx< T >::Array4D_cmplx().
 {return d4;}
Filterd1()
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::Filterd1 (size_t N)
Definition at line 2837 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, and Array4D_cmplx< T >::td1.
{
     for (size_t j(0); j < d2*d3*d4; ++j ){
         for (size_t i(j*td1); i< j*td1+2*N; ++i ){
             (*v)[i] = 0.0;
         }
     }
     return *this;
 }
imag() [1/2]
template<class T > T & Array4D_cmplx< T >::imag (size_t i, size_t j, size_t k, size_t l) inline
Definition at line 2430 of file lib-array.h.
References Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
Referenced by Array4D_cmplx< T >::multid1(), Array4D_cmplx< T >::multid2(), Array4D_cmplx< T >::multid3(), and Array4D_cmplx< T >::multid4().
{
     return (*v)[2*i+1+j*td1+k*td1d2+l*td1d2d3];
 }
imag() [2/2]
template<class T > T Array4D_cmplx< T >::imag (size_t i, size_t j, size_t k, size_t l) const inline
Definition at line 2434 of file lib-array.h.
References Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     return (*v)[2*i+1+j*td1+k*td1d2+l*td1d2d3];
 }
multid1() [1/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid1 (const valarray< T > & vmulti)
Definition at line 2659 of file lib-array.h.
References Array4D_cmplx< T >::d1, Array4D_cmplx< T >::dim(), and Array4D_cmplx< T >::td1.
{
     for (size_t j(0); j< 2*dim(); j+= td1 ){
         for (size_t i(0); i< d1; ++i ){
             (*v)[2*i+j]   *= vmulti[i];
             (*v)[2*i+1+j] *= vmulti[i];
         }
     }
     return *this;
 }
multid1() [2/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid1 (const valarray< complex< T > > & vmulti)
Definition at line 2669 of file lib-array.h.
References Array4D_cmplx< T >::d1, Array4D_cmplx< T >::dim(), Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::td1, and Array4D_cmplx< T >::v.
{
     for (size_t j(0); j< 2*dim(); j+=td1 ){
         for (size_t i(0); i< d1; ++i ){
             T vi((*v)[2*i+j]*vmulti[i].imag());
             (*v)[2*i+j]    *= vmulti[i].real();                     // v[i]   = Aa
             (*v)[2*i+j]    -= (*v)[2*i+1+j] * vmulti[i].imag();     // v[i]   = Aa - Bb
             (*v)[2*i+1+j]  *= vmulti[i].real();                     // v[i+1] = Ba
             (*v)[2*i+1+j]  += vi;                       // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
multid2() [1/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid2 (const valarray< T > & vmulti)
Definition at line 2683 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::dim(), and Array4D_cmplx< T >::td1.
{
     for (size_t k(0); k< 2*dim(); k+=td1*d2 ) {
         for (size_t j(0); j< d2; ++j ) {
             for (size_t i(j*td1); i< (j+1)*td1; ++i ){
                 (*v)[i+k] *= vmulti[j];
             }
         }
     }
     return *this;
 }
multid2() [2/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid2 (const valarray< complex< T > > & vmulti)
Definition at line 2694 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::dim(), Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::td1, and Array4D_cmplx< T >::v.
{
     for (size_t k(0); k< 2*dim(); k+=td1*d2 ) {
         for (size_t j(0); j< d2; ++j ) {
             for (size_t i(j*td1); i< (j+1)*td1; i+=2 ){
                 T vi((*v)[i+k]* vmulti[j].imag());
                 (*v)[i+k]    *= vmulti[j].real();                 // v[i]   = Aa
                 (*v)[i+k]    -= (*v)[i+k+1] * vmulti[j].imag();   // v[i]   = Aa - Bb
                 (*v)[i+k+1]  *= vmulti[j].real();                 // v[i+1] = Ba
                 (*v)[i+k+1]  += vi;                        // v[i+1] = Ba + Ab
             }
         }
     }
     return *this;
 }
multid2d3d4() [1/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid2d3d4 (const Array3D< T > & vd2d3d4)
Definition at line 2761 of file lib-array.h.
References Array3D< T >::array(), Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, and Array4D_cmplx< T >::td1.
{
     for (size_t j(0); j < d2*d3*d4; ++j ){
         for (size_t i(j*td1); i< (j+1)*td1; ++i ){
             (*v)[i] *= vd2d3d4.array()[j];
         }
     }
     return *this;
 }
multid2d3d4() [2/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid2d3d4 (const Array3D_cmplx< T > & vd2d3d4)
Definition at line 2772 of file lib-array.h.
References Array3D_cmplx< T >::array(), Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1, and Array4D_cmplx< T >::v.
{
     for (size_t j(0); j < d2*d3*d4; ++j ){
         for (size_t i(j*td1); i< (j+1)*td1; i+=2 ){
             T vi((*v)[i]*vd2d3d4.array()[2*j+1]);
             (*v)[i]    *= vd2d3d4.array()[2*j];               // v[i]   = Aa
             (*v)[i]    -= (*v)[i+1]*vd2d3d4.array()[2*j+1];   // v[i]   = Aa - Bb
             (*v)[i+1]  *= vd2d3d4.array()[2*j];               // v[i+1] = Ba
             (*v)[i+1]  += vi;                              // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
multid3() [1/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid3 (const valarray< T > & vmulti)
Definition at line 2710 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::dim(), and Array4D_cmplx< T >::td1.
{
     for (size_t l(0); l< 2*dim(); l+=td1*d2*d3) {
         for (size_t k(0); k< d3; ++k) {
             for (size_t i(k*td1*d2); i< (k+1)*td1*d2; ++i ){
                 (*v)[i+l] *= vmulti[k];
             }
         }
     }
     return *this;
 }
multid3() [2/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid3 (const valarray< complex< T > > & vmulti)
Definition at line 2721 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::dim(), Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::td1, and Array4D_cmplx< T >::v.
{
     for (size_t l(0); l< 2*dim(); l+=td1*d2*d3) {
         for (size_t k(0); k< d3; ++k) {
             for (size_t i(k*td1*d2); i< (k+1)*td1*d2; i+=2 ){
                 T vi((*v)[i+l]* vmulti[k].imag());
                 (*v)[i+l]    *= vmulti[k].real();                 // v[i]   = Aa
                 (*v)[i+l]    -= (*v)[i+l+1] * vmulti[k].imag();   // v[i]   = Aa - Bb
                 (*v)[i+l+1]  *= vmulti[k].real();                 // v[i+1] = Ba
                 (*v)[i+l+1]  += vi;                       // v[i+1] = Ba + Ab
             }
         }
     }
     return *this;
 }
multid4() [1/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid4 (const valarray< T > & vmulti)
Definition at line 2737 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, and Array4D_cmplx< T >::td1.
{
     for (size_t k(0); k< d4; ++k) {
         for (size_t i(k*td1*d2*d3); i< (k+1)*td1*d2*d3; ++i ){
             (*v)[i] *= vmulti[k];
         }
     }
     return *this;
 }
multid4() [2/2]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::multid4 (const valarray< complex< T > > & vmulti)
Definition at line 2746 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::td1, and Array4D_cmplx< T >::v.
{
     for (size_t k(0); k< d4; ++k) {
         for (size_t i(k*td1*d2*d3); i< (k+1)*td1*d2*d3; i+=2 ){
             T vi((*v)[i]* vmulti[k].imag());
             (*v)[i]    *= vmulti[k].real();               // v[i]   = Aa
             (*v)[i]    -= (*v)[i+1] * vmulti[k].imag();   // v[i]   = Aa - Bb
             (*v)[i+1]  *= vmulti[k].real();               // v[i+1] = Ba
             (*v)[i+1]  += vi;                          // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
operator*=() [1/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator*= (const T & d)
Definition at line 2562 of file lib-array.h.
{
     (*v) *=d;
     return *this;
 }
operator*=() [2/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator*= (const complex< T > & c)
Definition at line 2567 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::real(), Array4D_cmplx< T >::td1, and Array4D_cmplx< T >::v.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {            // suppose v[i]+iv[i+1]=A+iB,   c=a+ib
         T vi((*v)[i]*c.imag());
         (*v)[i]    *= c.real();                     // v[i]   = Aa
         (*v)[i]    -= (*v)[i+1]*c.imag();           // v[i]   = Aa - Bb
         (*v)[i+1]  *= c.real();                     // v[i+1] = Ba
         (*v)[i+1]  += vi;                           // v[i+1] = Ba + Ab
     }
     return *this;
 }
operator*=() [3/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator*= (const Array4D< T > & vmulti)
Definition at line 2578 of file lib-array.h.
References Array4D< T >::array(), Array4D_cmplx< T >::d1, Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, and Array4D_cmplx< T >::d4.
{
     for (size_t i(0); i< d1*d2*d3*d4; ++i) {
         (*v)[2*i]   *= vmulti.array()[i];
         (*v)[2*i+1] *= vmulti.array()[i];
     }
     return *this;
 }
operator*=() [4/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator*= (const Array4D_cmplx< T > & vmulti)
Definition at line 2586 of file lib-array.h.
References Array4D_cmplx< T >::array(), Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::td1, and Array4D_cmplx< T >::v.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {            // suppose v[i]+iv[i+1]=A+iB,   vmulti[i] + ivmulti[i+1] = a+ib
         T vi((*v)[i] * vmulti.array()[i+1]);
         (*v)[i]    *=  vmulti.array()[i];              // v[i]   = Aa
         (*v)[i]    -= (*v)[i+1]*vmulti.array()[i+1];   // v[i]   = Aa - Bb
         (*v)[i+1]  *= vmulti.array()[i];               // v[i+1] = Ba
         (*v)[i+1]  += vi;                              // v[i+1] = Ba + Ab
     }
     return *this;
 }
operator+=() [1/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator+= (const T & d)
Definition at line 2599 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, and Array4D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {
         (*v)[i] +=d;
     }
     return *this;
 }
operator+=() [2/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator+= (const complex< T > & c)
Definition at line 2606 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::real(), and Array4D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {
         (*v)[i]   +=c.real();
         (*v)[i+1] +=c.imag();
     }
     return *this;
 }
operator+=() [3/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator+= (const Array4D< T > & vadd)
Definition at line 2614 of file lib-array.h.
References Array4D< T >::array(), Array4D_cmplx< T >::d1, Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, and Array4D_cmplx< T >::d4.
{
     for (size_t i(0); i< d1*d2*d3*d4; ++i) {
         (*v)[2*i]   += vadd.array()[i];
     }
     return *this;
 }
operator+=() [4/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator+= (const Array4D_cmplx< T > & vadd)
Definition at line 2621 of file lib-array.h.
References Array4D_cmplx< T >::array().
{
     (*v) += vadd.array();
     return *this;
 }
operator-=() [1/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator-= (const T & d)
Definition at line 2628 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, and Array4D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {
         (*v)[i] -=d;
     }
     return *this;
 }
operator-=() [2/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator-= (const complex< T > & c)
Definition at line 2635 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::real(), and Array4D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {
         (*v)[i]   -=c.real();
         (*v)[i+1] -=c.imag();
     }
     return *this;
 }
operator-=() [3/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator-= (const Array4D< T > & vmin)
Definition at line 2643 of file lib-array.h.
References Array4D< T >::array(), Array4D_cmplx< T >::d1, Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, and Array4D_cmplx< T >::d4.
{
     for (size_t i(0); i< d1*d2*d3*d4; ++i) {
         (*v)[2*i]   -= vmin.array()[i];
     }
     return *this;
 }
operator-=() [4/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator-= (const Array4D_cmplx< T > & vmin)
Definition at line 2650 of file lib-array.h.
References Array4D_cmplx< T >::array().
{
     (*v) -= vmin.array();
     return *this;
 }
operator=() [1/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator= (const T & d)
Definition at line 2532 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, and Array4D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {
         (*v)[i] = d;
         (*v)[i+1] = 0.0;
     }
     return *this;
 }
operator=() [2/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator= (const complex< T > & c)
Definition at line 2539 of file lib-array.h.
References Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, Array4D_cmplx< T >::d4, Array4D_cmplx< T >::real(), and Array4D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3*d4; i+=2) {
         (*v)[i]   =c.real();
         (*v)[i+1] =c.imag();
     }
     return *this;
 }
operator=() [3/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator= (const Array4D< T > & other)
Definition at line 2546 of file lib-array.h.
References Array4D< T >::array(), Array4D_cmplx< T >::d1, Array4D_cmplx< T >::d2, Array4D_cmplx< T >::d3, and Array4D_cmplx< T >::d4.
{
     for (size_t i(0); i< d1*d2*d3*d4; ++i) {
         (*v)[2*i]   = other.array()[i];
         (*v)[2*i+1] = 0.0;
     }
     return *this;
 }
operator=() [4/4]
template<class T > Array4D_cmplx< T > & Array4D_cmplx< T >::operator= (const Array4D_cmplx< T > & other)
Definition at line 2553 of file lib-array.h.
References Array4D_cmplx< T >::array().
{
     if (this != &other) {   //self-assignment
         (*v) = other.array();
     }
     return *this;
 }
operator[]() [1/2]
template<class T > T & Array4D_cmplx< T >::operator[] (size_t i) inline
Definition at line 2414 of file lib-array.h.
References Array4D_cmplx< T >::v.
{
     return (*v)[i];
 }
operator[]() [2/2]
template<class T > T Array4D_cmplx< T >::operator[] (size_t i) const inline
Definition at line 2418 of file lib-array.h.
References Array4D_cmplx< T >::v.
{
     return (*v)[i];
 }
real() [1/2]
template<class T > T & Array4D_cmplx< T >::real (size_t i, size_t j, size_t k, size_t l) inline
Definition at line 2422 of file lib-array.h.
References Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
Referenced by Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator+=(), Array4D_cmplx< T >::operator-=(), and Array4D_cmplx< T >::operator=().
{
     return (*v)[2*i+j*td1+k*td1d2+l*td1d2d3];
 }
real() [2/2]
template<class T > T Array4D_cmplx< T >::real (size_t i, size_t j, size_t k, size_t l) const inline
Definition at line 2426 of file lib-array.h.
References Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     return (*v)[2*i+j*td1+k*td1d2+l*td1d2d3];
 }
SubArray4D() [1/2]
template<class T > GSlice_iter< T > Array4D_cmplx< T >::SubArray4D (size_t st, size_t nx, size_t ny, size_t nz, size_t nw) inline
Definition at line 2511 of file lib-array.h.
References Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
Referenced by Array4D_cmplx< T >::d4c().
{
     valarray<size_t> sz(4), str(4);
     str[3] = 1;   str[2] = td1;  str[1] = td1d2; str[0] = td1d2d3;
     sz[3]  = 2*nx;  sz[2]  = ny;  sz[1]  = nz;   sz[0]  = nw;
     return GSlice_iter<T>(v,gslice(2*st,sz,str));
 }
SubArray4D() [2/2]
template<class T > CGSlice_iter< T > Array4D_cmplx< T >::SubArray4D (size_t st, size_t nx, size_t ny, size_t nz, size_t nw) const inline
Definition at line 2521 of file lib-array.h.
References Array4D_cmplx< T >::td1, Array4D_cmplx< T >::td1d2, Array4D_cmplx< T >::td1d2d3, and Array4D_cmplx< T >::v.
{
     valarray<size_t> sz(4), str(4);
     str[3] = 1;   str[2] = td1;  str[1] = td1d2; str[0] = td1d2d3;
     sz[3]  = 2*nx;  sz[2]  = ny;  sz[1]  = nz;   sz[0]  = nw;
     return CGSlice_iter<T>(v,gslice(2*st,sz,str));
 }
Field Documentation
d1
template<class T > size_t Array4D_cmplx< T >::d1 private
Definition at line 2295 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::multid1(), Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator+=(), Array4D_cmplx< T >::operator-=(), and Array4D_cmplx< T >::operator=().
d2
template<class T > size_t Array4D_cmplx< T >::d2 private
Definition at line 2295 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::d1c(), Array4D_cmplx< T >::Filterd1(), Array4D_cmplx< T >::multid2(), Array4D_cmplx< T >::multid2d3d4(), Array4D_cmplx< T >::multid3(), Array4D_cmplx< T >::multid4(), Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator+=(), Array4D_cmplx< T >::operator-=(), and Array4D_cmplx< T >::operator=().
d3
template<class T > size_t Array4D_cmplx< T >::d3 private
Definition at line 2295 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::d1c(), Array4D_cmplx< T >::d2c(), Array4D_cmplx< T >::Filterd1(), Array4D_cmplx< T >::multid2d3d4(), Array4D_cmplx< T >::multid3(), Array4D_cmplx< T >::multid4(), Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator+=(), Array4D_cmplx< T >::operator-=(), and Array4D_cmplx< T >::operator=().
d4
template<class T > size_t Array4D_cmplx< T >::d4 private
Definition at line 2295 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::d1c(), Array4D_cmplx< T >::d2c(), Array4D_cmplx< T >::d3c(), Array4D_cmplx< T >::Filterd1(), Array4D_cmplx< T >::multid2d3d4(), Array4D_cmplx< T >::multid4(), Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator+=(), Array4D_cmplx< T >::operator-=(), and Array4D_cmplx< T >::operator=().
td1
template<class T > size_t Array4D_cmplx< T >::td1 private
Definition at line 2296 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::d1c(), Array4D_cmplx< T >::d2c(), Array4D_cmplx< T >::Dd2(), Array4D_cmplx< T >::Filterd1(), Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::multid1(), Array4D_cmplx< T >::multid2(), Array4D_cmplx< T >::multid2d3d4(), Array4D_cmplx< T >::multid3(), Array4D_cmplx< T >::multid4(), Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator+=(), Array4D_cmplx< T >::operator-=(), Array4D_cmplx< T >::operator=(), Array4D_cmplx< T >::real(), and Array4D_cmplx< T >::SubArray4D().
td1d2
template<class T > size_t Array4D_cmplx< T >::td1d2 private
Definition at line 2297 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::d1c(), Array4D_cmplx< T >::d2c(), Array4D_cmplx< T >::d3c(), Array4D_cmplx< T >::Dd3(), Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::real(), and Array4D_cmplx< T >::SubArray4D().
td1d2d3
template<class T > size_t Array4D_cmplx< T >::td1d2d3 private
Definition at line 2298 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::d1c(), Array4D_cmplx< T >::d2c(), Array4D_cmplx< T >::d3c(), Array4D_cmplx< T >::d4c(), Array4D_cmplx< T >::Dd4(), Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::real(), and Array4D_cmplx< T >::SubArray4D().
v
template<class T > valarray<T>* Array4D_cmplx< T >::v private
Definition at line 2294 of file lib-array.h.
Referenced by Array4D_cmplx< T >::Array4D_cmplx(), Array4D_cmplx< T >::d1c(), Array4D_cmplx< T >::d2c(), Array4D_cmplx< T >::d3c(), Array4D_cmplx< T >::d4c(), Array4D_cmplx< T >::imag(), Array4D_cmplx< T >::multid1(), Array4D_cmplx< T >::multid2(), Array4D_cmplx< T >::multid2d3d4(), Array4D_cmplx< T >::multid3(), Array4D_cmplx< T >::multid4(), Array4D_cmplx< T >::operator*=(), Array4D_cmplx< T >::operator[](), Array4D_cmplx< T >::real(), Array4D_cmplx< T >::SubArray4D(), and Array4D_cmplx< T >::~Array4D_cmplx().
The documentation for this class was generated from the following file:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/lib-array.h