OSHUN: Export_Files Namespace Reference
Export_Files Namespace Reference
Namespaces
ofconventions
Data Structures
class DefaultTags
class Header
class oAxis
class Restart_Facility
class Xport
Functions
template<typename T >
std::string stringify (T const &x)
int Makefolder (string _name)
void Folders ()
template<class T >
ofstream & operator<< (ofstream &s, const vector< T > &v)
template<class T >
ofstream & operator<< (ofstream &s, const valarray< T > &v)
template<class T >
ofstream & operator<< (ofstream &s, const Array2D< T > &array2D)
template<class T >
ofstream & operator<< (ofstream &s, const Array3D< T > &array3D)
Function Documentation
Folders()
void Export_Files::Folders ()
Definition at line 74 of file export.cpp.
References Input::List(), and Makefolder().
Referenced by main(), and stringify().
{
 //--------------------------------------------------------------
 //   create the directory tree
 //--------------------------------------------------------------
     if (Makefolder("RESTART") != 0) cout << "Warning: Folder 'RESTART' exists" << endl;
     if (Makefolder("OUTPUT") != 0) cout << "Warning: Folder 'OUTPUT' exists" << endl;
     if ( Input::List().o_EHist ) {
         if ( Makefolder("OUTPUT/NUM") != 0) cout << "Warning: Folder 'OUTPUT/NUM' exists" << endl;
     }
     if ( Input::List().o_Ex ||  Input::List().o_Ey || Input::List().o_Ez ||
          Input::List().o_Bx ||  Input::List().o_By || Input::List().o_Bz )  {
         if (Makefolder("OUTPUT/FLD") != 0)
             cout<<"Warning: Folder 'OUTPUT/FLD' exists" << endl;
         if (Input::List().o_Ex) {
             if (Makefolder("OUTPUT/FLD/Ex") != 0)
                 cout<<"Warning: Folder 'OUTPUT/FLD/EX' exists" << endl;
         }
         if (Input::List().o_Ey) {
             if (Makefolder("OUTPUT/FLD/Ey") != 0)
                 cout<<"Warning: Folder 'OUTPUT/FLD/EY' exists" << endl;
         }
         if (Input::List().o_Ez) {
             if (Makefolder("OUTPUT/FLD/Ez") != 0)
                 cout<<"Warning: Folder 'OUTPUT/FLD/EZ' exists" << endl;
         }
         if (Input::List().o_Bx) {
             if (Makefolder("OUTPUT/FLD/Bx") != 0)
                 cout<<"Warning: Folder 'OUTPUT/FLD/BX' exists" << endl;
         }
         if (Input::List().o_By) {
             if (Makefolder("OUTPUT/FLD/By") != 0)
                 cout<<"Warning: Folder 'OUTPUT/FLD/BY' exists" << endl;
         }
         if (Input::List().o_Bz) {
             if (Makefolder("OUTPUT/FLD/Bz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/FLD/BZ' exists" << endl;
         }
     }
     if ( Input::List().o_x1x2 ||  Input::List().o_pth ||
          Input::List().o_G  ||
          Input::List().o_Px || Input::List().o_PxPx ||
          Input::List().o_Py || Input::List().o_PxPy || Input::List().o_PyPy ||
          Input::List().o_Pz || Input::List().o_PxPz || Input::List().o_PyPz || Input::List().o_PzPz ||
          Input::List().o_Vx || Input::List().o_VxVx ||
          Input::List().o_Vy || Input::List().o_VxVy || Input::List().o_VyVy ||
          Input::List().o_VxVz || Input::List().o_VyVz || Input::List().o_VzVz ||
          Input::List().o_Vsq || Input::List().o_Temperature || Input::List().o_Pressure ||
          Input::List().o_Qx || Input::List().o_Qy || Input::List().o_Qz ||
          Input::List().o_p1x1 )  {
         if (Makefolder("OUTPUT/MOM") != 0)
             cout<<"Warning: Folder 'OUTPUT/MOM' exists" << endl;
 //          Relativistic Energy - Momentum Tensor
 //          - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - -
         if (Input::List().o_x1x2) {
             if (Makefolder("OUTPUT/MOM/n") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/N' exists" << endl;
         }
         if (Input::List().o_pth) {
             if (Makefolder("OUTPUT/MOM/Pth") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Pth' exists" << endl;
         }
         if (Input::List().o_G) {
             if (Makefolder("OUTPUT/MOM/Gam") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Gam' exists" << endl;
         }
         if (Input::List().o_Px) {
             if (Makefolder("OUTPUT/MOM/Px") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Px' exists" << endl;
         }
         if (Input::List().o_PxPx) {
             if (Makefolder("OUTPUT/MOM/PxPx") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/PxPx' exists" << endl;
         }
         if (Input::List().o_Py) {
             if (Makefolder("OUTPUT/MOM/Py") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Py' exists" << endl;
         }
         if (Input::List().o_PxPy) {
             if (Makefolder("OUTPUT/MOM/PxPy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/PxPy' exists" << endl;
         }
         if (Input::List().o_PyPy) {
             if (Makefolder("OUTPUT/MOM/PyPy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/PyPy' exists" << endl;
         }
         if (Input::List().o_Pz) {
             if (Makefolder("OUTPUT/MOM/Pz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Pz' exists" << endl;
         }
         if (Input::List().o_PxPz) {
             if (Makefolder("OUTPUT/MOM/PxPz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/PxPz' exists" << endl;
         }
         if (Input::List().o_PyPz) {
             if (Makefolder("OUTPUT/MOM/PyPz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/PyPz' exists" << endl;
         }
         if (Input::List().o_PzPz) {
             if (Makefolder("OUTPUT/MOM/PzPz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/PzPz' exists"  << endl;
         }
 //          Current
 //          - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - -
         if (Input::List().o_Jx) {
             if (Makefolder("OUTPUT/MOM/Jx") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Jx' exists" << endl;
         }
         if (Input::List().o_Jy) {
             if (Makefolder("OUTPUT/MOM/Jy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Jy' exists" << endl;
         }
         if (Input::List().o_Jz) {
             if (Makefolder("OUTPUT/MOM/Jz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Jz' exists" << endl;
         }
 //          Nonrelativistic output
 //          - - - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - -
         if (Input::List().o_Vx) {
             if (Makefolder("OUTPUT/MOM/Vx") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Vx' exists" << endl;
         }
         if (Input::List().o_VxVx) {
             if (Makefolder("OUTPUT/MOM/VxVx") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/VxVx' exists" << endl;
         }
         if (Input::List().o_Vy) {
             if (Makefolder("OUTPUT/MOM/Vy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Vy' exists" << endl;
         }
         if (Input::List().o_VxVy) {
             if (Makefolder("OUTPUT/MOM/VxVy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/VxVy' exists" << endl;
         }
         if (Input::List().o_VyVy) {
             if (Makefolder("OUTPUT/MOM/VyVy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/VyVy' exists" << endl;
         }
         if (Input::List().o_VxVz) {
             if (Makefolder("OUTPUT/MOM/VxVz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/VxVz' exists" << endl;
         }
         if (Input::List().o_VyVz) {
             if (Makefolder("OUTPUT/MOM/VyVz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/VyVz' exists" << endl;
         }
         if (Input::List().o_VzVz) {
             if (Makefolder("OUTPUT/MOM/VzVz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/VzVz' exists" << endl;
         }
         if (Input::List().o_Vsq) {
             if (Makefolder("OUTPUT/MOM/Vsq") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Vsq' exists" << endl;
         }
         if (Input::List().o_Temperature) {
 //                 if (Makefolder("OUTPUT/MOM/T_eV") != 0)
 //                     cout<<"Warning: Folder 'OUTPUT/MOM/T_eV' exists" << endl;
             if (Makefolder("OUTPUT/MOM/T") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/T' exists" << endl;
         }
         if (Input::List().o_Pressure) {
             if (Makefolder("OUTPUT/MOM/P_Mbar") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/P_Mbar' exists" << endl;
         }
         if (Input::List().o_ND) {
             if (Makefolder("OUTPUT/MOM/ND") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/ND' exists" << endl;
         }
         if (Input::List().o_Nu) {
             if (Makefolder("OUTPUT/MOM/Nu") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Nu' exists" << endl;
         }
         if (Input::List().o_Qx) {
             if (Makefolder("OUTPUT/MOM/Qx") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Qx' exists" << endl;
         }
         if (Input::List().o_Qy) {
             if (Makefolder("OUTPUT/MOM/Qy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Qy' exists" << endl;
         }
         if (Input::List().o_Qz) {
             if (Makefolder("OUTPUT/MOM/Qz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Qz' exists" << endl;
         }
         if (Input::List().o_vNx) {
             if (Makefolder("OUTPUT/MOM/vNx") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/vNx' exists" << endl;
         }
         if (Input::List().o_vNy) {
             if (Makefolder("OUTPUT/MOM/vNy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/vNy' exists" << endl;
         }
         if (Input::List().o_vNz) {
             if (Makefolder("OUTPUT/MOM/vNz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/vNz' exists" << endl;
         }
         if (Input::List().o_Ux) {
             if (Makefolder("OUTPUT/MOM/Ux") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Ux' exists" << endl;
         }
         if (Input::List().o_Uy) {
             if (Makefolder("OUTPUT/MOM/Uy") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Uy' exists" << endl;
         }
         if (Input::List().o_Uz) {
             if (Makefolder("OUTPUT/MOM/Uz") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Ux' exists" << endl;
         }
         if (Input::List().o_Z) {
             if (Makefolder("OUTPUT/MOM/Z") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Z' exists" << endl;
         }
         if (Input::List().o_ni) {
             if (Makefolder("OUTPUT/MOM/ni") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/ni' exists" << endl;
         }
         if (Input::List().o_Ti) {
             if (Makefolder("OUTPUT/MOM/Ti") != 0)
                 cout<<"Warning: Folder 'OUTPUT/MOM/Ti' exists" << endl;
         }
 //><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><
 //      TWO STREAM STUFF
 //><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><
 //            if (Input::List().o_p1x1) {
 //                if (Makefolder("OUTPUT/MOM/p1x1") != 0)
 //                    cout<<"Warning: Folder 'OUTPUT/MOM/p1x1' exists\n";
 //            }
 //><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><-><
     }
     if ( Input::List().o_f0x1 || Input::List().o_p1x1
         ||  Input::List().o_f10x1 ||  Input::List().o_f11x1 ||  Input::List().o_f20x1
         || Input::List().o_fl0x1) {
         if (Makefolder("OUTPUT/DISTR") != 0)
             cout<<"Warning: Folder 'OUTPUT/DISTR' exists" << endl;
     }
 }
Makefolder()
int Export_Files::Makefolder (string _name)
Definition at line 51 of file export.cpp.
Referenced by Folders(), Export_Files::Restart_Facility::Restart_Facility(), stringify(), and Export_Files::Xport::Xport().
{
     mode_t _permissions(S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH);
     // char*   foldername = new char [_name.length() + 1];
     const char*   foldername = _name.data();
     // strcpy(foldername, _name.c_str());
     // vector<char> foldername(_name.c_str(), _name.c_str() + _name.size() + 1);
     int   status(mkdir(foldername,_permissions));
     // if (status != 0) cout << "Warning: Folder "<< _name<< " exists\n";
     // delete[] foldername;
     return status;
 }
operator<<() [1/4]
template<class T > ofstream& Export_Files::operator<< (ofstream & s, const vector< T > & v)
Definition at line 62 of file export.h.
References Export_Files::ofconventions::ofile_precision.
{
         s << setprecision(ofconventions::ofile_precision);
         s << 1 <<"\n";
         s << v.size()<<"\n";
         for (size_t i(0); i < v.size(); ++i) {
             s << v[i]<<"\n";
         }
         return s;
     }
operator<<() [2/4]
template<class T > ofstream& Export_Files::operator<< (ofstream & s, const valarray< T > & v)
Definition at line 73 of file export.h.
References Export_Files::ofconventions::ofile_precision.
{
         s << setprecision(ofconventions::ofile_precision);
         s << 1 <<"\n";
         s << v.size()<<"\n";
         for (size_t i(0); i < v.size(); ++i) {
             s << v[i]<<"\n";
         }
         return s;
     }
operator<<() [3/4]
template<class T > ofstream& Export_Files::operator<< (ofstream & s, const Array2D< T > & array2D)
Definition at line 84 of file export.h.
References Export_Files::ofconventions::ofile_precision.
{
         s << setprecision(ofconventions::ofile_precision);
         s << 2 <<"\n";
         s << array2D.dim1()<<"\n";
         s << array2D.dim2()<<"\n";
         for (size_t i(0); i < array2D.dim(); ++i) {
             s << array2D(i)<<"\n";
         }
         return s;
     }
operator<<() [4/4]
template<class T > ofstream& Export_Files::operator<< (ofstream & s, const Array3D< T > & array3D)
Definition at line 96 of file export.h.
References Export_Files::ofconventions::ofile_precision.
{
         s << setprecision(ofconventions::ofile_precision);
         s << 3 <<"\n";
         s << array3D.dim1()<<"\n";
         s << array3D.dim2()<<"\n";
         s << array3D.dim3()<<"\n";
         for (size_t i(0); i < array3D.dim(); ++i) {
             s << array3D(i)<<"\n";
         }
         return s;
     }
stringify()
template<typename T > std::string Export_Files::stringify (T const & x) inline
Definition at line 30 of file export.h.
References Folders(), and Makefolder().
Referenced by Export_Files::Xport::oH5Fextension(), Export_Files::Restart_Facility::rFextension(), and Export_Files::Xport::Xport().
{
         std::ostringstream out;
         out << x;
         return out.str();
     }