OSHUN: InverseBremsstrahlung Class Reference
InverseBremsstrahlung Class Reference
#include <laser.h>
Public Member Functions
InverseBremsstrahlung (double pmax, size_t nump, size_t numx, int tout_start, const valarray< double > &grid)
void loop (SHarmonic1D &f0, valarray< double > &Zarray, const double &tnew)
int IBSOURCE () const
Data Fields
valarray< double > U2
valarray< double > U2m1
Private Attributes
double t
double tout
valarray< double > fc
RK4_IB rk4_ib
valarray< double > vr
int InvBremsstrahlung
int Nbc
int szx
int szy
valarray< double > IL_xprofile
const double vos
const double omega_0
const double omega_p
const double w0overwp
Detailed Description
Definition at line 99 of file laser.h.
Constructor & Destructor Documentation
InverseBremsstrahlung()
InverseBremsstrahlung::InverseBremsstrahlung (double pmax, size_t nump, size_t numx, int tout_start, const valarray< double > & grid)
Definition at line 297 of file laser.cpp.
References Input::Input_List::BoundaryCells, IL_xprofile, InvBremsstrahlung, Input::List(), Nbc, Input::Input_List::NxLocal, Setup_Y::parseprofile(), szx, U2, U2m1, and vr.
         :t(static_cast<double>(tout_start) *
            Input::List().t_stop / Input::List().n_outsteps),         // Initialize time = tout_start * dt_out
          tout(t + Input::List().t_stop / Input::List().n_outsteps),  // Initialize tout = time + dt_out
          fc(0.0, nump),
          rk4_ib(fc, pmax, tout_start),
          vr(Algorithms::MakeCAxis(0.0,pmax,nump)),
 //        vr(Algorithms::MakeAxis(pmax/(2.0*nump-1.0),pmax,nump)),
 //       ------------------------
          InvBremsstrahlung(Input::List().inverse_bremsstrahlung),
 //       ------------------------
          omega_0(3.0e+10*2.0*M_PI/(1.0e-4*Input::List().lambda_0)),
          omega_p(5.64 * 1.0e+4*sqrt(Input::List().density_np)),
          w0overwp(omega_0/omega_p),
 //       -----
 //       -----
          U2(0.0, nump),
          U2m1(0.0, nump),
 //       -----
          vos(Input::List().lambda_0 * sqrt(7.3e-19*Input::List().I_0)),
          IL_xprofile(numx)
 {
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       The intensity profile is: I0(t)*e^(-2*(r/w0)^2) and absorption takes place over
 //       depth L so that I0_r(t) ~ I0(t)*e^(-((x-x0)/L)^2). The idea is that if you
 //       integrate over x you get I0(t)
     // using Inputdata::IN;
     Nbc = Input::List().BoundaryCells;
     szx = Input::List().NxLocal[0];      // size of useful x axis
     for (size_t i(1); i < U2.size(); ++i) {
         U2[i]   = 0.5 * vr[i]*vr[i]          * (vr[i]-vr[i-1]);
         U2m1[i] = 0.5 * vr[i-1]*vr[i-1]      * (vr[i]-vr[i-1]);
     }
     // Construct the intensity profile map
     Setup_Y::parseprofile(grid, Input::List().intensity_profile_str, IL_xprofile);
     if ( abs(InvBremsstrahlung) > 1 ) {
         InvBremsstrahlung = 0;
     }
 }
Member Function Documentation
IBSOURCE()
int InverseBremsstrahlung::IBSOURCE () const
Definition at line 347 of file laser.cpp.
References InvBremsstrahlung.
 {return InvBremsstrahlung;}
loop()
void InverseBremsstrahlung::loop (SHarmonic1D & f0, valarray< double > & Zarray, const double & tnew)
Definition at line 351 of file laser.cpp.
References RK4_IB::advance(), fc, IL_xprofile, Input::List(), Nbc, RK4_IB::numh(), SHarmonic1D::numx(), rk4_ib, Input::Input_List::smaller_dt, szx, t, RK4_IB::th(), RK4_IB::time(), RK4_IB::tout(), U2, U2m1, and vos.
{
 //--------------------------------------------------------------
 //  Calculate the effect of the laser source
 //--------------------------------------------------------------
     //cout << "omega_0 = " << omega_0 <<"\n";
     //cout << "omega_p = " << omega_p <<"\n";
     //cout << "np/nc = " << pow(omega_p / omega_0,2) <<"\n";
     // cout << "vos = " << vos <<"\n";
     // cout << "polarization = " << POL() <<"\n";
     // double dt = tnew -t;
     // double Envelope_Value = t_Profile(tnew)/dt; // This is Envelope(t)*dt/dt = Envelope(t)
     /*debug*/ // cout << "vos("<<tnew<<") = " << Envelope_Value << "\n";
     // debug: cout << "Envelope = " << Envelope_Value << /*",  Carrier Signal = " << Carrier_Signal(tnew) <<*/"\n";
     /*switch (POL()) {
         case 1: {
            for (size_t i(0); i < Y.SH(0,0).numx(); ++i){
                 for (size_t j(0); j < Y.SH(0,0).numy(); ++j){
                     LaserFields.Ex()(i,j) = vos * IL_xprofile[i] * IL_yprofile[j]
                             * Envelope_Value * Carrier_Signal(tnew-xaxis(i));
                 }
             }
             break;
         }
         case 2: {
             for (size_t i(0); i < Y.SH(0,0).numx(); ++i){
                 for (size_t j(0); j < Y.SH(0,0).numy(); ++j){
                     LaserFields.Ey()(i,j) = vos  * IL_xprofile[i] * IL_yprofile[j]
                              * Envelope_Value * Carrier_Signal(tnew-xaxis(i));
                 }
             }
             break;
         }
         case 3: {
             for (size_t i(0); i < Y.SH(0,0).numx(); ++i){
                 for (size_t j(0); j < Y.SH(0,0).numy(); ++j){
                     LaserFields.Ez()(i,j) = vos * IL_xprofile[i] * IL_yprofile[j]
                             * Envelope_Value * Carrier_Signal(tnew-xaxis(i));
                 }
             }
             break;
         }
         default:
             break;
     }*/
     // Array2D< double > Vos(Y.SH(0,0).numx(),Y.SH(0,0).numy());
     valarray< double > Vos(0.0,f0.numx());//,Y.SH(0,0).numy());
     // for (size_t iy(0); iy < Y.SH(0,0).numy(); ++iy){
     for (size_t ix(0); ix < f0.numx(); ++ix){
         Vos[ix] = vos * sqrt(IL_xprofile[ix]);// * IL_yprofile[iy]);
     }
     // }
 //      Initialization
     rk4_ib.tout()  = tnew;
     rk4_ib.numh()  = static_cast<size_t>(static_cast<int>((tnew-t)/(Input::List().smaller_dt)))+1;
     rk4_ib.th()    = (tnew-t)/static_cast<double>(rk4_ib.numh());
     // for (size_t iy(0); iy < szy-2*Nbc; ++iy){
     for (size_t ix(0); ix < szx-2*Nbc; ++ix){
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         // Copy data for a specific location in space to valarray
         for (size_t ip(0); ip < fc.size(); ++ip){
             // fc[ip] = (Y.SH(0,0)(ip,ix+Nbc,iy+Nbc)).real();
             fc[ip] = f0(ip,ix+Nbc).real();
         }
         double I2_before(0.0);
         for (int n(1); n < U2.size(); ++n) {
             I2_before+= U2[n]*fc[n]+U2m1[n]*fc[n-1];
         }
         // Time loop: Update the valarray
         rk4_ib.time() = t;
         for (size_t h_step(0); h_step < rk4_ib.numh(); ++h_step){
             rk4_ib.advance(Vos[ix+Nbc], Zarray[ix+Nbc]);//,iy+Nbc));
             /*debug*/ // cout << "Vos("<<ix<<","<<iy<<") = "<< Vos(ix+Nbc,iy+Nbc) << "\n";
         }
         double I2_after(0.0);
         for (int n(1); n < U2.size(); ++n) {
             I2_after += U2[n]*fc[n]+U2m1[n]*fc[n-1];
         }
         fc *= I2_before/I2_after;
         // Return updated data to the harmonic
         for (int ip(0); ip < fc.size(); ++ip){
             // Y.SH(0,0)(ip,ix+Nbc,iy+Nbc) = fc[ip];
             f0(ip,ix+Nbc) = fc[ip];
         }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     }
     // }
     t = tnew;
 }
Field Documentation
fc
valarray<double> InverseBremsstrahlung::fc private
Definition at line 127 of file laser.h.
Referenced by loop().
IL_xprofile
valarray<double> InverseBremsstrahlung::IL_xprofile private
Definition at line 147 of file laser.h.
Referenced by InverseBremsstrahlung(), and loop().
InvBremsstrahlung
int InverseBremsstrahlung::InvBremsstrahlung private
Definition at line 136 of file laser.h.
Referenced by IBSOURCE(), and InverseBremsstrahlung().
Nbc
int InverseBremsstrahlung::Nbc private
Definition at line 139 of file laser.h.
Referenced by InverseBremsstrahlung(), and loop().
omega_0
const double InverseBremsstrahlung::omega_0 private
Definition at line 154 of file laser.h.
omega_p
const double InverseBremsstrahlung::omega_p private
Definition at line 154 of file laser.h.
rk4_ib
RK4_IB InverseBremsstrahlung::rk4_ib private
Definition at line 131 of file laser.h.
Referenced by loop().
szx
int InverseBremsstrahlung::szx private
Definition at line 139 of file laser.h.
Referenced by InverseBremsstrahlung(), and loop().
szy
int InverseBremsstrahlung::szy private
Definition at line 139 of file laser.h.
t
double InverseBremsstrahlung::t private
Definition at line 124 of file laser.h.
Referenced by loop().
tout
double InverseBremsstrahlung::tout private
Definition at line 124 of file laser.h.
U2
valarray<double> InverseBremsstrahlung::U2
Definition at line 111 of file laser.h.
Referenced by InverseBremsstrahlung(), and loop().
U2m1
valarray<double> InverseBremsstrahlung::U2m1
Definition at line 111 of file laser.h.
Referenced by InverseBremsstrahlung(), and loop().
vos
const double InverseBremsstrahlung::vos private
Definition at line 154 of file laser.h.
Referenced by loop().
vr
valarray<double> InverseBremsstrahlung::vr private
Definition at line 133 of file laser.h.
Referenced by InverseBremsstrahlung().
w0overwp
const double InverseBremsstrahlung::w0overwp private
Definition at line 154 of file laser.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/laser.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/laser.cpp