OSHUN: Node_Communications Class Reference
Node_Communications Class Reference
#include <parallel.h>
Public Member Functions
Node_Communications ()
~Node_Communications ()
int BNDX () const
void Send_right_X (State1D &Y, int dest)
void Recv_from_left_X (State1D &Y, int origin)
void Send_left_X (State1D &Y, int dest)
void Recv_from_right_X (State1D &Y, int origin)
void mirror_bound_Xleft (State1D &Y)
void mirror_bound_Xright (State1D &Y)
void sameNode_bound_X (State1D &Y)
Private Member Functions
void sameNode_periodic_X (State1D &Y)
void sameNode_mirror_X (State1D &Y)
Private Attributes
int Nbc
int bndX
int numspec
int numpmax
int msg_sizeX
complex< double > * msg_bufX
Detailed Description
Definition at line 81 of file parallel.h.
Constructor & Destructor Documentation
Node_Communications()
Node_Communications::Node_Communications ()
Definition at line 341 of file parallel.cpp.
References Input::List(), Input::Input_List::ls, Input::Input_List::ms, msg_bufX, msg_sizeX, Nbc, numspec, and Input::Input_List::ps.
                                           :
 //--------------------------------------------------------------
 //  Constructor
 //--------------------------------------------------------------
         Nbc(Input::List().BoundaryCells),      // # of boundary cells
         bndX(Input::List().bndX) {        // Type of boundary in X
     numspec = Input::List().ls.size();
     // numpmax = Input::List().ps;
     double temp;
     // # of harmonics
     msg_sizeX = 0; temp = 0;
     for(int s(0); s < numspec; ++s) {
         temp = ((Input::List().ms[s]+1)*(2*Input::List().ls[s]-Input::List().ms[s]+2))/2;
         msg_sizeX += temp*Input::List().ps[s];
     }
     // (# of harmonics) * (# cells in p)
     // msg_sizeX *= numpmax
     // 6 fields: Ex, Ey, Ez, Bx, By, Bz
     msg_sizeX += 6;
     // 6 Hydro Quantities, density, vx, vy, vz, temp, Z
     if (Input::List().hydromotion)
     {
         msg_sizeX += 6;
     }
     msg_sizeX *= Nbc;  //(IN().inp().y.dim()*Nbc);
     msg_bufX = new complex<double>[msg_sizeX];
 }
~Node_Communications()
Node_Communications::~Node_Communications ()
Definition at line 377 of file parallel.cpp.
References msg_bufX.
{
 //--------------------------------------------------------------
 //  Destructor
 //--------------------------------------------------------------
     delete[] msg_bufX;
 }
Member Function Documentation
BNDX()
int Node_Communications::BNDX () const
Definition at line 386 of file parallel.cpp.
References bndX.
Referenced by sameNode_bound_X().
 {return bndX;}
mirror_bound_Xleft()
void Node_Communications::mirror_bound_Xleft (State1D & Y)
Definition at line 701 of file parallel.cpp.
References EMF1D::Bx(), Hydro1D::density(), State1D::DF(), EMF1D::dim(), State1D::EMF(), EMF1D::Ey(), EMF1D::Ez(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, DistFunc1D::l0(), Input::List(), DistFunc1D::m0(), Nbc, SHarmonic1D::nump(), SHarmonic1D::numx(), State1D::SH(), State1D::Species(), Hydro1D::temperature(), Hydro1D::vx(), and Hydro1D::Z().
Referenced by Parallel_Environment_1D::Neighbor_Communications().
{
 //--------------------------------------------------------------
 //  Mirror boundary in the x direction on the left
 //--------------------------------------------------------------
     int sign(1);
     size_t Nx(Y.SH(0,0,0).numx());
     // Mirror the harmonics
     for(int s(0); s < Y.Species(); ++s) {
         for(int l(0); l < Y.DF(s).l0(); ++l){
             for(int m(0); m < ((Y.DF(s).m0() < l)? Y.DF(s).m0():l)+1; ++m){
                 sign = 1-2*((l+m)%2);          //(-1)^(m+n)
                 for (int c(0); c < Nbc; ++c) {
                     for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                         Y.SH(s,l,m)(p, c) = Y.SH(s,l,m)(p, 2*Nbc-c-1);
                         Y.SH(s,l,m)(p, c) *= sign;
                     }
                 }
             }
         }
     }
     // Mirror the fields
     for(int i(0); i < Y.EMF().dim(); ++i){
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(c) = Y.FLD(i)(2*Nbc-c-1);
     }
     for (int c(0); c < Nbc; ++c) {
 //          Ey
         Y.EMF().Ey()(c) *= -1.0; // left  boundary
 //          Ez
         Y.EMF().Ez()(c) *= -1.0; // left  boundary
 //          Bx
         Y.EMF().Bx()(c) *= -1.0; // left  boundary
 //        Y.EMF().By()(c) = 1e-3; // left  boundary
     }
     if (Input::List().hydromotion)
     {
         // Hydro Quantities:   x0 "Right-Bound ---> Left-Guard"
         for(int c(0); c < Nbc; c++) {
             Y.HYDRO().density(c) =  Y.HYDRO().density(2*Nbc-c-1);
             Y.HYDRO().temperature(c) =  Y.HYDRO().temperature(2*Nbc-c-1);
             Y.HYDRO().Z(c) =  Y.HYDRO().Z(2*Nbc-c-1);
             Y.HYDRO().vx(c) *= -1.0;
         }
     }
 }
mirror_bound_Xright()
void Node_Communications::mirror_bound_Xright (State1D & Y)
Definition at line 759 of file parallel.cpp.
References EMF1D::Bx(), Hydro1D::density(), State1D::DF(), EMF1D::dim(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, DistFunc1D::l0(), Input::List(), DistFunc1D::m0(), Nbc, SHarmonic1D::nump(), SHarmonic1D::numx(), Field1D::numx(), State1D::SH(), State1D::Species(), Hydro1D::temperature(), Hydro1D::vx(), and Hydro1D::Z().
Referenced by Parallel_Environment_1D::Neighbor_Communications().
{
 //--------------------------------------------------------------
 //  Mirror boundary in the x direction on the right
 //--------------------------------------------------------------
     int sign(1);
     size_t Nx(Y.SH(0,0,0).numx());
     // Mirror the harmonics
     for(int s(0); s < Y.Species(); ++s) {
         for(int l(0); l < Y.DF(s).l0(); ++l){
             for(int m(0); m < ((Y.DF(s).m0() < l)? Y.DF(s).m0():l)+1; ++m){
                 sign = 1-2*((l+m)%2);          //(-1)^(m+n)
                 for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                     for (int c(0); c < Nbc; ++c) {
                         Y.SH(s,l,m)(p, Nx-c-1) = Y.SH(s,l,m)(p, Nx-2*Nbc+c);
                         Y.SH(s,l,m)(p, Nx-c-1) *= sign;
                     }
                 }
             }
         }
     }
     // Mirror the fields
     for(int i(0); i < Y.EMF().dim(); ++i){
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(Nx-c-1) = Y.FLD(i)(Nx-2*Nbc+c);
     }
     for (int c(0); c < Nbc; ++c) {
         //Ey
         Y.EMF().Ey()(Nx-c-1) *= -1.0; // right boundary
         //Ez
         Y.EMF().Ez()(Nx-c-1) *= -1.0; // right boundary
         //Bx
         Y.EMF().Bx()(Nx-c-1) *= -1.0; // right boundary
 //        Y.EMF().By()(Nx-c-1) = 1e-3; // right  boundary
     }
     if (Input::List().hydromotion)
     {
         // Hydro Quantities:   x0 "Left-Bound ---> Right-Guard"
         for(int c(0); c < Nbc; c++) {
             Y.HYDRO().density(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().density(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().temperature(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().temperature(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().Z(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().Z(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().vx(Y.EMF().Ex().numx()-Nbc+c) *=  -1.0;
         }
     }
 }
Recv_from_left_X()
void Node_Communications::Recv_from_left_X (State1D & Y, int origin)
Definition at line 465 of file parallel.cpp.
References Hydro1D::density(), State1D::DF(), EMF1D::dim(), DistFunc1D::dim(), State1D::EMF(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, Input::List(), msg_bufX, msg_sizeX, Nbc, SHarmonic1D::nump(), State1D::SH(), State1D::Species(), Hydro1D::temperature(), Hydro1D::vx(), Hydro1D::vy(), Hydro1D::vz(), and Hydro1D::Z().
Referenced by Parallel_Environment_1D::Neighbor_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Receive data from the node on the left and update
 //           the left guard cells
 //--------------------------------------------------------------
     // static size_t step_h(Y.SH(s,0,0).nump()*Nbc);
     static size_t step_f(Nbc);
     size_t bufind(0);
     MPI_Status status;
     // Receive Data
     MPI_Recv(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, origin, 0, MPI_COMM_WORLD, &status);
     // Harmonics:x0-"---> Left-Guard"
     for(int s(0); s < Y.Species(); ++s) {
         for(int i = 0; i < Y.DF(s).dim(); ++i){
             for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                 for(int e(0); e < Nbc; e++) {
                     (Y.DF(s)(i))(p, e) = msg_bufX[bufind + e];
                 }
                 bufind += step_f;
             }
         }
     }
     // Fields:   x0-"---> Left-Guard"
     for(int i = 0; i < Y.EMF().dim(); ++i){
         for(int e(0); e < Nbc; e++) {
             Y.FLD(i)(e) = msg_bufX[bufind + e];
         }
         bufind += step_f;
     }
     if (Input::List().hydromotion)
     {
         // Hydro-velocity:   x0-"---> Left-Guard"
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().density(e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-velocity:   x0-"---> Left-Guard"
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().vx(e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-velocity:   x0-"---> Left-Guard"
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().vy(e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-velocity:   x0-"---> Left-Guard"
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().vz(e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-temperature:   x0-"---> Left-Guard"
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().temperature(e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-charge fraction:   x0-"---> Left-Guard"
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().Z(e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
     }
 }
Recv_from_right_X()
void Node_Communications::Recv_from_right_X (State1D & Y, int origin)
Definition at line 616 of file parallel.cpp.
References Hydro1D::density(), State1D::DF(), EMF1D::dim(), DistFunc1D::dim(), State1D::EMF(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, Input::List(), msg_bufX, msg_sizeX, Nbc, SHarmonic1D::nump(), Field1D::numx(), State1D::SH(), State1D::Species(), Hydro1D::temperature(), Hydro1D::vx(), Hydro1D::vy(), Hydro1D::vz(), and Hydro1D::Z().
Referenced by Parallel_Environment_1D::Neighbor_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Receive data from the node on the right and update
 //           the right guard cells
 //--------------------------------------------------------------
     // static size_t step_h(Y.SH(s,0,0).nump()*Nbc);
     static size_t step_f(Nbc);
     size_t bufind(0);
     MPI_Status status;
     // Receive Data
     MPI_Recv(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, origin, 1, MPI_COMM_WORLD, &status);
     // Harmonics:x0-"Right-Guard <--- "
     for(int s(0); s < Y.Species(); ++s) {
         for(int i = 0; i < Y.DF(s).dim(); ++i){
             for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                 for(int e(0); e < Nbc; e++) {
                     (Y.DF(s)(i))(p, Y.FLD(0).numx()-Nbc+e) = msg_bufX[bufind + e];
                 }
                 bufind += step_f;
             }
         }
     }
     // Fields:   x0-"Right-Guard <--- "
     for(int i = 0; i < Y.EMF().dim(); ++i){
         for(int e(0); e < Nbc; e++) {
             Y.FLD(i)(Y.FLD(0).numx()-Nbc+e) = msg_bufX[bufind + e];
         }
         bufind += step_f;
     }
     if (Input::List().hydromotion)
     {
         // Hydro-density:   x0-"Right-Guard <--- "
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().density(Y.FLD(0).numx()-Nbc+e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-velocity:   x0-"Right-Guard <--- "
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().vx(Y.FLD(0).numx()-Nbc+e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-velocity:   x0-"Right-Guard <--- "
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().vy(Y.FLD(0).numx()-Nbc+e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-velocity:   x0-"Right-Guard <--- "
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().vz(Y.FLD(0).numx()-Nbc+e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-temperature:   x0-"Right-Guard <--- "
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().temperature(Y.FLD(0).numx()-Nbc+e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
         // Hydro-charge fraction:   x0-"Right-Guard <--- "
         for(int e(0); e < Nbc; e++) {
             Y.HYDRO().Z(Y.FLD(0).numx()-Nbc+e) = (msg_bufX[bufind + e]).real();
         }
         bufind += step_f;
     }
 }
sameNode_bound_X()
void Node_Communications::sameNode_bound_X (State1D & Y)
Definition at line 821 of file parallel.cpp.
References BNDX(), sameNode_mirror_X(), and sameNode_periodic_X().
Referenced by Parallel_Environment_1D::Neighbor_Communications().
{
 //--------------------------------------------------------------
 //  Choose between boundary conditions in the x direction
 //--------------------------------------------------------------
     switch (BNDX()) {
         case 0:                   // periodic
             sameNode_periodic_X(Y);
             break;
         case 1:                   // mirror boundary
             sameNode_mirror_X(Y);
             break;
         default:
             cout<<"Not a valid boundary condition." << endl;
             break;
     }
 }
sameNode_mirror_X()
void Node_Communications::sameNode_mirror_X (State1D & Y) private
Definition at line 938 of file parallel.cpp.
References EMF1D::Bx(), State1D::DF(), EMF1D::dim(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, DistFunc1D::l0(), Input::List(), DistFunc1D::m0(), Nbc, SHarmonic1D::nump(), SHarmonic1D::numx(), Field1D::numx(), State1D::SH(), State1D::Species(), and Hydro1D::vx().
Referenced by sameNode_bound_X().
{
 //--------------------------------------------------------------
 //  Mirror boundary in the x direction for 1 node
 //--------------------------------------------------------------
     int sign(1);
     size_t Nx(Y.SH(0,0,0).numx());
     // Mirror the harmonics
     for(int s(0); s < Y.Species(); ++s) {
         for(int l(0); l < Y.DF(s).l0(); ++l){
             for(int m(0); m < ((Y.DF(s).m0() < l)? Y.DF(s).m0():l)+1; ++m){
                 sign = 1-2*((l+m)%2);          //(-1)^(m+n)
                 // right boundary
                 for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                     for (int c(0); c < Nbc; ++c) {
                         Y.SH(s,l,m)(p, Nx-c-1) = Y.SH(s,l,m)(p, Nx-2*Nbc+c);
                         Y.SH(s,l,m)(p, Nx-c-1) *= sign;
                     }
                 }
                 // left boundary
                 for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                     for (int c(0); c < Nbc; ++c) {
                         Y.SH(s,l,m)(p, c) = Y.SH(s,l,m)(p, 2*Nbc-c-1);
                         Y.SH(s,l,m)(p, c) *= sign;
                     }
                 }
             }
         }
     }
     // Mirror the fields
     for(int i(0); i < Y.EMF().dim(); ++i){
         // right boundary
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(Nx-c-1) = Y.FLD(i)(Nx-2*Nbc+c);
         // left boundary
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(c) = Y.FLD(i)(2*Nbc-c-1);
     }
     for(int c(0); c < Nbc; c++) {
         //Ey
         Y.EMF().Ey()(Nx-Nbc+c) *= -1.0; // right boundary
         Y.EMF().Ey()(c) *= -1.0;  // left  boundary
         //Ez
         Y.EMF().Ez()(Nx-Nbc+c) *= -1.0; // right boundary
         Y.EMF().Ez()(c) *= -1.0;  // left  boundary
         //Bx
         Y.EMF().Bx()(Nx-Nbc+c) *= -1.0; // right boundary
         Y.EMF().Bx()(c) *= -1.0;  // left  boundary
     }
     if (Input::List().hydromotion)
     {
         // Hydro Quantities:   x0 "Right-Bound ---> Left-Guard"
         for(int c(0); c < Nbc; c++) {
             Y.HYDRO().vx(c) *= -1.0;
         }
         // Hydro Quantities:   x0 "Left-Bound ---> Right-Guard"
         for(int c(0); c < Nbc; c++) {
             Y.HYDRO().vx(Y.EMF().Ex().numx()-Nbc+c) *= -1.0;
         }
     }
 }
sameNode_periodic_X()
void Node_Communications::sameNode_periodic_X (State1D & Y) private
Definition at line 842 of file parallel.cpp.
References Hydro1D::density(), State1D::DF(), EMF1D::dim(), DistFunc1D::dim(), State1D::EMF(), EMF1D::Ex(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, Input::List(), Nbc, SHarmonic1D::nump(), Field1D::numx(), State1D::SH(), State1D::Species(), Hydro1D::temperature(), Hydro1D::vx(), Hydro1D::vy(), Hydro1D::vz(), and Hydro1D::Z().
Referenced by sameNode_bound_X().
{
 //--------------------------------------------------------------
 //  Periodic boundary in the x direction for 1 node
 //--------------------------------------------------------------
     // Harmonics:x0 "Right-Bound ---> Left-Guard"
     for(int s(0); s < Y.Species(); ++s) {
         for(int i(0); i < Y.DF(s).dim(); ++i) {
             for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                 for(int c(0); c < Nbc; c++) {
                     (Y.DF(s)(i))(p, c) = (Y.DF(s)(i))(p, Y.EMF().Ex().numx()-2*Nbc+c);
                     // std::cout << "\n 1: DF(" << i << "," << p << "," << c << ") = " << (Y.DF(s)(i))(p, Y.EMF().Ex().numx()-2*Nbc+c) << "\n";
                 }
             }
         }
     }
     // Fields:   x0 "Right-Bound ---> Left-Guard"
     for(int i(0); i < Y.EMF().dim(); ++i) {
         for(int c(0); c < Nbc; c++) {
             Y.FLD(i)(c) = Y.FLD(i)(Y.EMF().Ex().numx()-2*Nbc+c);
             // std::cout << "\n 2: FLD(" << i << "," << c << ") = " << Y.FLD(i)(Y.EMF().Ex().numx()-2*Nbc+c) << "\n";
         }
     }
     // Harmonics:x0 "Left-Bound ---> Right-Guard"
     for(int s(0); s < Y.Species(); ++s) {
         for(int i(0); i < Y.DF(s).dim(); ++i) {
             for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                 for(int c(0); c < Nbc; c++) {
                     // std::cout << "\n 3: DF(" << i << "," << p << "," << Y.EMF().Ex().numx()-Nbc+c << ") = " << (Y.DF(s)(i))(p, Y.EMF().Ex().numx()-Nbc+c) << "\n";
                     (Y.DF(s)(i))(p, Y.EMF().Ex().numx()-Nbc+c) = (Y.DF(s)(i))(p, Nbc+c);
                     // std::cout << "\n 3n: DF(" << i << "," << p << "," << Y.EMF().Ex().numx()-Nbc+c << ") = " << (Y.DF(s)(i))(p, Y.EMF().Ex().numx()-Nbc+c-100.0) << "\n";
                     // if (c==2)
                 }
             }
         }
     }
     // Fields:   x0 "Left-Bound ---> Right-Guard"
     for(int i(0); i < Y.EMF().dim(); ++i) {
         for(int c(0); c < Nbc; c++) {
             // if (i == 0)                 std::cout << "\n 4: FLD(" << i << "," << Y.EMF().Ex().numx()-Nbc+c << ") = " << Y.FLD(i)(Y.EMF().Ex().numx()-Nbc+c) << "\n";
             Y.FLD(i)(Y.EMF().Ex().numx()-Nbc+c) = Y.FLD(i)(Nbc+c);
             // if (i == 0)                 std::cout << "\n 4n: FLD(" << i << "," << Y.EMF().Ex().numx()-Nbc+c << ") = " << Y.FLD(i)(Y.EMF().Ex().numx()-Nbc+c) << "\n";
         }
         // Y.FLD(i)(Y.EMF().Ex().numx()-1) = 0.0;
     }
     // temp = Y.DF(0).getcurrent(0);
     // for (size_t ix(0);ix<Y.SH(0,0,0).numx();++ix)
     // {
     //     std::cout<<"\n      new[" << ix  << "] = " << temp[ix] << "\n";
     // }
     if (Input::List().hydromotion)
     {
         // Hydro Quantities:   x0 "Right-Bound ---> Left-Guard"
         for(int c(0); c < Nbc; c++) {
             Y.HYDRO().density(c) = Y.HYDRO().density(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().vx(c) = Y.HYDRO().vx(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().vy(c) = Y.HYDRO().vy(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().vz(c) = Y.HYDRO().vz(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().temperature(c) = Y.HYDRO().temperature(Y.EMF().Ex().numx()-2*Nbc+c);
             Y.HYDRO().Z(c) = Y.HYDRO().Z(Y.EMF().Ex().numx()-2*Nbc+c);
             // Y.HYDRO().kpressure(c) = Y.HYDRO().velocity(Y.EMF().Ex().numx()-2*Nbc+c);
             // Y.HYDRO().mpressure(c) = Y.HYDRO().velocity(Y.EMF().Ex().numx()-2*Nbc+c);
         }
         // Hydro Quantities:   x0 "Left-Bound ---> Right-Guard"
         for(int c(0); c < Nbc; c++) {
             Y.HYDRO().density(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().density(Nbc+c);
             Y.HYDRO().vx(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().vx(Nbc+c);
             Y.HYDRO().vy(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().vy(Nbc+c);
             Y.HYDRO().vz(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().vz(Nbc+c);
             Y.HYDRO().temperature(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().temperature(Nbc+c);
             Y.HYDRO().Z(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().Z(Nbc+c);
             // Y.HYDRO().kpressure(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().velocity(Nbc+c);
             // Y.HYDRO().mpressure(Y.EMF().Ex().numx()-Nbc+c) =  Y.HYDRO().velocity(Nbc+c);
         }
     }
 }
Send_left_X()
void Node_Communications::Send_left_X (State1D & Y, int dest)
Definition at line 544 of file parallel.cpp.
References Hydro1D::density(), State1D::DF(), EMF1D::dim(), DistFunc1D::dim(), State1D::EMF(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, Input::List(), msg_bufX, msg_sizeX, Nbc, SHarmonic1D::nump(), State1D::SH(), State1D::Species(), Hydro1D::temperature(), Hydro1D::vx(), Hydro1D::vy(), Hydro1D::vz(), and Hydro1D::Z().
Referenced by Parallel_Environment_1D::Neighbor_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Read data from the left boundary and send them
 //           to the node on the left
 //--------------------------------------------------------------
     // static size_t step_h(Y.SH(s,0,0).nump()*Nbc);
     static size_t step_f(Nbc);
     size_t bufind(0);
     // Harmonics:x0 " <--- Left-Bound "
     for(int s(0); s < Y.Species(); ++s) {
         for(int i = 0; i < Y.DF(s).dim(); ++i){
             for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                 for(int e(0); e < Nbc; e++) {
                     msg_bufX[bufind + e] = (Y.DF(s)(i))(p, Nbc+e);
                 }
                 bufind += step_f;
             }
         }
     }
     // Fields:   x0 " <--- Left-Bound "
     for(int i = 0; i < Y.EMF().dim(); ++i){
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.FLD(i)(Nbc+e);
         }
         bufind += step_f;
     }
     if (Input::List().hydromotion)
     {
         // Hydro-velocity:   x0 " <--- Left-Bound "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().density(Nbc+e);
         }
         bufind += step_f;
         // Hydro-velocity:   x0 " <--- Left-Bound "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().vx(Nbc+e);
         }
         bufind += step_f;
         // Hydro-velocity:   x0 " <--- Left-Bound "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().vy(Nbc+e);
         }
         bufind += step_f;
         // Hydro-velocity:   x0 " <--- Left-Bound "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().vz(Nbc+e);
         }
         bufind += step_f;
         // Hydro-temperature:   x0 " <--- Left-Bound "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().temperature(Nbc+e);
         }
         bufind += step_f;
         // Hydro-charge-fraction:   x0 " <--- Left-Bound "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().Z(Nbc+e);
         }
         bufind += step_f;
     }
     MPI_Send(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, dest, 1, MPI_COMM_WORLD);
 }
Send_right_X()
void Node_Communications::Send_right_X (State1D & Y, int dest)
Definition at line 396 of file parallel.cpp.
References Hydro1D::density(), State1D::DF(), EMF1D::dim(), DistFunc1D::dim(), State1D::EMF(), State1D::FLD(), State1D::HYDRO(), Input::Input_List::hydromotion, Input::List(), msg_bufX, msg_sizeX, Nbc, SHarmonic1D::nump(), Field1D::numx(), State1D::SH(), State1D::Species(), Hydro1D::temperature(), Hydro1D::vx(), Hydro1D::vy(), Hydro1D::vz(), and Hydro1D::Z().
Referenced by Parallel_Environment_1D::Neighbor_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Read data from the right boundary and send them
 //           to the node on the right
 //--------------------------------------------------------------
     // static size_t step_h(numpmax*Nbc);
     static size_t step_f(Nbc);
     size_t bufind(0);
     // Harmonics:x0 "Right-Bound ---> "
     for(int s(0); s < Y.Species(); ++s) {
         for(size_t i = 0; i < Y.DF(s).dim(); ++i){
             for(int p(0); p < Y.SH(s,0,0).nump(); ++p) {
                 for(int e(0); e < Nbc; e++) {
                     msg_bufX[bufind + e] = (Y.DF(s)(i))(p, Y.FLD(0).numx()-2*Nbc+e);
                 }
                 bufind += step_f;
             }
         }
     }
     // Fields:   x0 "Right-Bound --> "
     for(size_t i = 0; i < Y.EMF().dim(); ++i){
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.FLD(i)(Y.FLD(0).numx()-2*Nbc+e);
         }
         bufind += step_f;
     }
     if (Input::List().hydromotion)
     {
         // Hydro-velocity:   x0 "Right-Bound --> "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().density(Y.FLD(0).numx()-2*Nbc+e);
         }
         bufind += step_f;
         // Hydro-velocity:   x0 "Right-Bound --> "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().vx(Y.FLD(0).numx()-2*Nbc+e);
         }
         bufind += step_f;
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().vy(Y.FLD(0).numx()-2*Nbc+e);
         }
         bufind += step_f;
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().vz(Y.FLD(0).numx()-2*Nbc+e);
         }
         bufind += step_f;
         // Hydro-temperature:   x0 "Right-Bound --> "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().temperature(Y.FLD(0).numx()-2*Nbc+e);
         }
         bufind += step_f;
         // Hydro-chargefraction:   x0 "Right-Bound --> "
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.HYDRO().Z(Y.FLD(0).numx()-2*Nbc+e);
         }
         bufind += step_f;
     }
     MPI_Send(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, dest, 0, MPI_COMM_WORLD);
 }
Field Documentation
bndX
int Node_Communications::bndX private
Definition at line 108 of file parallel.h.
Referenced by BNDX().
msg_bufX
complex<double>* Node_Communications::msg_bufX private
Definition at line 113 of file parallel.h.
Referenced by Node_Communications(), Recv_from_left_X(), Recv_from_right_X(), Send_left_X(), Send_right_X(), and ~Node_Communications().
msg_sizeX
int Node_Communications::msg_sizeX private
Definition at line 112 of file parallel.h.
Referenced by Node_Communications(), Recv_from_left_X(), Recv_from_right_X(), Send_left_X(), and Send_right_X().
Nbc
int Node_Communications::Nbc private
Definition at line 108 of file parallel.h.
Referenced by mirror_bound_Xleft(), mirror_bound_Xright(), Node_Communications(), Recv_from_left_X(), Recv_from_right_X(), sameNode_mirror_X(), sameNode_periodic_X(), Send_left_X(), and Send_right_X().
numpmax
int Node_Communications::numpmax private
Definition at line 109 of file parallel.h.
numspec
int Node_Communications::numspec private
Definition at line 109 of file parallel.h.
Referenced by Node_Communications().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/parallel.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/parallel.cpp