OSHUN: /Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/nmethods.h File Reference
nmethods.h File Reference
Numerical Methods - Declarations.
Functions
bool Gauss_Seidel (Array2D< double > &A, valarray< complex< double > > &b, valarray< complex< double > > &xk)
Performs Gauss-Seidel method on Ax = b.
void TridiagonalSolve (const valarray< double > &a, const valarray< double > &b, valarray< double > &c, valarray< complex< double > > d, valarray< complex< double > > &x)
Set up tridiagonal solver.
void TridiagonalSolve (const valarray< double > &a, const valarray< double > &b, valarray< double > &c, valarray< double > d, valarray< double > &x)
void TridiagonalSolve (const valarray< complex< double > > &a, const valarray< complex< double > > &b, valarray< complex< double > > &c, valarray< complex< double > > d, valarray< complex< double > > &x)
bool Thomas_Tridiagonal (Array2D< double > &A, valarray< double > &d, valarray< double > &xk)
The tridiagonal solver for implicit collisions.
bool Thomas_Tridiagonal (Array2D< double > &A, valarray< complex< double > > &d, valarray< complex< double > > &xk)
bool Thomas_Tridiagonal (Array2D< complex< double > > &A, valarray< complex< double > > &d, valarray< complex< double > > &xk)
complex< double > Det33 (Array2D< complex< double > > &A)
complex< double > Detx33 (valarray< complex< double > > &D, Array2D< complex< double > > &A)
complex< double > Dety33 (valarray< complex< double > > &D, Array2D< complex< double > > &A)
complex< double > Detz33 (valarray< complex< double > > &D, Array2D< complex< double > > &A)
valarray< float > vfloat (const valarray< double > &vDouble)
vector< float > vfloat (const vector< double > vDouble)
Convert data structure to float structure.
vector< float > vfloat (const vector< complex< double > > vDouble)
vector< float > vfloat_complex (const vector< complex< double > > vDouble)
valarray< double > df_4thorder (const valarray< double > &f)
valarray< double > df_4thorder (valarray< double > &f)
Array2D< complex< double > > df1_4thorder (Array2D< complex< double > > &f)
Array2D< complex< double > > df2_4thorder (Array2D< complex< double > > &f)
Detailed Description
Numerical Methods - Declarations.
Author
PICKSC
Date
September 1, 2016
This cpp file contains the definitions for the functions required for the numerical methods.
Definition in file nmethods.h.
Function Documentation
Det33()
complex<double> Det33 (Array2D< complex< double > > & A)
Detx33()
complex<double> Detx33 (valarray< complex< double > > & D, Array2D< complex< double > > & A)
Dety33()
complex<double> Dety33 (valarray< complex< double > > & D, Array2D< complex< double > > & A)
Detz33()
complex<double> Detz33 (valarray< complex< double > > & D, Array2D< complex< double > > & A)
df1_4thorder()
Array2D<complex<double> > df1_4thorder (Array2D< complex< double > > & f)
Definition at line 469 of file nmethods.cpp.
{
     Array2D<complex<double> > df(f.dim1(),f.dim2());
     for (long i2(0); i2<f.dim1();++i2){
         df(0,i2) = f(1,i2)-f(0,i2);
         df(1,i2) = 1.0/12.0*(f(4,i2)-6.0*f(3,i2)+18.0*f(2,i2)-10.0*f(1,i2)-3.0*f(0,i2));
         for (long i1(2); i1<f.dim1()-2;++i1){
             df(i1,i2) = 1.0/12.0*(-f(i1+2,i2)+8.0*f(i1+1,i2)-8.0*f(i1-1,i2)+f(i1-2,i2));
         }
         df(f.dim1()-2,i2) = 1.0/12.0*(3.0*f(f.dim2()-1,i2)+10.0*f(f.dim2()-2,i2)-18.0*f(f.dim2()-3,i2)+6.0*f(f.dim2()-4,i2)-f(f.dim2()-5,i2));
         df(f.dim1()-1,i2) = f(f.dim2()-1,i2)-f(f.dim2()-2,i2);
     }
     return df;
 }
df2_4thorder()
Array2D<complex<double> > df2_4thorder (Array2D< complex< double > > & f)
Definition at line 489 of file nmethods.cpp.
{
     Array2D<complex<double> > df(f.dim1(),f.dim2());
     for (long i1(0); i1<f.dim1();++i1){
         df(i1,0) = f(i1,1)-f(i1,0);
         df(i1,1) = 1.0/12.0*(f(i1,4)-6.0*f(i1,3)+18.0*f(i1,2)-10.0*f(i1,1)-3.0*f(i1,0));
         for (long i2(2); i2<f.dim2()-2;++i2){
             df(i1,i2) = 1.0/12.0*(-f(i1,i2+2)+8.0*f(i1,i2+1)-8.0*f(i1,i2-1)+f(i1,i2-2));
         }
         df(i1,f.dim2()-2) = 1.0/12.0*(3.0*f(i1,f.dim2()-1)+10.0*f(i1,f.dim2()-2)-18.0*f(i1,f.dim2()-3)+6.0*f(i1,f.dim2()-4)-f(i1,f.dim2()-5));
         df(i1,f.dim2()-1) = f(i1,f.dim2()-1)-f(i1,f.dim2()-2);
     }
     return df;
 }
df_4thorder() [1/2]
valarray<double> df_4thorder (const valarray< double > & f)
Definition at line 421 of file nmethods.cpp.
Referenced by Fluid_Equation_1D::chargefraction(), Fluid_Equation_1D::density(), and Fluid_Equation_1D::velocity().
{
     valarray<double> df(f.size());
     df[0] = f[1]-f[0];
     df[1] = 1.0/12.0*(f[4]-6.0*f[3]+18.0*f[2]-10.0*f[1]-3.0*f[0]);
     for (size_t i(2); i < df.size()-2; ++i) {
         df[i] = 1.0/12.0*(-f[i+2]+8.0*f[i+1]-8.0*f[i-1]+f[i-2]);
     }
     df[df.size()-2] = 1.0/12.0*(3.0*f[df.size()-1]+10.0*f[df.size()-2]-18.0*f[df.size()-3]+6.0*f[df.size()-4]-f[df.size()-5]);
     df[df.size()-1] = f[df.size()-1]-f[df.size()-2];
     return df;
 }
df_4thorder() [2/2]
valarray<double> df_4thorder (valarray< double > & f)
Definition at line 437 of file nmethods.cpp.
{
     valarray<double> df(f.size());
     df[0] = f[1]-f[0];
     df[1] = 1.0/12.0*(f[4]-6.0*f[3]+18.0*f[2]-10.0*f[1]-3.0*f[0]);
     for (size_t i(2); i < df.size()-2; ++i) {
         df[i] = 1.0/12.0*(-f[i+2]+8.0*f[i+1]-8.0*f[i-1]+f[i-2]);
     }
     df[df.size()-2] = 1.0/12.0*(3.0*f[df.size()-1]+10.0*f[df.size()-2]-18.0*f[df.size()-3]+6.0*f[df.size()-4]-f[df.size()-5]);
     df[df.size()-1] = f[df.size()-1]-f[df.size()-2];
     return df;
 }
Gauss_Seidel()
bool Gauss_Seidel (Array2D< double > & A, valarray< complex< double > > & b, valarray< complex< double > > & xk)
Performs Gauss-Seidel method on Ax = b.
Parameters
A Input matrix that contains collisional integrals and coefficients
b Vector representing distribution function at current time-step
xk The solution vector
Returns
The solution vector representing the distribution function at the next time-step
Fills solution into xk. The other matrices are not modified The function returns "false" if the matrix A is not diagonally dominant
Definition at line 29 of file nmethods.cpp.
References Array2D< T >::dim1(), and Array2D< T >::dim2().
Referenced by interspecies_flm_implicit_step::advance(), and self_flm_implicit_step::advance().
{
 //-------------------------------------------------------------------
         double     tol(1.0e-1);   //< Tolerance for absolute error
         int        MAXiter(5);    //< Maximum iteration allowed
 //      The Matrices all have the right dimensions
 //      -------------------------------------------------------------
         if ( ( A.dim1() != A.dim2()  ) ||
              ( A.dim1() != b.size()  ) ||
              ( A.dim1() != xk.size() )    )  {
             cout << "Error: The Matrices don't have the right dimensions!" << endl;
             exit(1);
         }
 //      Check if the matrix A is diagonally dominant
 //      -------------------------------------------------------------
         for (int i(0); i < A.dim1(); ++i){
             double rowi(0.0);
             for (int j(0); j < A.dim2(); ++j){
                 rowi += A(i,j);
             }
             if (!(rowi < 2.0*A(i,i))) return false;
         }
 //      -------------------------------------------------------------
 //      Calculate and invert the diagonal elements once and for all
 //      -------------------------------------------------------------
         valarray<double> invDIAG(A.dim1());
         for (int i(0); i < invDIAG.size(); ++i) invDIAG[i] = 1.0 / A(i,i);
         valarray<complex<double> > xold(xk);
         int iteration(0);         // used to count iterations
         int conv(0);              // used to test convergence
 //      Start the iteration loop
 //      -------------------------------------------------------------
         while ( (iteration++ < MAXiter) && (conv < b.size()) ) {
             xold = xk;
             for (int i(0); i < A.dim1(); ++i){
                 complex<double> sigma(0.0);    // Temporary sum
                 for (int j(0); j < i; ++j){
                     sigma += A(i,j)*xk[j];
                 }
                 for (int j(i+1); j < A.dim2(); ++j){
                     sigma += A(i,j)*xk[j];
                 }
                 xk[i] = invDIAG[i] * (b[i] - sigma);
             }
             // Calculate Dx = x_old - x_new
             xold -= xk;
 //          If the relative error < prescribed tolerance everywhere the method has converged
 //          |Dx(i)| < t*|x(i)| + eps
             conv = 0;
             while ( ( conv < b.size() ) &&
                     ( abs(xold[conv]) < (tol*abs(xk[conv] + 20.0*DBL_MIN)) ) ){
                 ++conv;
             }
             //----> Output for testing
             //--------------------------------
             //cout << "iteration = " << iteration << "    ";
             //for (int i(0); i < b.size(); ++i){
             //    cout << xk[i] << "        ";
             //}
             //cout << "\n";
             //--------------------------------
         }
         //----> Output for testing
         //--------------------------------
         // cout << "Iterations = " << iteration-1  <<"\n";
         //for (int i(0); i < b.size(); ++i) {
         //    cout << "Error |Dx| = " << abs(xold[i])
         //         << ",    "
         //         << "Tolerance * |x| = " << tol*abs(xk[i]) <<"\n";
         //}
         //--------------------------------
         return true;
     }
Thomas_Tridiagonal() [1/3]
bool Thomas_Tridiagonal (Array2D< double > & A, valarray< double > & d, valarray< double > & xk)
The tridiagonal solver for implicit collisions.
Parameters
A Input matrix
d Right Side
xk Solution vector
Returns
xk is returned as the solution vector
Definition at line 216 of file nmethods.cpp.
References Array2D< T >::dim1(), Array2D< T >::dim2(), and TridiagonalSolve().
Referenced by interspecies_flm_implicit_step::advance(), self_flm_implicit_step::advance(), Magnetic_Field_1D_f1::implicit(), Magnetic_Field_1D::implicit(), self_f00_implicit_collisions::loop(), and self_f00_implicit_step::takestep().
{
 //-------------------------------------------------------------------
 //   Fills solution into xk. The other matrices are not modified
 //   The function returns "false" if the matrix A is not diagonally
 //   dominant
 //-------------------------------------------------------------------
 //      The Matrices all have the right dimensions
 //      -------------------------------------------------------------
     if ( ( A.dim1() != A.dim2()  ) ||
          ( A.dim1() != d.size()  ) ||
          ( A.dim1() != xk.size() )    )  {
         cout << "Error: The Matrices don't have the right dimensions!" << endl;
         exit(1);
     }
 //      -------------------------------------------------------------
     valarray<double> a(d.size()), b(d.size()), c(d.size());
     for (int i(0); i < A.dim1()-1; ++i){
         a[i+1] = A(i+1,i);
     }
     for (int i(0); i < A.dim1(); ++i){
         b[i] = A(i,i);
     }
     for (int i(0); i < A.dim1()-1; ++i){
         c[i] = A(i,i+1);
     }
 //        valarray< double > dcopy(d);
     TridiagonalSolve(a,b,c,d,xk);
     return true;
 }
Thomas_Tridiagonal() [2/3]
bool Thomas_Tridiagonal (Array2D< double > & A, valarray< complex< double > > & d, valarray< complex< double > > & xk)
Definition at line 254 of file nmethods.cpp.
References Array2D< T >::dim1(), Array2D< T >::dim2(), and TridiagonalSolve().
{
 //-------------------------------------------------------------------
 //   Fills solution into xk. The other matrices are not modified
 //   The function returns "false" if the matrix A is not diagonally
 //   dominant
 //-------------------------------------------------------------------
 //      The Matrices all have the right dimensions
 //      -------------------------------------------------------------
     if ( ( A.dim1() != A.dim2()  ) ||
          ( A.dim1() != d.size()  ) ||
          ( A.dim1() != xk.size() )    )  {
         cout << "Error: The Matrices don't have the right dimensions!" << endl;
         exit(1);
     }
 //      -------------------------------------------------------------
     valarray<double> a(d.size()), b(d.size()), c(d.size());
     for (int i(0); i < A.dim1()-1; ++i){
         a[i+1] = A(i+1,i);
     }
     for (int i(0); i < A.dim1(); ++i){
         b[i] = A(i,i);
     }
     for (int i(0); i < A.dim1()-1; ++i){
         c[i] = A(i,i+1);
     }
 //        valarray< double > dcopy(d);
     TridiagonalSolve(a,b,c,d,xk);
     return true;
 }
Thomas_Tridiagonal() [3/3]
bool Thomas_Tridiagonal (Array2D< complex< double > > & A, valarray< complex< double > > & d, valarray< complex< double > > & xk)
TridiagonalSolve() [1/3]
void TridiagonalSolve (const valarray< double > & a, const valarray< double > & b, valarray< double > & c, valarray< complex< double > > d, valarray< complex< double > > & x)
Set up tridiagonal solver.
Parameters
[in] a ???
[in] b ???
c ???
[in] d right side
x solution
Definition at line 121 of file nmethods.cpp.
Referenced by Thomas_Tridiagonal().
{
 //-------------------------------------------------------------------
 //   Fills solution into x. Warning: will modify c and d!
 //-------------------------------------------------------------------
         size_t n(x.size());
     // Modify the coefficients.
     c[0] /= b[0];                            // Division by zero risk.
     d[0] /= b[0];                            // Division by zero would imply a singular matrix.
     for (int i(1); i < n; ++i){
             double id(1.0/(b[i]-c[i-1]*a[i]));   // Division by zero risk.
         c[i] *= id;                          // Last value calculated is redundant.
         d[i] -= d[i-1] * a[i];
         d[i] *= id;                          // d[i] = (d[i] - d[i-1] * a[i]) * id
     }
     // Now back substitute.
     x[n-1] = d[n-1];
     for (int i(n-2); i > -1; --i){
         x[i]  = d[i];
             x[i] -= c[i] * x[i+1];               // x[i] = d[i] - c[i] * x[i + 1];
         }
     }
TridiagonalSolve() [2/3]
void TridiagonalSolve (const valarray< double > & a, const valarray< double > & b, valarray< double > & c, valarray< double > d, valarray< double > & x)
Definition at line 151 of file nmethods.cpp.
{
 //-------------------------------------------------------------------
 //   Fills solution into x. Warning: will modify c and d!
 //-------------------------------------------------------------------
     size_t n(x.size());
     // Modify the coefficients.
     c[0] /= b[0];                            // Division by zero risk.
     d[0] /= b[0];                            // Division by zero would imply a singular matrix.
     for (int i(1); i < n; ++i){
         double id(1.0/(b[i]-c[i-1]*a[i]));   // Division by zero risk.
         c[i] *= id;                          // Last value calculated is redundant.
         d[i] -= d[i-1] * a[i];
         d[i] *= id;                          // d[i] = (d[i] - d[i-1] * a[i]) * id
     }
     // Now back substitute.
     x[n-1] = d[n-1];
     for (int i(n-2); i > -1; --i){
         x[i]  = d[i];
         x[i] -= c[i] * x[i+1];               // x[i] = d[i] - c[i] * x[i + 1];
     }
 }
TridiagonalSolve() [3/3]
void TridiagonalSolve (const valarray< complex< double > > & a, const valarray< complex< double > > & b, valarray< complex< double > > & c, valarray< complex< double > > d, valarray< complex< double > > & x)
vfloat() [1/3]
valarray<float> vfloat (const valarray< double > & vDouble)
Definition at line 381 of file nmethods.cpp.
Referenced by Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::n(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), and Output_Data::Output_Preprocessor_1D::vNz().
{
     valarray<float> vf(vDouble.size());
     for (size_t i(0); i < vf.size(); ++i) {
         vf[i] = static_cast<float>(vDouble[i]);
     }
     return vf;
 }
vfloat() [2/3]
vector<float> vfloat (const vector< double > vDouble)
Convert data structure to float structure.
Parameters
[in] vDouble The v double
Returns
float structure
Definition at line 397 of file nmethods.cpp.
{
     vector<float> vf;
     for (size_t i(0); i < vDouble.size(); ++i) {
         vf.push_back(static_cast<float>(vDouble[i]));
     }
     return vf;
 }
vfloat() [3/3]
vector<float> vfloat (const vector< complex< double > > vDouble)
Definition at line 404 of file nmethods.cpp.
{
     vector<float> vf;
     for (size_t i(0); i < vDouble.size(); ++i) {
         vf.push_back(static_cast<float>(vDouble[i].real()));
     }
     return vf;
 }
vfloat_complex()
vector<float> vfloat_complex (const vector< complex< double > > vDouble)
Definition at line 412 of file nmethods.cpp.
Referenced by Output_Data::Output_Preprocessor_1D::Jz(), Output_Data::Output_Preprocessor_1D::Qz(), and Output_Data::Output_Preprocessor_1D::vNz().
{
     vector<float> vf;
     for (size_t i(0); i < vDouble.size(); ++i) {
         vf.push_back(static_cast<float>(vDouble[i].imag()));
     }
     return vf;
 }