OSHUN: Input Namespace Reference
Input Namespace Reference
Data Structures
class Input_List
Functions
Input_List & List ()
Function Documentation
List()
Input::Input_List & Input::List ()
Definition at line 1585 of file input.cpp.
Referenced by collisions::advance(), self_collisions::advancef00(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Output_Data::Output_Preprocessor_1D::Bx(), Output_Data::Output_Preprocessor_1D::By(), Output_Data::Output_Preprocessor_1D::Bz(), Electric_Field_Methods::Current_xyz::Current_xyz(), Output_Data::Output_Preprocessor_1D::distdump(), Parallel_Environment_1D::error_check(), Output_Data::Output_Preprocessor_1D::Ex(), Output_Data::Output_Preprocessor_1D::Ey(), Output_Data::Output_Preprocessor_1D::Ez(), Output_Data::Output_Preprocessor_1D::f0(), Output_Data::Output_Preprocessor_1D::f10(), Output_Data::Output_Preprocessor_1D::f11(), Output_Data::Output_Preprocessor_1D::f20(), Output_Data::Output_Preprocessor_1D::fl0(), Fluid_Equation_1D::Fluid_Equation_1D(), Export_Files::Folders(), Export_Files::Xport::hinit_attr(), Export_Files::Xport::hinit_attr2(), Hydro_Advection_1D::Hydro_Advection_1D(), IB_f00::IB_f00(), Electric_Field_Methods::Implicit_E_Field::Implicit_E_Field(), Setup_Y::init_f0(), Setup_Y::init_f1(), Setup_Y::initialize(), interspecies_f00_explicit_collisions::interspecies_f00_explicit_collisions(), interspecies_f00_explicit_step::interspecies_f00_explicit_step(), interspecies_flm_implicit_collisions::interspecies_flm_implicit_collisions(), interspecies_flm_implicit_step::interspecies_flm_implicit_step(), InverseBremsstrahlung::InverseBremsstrahlung(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), self_f00_implicit_collisions::loop(), InverseBremsstrahlung::loop(), main(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Output_Data::Output_Preprocessor_1D::n(), Output_Data::Output_Preprocessor_1D::ni(), Node_Communications::Node_Communications(), Output_Data::Output_Preprocessor_1D::operator()(), Parallel_Environment_1D::Parallel_Environment_1D(), Output_Data::Output_Preprocessor_1D::px(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::Qz(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_mirror_X(), Node_Communications::sameNode_periodic_X(), self_f00_explicit_collisions::self_f00_explicit_collisions(), self_f00_explicit_step::self_f00_explicit_step(), self_f00_implicit_collisions::self_f00_implicit_collisions(), self_f00_implicit_step::self_f00_implicit_step(), self_flm_implicit_collisions::self_flm_implicit_collisions(), self_flm_implicit_step::self_flm_implicit_step(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), startmessages(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::Ti(), self_f00_implicit_step::update_D_and_delta(), Output_Data::Output_Preprocessor_1D::Ux(), Output_Data::Output_Preprocessor_1D::Uy(), Output_Data::Output_Preprocessor_1D::Uz(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), Output_Data::Output_Preprocessor_1D::vNz(), and Output_Data::Output_Preprocessor_1D::Z().
{
     static Input::Input_List incoming;
     return incoming;
 }