OSHUN: VlasovFunctor1D_f1_explicitEB Class Reference
VlasovFunctor1D_f1_explicitEB Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov_f1.h>
Public Member Functions
VlasovFunctor1D_f1_explicitEB (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_f1_explicitEB ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D_f1 > SA
vector< Electric_Field_1D_f1 > EF
vector< Current_1D > JX
vector< Ampere_1D > AM
vector< Faraday_1D > FA
Detailed Description
Definition at line 134 of file vlasov_f1.h.
Constructor & Destructor Documentation
VlasovFunctor1D_f1_explicitEB()
VlasovFunctor1D_f1_explicitEB::VlasovFunctor1D_f1_explicitEB (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 693 of file vlasov_f1.cpp.
References Spatial_Advection_1D_f1::Spatial_Advection_1D_f1().
{
 //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         double pmin( pmax[s] / ( double(Np[s] * 2 - 1)) );
         SA.push_back( Spatial_Advection_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         EF.push_back( Electric_Field_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         JX.push_back( Current_1D(pmin, pmax[s], Np[s], Nx) );
 //        BF.push_back( Magnetic_Field_1D(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
 //        HA.push_back( Hydro_Advection_1D(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         AM.push_back( Ampere_1D(xmin, xmax, Nx) );
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_f1_explicitEB()
VlasovFunctor1D_f1_explicitEB::~VlasovFunctor1D_f1_explicitEB () inline
Definition at line 141 of file vlasov_f1.h.
References Spatial_Advection_1D_f1::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_f1_explicitEB::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 722 of file vlasov_f1.cpp.
References State1D::DF(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), DistFunc1D::Filterp(), and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         SA[s](Yin.DF(s),Yslope.DF(s));
         EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
 //        if (Input::List().hydromotion) HA[s](Yin.DF(s),Yin.HYDRO(),Yslope.DF(s));
 //        BF[s](Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
         AM[s](Yin.EMF(),Yslope.EMF());
         FA[s](Yin.EMF(),Yslope.EMF());
         // std::cout << "\n";
         // for (int p(0);p < Yslope.SH(0,1,0).nump(); ++p)
         // {
         //     std::cout << Yslope.SH(0,1,0)(p,43).real() << "\n";
         // }
         // exit(1);
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_f1_explicitEB::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
Definition at line 757 of file vlasov_f1.cpp.
 {}
operator()() [3/3]
void VlasovFunctor1D_f1_explicitEB::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 756 of file vlasov_f1.cpp.
 {}
Field Documentation
AM
vector<Ampere_1D> VlasovFunctor1D_f1_explicitEB::AM private
Definition at line 156 of file vlasov_f1.h.
EF
vector<Electric_Field_1D_f1> VlasovFunctor1D_f1_explicitEB::EF private
Definition at line 154 of file vlasov_f1.h.
FA
vector<Faraday_1D> VlasovFunctor1D_f1_explicitEB::FA private
Definition at line 158 of file vlasov_f1.h.
JX
vector<Current_1D> VlasovFunctor1D_f1_explicitEB::JX private
Definition at line 155 of file vlasov_f1.h.
SA
vector<Spatial_Advection_1D_f1> VlasovFunctor1D_f1_explicitEB::SA private
Definition at line 153 of file vlasov_f1.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.cpp