OSHUN: Parallel_Environment_1D Class Reference
Parallel_Environment_1D Class Reference
#include <parallel.h>
Public Member Functions
Parallel_Environment_1D ()
~Parallel_Environment_1D ()
int RANK () const
int NODES () const
int BNDX () const
void Neighbor_ImplicitE_Communications (State1D &Y)
void Neighbor_Communications (State1D &Y)
Private Member Functions
bool error_check ()
Private Attributes
int rank
int Nnodes
int bndX
Node_ImplicitE_Communications Bfield_Data
Node_Communications X_Data
Detailed Description
Definition at line 130 of file parallel.h.
Constructor & Destructor Documentation
Parallel_Environment_1D()
Parallel_Environment_1D::Parallel_Environment_1D ()
Definition at line 1023 of file parallel.cpp.
References Input::Input_List::BoundaryCells, error_check(), Input::Input_List::globdx, Input::List(), Nnodes, Input::Input_List::NxLocal, Input::Input_List::NxLocalnobnd, rank, Input::Input_List::xmaxLocal, Input::Input_List::xminGlobal, and Input::Input_List::xminLocal.
                                                   :
 //--------------------------------------------------------------
 //  Constructor, domain decomposition
 //--------------------------------------------------------------
         bndX(Input::List().bndX),           // Type of boundary
         Nnodes(Input::List().NnodesX)   // Number of nodes in X-direction
 {
     // Determination of the rank and size of the run
     MPI_Comm_size(MPI_COMM_WORLD, &Nnodes);
     MPI_Comm_rank(MPI_COMM_WORLD, &rank);
     if (error_check()) {MPI_Finalize(); exit(1);}
     // Determination of the local computational domain (i.e. the x-axis and the y-axis)
     for(size_t i(0); i < Input::List().xminLocal.size(); ++i) {
         Input::List().xminLocal[i] = Input::List().xminGlobal[i]
                                      + rank * Input::List().NxLocalnobnd[i] * Input::List().globdx[i]
                                      - Input::List().BoundaryCells * Input::List().globdx[i];
         Input::List().xmaxLocal[i] = Input::List().xminLocal[i]
                                      + (Input::List().NxLocal[i]) * Input::List().globdx[i];
     }
     // Restart files will be generated when output_step % restart_step == 0
 //          if ( ( (Input::List().n_outsteps + 1) >  Input::List().n_restarts ) &&
 //                (Input::List().n_restarts > 0)  ) {
 //               restart_step = Input::List().n_outsteps / Input::List().n_restarts ;
 //          }
 //          else restart_step = -1;
 //          if ( Input::List().restart_time > Input::List().n_restarts ) {
 //              restart_time = 0;
 //          }
 //          else restart_time = Input::List().restart_time;
 }
~Parallel_Environment_1D()
Parallel_Environment_1D::~Parallel_Environment_1D ()
Definition at line 1062 of file parallel.cpp.
 { }
Member Function Documentation
BNDX()
int Parallel_Environment_1D::BNDX () const
Definition at line 1094 of file parallel.cpp.
References bndX.
Referenced by Neighbor_Communications(), and Neighbor_ImplicitE_Communications().
 {return bndX;}
error_check()
bool Parallel_Environment_1D::error_check () private
Definition at line 1066 of file parallel.cpp.
References Input::List(), Nnodes, Input::Input_List::NnodesX, and rank.
Referenced by Parallel_Environment_1D().
{
 //--------------------------------------------------------------
 //  Temporary error check
 //--------------------------------------------------------------
     // Test the number of cells
     if (rank == 0){
         if (Input::List().NxLocal[0] < 2*Input::List().BoundaryCells+2){
             std::cout << "Not enough cells per processor" << endl;
             return true;
         }
         if ( Nnodes != (Input::List().NnodesX) ) {
             std:: cout << "the number of nodes in the input deck is "
                        << (Input::List().NnodesX) << ", terminating ..." << endl;
             return true;
         }
     }
     return false;
 }
Neighbor_Communications()
void Parallel_Environment_1D::Neighbor_Communications (State1D & Y)
Update node "0" in the x direction
(Send) 0 –> 1
(Receive) 0 <– 1
// Update node "NODES()" in the x direction
(Receive) 0 <– 1
Update node "0" in the x direction
(Send) 0 –> 1
(Receive) 0 <– 1
// Update node "NODES()" in the x direction
Definition at line 1151 of file parallel.cpp.
References BNDX(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), NODES(), RANK(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_bound_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), and X_Data.
Referenced by main().
{
 //--------------------------------------------------------------
 //  Information exchange between neighbors
 //--------------------------------------------------------------
     int moduloX(RANK() % 2);
     int RNx((RANK() + 1) % NODES()),         // This is the right neighbor
             LNx((RANK() - 1 + NODES()) % NODES()); // This is the left  neighbor
     if (NODES() > 1) {
         //even nodes
 //        if (moduloX==0){
         if (BNDX() == 0) {
             if (((RANK() != 0) && (RANK() != NODES() - 1))) {
                 X_Data.Send_right_X(Y, RNx);                  //   (Send) 0 --> 1
                 X_Data.Recv_from_left_X(Y, LNx);          //          1 --> 0 (Receive)
                 X_Data.Send_left_X(Y, LNx);               //          1 <-- 0 (Send)
                 X_Data.Recv_from_right_X(Y, RNx);               // (Receive) 0 <-- 1
             } else if (RANK() == 0) {
                 X_Data.Recv_from_left_X(Y, NODES() - 1);          //          1 --> 0 (Receive)
                 X_Data.Send_left_X(Y, NODES() - 1);               //          1 <-- 0 (Send)
                 X_Data.Send_right_X(Y, RNx);
                 X_Data.Recv_from_right_X(Y, RNx);
             } else if (RANK() == NODES() - 1) {
                 X_Data.Send_right_X(Y, 0);                  //   (Send) 0 --> 1
                 X_Data.Recv_from_right_X(Y, 0);
                 X_Data.Recv_from_left_X(Y, LNx);          //          1 --> 0 (Receive)
                 X_Data.Send_left_X(Y, LNx);               //          1 <-- 0 (Send)
             }
         } else if (BNDX() == 1) {
             if (((RANK() != 0) && (RANK() != NODES() - 1))) {
                 X_Data.Send_right_X(Y, RNx);                  //   (Send) 0 --> 1
                 X_Data.Recv_from_left_X(Y, LNx);          //          1 --> 0 (Receive)
                 X_Data.Send_left_X(Y, LNx);               //          1 <-- 0 (Send)
                 X_Data.Recv_from_right_X(Y, RNx);               // (Receive) 0 <-- 1
             } else if (RANK() == 0) {
                 X_Data.mirror_bound_Xleft(Y);
                 X_Data.Send_right_X(Y, RNx);
                 X_Data.Recv_from_right_X(Y, RNx);
             } else if (RANK() == NODES() - 1) {
                 X_Data.mirror_bound_Xright(Y);
                 X_Data.Recv_from_left_X(Y, LNx);          //          1 --> 0 (Receive)
                 X_Data.Send_left_X(Y, LNx);               //          1 <-- 0 (Send)
             }
         } else {
             cout << "Invalid Boundary." << endl;
         }
 //            //odd nodes
 //        else {
 //            X_Data.Recv_from_left_X(Y,LNx);               //           0 --> 1 (Receive)
 //            if ((RANK()!=(NODES()-1)) || (BNDX()==0)){
 //                X_Data.Send_right_X(Y,RNx);              //   (Send)  1 --> 0
 //                X_Data.Recv_from_right_X(Y,RNx);         // (Receive) 1 <-- 0
 //            }
 //            else {
 //                if (BNDX()==1) {
 //                    X_Data.mirror_bound_Xright(Y);        // Update node "N-1" in the x direction
 //                }
 //                else {
 //                    cout<<"Invalid Boundary." << endl;
 //                }
 //            }
 //            X_Data.Send_left_X(Y,LNx);                    //           0 <-- 1 (Send)
 //        }
     } else { X_Data.sameNode_bound_X(Y); }
 }
Neighbor_ImplicitE_Communications()
void Parallel_Environment_1D::Neighbor_ImplicitE_Communications (State1D & Y)
Definition at line 1099 of file parallel.cpp.
References Bfield_Data, BNDX(), Node_ImplicitE_Communications::mirror_bound_Xleft(), Node_ImplicitE_Communications::mirror_bound_Xright(), NODES(), RANK(), Node_ImplicitE_Communications::Recv_from_left_X(), Node_ImplicitE_Communications::Recv_from_right_X(), Node_ImplicitE_Communications::sameNode_bound_X(), Node_ImplicitE_Communications::Send_left_X(), and Node_ImplicitE_Communications::Send_right_X().
Referenced by main().
{
 //--------------------------------------------------------------
 //  Information exchange between neighbors
 //--------------------------------------------------------------
     int moduloX(RANK()%2);
     int RNx((RANK()+1)%NODES()),         // This is the right neighbor
             LNx((RANK()-1+NODES())%NODES()); // This is the left  neighbor
     if (NODES() > 1) {
         //even nodes
         if (moduloX==0){
             Bfield_Data.Send_right_X(Y,RNx);                  //   (Send) 0 --> 1
             if ((RANK() != 0) || (BNDX()==0)){
                 Bfield_Data.Recv_from_left_X(Y,LNx);          //          1 --> 0 (Receive)
                 Bfield_Data.Send_left_X(Y,LNx);               //          1 <-- 0 (Send)
             }
             else {
                 if (BNDX()==1) {
                     Bfield_Data.mirror_bound_Xleft(Y);        // Update node "0" in the x direction
                 }
                 else {
                     cout<<"Invalid Boundary." << endl;
                 }
             }
             Bfield_Data.Recv_from_right_X(Y,RNx);               // (Receive) 0 <-- 1
         }
             //odd nodes
         else {
             Bfield_Data.Recv_from_left_X(Y,LNx);               //           0 --> 1 (Receive)
             if ((RANK()!=(NODES()-1)) || (BNDX()==0)){
                 Bfield_Data.Send_right_X(Y,RNx);              //   (Send)  1 --> 0
                 Bfield_Data.Recv_from_right_X(Y,RNx);         // (Receive) 1 <-- 0
             }
             else {
                 if (BNDX()==1) {
                     Bfield_Data.mirror_bound_Xright(Y);        // Update node "N-1" in the x direction
                 }
                 else {
                     cout<<"Invalid Boundary." << endl;;
                 }
             }
             Bfield_Data.Send_left_X(Y,LNx);                    //           0 <-- 1 (Send)
         }
     }
     else { Bfield_Data.sameNode_bound_X(Y); }
 }
NODES()
int Parallel_Environment_1D::NODES () const
Definition at line 1092 of file parallel.cpp.
References Nnodes.
Referenced by Output_Data::Output_Preprocessor_1D::Bx(), Output_Data::Output_Preprocessor_1D::By(), Output_Data::Output_Preprocessor_1D::Bz(), Output_Data::Output_Preprocessor_1D::Ex(), Output_Data::Output_Preprocessor_1D::Ey(), Output_Data::Output_Preprocessor_1D::Ez(), Output_Data::Output_Preprocessor_1D::f0(), Output_Data::Output_Preprocessor_1D::f10(), Output_Data::Output_Preprocessor_1D::f11(), Output_Data::Output_Preprocessor_1D::f20(), Output_Data::Output_Preprocessor_1D::fl0(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Output_Data::Output_Preprocessor_1D::n(), Neighbor_Communications(), Neighbor_ImplicitE_Communications(), Output_Data::Output_Preprocessor_1D::ni(), Output_Data::Output_Preprocessor_1D::px(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::Qz(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::Ti(), Output_Data::Output_Preprocessor_1D::Ux(), Output_Data::Output_Preprocessor_1D::Uy(), Output_Data::Output_Preprocessor_1D::Uz(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), Output_Data::Output_Preprocessor_1D::vNz(), and Output_Data::Output_Preprocessor_1D::Z().
 {return Nnodes;}
RANK()
int Parallel_Environment_1D::RANK () const
Definition at line 1090 of file parallel.cpp.
References rank.
Referenced by Output_Data::Output_Preprocessor_1D::Bx(), Output_Data::Output_Preprocessor_1D::By(), Output_Data::Output_Preprocessor_1D::Bz(), Output_Data::Output_Preprocessor_1D::Ex(), Output_Data::Output_Preprocessor_1D::Ey(), Output_Data::Output_Preprocessor_1D::Ez(), Output_Data::Output_Preprocessor_1D::f0(), Output_Data::Output_Preprocessor_1D::f10(), Output_Data::Output_Preprocessor_1D::f11(), Output_Data::Output_Preprocessor_1D::f20(), Output_Data::Output_Preprocessor_1D::fl0(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), main(), Output_Data::Output_Preprocessor_1D::n(), Neighbor_Communications(), Neighbor_ImplicitE_Communications(), Output_Data::Output_Preprocessor_1D::ni(), Output_Data::Output_Preprocessor_1D::px(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::Qz(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::Ti(), Output_Data::Output_Preprocessor_1D::Ux(), Output_Data::Output_Preprocessor_1D::Uy(), Output_Data::Output_Preprocessor_1D::Uz(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), Output_Data::Output_Preprocessor_1D::vNz(), and Output_Data::Output_Preprocessor_1D::Z().
 {return rank;}
Field Documentation
Bfield_Data
Node_ImplicitE_Communications Parallel_Environment_1D::Bfield_Data private
Definition at line 166 of file parallel.h.
Referenced by Neighbor_ImplicitE_Communications().
bndX
int Parallel_Environment_1D::bndX private
Definition at line 163 of file parallel.h.
Referenced by BNDX().
Nnodes
int Parallel_Environment_1D::Nnodes private
Definition at line 160 of file parallel.h.
Referenced by error_check(), NODES(), and Parallel_Environment_1D().
rank
int Parallel_Environment_1D::rank private
Definition at line 159 of file parallel.h.
Referenced by error_check(), Parallel_Environment_1D(), and RANK().
X_Data
Node_Communications Parallel_Environment_1D::X_Data private
Definition at line 167 of file parallel.h.
Referenced by Neighbor_Communications().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/parallel.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/parallel.cpp