OSHUN: CGSlice_iter< T > Class Template Reference
CGSlice_iter< T > Class Template Reference
#include <lib-array.h>
Public Member Functions
CGSlice_iter (valarray< T > *vv, gslice gss)
CGSlice_iter end () const
CGSlice_iter & operator++ ()
CGSlice_iter operator++ (int)
const T & operator[] (size_t i) const
const T & operator() (size_t i) const
const T & operator* () const
Private Member Functions
const T & ref (size_t i) const
Private Attributes
valarray< T > * v
gslice gs
size_t curr
valarray< size_t > gsizes
Friends
bool operator== (const CGSlice_iter &p, const CGSlice_iter &q)
bool operator!= (const CGSlice_iter &p, const CGSlice_iter &q)
bool operator< (const CGSlice_iter &p, const CGSlice_iter &q)
Detailed Description
template<class T>
class CGSlice_iter< T >
Definition at line 167 of file lib-array.h.
Constructor & Destructor Documentation
CGSlice_iter()
template<class T > CGSlice_iter< T >::CGSlice_iter (valarray< T > * vv, gslice gss)
Definition at line 227 of file lib-array.h.
References CGSlice_iter< T >::gsizes.
                                                         :
         v(vv), gs(gss), curr(0), gsizes(gs.size()){
     for (int ic=1; ic < gsizes.size(); ++ic) {
         gsizes[gss.size().size()-ic-1] *= gsizes[gss.size().size()-ic];
     }
 }
Member Function Documentation
end()
template<class T> CGSlice_iter CGSlice_iter< T >::end () const inline
Definition at line 191 of file lib-array.h.
References CGSlice_iter< T >::curr.
{
         CGSlice_iter t = *this;
         t.curr = gsizes[0];
         return t;
     }
operator()()
template<class T> const T& CGSlice_iter< T >::operator() (size_t i) const inline
Definition at line 201 of file lib-array.h.
References GSlice_iter< T >::ref().
Referenced by Array2D< complex< double > >::array().
 {return ref(i);}  // Fortran style subscript
operator*()
template<class T> const T& CGSlice_iter< T >::operator* () const inline
Definition at line 202 of file lib-array.h.
References GSlice_iter< T >::ref().
 {return ref(curr);}        // Current element
operator++() [1/2]
template<class T> CGSlice_iter& CGSlice_iter< T >::operator++ () inline
Definition at line 197 of file lib-array.h.
References GSlice_iter< T >::curr.
 {++curr; return *this;} //prefix
operator++() [2/2]
template<class T> CGSlice_iter CGSlice_iter< T >::operator++ (int) inline
Definition at line 198 of file lib-array.h.
References GSlice_iter< T >::curr.
 {CGSlice_iter t = *this; ++curr; return t;} //postfix
operator[]()
template<class T> const T& CGSlice_iter< T >::operator[] (size_t i) const inline
Definition at line 200 of file lib-array.h.
References GSlice_iter< T >::ref().
 {return ref(i);}  // C style subscript
ref()
template<class T > const T & CGSlice_iter< T >::ref (size_t i) const private
Definition at line 213 of file lib-array.h.
References GSlice_iter< T >::gs, GSlice_iter< T >::gsizes, and GSlice_iter< T >::v.
{
     size_t loc(0);
     for (size_t ic = 0; ic < gsizes.size()-1; ++ic){
         loc += (i/gsizes[ic+1]) * gs.stride()[ic];
         i %= gsizes[ic+1];
     }
     loc += i * gs.stride()[gsizes.size()-1];
     return (*v)[gs.start()+loc];
 }
Friends And Related Function Documentation
operator!=
template<class T> bool operator!= (const CGSlice_iter< T > & p, const CGSlice_iter< T > & q) friend
Definition at line 248 of file lib-array.h.
{
     return !(p==q);
 }
operator<
template<class T> bool operator< (const CGSlice_iter< T > & p, const CGSlice_iter< T > & q) friend
Definition at line 253 of file lib-array.h.
{
     size_t count(0);
     if (p.curr<q.curr && p.gs.start() == q.gs.start())
         while (  (p.gs.stride()[count] == p.gs.stride()[count])
                  && (p.gs.size()[count]   == p.gs.size()[count]  ))
             if (count++ == q.gs.size().size()-1) return true;
     return false;
 }
operator==
template<class T> bool operator== (const CGSlice_iter< T > & p, const CGSlice_iter< T > & q) friend
Definition at line 238 of file lib-array.h.
{
     size_t count(0);
     if (p.curr==q.curr && p.gs.start() == q.gs.start())
         while (  (p.gs.stride()[count] == p.gs.stride()[count])
                  && (p.gs.size()[count]   == p.gs.size()[count]  ))
             if (count++ == q.gs.size().size()-1) return true;
     return false;
 }
Field Documentation
curr
template<class T> size_t CGSlice_iter< T >::curr private
Definition at line 182 of file lib-array.h.
Referenced by CGSlice_iter< T >::end(), and operator==().
gs
template<class T> gslice CGSlice_iter< T >::gs private
Definition at line 181 of file lib-array.h.
Referenced by operator==().
gsizes
template<class T> valarray<size_t> CGSlice_iter< T >::gsizes private
Definition at line 183 of file lib-array.h.
Referenced by CGSlice_iter< T >::CGSlice_iter().
v
template<class T> valarray<T>* CGSlice_iter< T >::v private
Definition at line 180 of file lib-array.h.
Referenced by Array2D< complex< double > >::array().
The documentation for this class was generated from the following file:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/lib-array.h