OSHUN: VlasovFunctor1D_explicitEB Class Reference
VlasovFunctor1D_explicitEB Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov.h>
Public Member Functions
VlasovFunctor1D_explicitEB (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_explicitEB ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D > SA
vector< Electric_Field_1D > EF
vector< Current_1D > JX
vector< Ampere_1D > AM
vector< Faraday_1D > FA
Detailed Description
Definition at line 210 of file vlasov.h.
Constructor & Destructor Documentation
VlasovFunctor1D_explicitEB()
VlasovFunctor1D_explicitEB::VlasovFunctor1D_explicitEB (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 1538 of file vlasov.cpp.
References Ampere_1D::Ampere_1D().
{
 //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         SA.push_back( Spatial_Advection_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         EF.push_back( Electric_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         JX.push_back( Current_1D(0.0, pmax[s], Np[s], Nx) );
         AM.push_back( Ampere_1D(xmin, xmax, Nx) );
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_explicitEB()
VlasovFunctor1D_explicitEB::~VlasovFunctor1D_explicitEB () inline
Definition at line 217 of file vlasov.h.
References Spatial_Advection_1D::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_explicitEB::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 1561 of file vlasov.cpp.
References State1D::DF(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), DistFunc1D::Filterp(), DistFunc1D::l0(), and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         if (Yin.DF(s).l0() == 1) {
             SA[s].f1only(Yin.DF(s),Yslope.DF(s));
             EF[s].f1only(Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         }
         else{
             SA[s](Yin.DF(s),Yslope.DF(s));
             EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         }
         JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
         AM[s](Yin.EMF(),Yslope.EMF());
         FA[s](Yin.EMF(),Yslope.EMF());
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_explicitEB::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 1589 of file vlasov.cpp.
 {}
operator()() [3/3]
void VlasovFunctor1D_explicitEB::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 1588 of file vlasov.cpp.
 {}
Field Documentation
AM
vector<Ampere_1D> VlasovFunctor1D_explicitEB::AM private
Definition at line 232 of file vlasov.h.
EF
vector<Electric_Field_1D> VlasovFunctor1D_explicitEB::EF private
Definition at line 230 of file vlasov.h.
FA
vector<Faraday_1D> VlasovFunctor1D_explicitEB::FA private
Definition at line 234 of file vlasov.h.
JX
vector<Current_1D> VlasovFunctor1D_explicitEB::JX private
Definition at line 231 of file vlasov.h.
SA
vector<Spatial_Advection_1D> VlasovFunctor1D_explicitEB::SA private
Definition at line 229 of file vlasov.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.cpp