OSHUN: Hydro_Functor Class Reference
Hydro_Functor Class Reference
#include <fluid.h>
Public Member Functions
Hydro_Functor (double xmin, double xmax, size_t numx)
Constructor for hydro equations.
~Hydro_Functor ()
void operator() (const State1D &Hin, State1D &Hslope)
void operator() (const State1D &Hin, State1D &Hslope, size_t dir)
void operator() (const State1D &H1in, const State1D &H2in, State1D &Hslope)
Private Attributes
double idx
size_t szx
Fluid_Equation_1D FEQ
Detailed Description
Definition at line 41 of file fluid.h.
Constructor & Destructor Documentation
Hydro_Functor()
Hydro_Functor::Hydro_Functor (double xmin, double xmax, size_t numx)
Constructor for hydro equations.
Definition at line 36 of file fluid.cpp.
                                                                  :
     idx(numx/(xmax-xmin)), szx(numx), FEQ(xmin,xmax,numx) {}
~Hydro_Functor()
Hydro_Functor::~Hydro_Functor () inline
Definition at line 46 of file fluid.h.
 { };
Member Function Documentation
operator()() [1/3]
void Hydro_Functor::operator() (const State1D & Hin, State1D & Hslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 40 of file fluid.cpp.
References Fluid_Equation_1D::chargefraction(), Fluid_Equation_1D::density(), State1D::DF(), State1D::EMF(), FEQ, DistFunc1D::getdensity(), DistFunc1D::getpressure(), State1D::HYDRO(), szx, Fluid_Equation_1D::updateE(), and Fluid_Equation_1D::velocity().
{
     Yslope = 0.0;
     valarray<double> electronpressure(0.0,szx), electrondensity(0.0, szx);
     Array2D<double> electroncurrent(3,szx);
     electrondensity = Yin.DF(0).getdensity();
     electronpressure = Yin.DF(0).getpressure();
     FEQ.density(         Yin.HYDRO(), Yslope.HYDRO());
     FEQ.chargefraction(  Yin.HYDRO(), Yslope.HYDRO());
     FEQ.velocity(        Yin        , Yslope.HYDRO(), electrondensity, electronpressure, electroncurrent);
     FEQ.updateE(         Yin.HYDRO(), Yslope.EMF());
 }
operator()() [2/3]
void Hydro_Functor::operator() (const State1D & Hin, State1D & Hslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 56 of file fluid.cpp.
 {}
operator()() [3/3]
void Hydro_Functor::operator() (const State1D & H1in, const State1D & H2in, State1D & Hslope)
Definition at line 57 of file fluid.cpp.
 {}
Field Documentation
FEQ
Fluid_Equation_1D Hydro_Functor::FEQ private
Definition at line 56 of file fluid.h.
Referenced by operator()().
idx
double Hydro_Functor::idx private
Definition at line 54 of file fluid.h.
szx
size_t Hydro_Functor::szx private
Definition at line 55 of file fluid.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/fluid.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/fluid.cpp