OSHUN: Electric_Field_1D_f1 Class Reference
Electric_Field_1D_f1 Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov_f1.h>
Public Member Functions
Electric_Field_1D_f1 (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
void operator() (const DistFunc1D &Din, const Field1D &FEx, const Field1D &FEy, const Field1D &FEz, DistFunc1D &Dh)
void Implicit_Ex (const DistFunc1D &Din, const Field1D &FEx, DistFunc1D &Dh)
void Implicit_Ey (const DistFunc1D &Din, const Field1D &FEy, DistFunc1D &Dh)
void Implicit_Ez (const DistFunc1D &Din, const Field1D &FEz, DistFunc1D &Dh)
Private Member Functions
void MakeG00 (SHarmonic1D &f)
void MakeGH (SHarmonic1D &f, size_t l)
Private Attributes
SHarmonic1D H
SHarmonic1D G
SHarmonic1D TMP
complex< double > A100
complex< double > C100
complex< double > A210
complex< double > B211
complex< double > C311
complex< double > A310
valarray< complex< double > > pr
valarray< complex< double > > invpr
valarray< complex< double > > Hp0
Detailed Description
Definition at line 42 of file vlasov_f1.h.
Constructor & Destructor Documentation
Electric_Field_1D_f1()
Electric_Field_1D_f1::Electric_Field_1D_f1 (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
Definition at line 37 of file vlasov_f1.cpp.
References A100, A210, A310, B211, C100, C311, Hp0, invpr, and pr.
         : Hp0(Nl+1),
           H(Np,Nx), G(Np,Nx), TMP(Np,Nx),
           pr(Algorithms::MakeAxis(static_cast<complex<double> >(pmin),
                                   static_cast<complex<double> >(pmax),
                                   Np)),
           invpr(pr)
 {
 //      - - - - - - - - - - - - - - - - - - - - - - - - - - -
          complex<double> lc, mc;
 //       Inverted momentum axis
          for (size_t i(0); i < pr.size(); ++i) {
              invpr[i] = 1.0/pr[i];
          }
          double idp = (-1.0)/ (2.0*(pmax-pmin)/double(Np-1)); // -1/(2dp)
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
         A100 = static_cast<complex<double>>(idp);
         C100 = static_cast<complex<double>>(0.5*idp);
         A210 = static_cast<complex<double>>(1.0/3.0*idp);
         B211 = static_cast<complex<double>>(2.0/3.0);
         A310 = static_cast<complex<double>>(2.0/5.0*idp);
         C311 = static_cast<complex<double>>(-0.5*idp/5.0);
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       -2*Dp*H at the 0 momentum cell
          Hp0[0] = 1.0 / pr[0];
          for (size_t l(1); l < Nl+1; ++l) {
              double ld(l);
              Hp0[l] = Hp0[l-1] * (pr[0]/pr[1]) * (2.0*ld+1.0)/(2.0*ld-1.0);
          }
          Hp0 *= (-2.0)*(pr[1]-pr[0]);
 }
Member Function Documentation
Implicit_Ex()
void Electric_Field_1D_f1::Implicit_Ex (const DistFunc1D & Din, const Field1D & FEx, DistFunc1D & Dh)
Definition at line 142 of file vlasov_f1.cpp.
References A100, A210, Field1D::array(), G, H, MakeG00(), MakeGH(), SHarmonic1D::mxaxis(), and DistFunc1D::q().
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in x,
 //  which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     valarray<complex<double> > Ex(FEx.array());
     Ex *= Din.q();
 //      m = 0, l = 0
         MakeG00(Din(0,0));
         Ex *= A100;             Dh(1,0) += G.mxaxis(Ex);
 //      m = 0, l = 1
         MakeGH(Din(1,0),1);
         Ex *= A210 / A100;   Dh(0,0) += H.mxaxis(Ex);
         // Ex *= A1(1,0) / A2(1,0);   Dh(2,0) += G.mxaxis(Ex);
 //      m = 0, l = 2
         // Din(2,0)  = Din(0,0);
         // Din(2,0) *= static_cast<complex<double>>(1.0/3.0);
         // MakeGH(Din(2,0),2);
         // Ex *= A310 / A210;      TMP = H;      Dh(1,0) += H.mxaxis(Ex);
 }
Implicit_Ey()
void Electric_Field_1D_f1::Implicit_Ey (const DistFunc1D & Din, const Field1D & FEy, DistFunc1D & Dh)
Definition at line 171 of file vlasov_f1.cpp.
References Field1D::array(), B211, C100, G, H, MakeG00(), MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), and SHarmonic1D::Re().
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in y
 //  and z, which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     valarray<complex<double> > Em(FEy.array());
     valarray<complex<double> > Ep(FEy.array());
     Em *= Din.q();;
     Ep *= Din.q();;
 //      m = 0, l = 0
         MakeG00(Din(0,0));
         Em *= C100;            Dh(1,1) += G.mxaxis(Em);
 //      m = 0, l = 1
         // MakeGH(Din(1,0),1);
         // Em *= C1[1]   / C1[0];  Dh(2,1) += G.mxaxis(Em);
 //      m = 0, 1 < l < l0
         // Din(2,0)  = Din(0,0);
         // Din(2,0) *= static_cast<complex<double>>(1.0/3.0);
         // MakeGH(Din(2,0),2);
         // Em *= C311 / C100;                    Dh(1,1) += TMP.mxaxis(Em);
 //      m = 0,  l = 3
         // MakeGH(Din(3,0),3);
         // Em *= C3[3]   / C3[2];  Dh(2,1) += H.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
         MakeGH(Din(1,1),1);
         Ep *= B211;             H = H.mxaxis(Ep); Dh(0,0) += H.Re();
 }
Implicit_Ez()
void Electric_Field_1D_f1::Implicit_Ez (const DistFunc1D & Din, const Field1D & FEz, DistFunc1D & Dh)
Definition at line 212 of file vlasov_f1.cpp.
References Field1D::array(), B211, C100, C311, G, H, MakeG00(), MakeGH(), SHarmonic1D::mxaxis(), SHarmonic1D::Re(), and TMP.
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in y
 //  and z, which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Em(FEz.array());
     Em *= (-1.0)*ii;
     valarray<complex<double> > Ep(FEz.array());
     Ep *= ii;
     //      m = 0, l = 0
         MakeG00(Din(0,0));
         Em *= C100;            Dh(1,1) += G.mxaxis(Em);
 //      m = 0, l = 1
         // MakeGH(Din(1,0),1);
         // Em *= C1[1]   / C1[0];  Dh(2,1) += G.mxaxis(Em);
 //      m = 0, 1 < l < l0
         Din(2,0)  = Din(0,0);
         Din(2,0) *= static_cast<complex<double>>(1.0/3.0);
         MakeGH(Din(2,0),2);
         Em *= C311 / C100;                    Dh(1,1) += TMP.mxaxis(Em);
 // //      m = 0,  l = 3
 //         MakeGH(Din(3,0),3);
 //         Em *= C3[3]   / C3[2];  Dh(2,1) += H.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
         MakeGH(Din(1,1),1);
         Ep *= B211;             H = H.mxaxis(Ep); Dh(0,0) += H.Re();
 }
MakeG00()
void Electric_Field_1D_f1::MakeG00 (SHarmonic1D & f) private
Definition at line 278 of file vlasov_f1.cpp.
References SHarmonic1D::Dp(), G, SHarmonic1D::numx(), and pr.
Referenced by Implicit_Ex(), Implicit_Ey(), Implicit_Ez(), and operator()().
{
 //--------------------------------------------------------------
     G = f; G = G.Dp();
     complex<double> p0p1_sq( pr[0]*pr[0]/(pr[1]*pr[1]) ),
             inv_mp0p1_sq( 1.0/(1.0-p0p1_sq) ),
             g_r = -4.0*(pr[1]-pr[0]) * pr[0]/(pr[1]*pr[1]),
             f00;
     for (size_t i(0); i < f.numx(); ++i) {
         f00    = ( f(0,i) - f(1,i) * p0p1_sq) * inv_mp0p1_sq;
         G(0,i) = ( f(1,i) - f00) * g_r;
     }
 }
MakeGH()
void Electric_Field_1D_f1::MakeGH (SHarmonic1D & f, size_t l) private
Definition at line 257 of file vlasov_f1.cpp.
References SHarmonic1D::Dp(), G, H, Hp0, invpr, SHarmonic1D::mpaxis(), SHarmonic1D::numx(), and pr.
Referenced by Implicit_Ex(), Implicit_Ey(), Implicit_Ez(), and operator()().
{
 //--------------------------------------------------------------
     valarray<complex<double> > invpax(invpr);
     complex<double> ld(el);
     invpax *= (-2.0)*(ld+1.0) * (pr[1]-pr[0]);
     G = f;                   H = f;
     G = G.Dp();
     H  = H.mpaxis(invpax);
     H += G;
     G *= -(2.0*ld+1.0)/ld;
     G += H;
     for (size_t i(0); i < G.numx(); ++i) G(0,i) = 0.0;
     for (size_t i(0); i < H.numx(); ++i) H(0,i) = f(1,i) * Hp0[el];
 }
operator()()
void Electric_Field_1D_f1::operator() (const DistFunc1D & Din, const Field1D & FEx, const Field1D & FEy, const Field1D & FEz, DistFunc1D & Dh)
Definition at line 81 of file vlasov_f1.cpp.
References A100, A210, Field1D::array(), B211, C100, G, H, DistFunc1D::l0(), DistFunc1D::m0(), MakeG00(), MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), SHarmonic1D::Re(), and TMP.
{
 //--------------------------------------------------------------
 //  This is the core calculation for the electric field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Ex(FEx.array());
     valarray<complex<double> > Em(FEz.array());
     Em *= (-1.0)*ii;
     Em += FEy.array();
     valarray<complex<double> > Ep(FEz.array());
     Ep *= ii;
     Ep += FEy.array();
     Ex *= Din.q();
     Em *= Din.q();
     Ep *= Din.q();
     size_t l0(Din.l0());
     size_t m0(Din.m0());
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeG00(Din(0,0));
     Ex *= A100; TMP = G; Dh(1,0) += G.mxaxis(Ex);
     Em *= C100;            Dh(1,1) += TMP.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(1,0),1);
     Ex *= A210 / A100;          Dh(0,0) += H.mxaxis(Ex);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, 1 < l < l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         // Din(2,0)  = Din(0,0);
         // Din(2,0) *= static_cast<complex<double>>(1.0/3.0);
         // MakeGH(Din(2,0),2);
         // Ex *= A310 / A210;      TMP = H;      Dh(1,0) += H.mxaxis(Ex);
         // Em *= C311 / C100;                    Dh(1,1) += TMP.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         MakeGH(Din(1,1),1);
         Ep *= B211;              H = H.mxaxis(Ep);     Dh(0,0) += H.Re();
 }
Field Documentation
A100
complex<double> Electric_Field_1D_f1::A100 private
Definition at line 63 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), Implicit_Ex(), and operator()().
A210
complex<double> Electric_Field_1D_f1::A210 private
Definition at line 63 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), Implicit_Ex(), and operator()().
A310
complex<double> Electric_Field_1D_f1::A310 private
Definition at line 63 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1().
B211
complex<double> Electric_Field_1D_f1::B211 private
Definition at line 63 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), Implicit_Ey(), Implicit_Ez(), and operator()().
C100
complex<double> Electric_Field_1D_f1::C100 private
Definition at line 63 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), Implicit_Ey(), Implicit_Ez(), and operator()().
C311
complex<double> Electric_Field_1D_f1::C311 private
Definition at line 63 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), and Implicit_Ez().
G
SHarmonic1D Electric_Field_1D_f1::G private
Definition at line 61 of file vlasov_f1.h.
Referenced by Implicit_Ex(), Implicit_Ey(), Implicit_Ez(), MakeG00(), MakeGH(), and operator()().
H
SHarmonic1D Electric_Field_1D_f1::H private
Definition at line 61 of file vlasov_f1.h.
Referenced by Implicit_Ex(), Implicit_Ey(), Implicit_Ez(), MakeGH(), and operator()().
Hp0
valarray< complex<double> > Electric_Field_1D_f1::Hp0 private
Definition at line 69 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), and MakeGH().
invpr
valarray< complex<double> > Electric_Field_1D_f1::invpr private
Definition at line 69 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), and MakeGH().
pr
valarray< complex<double> > Electric_Field_1D_f1::pr private
Definition at line 69 of file vlasov_f1.h.
Referenced by Electric_Field_1D_f1(), MakeG00(), and MakeGH().
TMP
SHarmonic1D Electric_Field_1D_f1::TMP private
Definition at line 61 of file vlasov_f1.h.
Referenced by Implicit_Ez(), and operator()().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.cpp