OSHUN: VlasovFunctor1D_f1_explicitE Class Reference
VlasovFunctor1D_f1_explicitE Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov_f1.h>
Public Member Functions
VlasovFunctor1D_f1_explicitE (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_f1_explicitE ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D_f1 > SA
vector< Electric_Field_1D_f1 > EF
vector< Current_1D > JX
vector< Ampere_1D > AM
vector< Magnetic_Field_1D_f1 > BF
vector< Faraday_1D > FA
Detailed Description
Definition at line 102 of file vlasov_f1.h.
Constructor & Destructor Documentation
VlasovFunctor1D_f1_explicitE()
VlasovFunctor1D_f1_explicitE::VlasovFunctor1D_f1_explicitE (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 633 of file vlasov_f1.cpp.
References Spatial_Advection_1D_f1::Spatial_Advection_1D_f1().
{
 //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         double pmin( pmax[s] / ( double(Np[s] * 2 - 1)) );
         SA.push_back( Spatial_Advection_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         EF.push_back( Electric_Field_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         JX.push_back( Current_1D(pmin, pmax[s], Np[s], Nx) );
         BF.push_back( Magnetic_Field_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
 //        HA.push_back( Hydro_Advection_1D(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         AM.push_back( Ampere_1D(xmin, xmax, Nx) );
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_f1_explicitE()
VlasovFunctor1D_f1_explicitE::~VlasovFunctor1D_f1_explicitE () inline
Definition at line 109 of file vlasov_f1.h.
References Spatial_Advection_1D_f1::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_f1_explicitE::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 662 of file vlasov_f1.cpp.
References EMF1D::Bx(), EMF1D::By(), EMF1D::Bz(), State1D::DF(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), DistFunc1D::Filterp(), and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         SA[s](Yin.DF(s),Yslope.DF(s));
         EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
 //        if (Input::List().hydromotion) HA[s](Yin.DF(s),Yin.HYDRO(),Yslope.DF(s));
         BF[s](Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
         AM[s](Yin.EMF(),Yslope.EMF());
         FA[s](Yin.EMF(),Yslope.EMF());
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_f1_explicitE::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
Definition at line 689 of file vlasov_f1.cpp.
 {}
operator()() [3/3]
void VlasovFunctor1D_f1_explicitE::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 688 of file vlasov_f1.cpp.
 {}
Field Documentation
AM
vector<Ampere_1D> VlasovFunctor1D_f1_explicitE::AM private
Definition at line 124 of file vlasov_f1.h.
BF
vector<Magnetic_Field_1D_f1> VlasovFunctor1D_f1_explicitE::BF private
Definition at line 125 of file vlasov_f1.h.
EF
vector<Electric_Field_1D_f1> VlasovFunctor1D_f1_explicitE::EF private
Definition at line 122 of file vlasov_f1.h.
FA
vector<Faraday_1D> VlasovFunctor1D_f1_explicitE::FA private
Definition at line 126 of file vlasov_f1.h.
JX
vector<Current_1D> VlasovFunctor1D_f1_explicitE::JX private
Definition at line 123 of file vlasov_f1.h.
SA
vector<Spatial_Advection_1D_f1> VlasovFunctor1D_f1_explicitE::SA private
Definition at line 121 of file vlasov_f1.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.cpp