    #ifndef CUDA_COMPILE_CONFIG_H
    #define CUDA_COMPILE_CONFIG_H
	
	
	
	//#define VERIFY_CUDA_EXPLICIT_ELECTRONS_COLLSION_CALCULATIONS 1
	//#define VERIFY_CUDA_EXPLICIT_ELECTRONS_COLLSION_CALCULATIONS 1
	//#define ASSERT_PADDING_CELLS_REMAIN_ZERO_IN_EXPLICIT_ELECTRONS_COLLSION_CALCULATION
	//#define REMOVE_STUFF_TO_DEBUG_FASTER_BUT_PUT_IT_BACK_CAUSE_YOU_GET_WRONG_ANSWER_WITHOUT
	
	// this turns on beugging statements...
	//#define FRED 1
	
	
	
	
	
	
	
	
	
	
	#endif