OSHUN: Array2D_cmplx< T > Class Template Reference
Array2D_cmplx< T > Class Template Reference
#include <lib-array.h>
Public Member Functions
Array2D_cmplx (size_t x, size_t y)
Array2D_cmplx (const Array2D_cmplx &other)
~Array2D_cmplx ()
size_t dim () const
size_t dim1 () const
size_t dim2 () const
valarray< T > & array () const
T & operator[] (size_t i)
T operator[] (size_t i) const
T & real (size_t i, size_t j)
T real (size_t i, size_t j) const
T & imag (size_t i, size_t j)
T imag (size_t i, size_t j) const
GSlice_iter< T > d1c (size_t b, size_t e)
GSlice_iter< T > d2c (size_t b, size_t e)
GSlice_iter< T > SubArray2D (size_t st, size_t nx, size_t ny)
CGSlice_iter< T > d2c (size_t b, size_t e) const
CGSlice_iter< T > d1c (size_t b, size_t e) const
CGSlice_iter< T > SubArray2D (size_t st, size_t nx, size_t ny) const
Array2D_cmplx & operator= (const T &d)
Array2D_cmplx & operator= (const complex< T > &c)
Array2D_cmplx & operator= (const Array2D< T > &other)
Array2D_cmplx & operator= (const Array2D_cmplx &other)
Array2D_cmplx & operator*= (const T &d)
Array2D_cmplx & operator*= (const complex< T > &c)
Array2D_cmplx & operator*= (const Array2D< T > &vmulti)
Array2D_cmplx & operator*= (const Array2D_cmplx &vmulti)
Array2D_cmplx & operator+= (const T &d)
Array2D_cmplx & operator+= (const complex< T > &c)
Array2D_cmplx & operator+= (const Array2D< T > &vadd)
Array2D_cmplx & operator+= (const Array2D_cmplx &vadd)
Array2D_cmplx & operator-= (const T &d)
Array2D_cmplx & operator-= (const complex< T > &c)
Array2D_cmplx & operator-= (const Array2D< T > &vmin)
Array2D_cmplx & operator-= (const Array2D_cmplx &vmin)
Array2D_cmplx & multid1 (const valarray< T > &vmulti)
Array2D_cmplx & multid1 (const valarray< complex< T > > &vmulti)
Array2D_cmplx & multid2 (const valarray< T > &vmulti)
Array2D_cmplx & multid2 (const valarray< complex< T > > &vmulti)
Array2D_cmplx & Dd1 ()
Array2D_cmplx & Dd2 ()
Array2D_cmplx & Filterd1 (size_t N)
Private Attributes
valarray< T > * v
size_t d1
size_t d2
size_t td1
Detailed Description
template<class T>
class Array2D_cmplx< T >
Definition at line 624 of file lib-array.h.
Constructor & Destructor Documentation
Array2D_cmplx() [1/2]
template<class T > Array2D_cmplx< T >::Array2D_cmplx (size_t x, size_t y)
Definition at line 703 of file lib-array.h.
References Array2D_cmplx< T >::d1, Array2D_cmplx< T >::d2, Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
                                                                     : d1(x), d2(y) {
     td1 = 2*d1;
     v = new valarray<T>(2*d1*d2);
 }
Array2D_cmplx() [2/2]
template<class T > Array2D_cmplx< T >::Array2D_cmplx (const Array2D_cmplx< T > & other)
Definition at line 708 of file lib-array.h.
References Array2D_cmplx< T >::array(), Array2D_cmplx< T >::d1, Array2D_cmplx< T >::d2, Array2D_cmplx< T >::dim1(), Array2D_cmplx< T >::dim2(), Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     d1  = other.dim1();
     d2  = other.dim2();
     td1 = 2*d1;
     v = new valarray<T>(2*d1*d2);
     (*v) = other.array();
 }
~Array2D_cmplx()
template<class T > Array2D_cmplx< T >::~Array2D_cmplx ()
Definition at line 716 of file lib-array.h.
References Array2D_cmplx< T >::v.
{
     delete v;
 }
Member Function Documentation
array()
template<class T> valarray<T>& Array2D_cmplx< T >::array () const inline
Definition at line 643 of file lib-array.h.
References Array2D< T >::d1c(), Array2D< T >::d2c(), Array2D< T >::Dd1(), Array2D< T >::Dd2(), Array2D< T >::Filterd1(), Array2D< T >::multid1(), Array2D< T >::multid2(), Array2D< T >::operator*=(), Array2D< T >::operator+=(), Array2D< T >::operator-=(), Array2D< T >::operator=(), Array2D< T >::SubArray2D(), and Array2D< T >::v.
Referenced by Array2D_cmplx< T >::Array2D_cmplx(), Array3D_cmplx< T >::multid2d3(), Array2D_cmplx< T >::operator*=(), Array2D_cmplx< T >::operator+=(), Array2D_cmplx< T >::operator-=(), and Array2D_cmplx< T >::operator=().
 {return *v;}
d1c() [1/2]
template<class T > GSlice_iter< T > Array2D_cmplx< T >::d1c (size_t b, size_t e) inline
Definition at line 752 of file lib-array.h.
References Array2D_cmplx< T >::d2, Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
Referenced by Array3D< complex< double > >::array().
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1, str[1] = td1; str[0] = 2;
     sz[2] = 2,  sz[1]  = d2;  sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(2*b,sz,str));
 }
d1c() [2/2]
template<class T > CGSlice_iter< T > Array2D_cmplx< T >::d1c (size_t b, size_t e) const inline
Definition at line 760 of file lib-array.h.
References Array2D_cmplx< T >::d2, Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1, str[1] = td1; str[0] = 2;
     sz[2] = 2,  sz[1]  = d2;  sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(2*b,sz,str));
 }
d2c() [1/2]
template<class T > GSlice_iter< T > Array2D_cmplx< T >::d2c (size_t b, size_t e) inline
Definition at line 768 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
Referenced by Array3D< complex< double > >::array().
{
     valarray<size_t> sz(1), str(1);     // sz --> size, str --> stride
     str[0] = 1; sz[0]  = (e-b+1)*td1;
     return GSlice_iter<T>(v,gslice(b*td1,sz,str));
 }
d2c() [2/2]
template<class T > CGSlice_iter< T > Array2D_cmplx< T >::d2c (size_t b, size_t e) const inline
Definition at line 775 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     valarray<size_t> sz(1), str(1);     // sz --> size, str --> stride
     str[0] = 1; sz[0]  = (e-b+1)*td1;
     return CGSlice_iter<T>(v,gslice(b*td1,sz,str));
 }
Dd1()
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::Dd1 ()
Definition at line 987 of file lib-array.h.
References Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     for(long i(0); i< td1*d2-4; ++i) {
         (*v)[i] -= (*v)[i+4];
     }
     for(long i(td1*d2-5); i>-1; --i) {
         (*v)[i+2] = (*v)[i];
     }
     return *this;
 }
Dd2()
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::Dd2 ()
Definition at line 1003 of file lib-array.h.
References Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     int twotd1 = 2*td1;
     for(long i(0); i< td1*d2-twotd1; ++i) {
         (*v)[i] -= (*v)[i+twotd1];
     }
     for(long i(td1*d2-twotd1-1); i>-1; --i) {
         (*v)[i+td1] = (*v)[i];
     }
     return *this;
 }
dim()
template<class T> size_t Array2D_cmplx< T >::dim () const inline
Definition at line 640 of file lib-array.h.
References Array2D< T >::d2.
 {return d1*d2;}
dim1()
template<class T> size_t Array2D_cmplx< T >::dim1 () const inline
Definition at line 641 of file lib-array.h.
References Array2D< T >::d1.
Referenced by Array2D_cmplx< T >::Array2D_cmplx().
 {return d1;}
dim2()
template<class T> size_t Array2D_cmplx< T >::dim2 () const inline
Definition at line 642 of file lib-array.h.
References Array2D< T >::d2.
Referenced by Array2D_cmplx< T >::Array2D_cmplx().
 {return d2;}
Filterd1()
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::Filterd1 (size_t N)
Definition at line 1016 of file lib-array.h.
References Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     for (size_t j(0); j < d2; ++j ){
         for (size_t i(j*td1); i< j*td1+2*N; ++i ){
             (*v)[i] = 0.0;
         }
     }
     return *this;
 }
imag() [1/2]
template<class T > T & Array2D_cmplx< T >::imag (size_t i, size_t j) inline
Definition at line 740 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
Referenced by Array2D_cmplx< T >::multid1(), and Array2D_cmplx< T >::multid2().
{
     return (*v)[2*i+1+j*td1];
 }
imag() [2/2]
template<class T > T Array2D_cmplx< T >::imag (size_t i, size_t j) const inline
Definition at line 744 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     return (*v)[2*i+1+j*td1];
 }
multid1() [1/2]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::multid1 (const valarray< T > & vmulti)
Definition at line 931 of file lib-array.h.
References Array2D_cmplx< T >::d1, Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     for (size_t j(0); j< td1*d2; j+= td1 ){
         for (size_t i(0); i< d1; ++i ){
             (*v)[2*i+j]   *= vmulti[i];
             (*v)[2*i+1+j] *= vmulti[i];
         }
     }
     return *this;
 }
multid1() [2/2]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::multid1 (const valarray< complex< T > > & vmulti)
Definition at line 941 of file lib-array.h.
References Array2D_cmplx< T >::d1, Array2D_cmplx< T >::d2, Array2D_cmplx< T >::imag(), Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     for (size_t j(0); j< td1*d2; j+= td1 ){
         for (size_t i(0); i< d1; ++i ){
             T vi((*v)[2*i+j]*vmulti[i].imag());
             (*v)[2*i+j]    *= vmulti[i].real();                     // v[i]   = Aa
             (*v)[2*i+j]    -= (*v)[2*i+1+j] * vmulti[i].imag();     // v[i]   = Aa - Bb
             (*v)[2*i+1+j]  *= vmulti[i].real();                     // v[i+1] = Ba
             (*v)[2*i+1+j]  += vi;                       // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
multid2() [1/2]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::multid2 (const valarray< T > & vmulti)
Definition at line 955 of file lib-array.h.
References Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     for (size_t j(0); j< d2; ++j ){
         for (size_t i(j*td1); i< (j+1)*td1; ++i ){
             (*v)[i] *= vmulti[j];
         }
     }
     return *this;
 }
multid2() [2/2]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::multid2 (const valarray< complex< T > > & vmulti)
Definition at line 965 of file lib-array.h.
References Array2D_cmplx< T >::d2, Array2D_cmplx< T >::imag(), Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     for (size_t j(0); j< d2; ++j ){
         for (size_t i(j*td1); i< (j+1)*td1; i+=2 ){
             T vi((*v)[i]* vmulti[j].imag());
             (*v)[i]    *= vmulti[j].real();                 // v[i]   = Aa
             (*v)[i]    -= (*v)[i+1] * vmulti[j].imag();     // v[i]   = Aa - Bb
             (*v)[i+1]  *= vmulti[j].real();                 // v[i+1] = Ba
             (*v)[i+1]  += vi;                       // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
operator*=() [1/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator*= (const T & d)
Definition at line 834 of file lib-array.h.
Referenced by Array3D< complex< double > >::array().
{
     (*v) *=d;
     return *this;
 }
operator*=() [2/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator*= (const complex< T > & c)
Definition at line 839 of file lib-array.h.
References Array2D_cmplx< T >::d2, Array2D_cmplx< T >::real(), Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     for (size_t i(0); i< td1*d2; i+=2) {            // suppose v[i]+iv[i+1]=A+iB,   c=a+ib
         T vi((*v)[i]*c.imag());
         (*v)[i]    *= c.real();                     // v[i]   = Aa
         (*v)[i]    -= (*v)[i+1]*c.imag();           // v[i]   = Aa - Bb
         (*v)[i+1]  *= c.real();                     // v[i+1] = Ba
         (*v)[i+1]  += vi;                           // v[i+1] = Ba + Ab
     }
     return *this;
 }
operator*=() [3/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator*= (const Array2D< T > & vmulti)
Definition at line 850 of file lib-array.h.
References Array2D< T >::array(), Array2D_cmplx< T >::d1, and Array2D_cmplx< T >::d2.
{
     for (size_t i(0); i< d1*d2; ++i) {
         (*v)[2*i]   *= vmulti.array()[i];
         (*v)[2*i+1] *= vmulti.array()[i];
     }
     return *this;
 }
operator*=() [4/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator*= (const Array2D_cmplx< T > & vmulti)
Definition at line 858 of file lib-array.h.
References Array2D_cmplx< T >::array(), Array2D_cmplx< T >::d2, Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     for (size_t i(0); i< td1*d2; i+=2) {            // suppose v[i]+iv[i+1]=A+iB,   vmulti[i] + ivmulti[i+1] = a+ib
         T vi((*v)[i] * vmulti.array()[i+1]);
         (*v)[i]    *=  vmulti.array()[i];              // v[i]   = Aa
         (*v)[i]    -= (*v)[i+1]*vmulti.array()[i+1];   // v[i]   = Aa - Bb
         (*v)[i+1]  *= vmulti.array()[i];               // v[i+1] = Ba
         (*v)[i+1]  += vi;                              // v[i+1] = Ba + Ab
     }
     return *this;
 }
operator+=() [1/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator+= (const T & d)
Definition at line 871 of file lib-array.h.
References Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     for (size_t i(0); i< td1*d2; i+=2) {
         (*v)[i] +=d;
     }
     return *this;
 }
operator+=() [2/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator+= (const complex< T > & c)
Definition at line 878 of file lib-array.h.
References Array2D_cmplx< T >::d2, Array2D_cmplx< T >::real(), and Array2D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2; i+=2) {
         (*v)[i]   +=c.real();
         (*v)[i+1] +=c.imag();
     }
     return *this;
 }
operator+=() [3/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator+= (const Array2D< T > & vadd)
Definition at line 886 of file lib-array.h.
References Array2D< T >::array(), Array2D_cmplx< T >::d1, and Array2D_cmplx< T >::d2.
{
     for (size_t i(0); i< d1*d2; ++i) {
         (*v)[2*i]   += vadd.array()[i];
     }
     return *this;
 }
operator+=() [4/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator+= (const Array2D_cmplx< T > & vadd)
Definition at line 893 of file lib-array.h.
References Array2D_cmplx< T >::array().
{
     (*v) += vadd.array();
     return *this;
 }
operator-=() [1/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator-= (const T & d)
Definition at line 900 of file lib-array.h.
References Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     for (size_t i(0); i< td1*d2; i+=2) {
         (*v)[i] -=d;
     }
     return *this;
 }
operator-=() [2/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator-= (const complex< T > & c)
Definition at line 907 of file lib-array.h.
References Array2D_cmplx< T >::d2, Array2D_cmplx< T >::real(), and Array2D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2; i+=2) {
         (*v)[i]   -=c.real();
         (*v)[i+1] -=c.imag();
     }
     return *this;
 }
operator-=() [3/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator-= (const Array2D< T > & vmin)
Definition at line 915 of file lib-array.h.
References Array2D< T >::array(), Array2D_cmplx< T >::d1, and Array2D_cmplx< T >::d2.
{
     for (size_t i(0); i< d1*d2; ++i) {
         (*v)[2*i]   -= vmin.array()[i];
     }
     return *this;
 }
operator-=() [4/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator-= (const Array2D_cmplx< T > & vmin)
Definition at line 922 of file lib-array.h.
References Array2D_cmplx< T >::array().
{
     (*v) -= vmin.array();
     return *this;
 }
operator=() [1/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator= (const T & d)
Definition at line 804 of file lib-array.h.
References Array2D_cmplx< T >::d2, and Array2D_cmplx< T >::td1.
Referenced by Array3D< complex< double > >::array().
{
     for (size_t i(0); i< td1*d2; i+=2) {
         (*v)[i] = d;
         (*v)[i+1] = 0.0;
     }
     return *this;
 }
operator=() [2/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator= (const complex< T > & c)
Definition at line 811 of file lib-array.h.
References Array2D_cmplx< T >::d2, Array2D_cmplx< T >::real(), and Array2D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2; i+=2) {
         (*v)[i]   =c.real();
         (*v)[i+1] =c.imag();
     }
     return *this;
 }
operator=() [3/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator= (const Array2D< T > & other)
Definition at line 818 of file lib-array.h.
References Array2D< T >::array(), Array2D_cmplx< T >::d1, and Array2D_cmplx< T >::d2.
{
     for (size_t i(0); i< d1*d2; ++i) {
         (*v)[2*i]   = other.array()[i];
         (*v)[2*i+1] = 0.0;
     }
     return *this;
 }
operator=() [4/4]
template<class T > Array2D_cmplx< T > & Array2D_cmplx< T >::operator= (const Array2D_cmplx< T > & other)
Definition at line 825 of file lib-array.h.
References Array2D_cmplx< T >::array().
{
     if (this != &other) {   //self-assignment
         (*v) = other.array();
     }
     return *this;
 }
operator[]() [1/2]
template<class T > T & Array2D_cmplx< T >::operator[] (size_t i) inline
Definition at line 724 of file lib-array.h.
References Array2D_cmplx< T >::v.
{
     return (*v)[i];
 }
operator[]() [2/2]
template<class T > T Array2D_cmplx< T >::operator[] (size_t i) const inline
Definition at line 728 of file lib-array.h.
References Array2D_cmplx< T >::v.
{
     return (*v)[i];
 }
real() [1/2]
template<class T > T & Array2D_cmplx< T >::real (size_t i, size_t j) inline
Definition at line 732 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
Referenced by Array2D_cmplx< T >::operator*=(), Array2D_cmplx< T >::operator+=(), Array2D_cmplx< T >::operator-=(), and Array2D_cmplx< T >::operator=().
{
     return (*v)[2*i+j*td1];
 }
real() [2/2]
template<class T > T Array2D_cmplx< T >::real (size_t i, size_t j) const inline
Definition at line 736 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     return (*v)[2*i+j*td1];
 }
SubArray2D() [1/2]
template<class T > GSlice_iter< T > Array2D_cmplx< T >::SubArray2D (size_t st, size_t nx, size_t ny) inline
Definition at line 784 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1;    str[0] = td1;
     sz[1]  = 2*nx;  sz[0] = ny;
     return GSlice_iter<T>(v,gslice(2*st,sz,str));
 }
SubArray2D() [2/2]
template<class T > CGSlice_iter< T > Array2D_cmplx< T >::SubArray2D (size_t st, size_t nx, size_t ny) const inline
Definition at line 792 of file lib-array.h.
References Array2D_cmplx< T >::td1, and Array2D_cmplx< T >::v.
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1;    str[0] = td1;
     sz[1]  = 2*nx;  sz[0] = ny;
     return CGSlice_iter<T>(v,gslice(2*st,sz,str));
 }
Field Documentation
d1
template<class T> size_t Array2D_cmplx< T >::d1 private
Definition at line 630 of file lib-array.h.
Referenced by Array2D_cmplx< T >::Array2D_cmplx(), Array3D< complex< double > >::dim1(), Array2D_cmplx< T >::multid1(), Array2D_cmplx< T >::operator*=(), Array2D_cmplx< T >::operator+=(), Array2D_cmplx< T >::operator-=(), and Array2D_cmplx< T >::operator=().
d2
template<class T> size_t Array2D_cmplx< T >::d2 private
Definition at line 630 of file lib-array.h.
Referenced by Array2D_cmplx< T >::Array2D_cmplx(), Array2D_cmplx< T >::d1c(), Array2D_cmplx< T >::Dd1(), Array2D_cmplx< T >::Dd2(), Array3D< complex< double > >::dim2(), Array2D_cmplx< T >::Filterd1(), Array2D_cmplx< T >::multid1(), Array2D_cmplx< T >::multid2(), Array2D_cmplx< T >::operator*=(), Array2D_cmplx< T >::operator+=(), Array2D_cmplx< T >::operator-=(), and Array2D_cmplx< T >::operator=().
td1
template<class T> size_t Array2D_cmplx< T >::td1 private
Definition at line 631 of file lib-array.h.
Referenced by Array2D_cmplx< T >::Array2D_cmplx(), Array2D_cmplx< T >::d1c(), Array2D_cmplx< T >::d2c(), Array2D_cmplx< T >::Dd1(), Array2D_cmplx< T >::Dd2(), Array2D_cmplx< T >::Filterd1(), Array2D_cmplx< T >::imag(), Array2D_cmplx< T >::multid1(), Array2D_cmplx< T >::multid2(), Array2D_cmplx< T >::operator*=(), Array2D_cmplx< T >::operator+=(), Array2D_cmplx< T >::operator-=(), Array2D_cmplx< T >::operator=(), Array2D_cmplx< T >::real(), and Array2D_cmplx< T >::SubArray2D().
v
template<class T> valarray<T>* Array2D_cmplx< T >::v private
Definition at line 629 of file lib-array.h.
Referenced by Array3D< complex< double > >::array(), Array2D_cmplx< T >::Array2D_cmplx(), Array2D_cmplx< T >::d1c(), Array2D_cmplx< T >::d2c(), Array2D_cmplx< T >::imag(), Array2D_cmplx< T >::multid1(), Array2D_cmplx< T >::multid2(), Array2D_cmplx< T >::operator*=(), Array2D_cmplx< T >::operator[](), Array2D_cmplx< T >::real(), Array2D_cmplx< T >::SubArray2D(), and Array2D_cmplx< T >::~Array2D_cmplx().
The documentation for this class was generated from the following file:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/lib-array.h