OSHUN: VlasovFunctor1D_explicitE_implicitB Class Reference
VlasovFunctor1D_explicitE_implicitB Class Reference
#include <functors.h>
Public Member Functions
VlasovFunctor1D_explicitE_implicitB (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_explicitE_implicitB ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D > SA
vector< Electric_Field_1D > EF
vector< Current_1D > JX
vector< Ampere_1D > AM
vector< Faraday_1D > FA
Detailed Description
Definition at line 96 of file functors.h.
Constructor & Destructor Documentation
VlasovFunctor1D_explicitE_implicitB()
VlasovFunctor1D_explicitE_implicitB::VlasovFunctor1D_explicitE_implicitB (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 288 of file functors.cpp.
References VlasovFunctor1D_explicitE::AM, VlasovFunctor1D_explicitE::EF, VlasovFunctor1D_explicitE::FA, VlasovFunctor1D_explicitE::JX, and VlasovFunctor1D_explicitE::SA.
{
 //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         SA.push_back( Spatial_Advection_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         EF.push_back( Electric_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         JX.push_back( Current_1D(0.0, pmax[s], Np[s], Nx) );
         AM.push_back( Ampere_1D(xmin, xmax, Nx) );
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_explicitE_implicitB()
VlasovFunctor1D_explicitE_implicitB::~VlasovFunctor1D_explicitE_implicitB () inline
Definition at line 103 of file functors.h.
References VlasovFunctor1D_explicitE::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_explicitE_implicitB::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 311 of file functors.cpp.
References VlasovFunctor1D_explicitE::AM, State1D::DF(), VlasovFunctor1D_explicitE::EF, State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), VlasovFunctor1D_explicitE::FA, DistFunc1D::Filterp(), VlasovFunctor1D_explicitE::JX, DistFunc1D::l0(), VlasovFunctor1D_explicitE::SA, and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         if (Yin.DF(s).l0() == 1) {
             SA[s].f1only(Yin.DF(s),Yslope.DF(s));
             EF[s].f1only(Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         }
         else{
             SA[s](Yin.DF(s),Yslope.DF(s));
             EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         }
         JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
         AM[s](Yin.EMF(),Yslope.EMF());
         FA[s](Yin.EMF(),Yslope.EMF());
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_explicitE_implicitB::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
operator()() [3/3]
void VlasovFunctor1D_explicitE_implicitB::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 338 of file functors.cpp.
 {}
Field Documentation
AM
vector<Ampere_1D> VlasovFunctor1D_explicitE_implicitB::AM private
Definition at line 118 of file functors.h.
EF
vector<Electric_Field_1D> VlasovFunctor1D_explicitE_implicitB::EF private
Definition at line 116 of file functors.h.
FA
vector<Faraday_1D> VlasovFunctor1D_explicitE_implicitB::FA private
Definition at line 120 of file functors.h.
JX
vector<Current_1D> VlasovFunctor1D_explicitE_implicitB::JX private
Definition at line 117 of file functors.h.
SA
vector<Spatial_Advection_1D> VlasovFunctor1D_explicitE_implicitB::SA private
Definition at line 115 of file functors.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.cpp