OSHUN: Electric_Field_Methods::Efield_xyz Class Reference
Electric_Field_Methods::Efield_xyz Class Reference
#include <implicitE.h>
Public Member Functions
Efield_xyz (EMF1D &emf)
Field1D & E (int component)
Field1D & Ex ()
Field1D & Ey ()
Field1D & Ez ()
Private Attributes
Field1D efieldx
Field1D efieldy
Field1D efieldz
Detailed Description
Definition at line 71 of file implicitE.h.
Constructor & Destructor Documentation
Efield_xyz()
Electric_Field_Methods::Efield_xyz::Efield_xyz (EMF1D & emf)
Definition at line 169 of file implicitE.cpp.
        : efieldx(emf.Ex()),
          efieldy(emf.Ey()),
          efieldz(emf.Ez()) {
      }
Member Function Documentation
E()
Field1D & Electric_Field_Methods::Efield_xyz::E (int component)
Definition at line 180 of file implicitE.cpp.
References Ex(), Ey(), and Ez().
{
 //--------------------------------------------------------------
 //  Return the current component 1 --> x, 2 --> y, 3 --> z
 //--------------------------------------------------------------
     switch (component) {
         case 1: {
             return Ex();
             break;
         }
         case 2: {
             return Ey();
             break;
         }
         case 3: {
             return Ez();
             break;
         }
         default: {
                 cout << "There is no such component for the current!" << endl;
                 exit(1);
                 break;
         }
     }
     return Ex();
 }
Ex()
Field1D & Electric_Field_Methods::Efield_xyz::Ex ()
Definition at line 209 of file implicitE.cpp.
References efieldx.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), E(), and Electric_Field_Methods::Implicit_E_Field::FindDE().
{
        return efieldx;
     }
Ey()
Field1D & Electric_Field_Methods::Efield_xyz::Ey ()
Definition at line 215 of file implicitE.cpp.
References efieldy.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), E(), and Electric_Field_Methods::Implicit_E_Field::FindDE().
{
         return efieldy;
     }
Ez()
Field1D & Electric_Field_Methods::Efield_xyz::Ez ()
Definition at line 221 of file implicitE.cpp.
References efieldz, and Electric_Field_Methods::Efield_Method::~Efield_Method().
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), E(), and Electric_Field_Methods::Implicit_E_Field::FindDE().
{
         return efieldz;
     }
Field Documentation
efieldx
Field1D Electric_Field_Methods::Efield_xyz::efieldx private
Definition at line 88 of file implicitE.h.
Referenced by Ex().
efieldy
Field1D Electric_Field_Methods::Efield_xyz::efieldy private
Definition at line 88 of file implicitE.h.
Referenced by Ey().
efieldz
Field1D Electric_Field_Methods::Efield_xyz::efieldz private
Definition at line 88 of file implicitE.h.
Referenced by Ez().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/implicitE.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/implicitE.cpp