OSHUN: RK4_IB Class Reference
RK4_IB Class Reference
#include <laser.h>
Public Member Functions
RK4_IB (valarray< double > &fin, double pmax, int tout_start)
RK4_IB & advance (const double vosc, const double Zval)
double & tout ()
double & time ()
size_t & numh ()
double & th ()
Private Member Functions
valarray< double > & F (const valarray< double > &fin, const double vosc, const double Zval)
Private Attributes
valarray< double > f0
valarray< double > f1
valarray< double > fh
valarray< double > & f
IB_f00 Inversebremsstrahlung
size_t num_h
double h
double t
double Tout
Detailed Description
Definition at line 63 of file laser.h.
Constructor & Destructor Documentation
RK4_IB()
RK4_IB::RK4_IB (valarray< double > & fin, double pmax, int tout_start)
Definition at line 213 of file laser.cpp.
         :t(static_cast<double>(tout_start) *
            Input::List().t_stop / Input::List().n_outsteps),  // Initialize time = 0
          Tout(t + Input::List().t_stop / Input::List().n_outsteps),                                   // The next output time
          fh(0.0,fin.size()),
          f0(0.0,fin.size()),
          f1(0.0,fin.size()),    // 3 local "State" Variables
          f(fin),                                 // Initialize a reference to "State" Y
          Inversebremsstrahlung(fh, pmax){              // Initialize "Actions"
 }
Member Function Documentation
advance()
RK4_IB & RK4_IB::advance (const double vosc, const double Zval)
Definition at line 247 of file laser.cpp.
References F(), f, f0, f1, fh, h, and t.
Referenced by InverseBremsstrahlung::loop().
{
 //--------------------------------------------------------------
 //  Take a step using RK4
 //--------------------------------------------------------------
 //      Initialization
     f0 = f; f1 = f;
 //      Step 1
     F(f1,vosc,Zval);                          // fh = F(f1)
     fh *= (0.5*h);   f1 += fh;      // f1 = f1 + (h/2)*fh
     fh *= (1.0/3.0); f  += fh;      // f  = f  + (h/6)*fh
 //      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //      Step 2
     F(f1,vosc,Zval);     f1  = f0;            // fh = F(f1)
     fh *= (0.5*h);   f1 += fh;      // f1 = f0 + (h/2)*fh
     fh *= (2.0/3.0); f  += fh;      // f  = f  + (h/3)*fh
 //      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //      Step 3
     F(f1,vosc,Zval);                          // fh = F(f1)
     fh *= h;          f0 += fh;     // f1 = f0 + h*Yh
     fh *= (1.0/3.0);  f  += fh;     // f  = f  + (h/3)*fh
 //      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //      Step 4
     F(f0,vosc,Zval);                          // fh = F(f0)
     fh *= (h/6.0);    f += fh;      // f  = f  + (h/6)*Yh
 //      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     t += h;
     return *this;
 }
F()
valarray< double > & RK4_IB::F (const valarray< double > & fin, const double vosc, const double Zval) private
Definition at line 242 of file laser.cpp.
References IB_f00::Getslope(), and Inversebremsstrahlung.
Referenced by advance().
{
     return Inversebremsstrahlung.Getslope(fin,vosc,Zval);
 }
numh()
size_t & RK4_IB::numh ()
Definition at line 233 of file laser.cpp.
References num_h.
Referenced by InverseBremsstrahlung::loop().
 {return num_h;}
th()
double & RK4_IB::th ()
Definition at line 236 of file laser.cpp.
References h.
Referenced by InverseBremsstrahlung::loop().
 {return h;}
time()
double & RK4_IB::time ()
Definition at line 239 of file laser.cpp.
References t.
Referenced by InverseBremsstrahlung::loop().
 {return t;}
tout()
double & RK4_IB::tout ()
Definition at line 230 of file laser.cpp.
References Tout.
Referenced by InverseBremsstrahlung::loop().
 {return Tout;}
Field Documentation
f
valarray<double>& RK4_IB::f private
Definition at line 86 of file laser.h.
Referenced by advance().
f0
valarray<double> RK4_IB::f0 private
Definition at line 85 of file laser.h.
Referenced by advance().
f1
valarray<double> RK4_IB::f1 private
Definition at line 85 of file laser.h.
Referenced by advance().
fh
valarray<double> RK4_IB::fh private
Definition at line 85 of file laser.h.
Referenced by advance().
h
double RK4_IB::h private
Definition at line 92 of file laser.h.
Referenced by advance(), and th().
Inversebremsstrahlung
IB_f00 RK4_IB::Inversebremsstrahlung private
Definition at line 89 of file laser.h.
Referenced by F().
num_h
size_t RK4_IB::num_h private
Definition at line 91 of file laser.h.
Referenced by numh().
t
double RK4_IB::t private
Definition at line 92 of file laser.h.
Referenced by advance(), and time().
Tout
double RK4_IB::Tout private
Definition at line 92 of file laser.h.
Referenced by tout().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/laser.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/laser.cpp