OSHUN: Export_Files::Xport Class Reference
Export_Files::Xport Class Reference
#include <export.h>
Public Member Functions
Xport (const Algorithms::AxisBundle< double > &_axis, const vector< string > oTags, string homedir="")
void Export_h5 (const std::string tag, std::valarray< float > ex, const size_t &step, const int spec=-1)
void Export_h5 (const std::string tag, Array2D< float > ex, const size_t &step, const int spec=-1)
void Export_h5 (const std::string tag, Array3D< float > ex, const size_t &step, const int spec=-1)
H5::H5File hmake_file (string ofilename)
void hclose_file (H5::H5File &file)
void hinit_attr (H5::H5File &hfilehandle, const std::string tag, size_t step, float xmax, float xmin)
void hinit_attr2 (H5::H5File &hfilehandle, const std::string tag, size_t step, float xmax[], float xmin[])
void haxis (H5::Group &hgrouphandle, string axismainname, float axisrange[2], string axislongname, string axisname, string axistype, string axisunits)
void hfile_add_attr (H5::H5File &hfilehandle, string attrname, int attrdata)
void hfile_add_attr2 (H5::H5File &hfilehandle, string attrname, int attrdata[2])
void hfile_add_attr (H5::H5File &hfilehandle, string attrname, float attrdata)
void hfile_add_attr2 (H5::H5File &hfilehandle, string attrname, float attrdata[2])
void hfile_add_attr (H5::H5File &hfilehandle, string attrname, string attrdata)
void hfile_add_attr_todataset (H5::DataSet &hdatasethandle, string attrname, string attrdata)
Private Member Functions
string oH5Fextension (size_t step, int species=-1)
Private Attributes
map< string, Header > Hdr
Detailed Description
Definition at line 173 of file export.h.
Constructor & Destructor Documentation
Xport()
Export_Files::Xport::Xport (const Algorithms::AxisBundle< double > & _axis, const vector< string > oTags, string homedir = "")
Definition at line 530 of file export.cpp.
References formulary(), Export_Files::Header::Header(), Formulary::Label(), Export_Files::Header::label(), Export_Files::Makefolder(), Algorithms::AxisBundle< T >::Np(), Algorithms::AxisBundle< T >::Npx(), Algorithms::AxisBundle< T >::Npy(), Algorithms::AxisBundle< T >::Npz(), Algorithms::AxisBundle< T >::Nxg(), Algorithms::AxisBundle< T >::pdim(), Algorithms::AxisBundle< T >::pmax(), Algorithms::AxisBundle< T >::pmin(), Export_Files::stringify(), Formulary::Uconv(), Algorithms::AxisBundle< T >::xgmax(), and Algorithms::AxisBundle< T >::xgmin().
{
     size_t species(_axis.pdim());
     DefaultTags dTags(species);
     vector< oAxis > xyz, pxyz, imre, pr;
     xyz.push_back( Export_Files::oAxis(_axis.xgmin(0), _axis.xgmax(0), _axis.Nxg(0)) );
     for (size_t s(0); s < species; ++s) {
         pr.push_back( Export_Files::oAxis(_axis.pmin(s), _axis.pmax(s), _axis.Np(s)));
         pxyz.push_back( Export_Files::oAxis( (-1.0)*float(_axis.pmax(s)), float(_axis.pmax(s)), _axis.Npx(s)) );
         pxyz.push_back( Export_Files::oAxis( (-1.0)*float(_axis.pmax(s)), float(_axis.pmax(s)), _axis.Npy(s)) );
         pxyz.push_back( Export_Files::oAxis( (-1.0)*float(_axis.pmax(s)), float(_axis.pmax(s)), _axis.Npz(s)) );
     }
     imre.push_back( Export_Files::oAxis(0,1,2) );
 //  Time
     size_t tloc(0);                  // Find the location of the right tag
     while ( ( tloc < dTags.time.size()-1 ) &&
             ( find(oTags.begin(),oTags.end(), dTags.time[tloc]) == oTags.end() ) ) {
         ++tloc;
     }
     string tlabel = "t[" +formulary().Label(dTags.time[tloc])+"]";
     string tunits = formulary().Label(dTags.time[tloc]);
     float  tconv  =  formulary().Uconv(dTags.time[tloc]);
 //  xyz Axis
     size_t xloc(0);                  // Find the location of the right tag
     while ( ( xloc < dTags.space.size()-1 ) &&
             ( find(oTags.begin(),oTags.end(), dTags.space[xloc]) == oTags.end() ) ) {
         ++xloc;
     }
     xyz[0].label = "x["+ formulary().Label(dTags.space[xloc]) +"]";
     if ( xyz.size() > 1 ) xyz[1].label = "y["+ formulary().Label(dTags.space[xloc]) +"]";
     if ( xyz.size() > 2 ) xyz[2].label = "z["+ formulary().Label(dTags.space[xloc]) +"]";
     xyz[0].units = formulary().Label(dTags.space[xloc]);
     if ( xyz.size() > 1 ) xyz[1].units = formulary().Label(dTags.space[xloc]);
     if ( xyz.size() > 2 ) xyz[2].units = formulary().Label(dTags.space[xloc]);
 //  pxyz Axis
     for (size_t i(0); i < species; ++i) {
         pr[i].label = "p";
         pr[i].units = "m_e c";
         pxyz[i].label = "px[mc]";
         pxyz[i].units = "m_e c";
         // if ( pxyz.size()/species > 1 )
         pxyz[1+i].label = "py[mc]";
         pxyz[1+i].units = "m_e c";
         // if ( pxyz.size()/species > 2 )
         pxyz[2+i].label = "pz[mc]";
         pxyz[2+i].units = "m_e c";
         // if ( pxyz.size()/species > 1 )
         // if ( pxyz.size()/species > 2 ) pxyz[2*species+i].units = "m_e c";
     }
 //  Tags for Fields -->
     for (size_t i(0); i < dTags.fld.size(); ++i) {
         //     If this tag is an output tag
         if ( find(oTags.begin(),oTags.end(), dTags.fld[i]) != oTags.end() ) {
             string nounits = dTags.fld[i].substr(0, dTags.fld[i].find("_"));
             string folder = homedir + "OUTPUT/FLD/" + nounits + "/";
             //         Generate a header file for this tag
             Hdr[dTags.fld[i]] = Header(xyz,
                                        nounits+"["+formulary().Label(dTags.fld[i])+"]",
                                        formulary().Uconv(dTags.fld[i]),
                                        tlabel, tunits, tconv, folder);
         }
     } // <--
 //  Tags for Moments -->
     for (size_t i(0); i < dTags.mom.size(); ++i) {
         //     If this tag is an output tag
         if ( find(oTags.begin(),oTags.end(), dTags.mom[i]) != oTags.end() ) {
             string nounits = dTags.mom[i].substr(0, dTags.mom[i].find("_"));
             string folder = homedir + "OUTPUT/MOM/" + nounits + "/";
             //         Generate a header file for this tag
             Hdr[dTags.mom[i]] = Header(xyz,
                                        nounits+"["+formulary().Label(dTags.mom[i])+"]",
                                        formulary().Uconv(dTags.mom[i]),
                                        tlabel, tunits, tconv, folder);
         }
     } // <--
 //  Tags for p-x -->
     for (size_t i(0); i < dTags.pvsx.size(); ++i) {
         // for (size_t k(0); k < oTags.size(); ++k)
         //         std::cout << " \n \n k = " << oTags[k];
         //     If this tag is an output tag
         if ( find(oTags.begin(),oTags.end(), dTags.pvsx[i]) != oTags.end() ) {
             string folder = homedir + "OUTPUT/DISTR/" + dTags.pvsx[i] + "/";
             Makefolder(folder);
 //          Generate a header file for this tag
 //          For each 9 you have a different species
             Hdr[dTags.pvsx[i]] = Header( pr[i/3], xyz[0],
                                          "f"+stringify(i/3), 1.0, tlabel, tunits, tconv, folder);
             // std::cout << " \n k = " << dTags.pvsx[i] << "\n";
             // std::cout << " \n \n 11 ";
         }
     } //<--
 //  Tags for f-x -->
     for (size_t i(0); i < dTags.fvsx.size(); ++i) {
         //     If this tag is an output tag
         if ( find(oTags.begin(),oTags.end(), dTags.fvsx[i]) != oTags.end() ) {
             string folder = homedir + "OUTPUT/DISTR/" + dTags.fvsx[i] + "/";
             Makefolder(folder);
 //          Generate a header file for this tag
             Hdr[dTags.fvsx[i]] = Header( pr[i/5], xyz[0], imre[0],
                                          "f", 1.0, tlabel, tunits, tconv, folder);
         }
     } //<--
     //  Tags for p-p-x -->
     for (size_t i(0); i < dTags.pvspvsx.size(); ++i) {
         //     If this tag is an output tag
         if ( find(oTags.begin(),oTags.end(), dTags.pvspvsx[i]) != oTags.end() ) {
             string folder = homedir + "OUTPUT/DISTR/" + dTags.pvspvsx[i] + "/";
             Makefolder(folder);
 //          Generate a header file for this tag
             Hdr[dTags.pvspvsx[i]] = Header( pxyz[i/1+species],pxyz[(i+1)/1+species], xyz[0],
                                             "f"+stringify(i/1), 1.0, tlabel, tunits, tconv, folder);
             // std::cout << " \n \n 11 ";
         }
     } //<--
 }
Member Function Documentation
Export_h5() [1/3]
void Export_Files::Xport::Export_h5 (const std::string tag, std::valarray< float > ex, const size_t & step, const int spec = -1)
Definition at line 3416 of file export.cpp.
References Export_Files::Header::dim(), Export_Files::Header::Directory(), and formulary().
{
 //--------------------------------------------------------------
 //  Export data to H5 file
 //--------------------------------------------------------------
     string      filename(Hdr[tag].Directory());
 //  Check Header file correctness
     if (Hdr[tag].dim() != 1) {
         cout << "ERROR "<< tag <<" : "  << Hdr[tag].dim() << " dimensions != 1D structure\n";
         exit(1);
     }
 //  Open File
     filename.append(tag).append(oH5Fextension(step,spec));
     H5::H5File file = hmake_file(filename);
     hsize_t dimsf[1] = {data.size()};              // dataset dimensions
     H5::DataSpace dataspace( 1, dimsf );
     H5::DataSet dataset = file.createDataSet( tag, H5::PredType::NATIVE_FLOAT, dataspace );
     float xmin = {  static_cast<float>( Hdr[tag].min(0)) };
     float xmax = {  static_cast<float>( Hdr[tag].max(0)) };
     hinit_attr(file, tag, step, xmax, xmin);
     H5::Group group = file.createGroup("/AXIS");
     std::size_t pos = Hdr[tag].label(0).find("[");
     string axismainname = "AXIS1";
     float axisrange[2];
     axisrange[0] = xmin;
     axisrange[1] = xmax;
     string axislongname = Hdr[tag].label(0).substr(0,pos);
     string axisname = Hdr[tag].label(0).substr(0,pos);
     string axistype = "linear";
     string axisunits = Hdr[tag].units(0);
     haxis(group, axismainname, axisrange, axislongname, axisname, axistype, axisunits);
     group.close();
     dataset.write( &(data[0]) , H5::PredType::NATIVE_FLOAT );
     hfile_add_attr_todataset(dataset, "LONG_NAME", tag);
     hfile_add_attr_todataset(dataset, "UNITS", formulary().Label(tag));
     dataset.close();
     hclose_file(file);
 }
Export_h5() [2/3]
void Export_Files::Xport::Export_h5 (const std::string tag, Array2D< float > ex, const size_t & step, const int spec = -1)
Definition at line 3475 of file export.cpp.
References Array2D< T >::array(), Export_Files::Header::dim(), Array2D< T >::dim1(), Array2D< T >::dim2(), Export_Files::Header::Directory(), formulary(), Export_Files::Header::max(), and Export_Files::Header::min().
{
 //--------------------------------------------------------------
 //  Export data to H5 file
 //--------------------------------------------------------------
     string      filename(Hdr[tag].Directory());
 //  Check Header file correctness
     if (Hdr[tag].dim() != 2) {
         cout << "ERROR "<< tag <<" : "  << Hdr[tag].dim() << " dimensions != 2D structure\n";
         exit(1);
     }
 //  Open File
     filename.append(tag).append(oH5Fextension(step,spec));
     H5::H5File file = hmake_file(filename);
     hsize_t dimsf[2] = { data.dim2(), data.dim1() };              // dataset dimensions
     H5::DataSpace dataspace( 2, dimsf );
     H5::DataSet dataset = file.createDataSet( tag, H5::PredType::NATIVE_FLOAT, dataspace );
     float xmin[2] = {  static_cast<float>( Hdr[tag].min(0)),
                        static_cast<float>( Hdr[tag].min(1)) };
     float xmax[2] = {  static_cast<float>( Hdr[tag].max(0)),
                        static_cast<float>( Hdr[tag].max(1)) };
     hinit_attr2(file, tag, step, xmax, xmin);
     H5::Group group = file.createGroup("/AXIS");
     std::size_t pos = Hdr[tag].label(1).find("[");
     string axismainname = "AXIS1";
     float axisrange[2];
     axisrange[0] = xmin[1];
     axisrange[1] = xmax[1];
     string axislongname = Hdr[tag].label(1).substr(0,pos);
     string axisname = Hdr[tag].label(1).substr(0,pos);
     string axistype = "linear";
     string axisunits = Hdr[tag].units(1);
     haxis(group, axismainname, axisrange, axislongname, axisname, axistype, axisunits);
     pos = Hdr[tag].label(0).find("[");
     axismainname = "AXIS2";
     axisrange[0] = xmin[0];
     axisrange[1] = xmax[0];
     axislongname = Hdr[tag].label(0).substr(0,pos);
     axisname = Hdr[tag].label(0).substr(0,pos);
     axisunits = Hdr[tag].units(0);
     haxis(group, axismainname, axisrange, axislongname, axisname, axistype, axisunits);
     group.close();
     dataset.write( &(data.array())[0] , H5::PredType::NATIVE_FLOAT );
     hfile_add_attr_todataset(dataset, "LONG_NAME", tag);
     hfile_add_attr_todataset(dataset, "UNITS", formulary().Label(tag));
     dataset.close();
     hclose_file(file);
 }
Export_h5() [3/3]
void Export_Files::Xport::Export_h5 (const std::string tag, Array3D< float > ex, const size_t & step, const int spec = -1)
Definition at line 3548 of file export.cpp.
References Array3D< T >::array(), Export_Files::Header::dim(), Array3D< T >::dim1(), Array3D< T >::dim2(), Array3D< T >::dim3(), Export_Files::Header::Directory(), formulary(), Export_Files::Header::max(), and Export_Files::Header::min().
{
 //--------------------------------------------------------------
 //  Export data to H5 file
 //--------------------------------------------------------------
     string      filename(Hdr[tag].Directory());
 //  Check Header file correctness
     if (Hdr[tag].dim() != 3) {
         cout << "ERROR "<< tag <<" : "  << Hdr[tag].dim() << " dimensions != 3D structure\n";
         exit(1);
     }
 //  Open File
     filename.append(tag).append(oH5Fextension(step,spec));
     H5::H5File file = hmake_file(filename);
     hsize_t dimsf[3] = { data.dim3(), data.dim2(), data.dim1() };              // dataset dimensions
     H5::DataSpace dataspace( 3, dimsf );
     H5::DataSet dataset = file.createDataSet( tag, H5::PredType::NATIVE_FLOAT, dataspace );
     float xmin[3] = {  static_cast<float>( Hdr[tag].min(0)),
                        static_cast<float>( Hdr[tag].min(1)),
                        static_cast<float>( Hdr[tag].min(2))};
     float xmax[3] = {  static_cast<float>( Hdr[tag].max(0)),
                        static_cast<float>( Hdr[tag].max(1)),
                        static_cast<float>( Hdr[tag].max(2))};
     hinit_attr2(file, tag, step, xmax, xmin);
     H5::Group group = file.createGroup("/AXIS");
     std::size_t pos = Hdr[tag].label(1).find("[");
     string axismainname = "AXIS1";
     float axisrange[2];
     axisrange[0] = xmin[1];
     axisrange[1] = xmax[1];
     string axislongname = Hdr[tag].label(1).substr(0,pos);
     string axisname = Hdr[tag].label(1).substr(0,pos);
     string axistype = "linear";
     string axisunits = Hdr[tag].units(1);
     haxis(group, axismainname, axisrange, axislongname, axisname, axistype, axisunits);
     pos = Hdr[tag].label(0).find("[");
     axismainname = "AXIS2";
     axisrange[0] = xmin[0];
     axisrange[1] = xmax[0];
     axislongname = Hdr[tag].label(0).substr(0,pos);
     axisname = Hdr[tag].label(0).substr(0,pos);
     axisunits = Hdr[tag].units(0);
     haxis(group, axismainname, axisrange, axislongname, axisname, axistype, axisunits);
     pos = Hdr[tag].label(2).find("[");
     axismainname = "AXIS3";
     axisrange[0] = xmin[2];
     axisrange[1] = xmax[2];
     axislongname = Hdr[tag].label(2).substr(0,pos);
     axisname = Hdr[tag].label(2).substr(0,pos);
     axisunits = Hdr[tag].units(2);
     haxis(group, axismainname, axisrange, axislongname, axisname, axistype, axisunits);
     group.close();
     dataset.write( &(data.array())[0] , H5::PredType::NATIVE_FLOAT );
     hfile_add_attr_todataset(dataset, "LONG_NAME", tag);
     hfile_add_attr_todataset(dataset, "UNITS", formulary().Label(tag));
     dataset.close();
     hclose_file(file);
 }
haxis()
void Export_Files::Xport::haxis (H5::Group & hgrouphandle, string axismainname, float axisrange[2], string axislongname, string axisname, string axistype, string axisunits)
Definition at line 3736 of file export.cpp.
{
 //--------------------------------------------------------------
 //   Add axis attributes
 //--------------------------------------------------------------
     hsize_t dims2[1] = { 2 };
     H5::DataSpace dataspaceg1( 1, dims2 );
     H5::DataSet datasetg1 = hgrouphandle.createDataSet(axismainname, H5::PredType::NATIVE_FLOAT,
                                                        dataspaceg1);
     datasetg1.write( axisrange, H5::PredType::NATIVE_FLOAT );
     hfile_add_attr_todataset(datasetg1, "LONG_NAME", axislongname);
     hfile_add_attr_todataset(datasetg1, "NAME", axisname);
     hfile_add_attr_todataset(datasetg1, "TYPE", axistype);
     hfile_add_attr_todataset(datasetg1, "UNITS", axisunits);
     dataspaceg1.close();
     datasetg1.close();
 }
hclose_file()
void Export_Files::Xport::hclose_file (H5::H5File & file)
Definition at line 3646 of file export.cpp.
{
 //--------------------------------------------------------------
 //    Close HDF5 file
 //--------------------------------------------------------------
     file.close();
 }
hfile_add_attr() [1/3]
void Export_Files::Xport::hfile_add_attr (H5::H5File & hfilehandle, string attrname, int attrdata)
Definition at line 3761 of file export.cpp.
{
 //--------------------------------------------------------------
 //   Add 1D integer attribute
 //--------------------------------------------------------------
     hsize_t dims1[1] = { 1 };
     H5::DataSpace attr_dataspace_1 = H5::DataSpace (1, dims1 );
     H5::Attribute attribute_int = hfilehandle.createAttribute( attrname, H5::PredType::NATIVE_INT,
                                                                attr_dataspace_1);
     attribute_int.write( H5::PredType::NATIVE_INT, &attrdata);
     attr_dataspace_1.close();
     attribute_int.close();
 }
hfile_add_attr() [2/3]
void Export_Files::Xport::hfile_add_attr (H5::H5File & hfilehandle, string attrname, float attrdata)
Definition at line 3801 of file export.cpp.
{
 //--------------------------------------------------------------
 //   Add 1D float attribute
 //--------------------------------------------------------------
     hsize_t dims1[1] = { 1 };
     H5::DataSpace attr_dataspace_1 = H5::DataSpace (1, dims1 );
     H5::Attribute attribute_float = hfilehandle.createAttribute( attrname, H5::PredType::NATIVE_FLOAT,
                                                                  attr_dataspace_1);
     attribute_float.write( H5::PredType::NATIVE_FLOAT, &attrdata);
     attr_dataspace_1.close();
     attribute_float.close();
 }
hfile_add_attr() [3/3]
void Export_Files::Xport::hfile_add_attr (H5::H5File & hfilehandle, string attrname, string attrdata)
Definition at line 3841 of file export.cpp.
{
 //--------------------------------------------------------------
 //   Add string attribute
 //--------------------------------------------------------------
     hsize_t dims1[1] = { 1 };
     H5::DataSpace attr_dataspace_1 = H5::DataSpace (1, dims1 );
     H5::StrType strdatatype(H5::PredType::C_S1, 256); // of length 256 characters
     H5std_string strwritebuf ( attrdata );
     H5::Attribute attribute_string = hfilehandle.createAttribute( attrname, strdatatype, attr_dataspace_1);
     attribute_string.write(strdatatype, strwritebuf);
     attr_dataspace_1.close();
     attribute_string.close();
 }
hfile_add_attr2() [1/2]
void Export_Files::Xport::hfile_add_attr2 (H5::H5File & hfilehandle, string attrname, int attrdata[2])
Definition at line 3781 of file export.cpp.
{
 //--------------------------------------------------------------
 //   Add 2D integer attribute
 //--------------------------------------------------------------
     hsize_t dims1[1] = { 2 };
     H5::DataSpace attr_dataspace_2 = H5::DataSpace (1, dims1 );
     H5::Attribute attribute_int = hfilehandle.createAttribute( attrname, H5::PredType::NATIVE_INT,
                                                                attr_dataspace_2);
     attribute_int.write( H5::PredType::NATIVE_INT, attrdata);
     attr_dataspace_2.close();
     attribute_int.close();
 }
hfile_add_attr2() [2/2]
void Export_Files::Xport::hfile_add_attr2 (H5::H5File & hfilehandle, string attrname, float attrdata[2])
Definition at line 3821 of file export.cpp.
{
 //--------------------------------------------------------------
 //   Add 2D float attribute
 //--------------------------------------------------------------
     hsize_t dims1[1] = { 2 };
     H5::DataSpace attr_dataspace_2 = H5::DataSpace (1, dims1 );
     H5::Attribute attribute_float = hfilehandle.createAttribute( attrname, H5::PredType::NATIVE_FLOAT,
                                                                  attr_dataspace_2);
     attribute_float.write( H5::PredType::NATIVE_FLOAT, attrdata);
     attr_dataspace_2.close();
     attribute_float.close();
 }
hfile_add_attr_todataset()
void Export_Files::Xport::hfile_add_attr_todataset (H5::DataSet & hdatasethandle, string attrname, string attrdata)
Definition at line 3862 of file export.cpp.
{
 //--------------------------------------------------------------
 //   Add string attribute to a specific dataset
 //--------------------------------------------------------------
     hsize_t dims1[1] = { 1 };
     H5::DataSpace attr_dataspace_1 = H5::DataSpace (1, dims1 );
     H5::StrType strdatatype(H5::PredType::C_S1, 256); // of length 256 characters
     H5std_string strwritebuf ( attrdata );
     H5::Attribute attribute_string = hdatasethandle.createAttribute( attrname, strdatatype, attr_dataspace_1);
     attribute_string.write(strdatatype, strwritebuf);
     attr_dataspace_1.close();
     attribute_string.close();
 }
hinit_attr()
void Export_Files::Xport::hinit_attr (H5::H5File & hfilehandle, const std::string tag, size_t step, float xmax, float xmin)
Definition at line 3658 of file export.cpp.
References Input::List(), and Export_Files::Header::time.
{
 //--------------------------------------------------------------
 //    Add initial attributes:
 //    time step, iteration number, name of diagnostic,
 //    physical time, time units, type, and max and min of axes ranges
 //--------------------------------------------------------------
     double dt_out(Input::List().t_stop / Input::List().n_outsteps);
     float dt = { static_cast<float>(
                          dt_out/static_cast<double>(
                                  size_t(static_cast<int>(dt_out
                                                          /Input::List().clf_dp))+1
                          ))};
     hfile_add_attr(hfilehandle, "DT", dt);
     float time = { static_cast<float>(dt_out*step) };
     hfile_add_attr(hfilehandle, "TIME", time);
     hfile_add_attr(hfilehandle, "NAME", tag);
     // float time = { static_cast<float>(dt_out*step*dt) };
     // hfile_add_attr(hfilehandle, "TIME", time);
     string timeunits = "1/\\omega_p";
     hfile_add_attr(hfilehandle, "TIME UNITS", timeunits);
     string typegrid = "grid";
     hfile_add_attr(hfilehandle, "TYPE", typegrid);
     hfile_add_attr(hfilehandle, "XMAX", xmax);
     hfile_add_attr(hfilehandle, "XMIN", xmin);
 }
hinit_attr2()
void Export_Files::Xport::hinit_attr2 (H5::H5File & hfilehandle, const std::string tag, size_t step, float xmax[], float xmin[])
Definition at line 3698 of file export.cpp.
References Input::List(), and Export_Files::Header::time.
{
 //--------------------------------------------------------------
 //    Add initial attributes:
 //    time step, iteration number, name of diagnostic,
 //    physical time, time units, type, and max and min of axes ranges
 //--------------------------------------------------------------
     double dt_out(Input::List().t_stop / Input::List().n_outsteps);
     float dt = { static_cast<float>(
                          dt_out/static_cast<double>(
                                  size_t(static_cast<int>(dt_out
                                                          /Input::List().clf_dp))+1
                          ))};
     hfile_add_attr(hfilehandle, "DT", dt);
     float time = { static_cast<float>(dt_out*step) };
     hfile_add_attr(hfilehandle, "TIME", time);
     hfile_add_attr(hfilehandle, "NAME", tag);
     string timeunits = "1/\\omega_p";
     hfile_add_attr(hfilehandle, "TIME UNITS", timeunits);
     string typegrid = "grid";
     hfile_add_attr(hfilehandle, "TYPE", typegrid);
     hfile_add_attr2(hfilehandle, "XMAX", xmax);
     hfile_add_attr2(hfilehandle, "XMIN", xmin);
 }
hmake_file()
H5::H5File Export_Files::Xport::hmake_file (string ofilename)
Definition at line 3632 of file export.cpp.
{
 //--------------------------------------------------------------
 //    Create HDF5 file
 //--------------------------------------------------------------
     const H5std_string  FILE_NAME( ofilename );
     H5::H5File file( FILE_NAME, H5F_ACC_TRUNC );
     return file;
 }
oH5Fextension()
string Export_Files::Xport::oH5Fextension (size_t step, int species = -1) private
Definition at line 683 of file export.cpp.
References Export_Files::ofconventions::h5file_extension, Export_Files::ofconventions::ofile_digits, and Export_Files::stringify().
{
     stringstream sFilename;
     if(species >= 0) sFilename << "_s" << species;
     sFilename << "_";
     // Number of zeros to add to the filename
     int Nzeros(ofconventions::ofile_digits - stringify(step).length());
     while (Nzeros-- > 0) {
         sFilename << "0";
     }
     sFilename << step << ofconventions::h5file_extension;
     return sFilename.str();
 }
Field Documentation
Hdr
map< string, Header > Export_Files::Xport::Hdr private
Definition at line 206 of file export.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/export.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/export.cpp