OSHUN: VlasovFunctor1D_implicitE_p1 Class Reference
VlasovFunctor1D_implicitE_p1 Class Reference
#include <functors.h>
Public Member Functions
VlasovFunctor1D_implicitE_p1 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_implicitE_p1 ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D > SA
vector< Magnetic_Field_1D > BF
vector< Hydro_Advection_1D > HA
Detailed Description
Definition at line 128 of file functors.h.
Constructor & Destructor Documentation
VlasovFunctor1D_implicitE_p1()
VlasovFunctor1D_implicitE_p1::VlasovFunctor1D_implicitE_p1 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 345 of file functors.cpp.
References VlasovFunctor1D_explicitE::BF, and VlasovFunctor1D_explicitE::SA.
{
 // //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         SA.push_back( Spatial_Advection_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         HA.push_back( Hydro_Advection_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         BF.push_back( Magnetic_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_implicitE_p1()
VlasovFunctor1D_implicitE_p1::~VlasovFunctor1D_implicitE_p1 () inline
Definition at line 135 of file functors.h.
References VlasovFunctor1D_explicitE::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_implicitE_p1::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 364 of file functors.cpp.
References VlasovFunctor1D_explicitE::BF, EMF1D::Bx(), EMF1D::By(), EMF1D::Bz(), State1D::DF(), State1D::EMF(), DistFunc1D::Filterp(), DistFunc1D::l0(), VlasovFunctor1D_explicitE::SA, and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         if (Yin.DF(s).l0() == 1) {
             SA[s].f1only(Yin.DF(s),Yslope.DF(s));
             BF[s].f1only(Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
             // HA[s](Yin.DF(s),Yin.HYDRO(),Yslope.DF(s));
         }
         else {
             SA[s](Yin.DF(s),Yslope.DF(s));
             BF[s](Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
             // HA[s](Yin.DF(s),Yin.HYDRO(),Yslope.DF(s));
         }
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_implicitE_p1::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
operator()() [3/3]
void VlasovFunctor1D_implicitE_p1::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 389 of file functors.cpp.
 {}
Field Documentation
BF
vector<Magnetic_Field_1D> VlasovFunctor1D_implicitE_p1::BF private
Definition at line 147 of file functors.h.
HA
vector<Hydro_Advection_1D> VlasovFunctor1D_implicitE_p1::HA private
Definition at line 149 of file functors.h.
SA
vector<Spatial_Advection_1D> VlasovFunctor1D_implicitE_p1::SA private
Definition at line 143 of file functors.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.cpp