OSHUN: Node_ImplicitE_Communications Class Reference
Node_ImplicitE_Communications Class Reference
#include <parallel.h>
Public Member Functions
Node_ImplicitE_Communications ()
~Node_ImplicitE_Communications ()
int BNDX () const
void Send_right_X (State1D &Y, int dest)
void Recv_from_left_X (State1D &Y, int origin)
void Send_left_X (State1D &Y, int dest)
void Recv_from_right_X (State1D &Y, int origin)
void mirror_bound_Xleft (State1D &Y)
void mirror_bound_Xright (State1D &Y)
void sameNode_bound_X (State1D &Y)
Private Member Functions
void sameNode_periodic_X (State1D &Y)
void sameNode_mirror_X (State1D &Y)
Private Attributes
int Nbc
int bndX
int msg_sizeX
complex< double > * msg_bufX
Detailed Description
Definition at line 37 of file parallel.h.
Constructor & Destructor Documentation
Node_ImplicitE_Communications()
Node_ImplicitE_Communications::Node_ImplicitE_Communications ()
Definition at line 78 of file parallel.cpp.
References msg_bufX, msg_sizeX, and Nbc.
                                                               :
 //--------------------------------------------------------------
 //  Constructor
 //--------------------------------------------------------------
         Nbc(Input::List().BoundaryCells),      // # of boundary cells
         bndX(Input::List().bndX) {        // Type of boundary in X
     // 3 components for Bx, By, Bz
     msg_sizeX = 3;
     msg_sizeX *= Nbc; //(IN().inp().y.dim()*Nbc);
     msg_bufX = new complex<double>[msg_sizeX];
 }
~Node_ImplicitE_Communications()
Node_ImplicitE_Communications::~Node_ImplicitE_Communications ()
Definition at line 95 of file parallel.cpp.
References msg_bufX.
{
 //--------------------------------------------------------------
 //  Destructor
 //--------------------------------------------------------------
     delete[] msg_bufX;
 }
Member Function Documentation
BNDX()
int Node_ImplicitE_Communications::BNDX () const
Definition at line 104 of file parallel.cpp.
References bndX.
Referenced by sameNode_bound_X().
 {return bndX;}
mirror_bound_Xleft()
void Node_ImplicitE_Communications::mirror_bound_Xleft (State1D & Y)
Definition at line 215 of file parallel.cpp.
References EMF1D::Bx(), EMF1D::dim(), State1D::EMF(), State1D::FLD(), Nbc, SHarmonic1D::numx(), and State1D::SH().
Referenced by Parallel_Environment_1D::Neighbor_ImplicitE_Communications().
{
 //-------------------------------------------------------------------------------------
 //  Mirror boundary in the x direction on the left
 //-------------------------------------------------------------------------------------
     size_t Nx(Y.SH(0,0,0).numx());
     // Mirror the fields
     for(int i(3); i < Y.EMF().dim(); ++i){ // "3" as opposed to "0"
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(c) = Y.FLD(i)(2*Nbc-c-1);
     }
     //Bx
     for(int c(0); c < Nbc; ++c) {
         Y.EMF().Bx()(c) *= -1.0; // left  boundary
     }
 }
mirror_bound_Xright()
void Node_ImplicitE_Communications::mirror_bound_Xright (State1D & Y)
Definition at line 237 of file parallel.cpp.
References EMF1D::Bx(), EMF1D::dim(), State1D::EMF(), State1D::FLD(), Nbc, SHarmonic1D::numx(), and State1D::SH().
Referenced by Parallel_Environment_1D::Neighbor_ImplicitE_Communications().
{
 //--------------------------------------------------------------
 //  Mirror boundary in the x direction on the right
 //--------------------------------------------------------------
     size_t Nx(Y.SH(0,0,0).numx());
     // Mirror the fields
     for(int i(3); i < Y.EMF().dim(); ++i){ // "3" as opposed to "0"
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(Nx-c-1) = Y.FLD(i)(Nx-2*Nbc+c);
     }
     //Bx
     for(int c(0); c < Nbc; ++c) {
         Y.EMF().Bx()(Nx-1-c) *= -1.0; // right  boundary
     }
 }
Recv_from_left_X()
void Node_ImplicitE_Communications::Recv_from_left_X (State1D & Y, int origin)
Definition at line 136 of file parallel.cpp.
References EMF1D::dim(), State1D::EMF(), State1D::FLD(), msg_bufX, msg_sizeX, and Nbc.
Referenced by Parallel_Environment_1D::Neighbor_ImplicitE_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Receive data from the node on the left and update
 //           the left guard cells
 //--------------------------------------------------------------
     static size_t step_f(Nbc);
     size_t bufind(0);
     MPI_Status status;
     // Receive Data
     MPI_Recv(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, origin, 0, MPI_COMM_WORLD, &status);
     // Fields:   x0-"---> Left-Guard"
     for(int i(3); i < Y.EMF().dim(); ++i){ // "3" as opposed to "0"
         for(int e(0); e < Nbc; e++) {
             Y.FLD(i)(e) = msg_bufX[bufind + e];
         }
         bufind += step_f;
     }
 }
Recv_from_right_X()
void Node_ImplicitE_Communications::Recv_from_right_X (State1D & Y, int origin)
Definition at line 182 of file parallel.cpp.
References EMF1D::dim(), State1D::EMF(), State1D::FLD(), msg_bufX, msg_sizeX, Nbc, and Field1D::numx().
Referenced by Parallel_Environment_1D::Neighbor_ImplicitE_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Receive data from the node on the right and update
 //           the right guard cells
 //--------------------------------------------------------------
     static size_t step_f(Nbc);
     size_t bufind(0);
     MPI_Status status;
     // Receive Data
     MPI_Recv(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, origin, 1, MPI_COMM_WORLD, &status);
     // Fields:   x0-"Right-Guard <--- "
     for(int i(3); i < Y.EMF().dim(); ++i){ // "3" as opposed to "0"
         for(int e(0); e < Nbc; e++) {
             Y.FLD(i)(Y.FLD(i).numx()-Nbc+e) = msg_bufX[bufind + e];
         }
         bufind += step_f;
     }
 }
sameNode_bound_X()
void Node_ImplicitE_Communications::sameNode_bound_X (State1D & Y)
Definition at line 264 of file parallel.cpp.
References BNDX(), sameNode_mirror_X(), and sameNode_periodic_X().
Referenced by Parallel_Environment_1D::Neighbor_ImplicitE_Communications().
{
 //--------------------------------------------------------------
 //  Choose between boundary conditions in the x direction
 //--------------------------------------------------------------
     switch (BNDX()) {
         case 0:                   // periodic
             sameNode_periodic_X(Y);
             break;
         case 1:                   // mirror boundary
             sameNode_mirror_X(Y);
             break;
         default:
             cout<<"Not a valid boundary condition." << endl;
             break;
     }
 }
sameNode_mirror_X()
void Node_ImplicitE_Communications::sameNode_mirror_X (State1D & Y) private
Definition at line 305 of file parallel.cpp.
References EMF1D::Bx(), EMF1D::dim(), State1D::EMF(), State1D::FLD(), Nbc, SHarmonic1D::numx(), and State1D::SH().
Referenced by sameNode_bound_X().
{
 //--------------------------------------------------------------
 //  Mirror boundary in the x direction for 1 node
 //--------------------------------------------------------------
     size_t Nx(Y.SH(0,0,0).numx());
     // Mirror the fields
     for(int i(3); i < Y.EMF().dim(); ++i){ // "3" as opposed to "0"
         // right boundary
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(Nx-c-1) = Y.FLD(i)(Nx-2*Nbc+c);
         // left boundary
         for (int c(0); c < Nbc; ++c)
             Y.FLD(i)(c) = Y.FLD(i)(2*Nbc-c-1);
     }
     //Bx
     for (int c(0); c < Nbc; ++c) {
         Y.EMF().Bx()(c) *= -1.0; // left  boundary
         Y.EMF().Bx()(Nx-Nbc+c) *= -1.0; // right  boundary
     }
 }
sameNode_periodic_X()
void Node_ImplicitE_Communications::sameNode_periodic_X (State1D & Y) private
Definition at line 284 of file parallel.cpp.
References EMF1D::dim(), State1D::EMF(), EMF1D::Ex(), State1D::FLD(), Nbc, and Field1D::numx().
Referenced by sameNode_bound_X().
{
 //--------------------------------------------------------------
 //  Periodic boundary in the x direction for 1 node
 //--------------------------------------------------------------
     // Fields:   x0 "Right-Bound ---> Left-Guard"
     for(int i(3); i < Y.EMF().dim(); ++i) // "3" as opposed to "0"
         for(int c(0); c < Nbc; c++) {
             Y.FLD(i)(c) = Y.FLD(i)(Y.EMF().Ex().numx()-2*Nbc+c);
         }
     // Fields:   x0 "Left-Bound ---> Right-Guard"
     for(int i(3); i < Y.EMF().dim(); ++i) // "3" as opposed to "0"
         for(int c(0); c < Nbc; c++) {
             Y.FLD(i)(Y.EMF().Ex().numx()-Nbc+c) = Y.FLD(i)(Nbc+c);
         }
 }
Send_left_X()
void Node_ImplicitE_Communications::Send_left_X (State1D & Y, int dest)
Definition at line 160 of file parallel.cpp.
References EMF1D::dim(), State1D::EMF(), State1D::FLD(), msg_bufX, msg_sizeX, and Nbc.
Referenced by Parallel_Environment_1D::Neighbor_ImplicitE_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Read data from the left boundary and send them
 //           to the node on the left
 //--------------------------------------------------------------
     static size_t step_f(Nbc);
     size_t bufind(0);
     // Fields:   x0 " <--- Left-Bound "
     for(int i(3); i < Y.EMF().dim(); ++i){ // "3" as opposed to "0"
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.FLD(i)(Nbc+e);
         }
         bufind += step_f;
     }
     MPI_Send(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, dest, 1, MPI_COMM_WORLD);
 }
Send_right_X()
void Node_ImplicitE_Communications::Send_right_X (State1D & Y, int dest)
Definition at line 114 of file parallel.cpp.
References EMF1D::dim(), State1D::EMF(), State1D::FLD(), msg_bufX, msg_sizeX, Nbc, and Field1D::numx().
Referenced by Parallel_Environment_1D::Neighbor_ImplicitE_Communications().
{
 //--------------------------------------------------------------
 //  X-axis : Read data from the right boundary and send them
 //           to the node on the right
 //--------------------------------------------------------------
     static size_t step_f(Nbc);
     size_t bufind(0);
     // Fields:   x0 "Right-Bound --> "
     for(size_t i(3); i < Y.EMF().dim(); ++i){  // "3" as opposed to "0"
         for(int e(0); e < Nbc; e++) {
             msg_bufX[bufind + e] = Y.FLD(i)(Y.FLD(i).numx()-2*Nbc+e);
         }
         bufind += step_f;
     }
     MPI_Send(msg_bufX, msg_sizeX, MPI_DOUBLE_COMPLEX, dest, 0, MPI_COMM_WORLD);
 }
Field Documentation
bndX
int Node_ImplicitE_Communications::bndX private
Definition at line 64 of file parallel.h.
Referenced by BNDX().
msg_bufX
complex<double>* Node_ImplicitE_Communications::msg_bufX private
Definition at line 68 of file parallel.h.
Referenced by Node_ImplicitE_Communications(), Recv_from_left_X(), Recv_from_right_X(), Send_left_X(), Send_right_X(), and ~Node_ImplicitE_Communications().
msg_sizeX
int Node_ImplicitE_Communications::msg_sizeX private
Definition at line 67 of file parallel.h.
Referenced by Node_ImplicitE_Communications(), Recv_from_left_X(), Recv_from_right_X(), Send_left_X(), and Send_right_X().
Nbc
int Node_ImplicitE_Communications::Nbc private
Definition at line 64 of file parallel.h.
Referenced by mirror_bound_Xleft(), mirror_bound_Xright(), Node_ImplicitE_Communications(), Recv_from_left_X(), Recv_from_right_X(), sameNode_mirror_X(), sameNode_periodic_X(), Send_left_X(), and Send_right_X().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/parallel.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/parallel.cpp