OSHUN: VlasovFunctor1D_momentumpush Class Reference
VlasovFunctor1D_momentumpush Class Reference
#include <functors.h>
Public Member Functions
VlasovFunctor1D_momentumpush (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_momentumpush ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Electric_Field_1D > EF
vector< Current_1D > JX
vector< Ampere_1D > AM
vector< Magnetic_Field_1D > BF
vector< Faraday_1D > FA
Detailed Description
Definition at line 67 of file functors.h.
Constructor & Destructor Documentation
VlasovFunctor1D_momentumpush()
VlasovFunctor1D_momentumpush::VlasovFunctor1D_momentumpush (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 213 of file functors.cpp.
References VlasovFunctor1D_explicitE::AM, VlasovFunctor1D_explicitE::BF, VlasovFunctor1D_explicitE::EF, VlasovFunctor1D_explicitE::FA, and VlasovFunctor1D_explicitE::JX.
{
 //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         EF.push_back( Electric_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         JX.push_back( Current_1D(0.0, pmax[s], Np[s], Nx) );
         BF.push_back( Magnetic_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         AM.push_back( Ampere_1D(xmin, xmax, Nx) );
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_momentumpush()
VlasovFunctor1D_momentumpush::~VlasovFunctor1D_momentumpush () inline
Definition at line 74 of file functors.h.
References VlasovFunctor1D_explicitE::operator()().
 { };
Member Function Documentation
operator()() [1/2]
void VlasovFunctor1D_momentumpush::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 236 of file functors.cpp.
References VlasovFunctor1D_explicitE::AM, VlasovFunctor1D_explicitE::BF, EMF1D::Bx(), EMF1D::By(), EMF1D::Bz(), State1D::DF(), VlasovFunctor1D_explicitE::EF, State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), VlasovFunctor1D_explicitE::FA, DistFunc1D::Filterp(), VlasovFunctor1D_explicitE::JX, DistFunc1D::l0(), DistFunc1D::m0(), and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         if (Yin.DF(s).l0() == 1) {
             EF[s].f1only(Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
             BF[s].f1only(Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
             JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
             AM[s](Yin.EMF(),Yslope.EMF());
             FA[s](Yin.EMF(),Yslope.EMF());
         }
         else if (Yin.DF(s).m0() == 0) {
             EF[s].es1d(Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
             JX[s].es1d(Yin.DF(s),Yslope.EMF().Ex());
         }
         else {
             EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
             BF[s](Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
             JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
             AM[s](Yin.EMF(),Yslope.EMF());
             FA[s](Yin.EMF(),Yslope.EMF());
         }
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/2]
void VlasovFunctor1D_momentumpush::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 285 of file functors.cpp.
 {}
Field Documentation
AM
vector<Ampere_1D> VlasovFunctor1D_momentumpush::AM private
Definition at line 84 of file functors.h.
BF
vector<Magnetic_Field_1D> VlasovFunctor1D_momentumpush::BF private
Definition at line 85 of file functors.h.
EF
vector<Electric_Field_1D> VlasovFunctor1D_momentumpush::EF private
Definition at line 82 of file functors.h.
FA
vector<Faraday_1D> VlasovFunctor1D_momentumpush::FA private
Definition at line 86 of file functors.h.
JX
vector<Current_1D> VlasovFunctor1D_momentumpush::JX private
Definition at line 83 of file functors.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.cpp