OSHUN: St2d
St2d
Data Structures
class SHarmonic2D
A 2D Spherical Harmonic.
class Field2D
A 2D Field.
class EMF1D
class EMF2D
An EMF2D is the container for the 6 EM fields in a 2D-3P code.
class DistFunc2D
The 2D distribution function is the container for all SHarmonic2D per species.
class State2D
Functions
SHarmonic1D::SHarmonic1D (size_t nump, size_t numx)
The constructor requires nump, and numx as inputs.
SHarmonic1D::SHarmonic1D (const SHarmonic1D &other)
SHarmonic1D::~SHarmonic1D ()
Array2D< complex< double > > & SHarmonic1D::array () const
To retrieve the the array that stores the information.
size_t SHarmonic1D::dim () const
size_t SHarmonic1D::nump () const
size_t SHarmonic1D::numx () const
complex< double > & SHarmonic1D::operator() (size_t i, size_t j)
complex< double > SHarmonic1D::operator() (size_t i, size_t j) const
complex< double > & SHarmonic1D::operator() (size_t i)
complex< double > SHarmonic1D::operator() (size_t i) const
vector< complex< double > > SHarmonic1D::xVec (size_t j) const
SHarmonic1D & SHarmonic1D::operator= (const complex< double > &d)
SHarmonic1D & SHarmonic1D::operator= (const SHarmonic1D &other)
SHarmonic1D & SHarmonic1D::operator*= (const complex< double > &d)
SHarmonic1D & SHarmonic1D::operator*= (const SHarmonic1D &shmulti)
SHarmonic1D & SHarmonic1D::operator+= (const complex< double > &d)
SHarmonic1D & SHarmonic1D::operator+= (const SHarmonic1D &shadd)
SHarmonic1D & SHarmonic1D::operator-= (const complex< double > &d)
SHarmonic1D & SHarmonic1D::operator-= (const SHarmonic1D &shmin)
SHarmonic1D & SHarmonic1D::mpaxis (const valarray< complex< double > > &shmulti)
SHarmonic1D & SHarmonic1D::mxaxis (const valarray< complex< double > > &shmulti)
SHarmonic1D & SHarmonic1D::Re ()
SHarmonic1D & SHarmonic1D::Dp ()
SHarmonic1D & SHarmonic1D::Dx ()
SHarmonic1D & SHarmonic1D::Filterp (size_t N)
void SHarmonic1D::checknan ()
SHarmonic2D::SHarmonic2D (size_t nump, size_t numx, size_t numy)
SHarmonic2D::SHarmonic2D (const SHarmonic2D &other)
SHarmonic2D::~SHarmonic2D ()
Array3D< complex< double > > & SHarmonic2D::array () const
size_t SHarmonic2D::dim () const
size_t SHarmonic2D::nump () const
size_t SHarmonic2D::numx () const
size_t SHarmonic2D::numy () const
complex< double > & SHarmonic2D::operator() (size_t i, size_t j, size_t k)
complex< double > & SHarmonic2D::operator() (size_t i)
SHarmonic2D & SHarmonic2D::operator= (const complex< double > &d)
SHarmonic2D & SHarmonic2D::operator= (const SHarmonic2D &other)
SHarmonic2D & SHarmonic2D::operator*= (const complex< double > &d)
SHarmonic2D & SHarmonic2D::operator*= (const SHarmonic2D &shmulti)
SHarmonic2D & SHarmonic2D::operator+= (const complex< double > &d)
SHarmonic2D & SHarmonic2D::operator+= (const SHarmonic2D &shadd)
SHarmonic2D & SHarmonic2D::operator-= (const complex< double > &d)
SHarmonic2D & SHarmonic2D::operator-= (const SHarmonic2D &shmin)
SHarmonic2D & SHarmonic2D::mpaxis (const valarray< complex< double > > &shmulti)
SHarmonic2D & SHarmonic2D::mxaxis (const valarray< complex< double > > &shmulti)
SHarmonic2D & SHarmonic2D::myaxis (const valarray< complex< double > > &shmulti)
SHarmonic2D & SHarmonic2D::mxy_matrix (Array2D< complex< double > > &shmultiM)
SHarmonic2D & SHarmonic2D::Dx ()
SHarmonic2D & SHarmonic2D::Dy ()
SHarmonic2D & SHarmonic2D::Filterp (size_t N)
Field1D::Field1D (size_t numx)
Field1D::Field1D (const Field1D &other)
Field1D::~Field1D ()
valarray< complex< double > > & Field1D::array () const
size_t Field1D::numx () const
complex< double > & Field1D::operator() (size_t i)
complex< double > Field1D::operator() (size_t i) const
Field1D & Field1D::operator= (const complex< double > &d)
Field1D & Field1D::operator= (const valarray< complex< double > > &other)
Field1D & Field1D::operator= (const Field1D &other)
Field1D & Field1D::operator*= (const complex< double > &d)
Field1D & Field1D::operator*= (const valarray< complex< double > > &fimulti)
Field1D & Field1D::operator*= (const Field1D &fimulti)
Field1D & Field1D::operator+= (const complex< double > &d)
Field1D & Field1D::operator+= (const Field1D &fiadd)
Field1D & Field1D::operator-= (const complex< double > &d)
Field1D & Field1D::operator-= (const Field1D &fimin)
Field1D & Field1D::Re ()
Field1D & Field1D::Dx ()
Field2D::Field2D (size_t numx, size_t numy)
Field2D::Field2D (const Field2D &other)
Field2D::~Field2D ()
Array2D< complex< double > > & Field2D::array () const
size_t Field2D::numx () const
size_t Field2D::numy () const
complex< double > & Field2D::operator() (size_t i, size_t j)
complex< double > & Field2D::operator() (size_t i)
Field2D & Field2D::operator= (const complex< double > &d)
Field2D & Field2D::operator= (const Field2D &other)
Field2D & Field2D::operator*= (const complex< double > &d)
Field2D & Field2D::operator*= (const Field2D &fimulti)
Field2D & Field2D::operator+= (const complex< double > &d)
Field2D & Field2D::operator+= (const Field2D &fiadd)
Field2D & Field2D::operator-= (const complex< double > &d)
Field2D & Field2D::operator-= (const Field2D &fimin)
Field2D & Field2D::Dx ()
Field2D & Field2D::Dy ()
EMF1D::EMF1D (size_t nx)
EMF1D::EMF1D (const EMF1D &other)
EMF1D::~EMF1D ()
size_t EMF1D::dim () const
Field1D & EMF1D::operator() (size_t i)
Field1D EMF1D::operator() (size_t i) const
Field1D & EMF1D::Ex ()
Field1D & EMF1D::Ey ()
Field1D & EMF1D::Ez ()
Field1D & EMF1D::Bx ()
Field1D & EMF1D::By ()
Field1D & EMF1D::Bz ()
EMF1D & EMF1D::operator= (const complex< double > &d)
EMF1D & EMF1D::operator= (const Field1D &h)
EMF1D & EMF1D::operator= (const EMF1D &other)
EMF1D & EMF1D::operator*= (const complex< double > &d)
EMF1D & EMF1D::operator*= (const EMF1D &other)
EMF1D & EMF1D::operator+= (const complex< double > &d)
EMF1D & EMF1D::operator+= (const EMF1D &other)
EMF1D & EMF1D::operator-= (const complex< double > &d)
EMF1D & EMF1D::operator-= (const EMF1D &other)
EMF2D::EMF2D (size_t nx, size_t ny)
EMF2D::EMF2D (const EMF2D &other)
EMF2D::~EMF2D ()
size_t EMF2D::dim () const
Field2D & EMF2D::operator() (size_t i)
Field2D EMF2D::operator() (size_t i) const
Field2D & EMF2D::Ex ()
Field2D & EMF2D::Ey ()
Field2D & EMF2D::Ez ()
Field2D & EMF2D::Bx ()
Field2D & EMF2D::By ()
Field2D & EMF2D::Bz ()
EMF2D & EMF2D::operator= (const complex< double > &d)
EMF2D & EMF2D::operator= (const Field2D &h)
EMF2D & EMF2D::operator= (const EMF2D &other)
EMF2D & EMF2D::operator*= (const complex< double > &d)
EMF2D & EMF2D::operator*= (const EMF2D &other)
EMF2D & EMF2D::operator+= (const complex< double > &d)
EMF2D & EMF2D::operator+= (const EMF2D &other)
EMF2D & EMF2D::operator-= (const complex< double > &d)
EMF2D & EMF2D::operator-= (const EMF2D &other)
DistFunc1D::DistFunc1D (size_t l, size_t m, size_t np, double pma, size_t nx, double q, double _ma)
DistFunc1D::DistFunc1D (const DistFunc1D &other)
DistFunc1D::~DistFunc1D ()
size_t DistFunc1D::dim () const
size_t DistFunc1D::l0 () const
size_t DistFunc1D::m0 () const
double DistFunc1D::pmax () const
double DistFunc1D::q () const
double DistFunc1D::mass () const
Array2D< int > DistFunc1D::indx () const
valarray< double > DistFunc1D::getdensity ()
valarray< double > DistFunc1D::getcurrent (size_t dir)
valarray< double > DistFunc1D::getcurrent (size_t dir) const
Array2D< double > DistFunc1D::getcurrent () const
valarray< double > DistFunc1D::getpressure ()
SHarmonic1D & DistFunc1D::operator() (int i)
SHarmonic1D & DistFunc1D::operator() (int i) const
SHarmonic1D & DistFunc1D::operator() (size_t l, size_t m)
SHarmonic1D & DistFunc1D::operator() (size_t l, size_t m) const
DistFunc1D & DistFunc1D::operator= (const complex< double > &d)
DistFunc1D & DistFunc1D::operator= (const SHarmonic1D &h)
DistFunc1D & DistFunc1D::operator= (const DistFunc1D &other)
DistFunc1D & DistFunc1D::operator*= (const complex< double > &d)
DistFunc1D & DistFunc1D::operator*= (const DistFunc1D &other)
DistFunc1D & DistFunc1D::operator+= (const complex< double > &d)
DistFunc1D & DistFunc1D::operator+= (const DistFunc1D &other)
DistFunc1D & DistFunc1D::operator-= (const complex< double > &d)
DistFunc1D & DistFunc1D::operator-= (const DistFunc1D &other)
DistFunc1D & DistFunc1D::Filterp ()
void DistFunc1D::checknan ()
Array2D< int > DistFunc2D::indx () const
DistFunc2D::DistFunc2D (size_t l, size_t m, size_t np, size_t nx, size_t ny, double q, double _ma)
DistFunc2D::DistFunc2D (const DistFunc2D &other)
DistFunc2D::~DistFunc2D ()
size_t DistFunc2D::dim () const
size_t DistFunc2D::ldim () const
size_t DistFunc2D::mdim () const
size_t DistFunc2D::l0 () const
size_t DistFunc2D::m0 () const
double DistFunc2D::q () const
double DistFunc2D::mass () const
SHarmonic2D * DistFunc2D::operator() (size_t i)
SHarmonic2D * DistFunc2D::operator() (size_t i) const
SHarmonic2D * DistFunc2D::operator() (size_t l, size_t m)
SHarmonic2D * DistFunc2D::operator() (size_t l, size_t m) const
DistFunc2D & DistFunc2D::operator= (const complex< double > &d)
DistFunc2D & DistFunc2D::operator= (const SHarmonic2D &h)
DistFunc2D & DistFunc2D::operator= (const DistFunc2D &other)
DistFunc2D & DistFunc2D::operator*= (const complex< double > &d)
DistFunc2D & DistFunc2D::operator*= (const DistFunc2D &other)
DistFunc2D & DistFunc2D::operator+= (const complex< double > &d)
DistFunc2D & DistFunc2D::operator+= (const DistFunc2D &other)
DistFunc2D & DistFunc2D::operator-= (const complex< double > &d)
DistFunc2D & DistFunc2D::operator-= (const DistFunc2D &other)
Hydro1D::Hydro1D (size_t numx, double _mass, double _charge)
Hydro1D::Hydro1D (const Hydro1D &other)
Hydro1D::~Hydro1D ()
size_t Hydro1D::numx () const
double Hydro1D::mass () const
double Hydro1D::charge () const
double & Hydro1D::density (size_t i)
double Hydro1D::density (size_t i) const
double & Hydro1D::vx (size_t i)
double Hydro1D::vx (size_t i) const
double & Hydro1D::vy (size_t i)
double Hydro1D::vy (size_t i) const
double & Hydro1D::vz (size_t i)
double Hydro1D::vz (size_t i) const
double & Hydro1D::temperature (size_t i)
double Hydro1D::temperature (size_t i) const
double & Hydro1D::Z (size_t i)
double Hydro1D::Z (size_t i) const
valarray< double > & Hydro1D::densityarray () const
valarray< double > & Hydro1D::vxarray () const
valarray< double > & Hydro1D::vyarray () const
valarray< double > & Hydro1D::vzarray () const
valarray< double > & Hydro1D::temperaturearray () const
valarray< double > & Hydro1D::Zarray () const
Hydro1D & Hydro1D::operator= (const double &d)
Hydro1D & Hydro1D::operator= (const valarray< double > &other)
Hydro1D & Hydro1D::operator= (const Hydro1D &other)
Hydro1D & Hydro1D::operator*= (const double &d)
Hydro1D & Hydro1D::operator*= (const valarray< double > &other)
Hydro1D & Hydro1D::operator*= (const Hydro1D &other)
Hydro1D & Hydro1D::operator+= (const double &d)
Hydro1D & Hydro1D::operator+= (const valarray< double > &other)
Hydro1D & Hydro1D::operator+= (const Hydro1D &other)
Hydro1D & Hydro1D::operator-= (const double &d)
Hydro1D & Hydro1D::operator-= (const valarray< double > &other)
Hydro1D & Hydro1D::operator-= (const Hydro1D &other)
State1D::State1D (size_t nx, vector< size_t > l0, vector< size_t > m0, vector< size_t > np, vector< double > pmax, vector< double > q, vector< double > ma, double hydromass, double hydrocharge)
State1D::State1D (const State1D &other)
State1D::~State1D ()
size_t State1D::Species () const
size_t State1D::Fields () const
void State1D::checknan ()
DistFunc1D & State1D::DF (size_t s)
DistFunc1D & State1D::DF (size_t s) const
SHarmonic1D & State1D::SH (size_t s, size_t lh, size_t mh)
SHarmonic1D & State1D::SH (size_t s, size_t lh, size_t mh) const
EMF1D & State1D::EMF () const
Field1D & State1D::FLD (size_t ip) const
Hydro1D & State1D::HYDRO ()
Hydro1D & State1D::HYDRO () const
State1D & State1D::operator= (const State1D &other)
State1D & State1D::operator= (const complex< double > &d)
State1D & State1D::operator*= (const State1D &other)
State1D & State1D::operator*= (const complex< double > &d)
State1D & State1D::operator+= (const State1D &other)
State1D & State1D::operator+= (const complex< double > &d)
State1D & State1D::operator-= (const State1D &other)
State1D & State1D::operator-= (const complex< double > &d)
State2D::State2D (size_t nx, size_t ny, vector< size_t > l0, vector< size_t > m0, vector< size_t > np, vector< double > q, vector< double > ma)
State2D::State2D (const State2D &other)
State2D::~State2D ()
size_t State2D::Species () const
size_t State2D::Fields () const
DistFunc2D & State2D::DF (size_t s)
DistFunc2D & State2D::DF (size_t s) const
SHarmonic2D & State2D::SH (size_t s, size_t lh, size_t mh)
SHarmonic2D & State2D::SH (size_t s, size_t lh, size_t mh) const
SHarmonic2D * State2D::SHp (size_t s, size_t lh, size_t mh)
SHarmonic2D * State2D::SHp (size_t s, size_t lh, size_t mh) const
EMF2D & State2D::EMF () const
Field2D & State2D::FLD (size_t ip) const
State2D & State2D::operator= (const State2D &other)
State2D & State2D::operator= (const complex< double > &d)
State2D & State2D::operator*= (const State2D &other)
State2D & State2D::operator*= (const complex< double > &d)
State2D & State2D::operator+= (const State2D &other)
State2D & State2D::operator+= (const complex< double > &d)
State2D & State2D::operator-= (const State2D &other)
State2D & State2D::operator-= (const complex< double > &d)
Variables
Array2D< complex< double > > * SHarmonic1D::sh
Array3D< complex< double > > * SHarmonic2D::sh
valarray< complex< double > > * Field1D::fi
Array2D< complex< double > > * Field2D::fi
vector< Field1D > * EMF1D::fie
vector< Field2D > * EMF2D::fie
vector< SHarmonic1D > * DistFunc1D::df
size_t DistFunc1D::lmax
size_t DistFunc1D::mmax
size_t DistFunc1D::sz
double DistFunc1D::pmx
double DistFunc1D::charge
double DistFunc1D::ma
Array2D< int > DistFunc1D::ind
valarray< int > DistFunc1D::filter_ceiling
vector< SHarmonic2D > * DistFunc2D::df
size_t DistFunc2D::lmax
size_t DistFunc2D::mmax
size_t DistFunc2D::sz
double DistFunc2D::charge
double DistFunc2D::ma
Array2D< int > DistFunc2D::ind
valarray< double > * Hydro1D::hn
valarray< double > * Hydro1D::hvx
valarray< double > * Hydro1D::hvy
valarray< double > * Hydro1D::hvz
valarray< double > * Hydro1D::ht
valarray< double > * Hydro1D::hz
double Hydro1D::hydromass
double Hydro1D::hydrocharge
vector< DistFunc1D > * State1D::sp
EMF1D * State1D::flds
Hydro1D * State1D::hydro
size_t State1D::ns
vector< DistFunc2D > * State2D::sp
EMF2D * State2D::flds
size_t State2D::ns
Detailed Description
Function Documentation
array() [1/4]
Array2D<complex<double> >& SHarmonic1D::array () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
To retrieve the the array that stores the information.
Definition at line 69 of file state.h.
Referenced by SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), SHarmonic1D::operator=(), and SHarmonic1D::SHarmonic1D().
 {return (*sh);}
array() [2/4]
Array3D< complex <double> >& SHarmonic2D::array () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 134 of file state.h.
Referenced by SHarmonic2D::operator*=(), SHarmonic2D::operator+=(), SHarmonic2D::operator-=(), SHarmonic2D::operator=(), and SHarmonic2D::SHarmonic2D().
 {return (*sh);}
array() [3/4]
valarray<complex<double> >& Field1D::array () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 196 of file state.h.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Magnetic_Field_1D::f1only(), Field1D::Field1D(), Magnetic_Field_1D_f1::implicit(), Magnetic_Field_1D::implicit(), Electric_Field_1D_f1::Implicit_Ex(), Electric_Field_1D::Implicit_Ex(), Electric_Field_1D::Implicit_Ex_f1only(), Electric_Field_1D_f1::Implicit_Ey(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D_f1::Implicit_Ez(), Electric_Field_1D::Implicit_Ez(), Electric_Field_1D::Implicit_Ez_f1only(), Electric_Field_1D::operator()(), Electric_Field_1D_f1::operator()(), Magnetic_Field_1D_f1::operator()(), Magnetic_Field_1D::operator()(), Field1D::operator*=(), Field1D::operator+=(), Field1D::operator-=(), and Field1D::operator=().
 {return (*fi);}
array() [4/4]
Array2D< complex <double> >& Field2D::array () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 245 of file state.h.
Referenced by Field2D::Field2D(), Field2D::operator*=(), Field2D::operator+=(), Field2D::operator-=(), and Field2D::operator=().
 {return (*fi);}
Bx() [1/2]
Field1D& EMF1D::Bx () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 293 of file state.h.
Referenced by Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Output_Data::Output_Preprocessor_1D::Bx(), Node_ImplicitE_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xleft(), Node_ImplicitE_Communications::mirror_bound_Xright(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_f1_implicitE_p1::operator()(), Node_ImplicitE_Communications::sameNode_mirror_X(), Node_Communications::sameNode_mirror_X(), and Fluid_Equation_1D::velocity().
 {return (*fie)[3];}
Bx() [2/2]
Field2D& EMF2D::Bx () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 345 of file state.h.
 {return (*fie)[3];}
By() [1/2]
Field1D& EMF1D::By () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 294 of file state.h.
Referenced by Electric_Field_Methods::Implicit_E_Field::Ampere(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Output_Data::Output_Preprocessor_1D::By(), VlasovFunctor1D_explicitE::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), Faraday_1D::operator()(), Ampere_1D::operator()(), VlasovFunctor1D_f1_implicitE_p1::operator()(), and Fluid_Equation_1D::velocity().
 {return (*fie)[4];}
By() [2/2]
Field2D& EMF2D::By () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 346 of file state.h.
 {return (*fie)[4];}
Bz() [1/2]
Field1D& EMF1D::Bz () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 295 of file state.h.
References SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
Referenced by Electric_Field_Methods::Implicit_E_Field::Ampere(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Output_Data::Output_Preprocessor_1D::Bz(), VlasovFunctor1D_explicitE::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), Faraday_1D::operator()(), Ampere_1D::operator()(), VlasovFunctor1D_f1_implicitE_p1::operator()(), and Fluid_Equation_1D::velocity().
 {return (*fie)[5];}
Bz() [2/2]
Field2D& EMF2D::Bz () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 347 of file state.h.
References SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
 {return (*fie)[5];}
charge()
double Hydro1D::charge () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 524 of file state.h.
Referenced by State1D::State1D(), and Fluid_Equation_1D::velocity().
 {return hydrocharge;}
checknan() [1/3]
void SHarmonic1D::checknan ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 218 of file state.cpp.
References SHarmonic1D::nump(), SHarmonic1D::numx(), and SHarmonic1D::sh.
Referenced by State1D::Fields(), DistFunc1D::indx(), and SHarmonic1D::xVec().
{
     for (size_t i(0); i<numx();++i){
         for (size_t p(0); p<nump();++p){
             if ((isnan((*sh)(p,i).real())) || (isnan((*sh)(p,i).imag())))
             {
                 std::cout << "NaN @ (" << p << "," << i << ")\n";
                 exit(1);
             }
         }
     }
 //    std::cout << "SH OK! \n";
     return;
 }
checknan() [2/3]
void DistFunc1D::checknan ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1103 of file state.cpp.
References DistFunc1D::df, DistFunc1D::dim(), and DistFunc1D::indx().
{
     for (int indx(0); indx<dim();++indx){
         for (size_t i(0); i<(*df)[indx].numx();++i){
             for (size_t p(0); p<(*df)[indx].nump();++p){
                 if (  isnan((*df)[indx](p,i).real()) || isnan((*df)[indx](p,i).imag())   )
                 {
                     std::cout << "NaN @ (" << indx << "," << p << "," << i << ")\n";
                     exit(1);
                 }
             }
         }
     }
 //    std::cout << "OK! \n";
     return;
 }
checknan() [3/3]
void State1D::checknan ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1630 of file state.cpp.
References State1D::ns.
                       {
     for(size_t s(0); s < ns; ++s){
         (*sp)[s].checknan();
     }
 //    std::cout << "Y OK! \n";
     return;
 }
density() [1/2]
double& Hydro1D::density (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 527 of file state.h.
Referenced by Fluid_Equation_1D::density(), Setup_Y::initialize(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Output_Data::Output_Preprocessor_1D::ni(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), and Fluid_Equation_1D::velocity().
 { return (*hn)[i];}             //1D-style
density() [2/2]
double Hydro1D::density (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 528 of file state.h.
 {return (*hn)[i];}
densityarray()
valarray<double >& Hydro1D::densityarray () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 545 of file state.h.
Referenced by Fluid_Equation_1D::chargefraction(), Fluid_Equation_1D::density(), Hydro1D::Hydro1D(), Setup_Y::initialize(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Fluid_Equation_1D::velocity().
 {return (*hn);}
DF() [1/4]
DistFunc1D& State1D::DF (size_t s) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 602 of file state.h.
Referenced by collisions::advance(), collisions::advancef0(), collisions::advancef1(), collisions::advanceflm(), Electric_Field_Methods::Current_xyz::calculate_J(), collisions::collisions(), Output_Data::Output_Preprocessor_1D::f0(), Output_Data::Output_Preprocessor_1D::f10(), Output_Data::Output_Preprocessor_1D::f11(), Output_Data::Output_Preprocessor_1D::f20(), Output_Data::Output_Preprocessor_1D::fl0(), Setup_Y::initialize(), interspecies_collisions::interspecies_collisions(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), Hydro_Functor::operator()(), VlasovFunctor1D_spatialpush::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_f1_explicitEB::operator()(), VlasovFunctor1D_implicitE_implicitB_p1::operator()(), VlasovFunctor1D_f1_implicitE_p1::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_f1_implicitEB_p1::operator()(), VlasovFunctor1D_f1_implicitE_p2::operator()(), State1D::operator*=(), State1D::operator+=(), State1D::operator-=(), State1D::operator=(), Output_Data::Output_Preprocessor_1D::px(), Export_Files::Restart_Facility::Read(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_mirror_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), State1D::State1D(), Output_Data::Output_Preprocessor_1D::T(), and Export_Files::Restart_Facility::Write().
 {return (*sp)[s];}
DF() [2/4]
DistFunc1D& State1D::DF (size_t s) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 603 of file state.h.
 {return (*sp)[s];}
DF() [3/4]
DistFunc2D& State2D::DF (size_t s) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 656 of file state.h.
Referenced by State2D::operator*=(), State2D::operator+=(), State2D::operator-=(), State2D::operator=(), and State2D::State2D().
 {return (*sp)[s];}
DF() [4/4]
DistFunc2D& State2D::DF (size_t s) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 657 of file state.h.
 {return (*sp)[s];}
dim() [1/6]
size_t SHarmonic1D::dim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 70 of file state.h.
Referenced by EMF1D::operator*=(), EMF2D::operator*=(), EMF1D::operator+=(), EMF2D::operator+=(), EMF1D::operator-=(), EMF2D::operator-=(), EMF1D::operator=(), EMF2D::operator=(), and SHarmonic1D::Re().
 {return (*sh).dim();} //< Total number of values in the array
dim() [2/6]
size_t SHarmonic2D::dim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 135 of file state.h.
 {return (*sh).dim();}
dim() [3/6]
size_t EMF1D::dim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 286 of file state.h.
Referenced by EMF1D::EMF1D(), Node_ImplicitE_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xleft(), Node_ImplicitE_Communications::mirror_bound_Xright(), Node_Communications::mirror_bound_Xright(), Node_ImplicitE_Communications::Recv_from_left_X(), Node_Communications::Recv_from_left_X(), Node_ImplicitE_Communications::Recv_from_right_X(), Node_Communications::Recv_from_right_X(), Node_ImplicitE_Communications::sameNode_mirror_X(), Node_Communications::sameNode_mirror_X(), Node_ImplicitE_Communications::sameNode_periodic_X(), Node_Communications::sameNode_periodic_X(), Node_ImplicitE_Communications::Send_left_X(), Node_Communications::Send_left_X(), Node_ImplicitE_Communications::Send_right_X(), and Node_Communications::Send_right_X().
 {return (*fie).size();}
dim() [4/6]
size_t EMF2D::dim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 338 of file state.h.
Referenced by EMF2D::EMF2D().
 {return (*fie).size();}
dim() [5/6]
size_t DistFunc1D::dim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 395 of file state.h.
Referenced by collisions::advance(), DistFunc1D::checknan(), DistFunc1D::Filterp(), Output_Data::p1x1_1D::operator()(), DistFunc1D::operator*=(), DistFunc1D::operator+=(), DistFunc1D::operator-=(), DistFunc1D::operator=(), Export_Files::Restart_Facility::Read(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), and Export_Files::Restart_Facility::Write().
 {return sz;}
dim() [6/6]
size_t DistFunc2D::dim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 468 of file state.h.
Referenced by DistFunc2D::operator*=(), DistFunc2D::operator+=(), DistFunc2D::operator-=(), and DistFunc2D::operator=().
 {return sz;}
DistFunc1D() [1/2]
DistFunc1D::DistFunc1D (size_t l, size_t m, size_t np, double pma, size_t nx, double q = 1, double _ma = 1)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 749 of file state.cpp.
References DistFunc1D::df, DistFunc1D::filter_ceiling, DistFunc1D::ind, DistFunc1D::lmax, DistFunc1D::mmax, and DistFunc1D::sz.
         : lmax(l), mmax(m), pmx(pma), charge(q), ma(_ma), ind(l+1,m+1) {
 //      Initialize the array of the harmonics
     if (lmax < 1) {
         cout << "l0 < 1 is not acceptable.\n";
         exit(1);
     }
 //      Generate container for the harmonics
     sz = ((mmax+1)*(2*lmax-mmax+2))/2;
     df = new vector<SHarmonic1D>(sz,SHarmonic1D(np,nx));
     valarray<int> filter_ceiling(0,sz);
 //      Define the index for the triangular array
     ind = -1;
     if (mmax == 0)
     {
         for(int il(0); il < lmax+1 ; ++il){
             ind(il,0) = il;
             // filter_ceiling[il] = floor(il/ceil(lmax/np));
             filter_ceiling[il] = ((il < np)?il:np);
         }
     }
     else
     {
         for(int il=0; il < lmax+1 ; ++il){
             for(int im=0; im < ((mmax < il)? mmax:il)+1; ++im){
                 ind(il,im) = ((il < mmax+1)?((il*(il+1))/2+im):
                               (il*(mmax+1)-(mmax*(mmax+1))/2 + im));
                 filter_ceiling[ind(il,im)] = ((il < np)?il:np);
             }
         }
     }
     // exit(1);
 }
DistFunc1D() [2/2]
DistFunc1D::DistFunc1D (const DistFunc1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 791 of file state.cpp.
References DistFunc1D::df, DistFunc1D::filter_ceiling, DistFunc1D::ind, DistFunc1D::lmax, DistFunc1D::mmax, and DistFunc1D::sz.
         : lmax(other.l0()), mmax(other.m0()), pmx(other.pmax()),
           charge(other.q()), ma(other.mass()), ind(other.l0()+1,other.m0()+1),
           filter_ceiling(((mmax+1)*(2*lmax-mmax+2))/2)  {
 //      Generate container for the harmonics
     sz = ((mmax+1)*(2*lmax-mmax+2))/2;
     df = new vector<SHarmonic1D>(sz,SHarmonic1D(other(0).nump(),other(0).numx()));
     for(size_t i(0); i < sz ; ++i){
         (*df).push_back(other(i));
     }
 //      Define the index for the triangular array
     ind = -1;
     if (mmax == 0)
     {
         for(int il(0); il < lmax+1 ; ++il){
             ind(il,0) = il;
             filter_ceiling[il] = (il < other(0).nump())?il:other(0).nump();
         }
     }
     else
     {
         for(int il=0; il < lmax+1 ; ++il){
             for(int im=0; im < ((mmax < il)? mmax:il)+1; ++im){
                 ind(il,im) = ((il < mmax+1)?((il*(il+1))/2+im):
                               (il*(mmax+1)-(mmax*(mmax+1))/2 + im));
                 filter_ceiling[ind(il,im)] = (il*im < other(0).nump())?il*im:other(0).nump();
             }
         }
     }
     // exit(1);
 }
DistFunc2D() [1/2]
DistFunc2D::DistFunc2D (size_t l, size_t m, size_t np, size_t nx, size_t ny, double q = 1, double _ma = 1)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1131 of file state.cpp.
References DistFunc2D::df, DistFunc2D::ind, DistFunc2D::lmax, DistFunc2D::mmax, and DistFunc2D::sz.
         : lmax(l), mmax(m), charge(q), ma(_ma), ind(l+1,m+1) {
     // double q=1, double _ma=1)
 //      Initialize the array of the harmonics
     if (lmax < 1 || mmax < 1) {
         cout << "l0 < 1 or m0 < 1 is not acceptable.\n";
         exit(1);
     }
     sz = ((mmax+1)*(2*lmax-mmax+2))/2;
 //      Generate container for the harmonics
     df = new vector<SHarmonic2D>(sz,SHarmonic2D(np,nx,ny));
 //      Define the index for the triangular array
     ind = -1;
     for(int il=0; il < lmax+1 ; ++il){
         for(int im=0; im < ((mmax < il)? mmax:il)+1; ++im){
             ind(il,im) = ((il < mmax+1)?((il*(il+1))/2+im):
                           (il*(mmax+1)-(mmax*(mmax+1))/2 + im));
         }
     }
 }
DistFunc2D() [2/2]
DistFunc2D::DistFunc2D (const DistFunc2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1159 of file state.cpp.
References DistFunc2D::df, DistFunc2D::ind, DistFunc2D::l0(), and DistFunc2D::m0().
         : lmax(other.l0()), mmax(other.m0()), charge(other.q()), ma(other.mass()), ind(other.ldim(),other.mdim()) {
 //      Generate container for the harmonics
     df = new vector<SHarmonic2D>;
     for(size_t l(0); l < other.l0()+1 ; ++l){
         for(size_t m(0); m < other.m0()+1 ; ++m){
             (*df).push_back(*(other(l,m)));
         }
     }
     //      Define the index for the triangular array
     ind = -1;
     for(int il=0; il < l0()+1 ; ++il){
         for(int im=0; im < ((m0() < il)? m0():il)+1; ++im){
             ind(il,im) = ((il < m0()+1)?((il*(il+1))/2+im):
                           (il*(m0()+1)-(m0()*(m0()+1))/2 + im));
         }
     }
 }
Dp()
SHarmonic1D & SHarmonic1D::Dp ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
2nd order
4th order
Definition at line 139 of file state.cpp.
References Array2D< T >::Dd1(), SHarmonic1D::nump(), SHarmonic1D::numx(), and SHarmonic1D::sh.
Referenced by Setup_Y::init_f1(), Electric_Field_1D_f1::MakeG00(), Electric_Field_1D::MakeG00(), Hydro_Advection_1D::MakeG00(), Electric_Field_1D_f1::MakeGH(), Electric_Field_1D::MakeGH(), Hydro_Advection_1D::MakeGH(), and SHarmonic1D::xVec().
{
     //--------------------------------------------------------//
     //--------------------------------------------------------//
         valarray  <complex<double> >  plast(this->numx());
         for (size_t i(0); i < plast.size(); ++i) {
             plast[i] = (*sh)(nump()-2,i) - (*sh)(nump()-1,i);
         }
         *sh = (*sh).Dd1();
         for (size_t i(0); i < plast.size(); ++i) {
           // TODO                The Dp at the zeroth cell is taken care off
           // (*sh)(0,i) = 0.0;     //separately, both for the E-field and the collisions.
             (*sh)(nump()-1,i) = 2.0*plast[i];
         }
     //--------------------------------------------------------//
     //--------------------------------------------------------//
     // Array2D<complex<double> > df((*this).nump(),(*this).numx());
     // for (long i2(0); i2<numx();++i2){
     //     df(0,i2) = (*this)(1,i2)-(*this)(0,i2);
     //     df(1,i2) = 1.0/12.0*((*this)(4,i2)-6.0*(*this)(3,i2)+18.0*(*this)(2,i2)-10.0*(*this)(1,i2)-3.0*(*this)(0,i2));
     //     for (long i1(2); i1<nump()-2;++i1){
     //         df(i1,i2) = 1.0/12.0*(-(*this)(i1+2,i2)+8.0*(*this)(i1+1,i2)-8.0*(*this)(i1-1,i2)+(*this)(i1-2,i2));
     //     }
     //     df(nump()-2,i2) = 0.0; //1.0/12.0*(3.0*(*this)(nump()-1,i2)+10.0*(*this)(nump()-2,i2)-18.0*(*this)(nump()-3,i2)+6.0*(*this)(nump()-4,i2)-(*this)(nump()-5,i2));
     //     df(nump()-1,i2) = 0.0; //(*this)(nump()-1,i2)-(*this)(nump()-2,i2);
     // }
     // for (long i2(0); i2<numx();++i2) {
     //     for (long i1(0); i1 < nump(); ++i1) {
     //         (*this)(i1, i2) = -2.0*df(i1, i2);
     //     }
     // }
     return *this;
 }
Dx() [1/4]
SHarmonic1D & SHarmonic1D::Dx ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
2nd order
Definition at line 185 of file state.cpp.
References Array2D< T >::Dd2(), and SHarmonic1D::sh.
Referenced by Spatial_Advection_1D::f1only(), Spatial_Advection_1D::operator()(), Spatial_Advection_1D_f1::operator()(), SHarmonic2D::operator()(), Field1D::operator()(), Field2D::operator()(), and SHarmonic1D::xVec().
{
     //--------------------------------------------------------//
     //--------------------------------------------------------//
     // for (size_t ix(0); ix < this->numx(); ++ix) {
     //     for (size_t ip(0); ip < this->nump(); ++ip) {
     //         (*sh)(ip,ix) = ix;
     //     }
     // }
     *sh = (*sh).Dd2();                          // Worry about boundaries elsewhere
     // for (size_t ix(0); ix < this->numx(); ++ix) {
     //     for (size_t ip(0); ip < this->nump(); ++ip) {
     //         std::cout << "*sh(" << ip << "," << ix << ")" <<  (*sh)(ip,ix) << "\n";
     //     }
     // }
     //--------------------------------------------------------//
     //--------------------------------------------------------//
     return *this;
 }
Dx() [2/4]
SHarmonic2D & SHarmonic2D::Dx ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 341 of file state.cpp.
References Array2D< T >::Dd2(), and SHarmonic1D::sh.
{
     *sh = (*sh).Dd2();                          // Worry about boundaries elsewhere
     return *this;
 }
Dx() [3/4]
Field1D & Field1D::Dx ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
4th order
Definition at line 450 of file state.cpp.
References SHarmonic1D::numx().
Referenced by Faraday_1D::operator()(), and Ampere_1D::operator()().
                     {
 //--------------------------------------------------------------
     //--------------------------------------------------------//
     //--------------------------------------------------------//
     // valarray<complex<double> > df(numx());
     // df[0] = (*fi)[1]-(*fi)[0];
     // df[1] = 1.0/12.0*((*fi)[4]-6.0*(*fi)[3]+18.0*(*fi)[2]-10.0*(*fi)[1]-3.0*(*fi)[0]);
     // for (long i(2); i < numx()-2; ++i) {
     //     df[i] = 1.0/12.0*(-(*fi)[i+2]+8.0*(*fi)[i+1]-8.0*(*fi)[i-1]+(*fi)[i-2]);
     // }
     // df[numx()-2] = 1.0/12.0*(3.0*(*fi)[numx()-1]+10.0*(*fi)[numx()-2]-18.0*(*fi)[numx()-3]+6.0*(*fi)[numx()-4]-(*fi)[numx()-5]);
     // df[numx()-1] = (*fi)[numx()-1]-(*fi)[numx()-2];
     // for (long i(0); i < numx(); ++i)
     //     (*fi)[i] = -2.0*df[i];
     //--------------------------------------------------------//
     //--------------------------------------------------------//
     // 2nd order
         // df[0] = 2.0*((*fi)[0]-(*fi)[1]);
         // for(long i(0); i < long(numx())-1; ++i) {
         //     df[i] = (*fi)[i-1]-(*fi)[i+1];
         // }
         // df[numx()-1] = 2.0*((*fi)[numx()-2]-(*fi)[numx()-1]);
         // *fi = df;
         for(long i(0); i< long(numx())-2; ++i) {
             (*fi)[i] -= (*fi)[i+2];
         }
         for(long i(numx()-3); i>-1; --i) {
             (*fi)[i+1] = (*fi)[i];
         }
     //--------------------------------------------------------//
     //--------------------------------------------------------//
     return *this;
 }
Dx() [4/4]
Field2D & Field2D::Dx ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 556 of file state.cpp.
                     {
 //--------------------------------------------------------------
     *fi = (*fi).Dd1();
     return *this;
 }
Dy() [1/2]
SHarmonic2D & SHarmonic2D::Dy ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 347 of file state.cpp.
References SHarmonic1D::sh.
{
     *sh = (*sh).Dd3();                          // Worry about boundaries elsewhere
     return *this;
 }
Dy() [2/2]
Field2D & Field2D::Dy ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 562 of file state.cpp.
                     {
 //--------------------------------------------------------------
     *fi = (*fi).Dd2();
     return *this;
 }
EMF() [1/2]
EMF1D& State1D::EMF () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 610 of file state.h.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Output_Data::Output_Preprocessor_1D::Bx(), Output_Data::Output_Preprocessor_1D::By(), Output_Data::Output_Preprocessor_1D::Bz(), Electric_Field_Methods::Current_xyz::calculate_J(), Output_Data::Output_Preprocessor_1D::Ex(), Output_Data::Output_Preprocessor_1D::Ey(), Output_Data::Output_Preprocessor_1D::Ez(), Setup_Y::initialize(), Node_ImplicitE_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xleft(), Node_ImplicitE_Communications::mirror_bound_Xright(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), Hydro_Functor::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_f1_explicitEB::operator()(), VlasovFunctor1D_f1_implicitE_p1::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_f1_implicitE_p2::operator()(), State1D::operator*=(), State1D::operator+=(), State1D::operator-=(), State1D::operator=(), Export_Files::Restart_Facility::Read(), Node_ImplicitE_Communications::Recv_from_left_X(), Node_Communications::Recv_from_left_X(), Node_ImplicitE_Communications::Recv_from_right_X(), Node_Communications::Recv_from_right_X(), Node_ImplicitE_Communications::sameNode_mirror_X(), Node_Communications::sameNode_mirror_X(), Node_ImplicitE_Communications::sameNode_periodic_X(), Node_Communications::sameNode_periodic_X(), Node_ImplicitE_Communications::Send_left_X(), Node_Communications::Send_left_X(), Node_ImplicitE_Communications::Send_right_X(), Node_Communications::Send_right_X(), State1D::State1D(), Fluid_Equation_1D::velocity(), and Export_Files::Restart_Facility::Write().
 {return (*flds);}
EMF() [2/2]
EMF2D& State2D::EMF () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 664 of file state.h.
Referenced by State2D::operator*=(), State2D::operator+=(), State2D::operator-=(), State2D::operator=(), and State2D::State2D().
 {return (*flds);}
EMF1D() [1/2]
EMF1D::EMF1D (size_t nx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 581 of file state.cpp.
{
     fie = new vector<Field1D> (6,Field1D(nx));
 }
EMF1D() [2/2]
EMF1D::EMF1D (const EMF1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 586 of file state.cpp.
References EMF1D::dim(), and SHarmonic1D::numx().
{
     fie = new vector<Field1D>(6,Field1D(other(1).numx()));
     for(int i=0; i < other.dim() ; ++i) (*fie)[i] = other(i);
 }
EMF2D() [1/2]
EMF2D::EMF2D (size_t nx, size_t ny)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 664 of file state.cpp.
{
     fie = new vector<Field2D> (6,Field2D(nx,ny));
 }
EMF2D() [2/2]
EMF2D::EMF2D (const EMF2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 669 of file state.cpp.
References EMF2D::dim(), and SHarmonic1D::numx().
{
     fie = new vector<Field2D>(6,Field2D(other(1).numx(),other(1).numy()));
     for(int i=0; i < other.dim() ; ++i) (*fie)[i] = other(i);
 }
Ex() [1/2]
Field1D& EMF1D::Ex () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 290 of file state.h.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Electric_Field_Methods::Current_xyz::calculate_J(), Output_Data::Output_Preprocessor_1D::Ex(), Electric_Field_Methods::Implicit_E_Field::FindDE(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_f1_explicitEB::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_f1_implicitE_p2::operator()(), Export_Files::Restart_Facility::Read(), Node_Communications::sameNode_mirror_X(), Node_ImplicitE_Communications::sameNode_periodic_X(), Node_Communications::sameNode_periodic_X(), Fluid_Equation_1D::velocity(), and Export_Files::Restart_Facility::Write().
 {return (*fie)[0];}
Ex() [2/2]
Field2D& EMF2D::Ex () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 342 of file state.h.
 {return (*fie)[0];}
Ey() [1/2]
Field1D& EMF1D::Ey () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 291 of file state.h.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Output_Data::Output_Preprocessor_1D::Ey(), Electric_Field_Methods::Implicit_E_Field::FindDE(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), Faraday_1D::operator()(), VlasovFunctor1D_f1_explicitEB::operator()(), Ampere_1D::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_f1_implicitE_p2::operator()(), Node_Communications::sameNode_mirror_X(), and Fluid_Equation_1D::velocity().
 {return (*fie)[1];}
Ey() [2/2]
Field2D& EMF2D::Ey () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 343 of file state.h.
 {return (*fie)[1];}
Ez() [1/2]
Field1D& EMF1D::Ez () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 292 of file state.h.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Output_Data::Output_Preprocessor_1D::Ez(), Electric_Field_Methods::Implicit_E_Field::FindDE(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), Faraday_1D::operator()(), VlasovFunctor1D_f1_explicitEB::operator()(), Ampere_1D::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_f1_implicitE_p2::operator()(), Node_Communications::sameNode_mirror_X(), and Fluid_Equation_1D::velocity().
 {return (*fie)[2];}
Ez() [2/2]
Field2D& EMF2D::Ez () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 344 of file state.h.
 {return (*fie)[2];}
Field1D() [1/2]
Field1D::Field1D (size_t numx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 377 of file state.cpp.
References SHarmonic1D::numx().
{
     fi = new  valarray<complex<double> >(numx);
 }
Field1D() [2/2]
Field1D::Field1D (const Field1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 381 of file state.cpp.
References Field1D::array(), and Field1D::numx().
{
     fi = new valarray<complex<double> >(other.numx());
     *fi = other.array();
 }
Field2D() [1/2]
Field2D::Field2D (size_t numx, size_t numy)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 499 of file state.cpp.
References SHarmonic1D::numx().
{
     fi = new  Array2D < complex <double> >(numx,numy);
 }
Field2D() [2/2]
Field2D::Field2D (const Field2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 503 of file state.cpp.
References Field2D::array(), Field2D::numx(), and Field2D::numy().
{
     fi = new Array2D < complex < double > >(other.numx(),other.numy());
     *fi = other.array();
 }
Fields() [1/2]
size_t State1D::Fields () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 597 of file state.h.
References SHarmonic1D::checknan().
 {return 6;}
Fields() [2/2]
size_t State2D::Fields () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 652 of file state.h.
 {return 6;}
Filterp() [1/3]
SHarmonic1D & SHarmonic1D::Filterp (size_t N)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 212 of file state.cpp.
References Array2D< T >::Filterd1(), and SHarmonic1D::sh.
Referenced by DistFunc1D::indx(), SHarmonic2D::operator()(), and SHarmonic1D::xVec().
{
     *sh = (*sh).Filterd1(N);
     return *this;
 }
Filterp() [2/3]
SHarmonic2D & SHarmonic2D::Filterp (size_t N)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 364 of file state.cpp.
References Array2D< T >::Filterd1(), and SHarmonic1D::sh.
{
     *sh = (*sh).Filterd1(N);
     return *this;
 }
Filterp() [3/3]
DistFunc1D & DistFunc1D::Filterp ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 934 of file state.cpp.
References DistFunc1D::dim(), and DistFunc1D::Filterp().
Referenced by DistFunc1D::Filterp(), VlasovFunctor1D_spatialpush::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_f1_explicitEB::operator()(), VlasovFunctor1D_implicitE_implicitB_p1::operator()(), VlasovFunctor1D_f1_implicitE_p1::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_f1_implicitEB_p1::operator()(), and VlasovFunctor1D_f1_implicitE_p2::operator()().
{
     for(size_t i(0); i < dim() ; ++i) {
         (*df)[i].Filterp(i);
         // (*df)[i].Filterp(filter_ceiling[i]);
     }
     return *this;
 }
FLD() [1/2]
Field1D& State1D::FLD (size_t ip) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 611 of file state.h.
Referenced by Node_ImplicitE_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xleft(), Node_ImplicitE_Communications::mirror_bound_Xright(), Node_Communications::mirror_bound_Xright(), Node_ImplicitE_Communications::Recv_from_left_X(), Node_Communications::Recv_from_left_X(), Node_ImplicitE_Communications::Recv_from_right_X(), Node_Communications::Recv_from_right_X(), Node_ImplicitE_Communications::sameNode_mirror_X(), Node_Communications::sameNode_mirror_X(), Node_ImplicitE_Communications::sameNode_periodic_X(), Node_Communications::sameNode_periodic_X(), Node_ImplicitE_Communications::Send_left_X(), Node_Communications::Send_left_X(), Node_ImplicitE_Communications::Send_right_X(), Node_Communications::Send_right_X(), and State1D::State1D().
 {return (*flds)(ip);}
FLD() [2/2]
Field2D& State2D::FLD (size_t ip) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 665 of file state.h.
References SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
Referenced by State2D::State2D().
 {return (*flds)(ip);}
getcurrent() [1/3]
valarray< double > DistFunc1D::getcurrent (size_t dir)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 965 of file state.cpp.
References DistFunc1D::charge, DistFunc1D::df, DistFunc1D::ma, Algorithms::MakeCAxis(), DistFunc1D::pmax(), and Algorithms::relativistic_invg_moment().
Referenced by Electric_Field_Methods::Current_xyz::calculate_J(), Current_1D::es1d(), and Current_1D::operator()().
{
     // complex<double> ii(0.0,-1.0);
     valarray<double> out((*df)[0].numx());
    // valarray<complex<double> > vr(Algorithms::MakeAxis(
    //         static_cast<complex<double> > (pmax()/(2.0*((*df)[0].nump()))),static_cast<complex<double> >(pmax()),(*df)[0].nump()
    // ));
     valarray<complex<double> > vr(Algorithms::MakeCAxis(
             static_cast<complex<double> > (0.0),static_cast<complex<double> >(pmax()),(*df)[0].nump()
     ));
     if (dir == 0)
     {
         for (size_t i(0); i<(*df)[0].numx();++i){
             out[i] = (4.0/3.0*M_PI*charge/ma)*(Algorithms::relativistic_invg_moment((*df)[1].xVec(i),vr,3.0)).real();
         }
     }
     else if (dir == 1)
     {
         for (size_t i(0); i<(*df)[0].numx();++i){
             out[i] = (8.0/3.0*M_PI*charge/ma)*(Algorithms::relativistic_invg_moment((*df)[2].xVec(i),vr,3.0)).real();
         }
     }
     else if (dir == 2)
     {
         for (size_t i(0); i<(*df)[0].numx();++i){
             out[i] = (-8.0/3.0*M_PI*charge/ma)*(Algorithms::relativistic_invg_moment((*df)[2].xVec(i),vr,3.0)).imag();
         }
     }
     else
     {
         std::cout << "\n\n ERROR: Wrong current Direction \n\n ";
         exit(1);
     }
     return out;
 }
getcurrent() [2/3]
valarray< double > DistFunc1D::getcurrent (size_t dir) const
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1008 of file state.cpp.
References DistFunc1D::charge, DistFunc1D::df, DistFunc1D::ma, Algorithms::MakeCAxis(), DistFunc1D::pmax(), and Algorithms::relativistic_invg_moment().
{
     // complex<double> ii(0.0,-1.0);
     valarray<double> out((*df)[0].numx());
    // valarray<complex<double> > vr(Algorithms::MakeAxis(
    //         static_cast<complex<double> > (pmax()/(2.0*((*df)[0].nump()))),static_cast<complex<double> >(pmax()),(*df)[0].nump()
    // ));
     valarray<complex<double> > vr(Algorithms::MakeCAxis(
             static_cast<complex<double> > (0.0),static_cast<complex<double> >(pmax()),(*df)[0].nump()
     ));
     if (dir == 0)
     {
         for (size_t i(0); i<(*df)[0].numx();++i){
             out[i] = (4.0/3.0*M_PI*charge/ma)*(Algorithms::relativistic_invg_moment((*df)[1].xVec(i),vr,3.0)).real();
         }
     }
     else if (dir == 1)
     {
         for (size_t i(0); i<(*df)[0].numx();++i){
             out[i] = (8.0/3.0*M_PI*charge/ma)*(Algorithms::relativistic_invg_moment((*df)[2].xVec(i),vr,3.0)).real();
         }
     }
     else if (dir == 2)
     {
         for (size_t i(0); i<(*df)[0].numx();++i){
             out[i] = (-8.0/3.0*M_PI*charge/ma)*(Algorithms::relativistic_invg_moment((*df)[2].xVec(i),vr,3.0)).imag();
         }
     }
     else
     {
         std::cout << "\n\n ERROR: Wrong current Direction \n\n ";
         exit(1);
     }
     return out;
 }
getcurrent() [3/3]
Array2D< double > DistFunc1D::getcurrent () const
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1050 of file state.cpp.
References DistFunc1D::charge, DistFunc1D::df, DistFunc1D::ma, Algorithms::MakeCAxis(), DistFunc1D::pmax(), and Algorithms::relativistic_invg_moment().
{
     // complex<double> ii(0.0,-1.0);
     Array2D<double> out(3,(*df)[0].numx());
 //        valarray<complex<double> > vr(Algorithms::MakeAxis(
 //            static_cast<complex<double> > (pmax()/(2.0*((*df)[0].nump())-1.0)),static_cast<complex<double> >(pmax()),(*df)[0].nump()
 //            ));
     valarray<complex<double> > vr(Algorithms::MakeCAxis(
             static_cast<complex<double> > (0.0),static_cast<complex<double> >(pmax()),(*df)[0].nump()
     ));
     double current_c1(4.0/3.0*M_PI*charge/ma);
     double current_c2(2.0*current_c1);
     double current_c3(-1.0*current_c2);
     for (size_t i(0); i<(*df)[0].numx();++i){
         out(0,i) = (current_c1)*(Algorithms::relativistic_invg_moment((*df)[1].xVec(i),vr,3.0)).real();
         out(1,i) = (current_c2)*(Algorithms::relativistic_invg_moment((*df)[2].xVec(i),vr,3.0)).real();
         out(2,i) = (current_c3)*(Algorithms::relativistic_invg_moment((*df)[2].xVec(i),vr,3.0)).imag();
     }
     return out;
 }
getdensity()
valarray< double > DistFunc1D::getdensity ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 945 of file state.cpp.
References DistFunc1D::df, Algorithms::MakeCAxis(), Algorithms::moment(), and DistFunc1D::pmax().
Referenced by Hydro_Functor::operator()().
{
     valarray<double> out((*df)[0].numx());
 //    valarray<complex<double> > vr(Algorithms::MakeAxis(
 //            static_cast<complex<double> > (pmax()/(2.0*((*df)[0].nump())-1.0)),static_cast<complex<double> >(pmax()),(*df)[0].nump()
 //    ));
     valarray<complex<double> > vr(Algorithms::MakeCAxis(
             static_cast<complex<double> > (0.0),static_cast<complex<double> >(pmax()),(*df)[0].nump()
     ));
     for (size_t i(0); i<(*df)[0].numx();++i){
         out[i] = (4.0*M_PI*Algorithms::moment((*df)[0].xVec(i),vr,2.0)).real();
     }
     return out;
 }
getpressure()
valarray< double > DistFunc1D::getpressure ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1081 of file state.cpp.
References DistFunc1D::df, DistFunc1D::ma, Algorithms::MakeCAxis(), Algorithms::moment(), and DistFunc1D::pmax().
Referenced by Hydro_Functor::operator()().
{
     valarray<double> out((*df)[0].numx());
 //    valarray<complex<double> > vr(Algorithms::MakeAxis(
 //            static_cast<complex<double> > (pmax()/(2.0*((*df)[0].nump())-1.0)),static_cast<complex<double> >(pmax()),(*df)[0].nump()
 //    ));
     valarray<complex<double> > vr(Algorithms::MakeCAxis(
             static_cast<complex<double> > (0.0),static_cast<complex<double> >(pmax()),(*df)[0].nump()
     ));
     for (size_t i(0); i<(*df)[0].numx();++i){
         out[i] = (4.0/3.0/ma*M_PI*Algorithms::moment((*df)[0].xVec(i),vr,4.0)).real();
     }
     return out;
 }
HYDRO() [1/2]
Hydro1D& State1D::HYDRO () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 613 of file state.h.
Referenced by collisions::advancef0(), collisions::advancef1(), collisions::advanceflm(), Setup_Y::initialize(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Output_Data::Output_Preprocessor_1D::ni(), Hydro_Functor::operator()(), State1D::operator*=(), State1D::operator+=(), State1D::operator-=(), State1D::operator=(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_mirror_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), State1D::State1D(), Output_Data::Output_Preprocessor_1D::Ti(), Output_Data::Output_Preprocessor_1D::Ux(), Output_Data::Output_Preprocessor_1D::Uy(), Output_Data::Output_Preprocessor_1D::Uz(), Fluid_Equation_1D::velocity(), and Output_Data::Output_Preprocessor_1D::Z().
 {return (*hydro);}
HYDRO() [2/2]
Hydro1D& State1D::HYDRO () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 614 of file state.h.
References SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
 {return (*hydro);}
Hydro1D() [1/2]
Hydro1D::Hydro1D (size_t numx, double _mass, double _charge)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1337 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
                                                         : hydromass(_mass), hydrocharge(_charge) {
     hn  = new  valarray<double >(nx);
     hvx = new  valarray<double >(nx);
     hvy = new  valarray<double >(nx);
     hvz = new  valarray<double >(nx);
     ht  = new  valarray<double >(nx);
     hz  = new  valarray<double >(nx);
 }
Hydro1D() [2/2]
Hydro1D::Hydro1D (const Hydro1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1346 of file state.cpp.
References Hydro1D::densityarray(), Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, Hydro1D::hz, Hydro1D::numx(), Hydro1D::temperaturearray(), Hydro1D::vxarray(), Hydro1D::vyarray(), Hydro1D::vzarray(), and Hydro1D::Zarray().
{
     hn = new valarray<double >(other.numx());
     *hn = other.densityarray();
     hvx = new valarray<double >(other.numx());
     *hvx = other.vxarray();
     hvy = new valarray<double >(other.numx());
     *hvy = other.vyarray();
     hvz = new valarray<double >(other.numx());
     *hvz = other.vzarray();
     ht = new valarray<double >(other.numx());
     *ht = other.temperaturearray();
     hz = new valarray<double >(other.numx());
     *hz = other.Zarray();
 }
indx() [1/2]
Array2D<int> DistFunc1D::indx () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 402 of file state.h.
References SHarmonic1D::checknan(), SHarmonic1D::Filterp(), SHarmonic1D::operator()(), SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
Referenced by DistFunc1D::checknan().
 {return ind;}
indx() [2/2]
Array2D<int> DistFunc2D::indx () const inline private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 458 of file state.h.
 {return ind;}
l0() [1/2]
size_t DistFunc1D::l0 () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 396 of file state.h.
Referenced by Spatial_Advection_1D::es1d(), Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Output_Data::Output_Preprocessor_1D::fl0(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Spatial_Advection_1D::operator()(), VlasovFunctor1D_explicitE::operator()(), Electric_Field_1D::operator()(), Electric_Field_1D_f1::operator()(), VlasovFunctor1D_spatialpush::operator()(), Hydro_Advection_1D::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_implicitE_implicitB_p1::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), and Node_Communications::sameNode_mirror_X().
 {return lmax;  }
l0() [2/2]
size_t DistFunc2D::l0 () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 471 of file state.h.
Referenced by DistFunc2D::DistFunc2D(), and State2D::State2D().
 {return lmax;  }
ldim()
size_t DistFunc2D::ldim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 469 of file state.h.
Referenced by DistFunc2D::operator*=(), and DistFunc2D::operator=().
 {return lmax+1;}
m0() [1/2]
size_t DistFunc1D::m0 () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 397 of file state.h.
Referenced by Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ez(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), Spatial_Advection_1D::operator()(), Electric_Field_1D::operator()(), Electric_Field_1D_f1::operator()(), VlasovFunctor1D_spatialpush::operator()(), Hydro_Advection_1D::operator()(), VlasovFunctor1D_momentumpush::operator()(), and Node_Communications::sameNode_mirror_X().
 {return mmax;  }
m0() [2/2]
size_t DistFunc2D::m0 () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 472 of file state.h.
Referenced by DistFunc2D::DistFunc2D(), and State2D::State2D().
 {return mmax;  }
mass() [1/3]
double DistFunc1D::mass () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 400 of file state.h.
Referenced by Spatial_Advection_1D::es1d(), Spatial_Advection_1D::f1only(), Setup_Y::initialize(), interspecies_f00_explicit_step::interspecies_f00_explicit_step(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Spatial_Advection_1D::operator()(), Spatial_Advection_1D_f1::operator()(), Hydro_Advection_1D::operator()(), and Output_Data::Output_Preprocessor_1D::T().
 {return ma;    }
mass() [2/3]
double DistFunc2D::mass () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 474 of file state.h.
References SHarmonic1D::operator()().
Referenced by State2D::State2D().
 {return ma;}
mass() [3/3]
double Hydro1D::mass () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 523 of file state.h.
Referenced by State1D::State1D(), and Fluid_Equation_1D::velocity().
 {return hydromass;}
mdim()
size_t DistFunc2D::mdim () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 470 of file state.h.
Referenced by DistFunc2D::operator*=(), and DistFunc2D::operator=().
 {return mmax+1;}
mpaxis() [1/2]
SHarmonic1D & SHarmonic1D::mpaxis (const valarray< complex< double > > & shmulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 122 of file state.cpp.
Referenced by Spatial_Advection_1D::es1d(), Spatial_Advection_1D::f1only(), Electric_Field_1D_f1::MakeGH(), Electric_Field_1D::MakeGH(), Hydro_Advection_1D::MakeGH(), Spatial_Advection_1D::operator()(), Spatial_Advection_1D_f1::operator()(), SHarmonic2D::operator()(), and SHarmonic1D::xVec().
{
     (*sh).multid1(shmulti);
     return *this;
 }
mpaxis() [2/2]
SHarmonic2D & SHarmonic2D::mpaxis (const valarray< complex< double > > & shmulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 303 of file state.cpp.
{
     (*sh).multid1(shmulti);
     return *this;
 }
mxaxis() [1/2]
SHarmonic1D & SHarmonic1D::mxaxis (const valarray< complex< double > > & shmulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 126 of file state.cpp.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Magnetic_Field_1D::f1only(), Electric_Field_1D_f1::Implicit_Ex(), Electric_Field_1D::Implicit_Ex(), Electric_Field_1D::Implicit_Ex_f1only(), Electric_Field_1D_f1::Implicit_Ey(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D_f1::Implicit_Ez(), Electric_Field_1D::Implicit_Ez(), Electric_Field_1D::Implicit_Ez_f1only(), Electric_Field_1D::operator()(), Electric_Field_1D_f1::operator()(), Magnetic_Field_1D_f1::operator()(), Magnetic_Field_1D::operator()(), SHarmonic2D::operator()(), and SHarmonic1D::xVec().
{
     (*sh).multid2(shmulti);
     return *this;
 }
mxaxis() [2/2]
SHarmonic2D & SHarmonic2D::mxaxis (const valarray< complex< double > > & shmulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 307 of file state.cpp.
{
     (*sh).multid2(shmulti);
     return *this;
 }
mxy_matrix()
SHarmonic2D & SHarmonic2D::mxy_matrix (Array2D< complex< double > > & shmultiM)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 352 of file state.cpp.
References SHarmonic1D::nump(), and SHarmonic1D::sh.
{
     int st(0), nxt(nump());
     for (int im(0); im < shmultiM.dim(); ++im) {
         for (int ip(st); ip < nxt; ++ip)
             (*sh)(ip) *= shmultiM(im);
         st += nump(); nxt += nump();
     }
     return *this;
 }
myaxis()
SHarmonic2D & SHarmonic2D::myaxis (const valarray< complex< double > > & shmulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 311 of file state.cpp.
{
     (*sh).multid3(shmulti);
     return *this;
 }
nump() [1/2]
size_t SHarmonic1D::nump () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 71 of file state.h.
Referenced by SHarmonic1D::checknan(), SHarmonic1D::Dp(), Setup_Y::init_f0(), Setup_Y::init_f1(), Setup_Y::init_f2(), self_f00_implicit_collisions::loop(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), SHarmonic2D::mxy_matrix(), VlasovFunctor1D_explicitE::operator()(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_mirror_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), SHarmonic1D::SHarmonic1D(), and SHarmonic2D::SHarmonic2D().
 {return (*sh).dim1();} //< Number of momentum cells
nump() [2/2]
size_t SHarmonic2D::nump () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 136 of file state.h.
Referenced by SHarmonic2D::SHarmonic2D().
 {return (*sh).dim1();}
numx() [1/5]
size_t SHarmonic1D::numx () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 72 of file state.h.
Referenced by Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), SHarmonic1D::checknan(), SHarmonic1D::Dp(), Field1D::Dx(), EMF1D::EMF1D(), EMF2D::EMF2D(), Field1D::Field1D(), Field2D::Field2D(), Setup_Y::init_f0(), Setup_Y::init_f1(), Setup_Y::init_f2(), self_f00_implicit_collisions::loop(), InverseBremsstrahlung::loop(), Electric_Field_1D_f1::MakeG00(), Electric_Field_1D::MakeG00(), Hydro_Advection_1D::MakeG00(), Electric_Field_1D_f1::MakeGH(), Electric_Field_1D::MakeGH(), Hydro_Advection_1D::MakeGH(), Node_ImplicitE_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xleft(), Node_ImplicitE_Communications::mirror_bound_Xright(), Node_Communications::mirror_bound_Xright(), VlasovFunctor1D_explicitE::operator()(), Field1D::Re(), Node_ImplicitE_Communications::sameNode_mirror_X(), Node_Communications::sameNode_mirror_X(), SHarmonic1D::SHarmonic1D(), and SHarmonic2D::SHarmonic2D().
 {return (*sh).dim2();} //< Number of spatial cells
numx() [2/5]
size_t SHarmonic2D::numx () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 137 of file state.h.
Referenced by SHarmonic2D::SHarmonic2D().
 {return (*sh).dim2();}
numx() [3/5]
size_t Field1D::numx () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 197 of file state.h.
Referenced by Electric_Field_Methods::Current_xyz::calculate_J(), Current_1D::es1d(), Field1D::Field1D(), Node_Communications::mirror_bound_Xright(), Current_1D::operator()(), Export_Files::Restart_Facility::Read(), Node_ImplicitE_Communications::Recv_from_right_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_mirror_X(), Node_ImplicitE_Communications::sameNode_periodic_X(), Node_Communications::sameNode_periodic_X(), Node_ImplicitE_Communications::Send_right_X(), Node_Communications::Send_right_X(), State1D::State1D(), and Export_Files::Restart_Facility::Write().
 {return (*fi).size();}
numx() [4/5]
size_t Field2D::numx () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 246 of file state.h.
Referenced by Field2D::Field2D(), and State2D::State2D().
 {return (*fi).dim1();}
numx() [5/5]
size_t Hydro1D::numx () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 522 of file state.h.
Referenced by Hydro1D::Hydro1D().
 {return (*hn).size();}
numy() [1/2]
size_t SHarmonic2D::numy () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 138 of file state.h.
Referenced by SHarmonic2D::SHarmonic2D().
 {return (*sh).dim3();}
numy() [2/2]
size_t Field2D::numy () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 247 of file state.h.
Referenced by Field2D::Field2D(), and State2D::State2D().
 {return (*fi).dim2();}
operator()() [1/22]
complex<double>& SHarmonic1D::operator() (size_t i, size_t j) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 75 of file state.h.
Referenced by DistFunc1D::indx(), and DistFunc2D::mass().
 {return (*sh)(i,j);}
operator()() [2/22]
complex<double> SHarmonic1D::operator() (size_t i, size_t j) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 76 of file state.h.
 {return (*sh)(i,j);}
operator()() [3/22]
complex<double>& SHarmonic1D::operator() (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 77 of file state.h.
 {return (*sh)(i);}             //1D-style
operator()() [4/22]
complex<double> SHarmonic1D::operator() (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 78 of file state.h.
 {return (*sh)(i);}       //1D-style
operator()() [5/22]
complex<double>& SHarmonic2D::operator() (size_t i, size_t j, size_t k) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 141 of file state.h.
 {return (*sh)(i,j,k);}
operator()() [6/22]
complex<double>& SHarmonic2D::operator() (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 142 of file state.h.
References SHarmonic1D::Dx(), SHarmonic1D::Filterp(), SHarmonic1D::mpaxis(), SHarmonic1D::mxaxis(), SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
 {return (*sh)(i);}             //1D-style
operator()() [7/22]
complex<double>& Field1D::operator() (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 198 of file state.h.
 { return (*fi)[i];}             //1D-style
operator()() [8/22]
complex<double> Field1D::operator() (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 199 of file state.h.
References SHarmonic1D::Dx(), SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), SHarmonic1D::operator=(), and SHarmonic1D::Re().
 {return (*fi)[i];}
operator()() [9/22]
complex<double>& Field2D::operator() (size_t i, size_t j) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 248 of file state.h.
 {return (*fi)(i,j);} //Fortran-style
operator()() [10/22]
complex<double>& Field2D::operator() (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 249 of file state.h.
References SHarmonic1D::Dx(), SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
 {return (*fi)(i);}             //1D-style
operator()() [11/22]
Field1D& EMF1D::operator() (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 287 of file state.h.
 {return (*fie)[i];}
operator()() [12/22]
Field1D EMF1D::operator() (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 288 of file state.h.
 {return (*fie)[i];}
operator()() [13/22]
Field2D& EMF2D::operator() (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 339 of file state.h.
 {return (*fie)[i];}
operator()() [14/22]
Field2D EMF2D::operator() (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 340 of file state.h.
 {return (*fie)[i];}
operator()() [15/22]
SHarmonic1D & DistFunc1D::operator() (int i)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 838 of file state.cpp.
References DistFunc1D::df.
{
 //         if ((l < 0) || (l> lmax)) return NULL;
     return (*df)[size_t(i)];
 }
operator()() [16/22]
SHarmonic1D & DistFunc1D::operator() (int i) const
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 843 of file state.cpp.
References DistFunc1D::df.
{
 //         if ((l < 0) || (l> lmax)) return NULL;
     return (*df)[size_t(i)];
 }
operator()() [17/22]
SHarmonic1D & DistFunc1D::operator() (size_t l, size_t m)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 848 of file state.cpp.
References DistFunc1D::df, and DistFunc1D::ind.
{
 //         if ((l < 0) || (l> lmax)) return NULL;
     return (*df)[ind(l,m)];
 }
operator()() [18/22]
SHarmonic1D & DistFunc1D::operator() (size_t l, size_t m) const
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 853 of file state.cpp.
References DistFunc1D::df, and DistFunc1D::ind.
{
 //         if ((l < 0) || (l> lmax)) return NULL;
     return (*df)[ind(l,m)];
 }
operator()() [19/22]
SHarmonic2D * DistFunc2D::operator() (size_t i)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1196 of file state.cpp.
{
     return &((*df)[size_t(i)]);
 }
operator()() [20/22]
SHarmonic2D * DistFunc2D::operator() (size_t i) const
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1206 of file state.cpp.
{
     // if ((l < 0) || (l> lmax) || (m < 0) || (m > mmax)) return NULL;
     return &((*df)[size_t(i)]);
 }
operator()() [21/22]
SHarmonic2D* DistFunc2D::operator() (size_t l, size_t m) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 479 of file state.h.
 {return &(*df)[ind(l,m)];}
operator()() [22/22]
SHarmonic2D* DistFunc2D::operator() (size_t l, size_t m) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 480 of file state.h.
References SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
 {return &(*df)[ind(l,m)];}                   // Returns the address of a harmonic, NULL if out-of-bounds
operator*=() [1/24]
SHarmonic1D & SHarmonic1D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 92 of file state.cpp.
Referenced by EMF1D::Bz(), EMF2D::Bz(), State2D::FLD(), State1D::HYDRO(), DistFunc1D::indx(), SHarmonic2D::operator()(), Field1D::operator()(), Field2D::operator()(), DistFunc2D::operator()(), SHarmonic1D::xVec(), and Hydro1D::Zarray().
{
     (*sh) *=d;
     return *this;
 }
operator*=() [2/24]
SHarmonic1D & SHarmonic1D::operator*= (const SHarmonic1D & shmulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 96 of file state.cpp.
References SHarmonic1D::array().
{
     (*sh) *= shmulti.array();
     return *this;
 }
operator*=() [3/24]
SHarmonic2D & SHarmonic2D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 273 of file state.cpp.
{
     (*sh) *=d;
     return *this;
 }
operator*=() [4/24]
SHarmonic2D & SHarmonic2D::operator*= (const SHarmonic2D & shmulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 277 of file state.cpp.
References SHarmonic2D::array().
{
     (*sh) *= shmulti.array();
     return *this;
 }
operator*=() [5/24]
Field1D & Field1D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 409 of file state.cpp.
{
     (*fi) *=d;
     return *this;
 }
operator*=() [6/24]
Field1D & Field1D::operator*= (const valarray< complex< double > > & fimulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 413 of file state.cpp.
{
     (*fi) *= fimulti;
     return *this;
 }
operator*=() [7/24]
Field1D & Field1D::operator*= (const Field1D & fimulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 417 of file state.cpp.
References Field1D::array().
{
     (*fi) *= fimulti.array();
     return *this;
 }
operator*=() [8/24]
Field2D & Field2D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 527 of file state.cpp.
{
     (*fi) *=d;
     return *this;
 }
operator*=() [9/24]
Field2D & Field2D::operator*= (const Field2D & fimulti)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 532 of file state.cpp.
References Field2D::array().
{
     (*fi) *= fimulti.array();
     return *this;
 }
operator*=() [10/24]
EMF1D & EMF1D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 620 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] *= d;
     return *this;
 }
operator*=() [11/24]
EMF1D & EMF1D::operator*= (const EMF1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 625 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] *= other(i);
     }
     return *this;
 }
operator*=() [12/24]
EMF2D & EMF2D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 703 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] *= d;
     return *this;
 }
operator*=() [13/24]
EMF2D & EMF2D::operator*= (const EMF2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 708 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] *= other(i);
     }
     return *this;
 }
operator*=() [14/24]
DistFunc1D & DistFunc1D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 889 of file state.cpp.
References DistFunc1D::dim().
{
     for(size_t i(0); i < dim() ; ++i) {
         (*df)[i] *= d;
     }
     return *this;
 }
operator*=() [15/24]
DistFunc1D & DistFunc1D::operator*= (const DistFunc1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 895 of file state.cpp.
References DistFunc1D::dim().
{
     if (this != &other) {   //self-assignment
         for(size_t i(0); i < dim() ; ++i) {
             (*df)[i] *= other(i);
         }
     }
     return *this;
 }
operator*=() [16/24]
DistFunc2D & DistFunc2D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1249 of file state.cpp.
References DistFunc2D::dim().
{
     for(size_t i(0); i < dim() ; ++i) {
         (*df)[i] *= d;
     }
     return *this;
 }
operator*=() [17/24]
DistFunc2D & DistFunc2D::operator*= (const DistFunc2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1255 of file state.cpp.
References DistFunc2D::ldim(), and DistFunc2D::mdim().
{
     if (this != &other) {   //self-assignment
         // for(size_t i(0); i < dim() ; ++i) {
         size_t i(0);
         for(size_t l(0); l < ldim() ; ++l)
         {
             for(size_t m(0); m < mdim() ; ++m)
             {
                 (*df)[i] *= *(other(l,m));
                 ++i;
             }
         }
     }
     return *this;
 }
operator*=() [18/24]
Hydro1D & Hydro1D::operator*= (const double & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1409 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn *= d;
     *hvx *= d;
     *hvy *= d;
     *hvz *= d;
     *ht *= d;
     *hz *= d;
     return *this;
 }
operator*=() [19/24]
Hydro1D & Hydro1D::operator*= (const valarray< double > & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1418 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn *= other;
     *hvx *= other;
     *hvy *= other;
     *hvz *= other;
     *ht *= other;
     *hz *= other;
     return *this;
 }
operator*=() [20/24]
Hydro1D & Hydro1D::operator*= (const Hydro1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1427 of file state.cpp.
References Hydro1D::densityarray(), Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, Hydro1D::hz, Hydro1D::temperaturearray(), Hydro1D::vxarray(), Hydro1D::vyarray(), Hydro1D::vzarray(), and Hydro1D::Zarray().
{
     if (this != &other) {   //self-assignment
         *hn *= other.densityarray();
         *hvx *= other.vxarray();
         *hvy *= other.vyarray();
         *hvz *= other.vzarray();
         *ht *= other.temperaturearray();
         *hz *= other.Zarray();
     }
     return *this;
 }
operator*=() [21/24]
State1D & State1D::operator*= (const State1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1576 of file state.cpp.
References State1D::DF(), State1D::EMF(), State1D::flds, State1D::hydro, State1D::HYDRO(), and State1D::ns.
{
     for(size_t s(0); s < ns; ++s){
         (*sp)[s] *= other.DF(s);
     }
     *flds *= other.EMF();
     *hydro *= other.HYDRO();
     return *this;
 }
operator*=() [22/24]
State1D & State1D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1585 of file state.cpp.
References State1D::hydro, and State1D::ns.
{
     for(size_t s(0); s < ns; ++s){
         (*sp)[s] *= d;
     }
     (*flds) *= d;
     *hydro *= d.real();
     return *this;
 }
operator*=() [23/24]
State2D & State2D::operator*= (const State2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1705 of file state.cpp.
References State2D::DF(), State2D::EMF(), State2D::flds, State2D::ns, and State2D::sp.
{
     for(size_t s(0); s < ns; ++s) (*sp)[s] *= other.DF(s);
     *flds *= other.EMF();
     return *this;
 }
operator*=() [24/24]
State2D & State2D::operator*= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1711 of file state.cpp.
References State2D::flds, State2D::ns, and State2D::sp.
{
     for(size_t s(0); s < ns; ++s) (*sp)[s] *= d;
     *flds *= d;
     return *this;
 }
operator+=() [1/23]
SHarmonic1D & SHarmonic1D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 101 of file state.cpp.
Referenced by EMF1D::Bz(), EMF2D::Bz(), State2D::FLD(), State1D::HYDRO(), DistFunc1D::indx(), SHarmonic2D::operator()(), Field1D::operator()(), Field2D::operator()(), DistFunc2D::operator()(), SHarmonic1D::xVec(), and Hydro1D::Zarray().
{
     (*sh) +=d;
     return *this;
 }
operator+=() [2/23]
SHarmonic1D & SHarmonic1D::operator+= (const SHarmonic1D & shadd)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 105 of file state.cpp.
References SHarmonic1D::array().
{
     (*sh) += shadd.array();
     return *this;
 }
operator+=() [3/23]
SHarmonic2D & SHarmonic2D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 282 of file state.cpp.
{
     (*sh) +=d;
     return *this;
 }
operator+=() [4/23]
SHarmonic2D & SHarmonic2D::operator+= (const SHarmonic2D & shadd)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 286 of file state.cpp.
References SHarmonic2D::array().
{
     (*sh) += shadd.array();
     return *this;
 }
operator+=() [5/23]
Field1D & Field1D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 422 of file state.cpp.
{
     (*fi) +=d;
     return *this;
 }
operator+=() [6/23]
Field1D & Field1D::operator+= (const Field1D & fiadd)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 426 of file state.cpp.
References Field1D::array().
{
     (*fi) += fiadd.array();
     return *this;
 }
operator+=() [7/23]
Field2D & Field2D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 537 of file state.cpp.
{
     (*fi) +=d;
     return *this;
 }
operator+=() [8/23]
Field2D & Field2D::operator+= (const Field2D & fiadd)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 541 of file state.cpp.
References Field2D::array().
{
     (*fi) += fiadd.array();
     return *this;
 }
operator+=() [9/23]
EMF1D & EMF1D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 633 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] += d;
     return *this;
 }
operator+=() [10/23]
EMF1D & EMF1D::operator+= (const EMF1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 638 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] += other(i);
     }
     return *this;
 }
operator+=() [11/23]
EMF2D & EMF2D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 716 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] += d;
     return *this;
 }
operator+=() [12/23]
EMF2D & EMF2D::operator+= (const EMF2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 721 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] += other(i);
     }
     return *this;
 }
operator+=() [13/23]
DistFunc1D & DistFunc1D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 904 of file state.cpp.
References DistFunc1D::dim().
{
     for(size_t i(0); i < dim() ; ++i) {
         (*df)[i] += d;
     }
     return *this;
 }
operator+=() [14/23]
DistFunc1D & DistFunc1D::operator+= (const DistFunc1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 910 of file state.cpp.
References DistFunc1D::dim().
{
     if (this != &other) {   //self-assignment
         for(size_t i(0); i < dim() ; ++i) {
             (*df)[i] += other(i);
         }
     }
     return *this;
 }
operator+=() [15/23]
DistFunc2D & DistFunc2D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1271 of file state.cpp.
References DistFunc2D::dim().
{
     for(size_t i(0); i < dim() ; ++i) {
         (*df)[i] += d;
     }
     return *this;
 }
operator+=() [16/23]
DistFunc2D & DistFunc2D::operator+= (const DistFunc2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1277 of file state.cpp.
References DistFunc2D::dim().
{
 // MORE L AND M STUFF TO CHECK AGAINST ORIGINAL
 //        if (this != &other) //self-assignment
 //        {
 //            size_t i(0);
 //            // for(size_t i(0); i < dim() ; ++i) {
 //            for(size_t l(0); l < ldim() ; ++l)
 //            {
 //                for(size_t m(0); m < mdim() ; ++m)
 //                {
 //                    (*df)[i] *= *(other(l,m));
 //                    ++i;
 //                }
     if (this != &other) {   //self-assignment
         for(size_t i(0); i < dim() ; ++i) {
             (*df)[i] += *(other(i));
         }
     }
     return *this;
 }
operator+=() [17/23]
Hydro1D & Hydro1D::operator+= (const double & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1441 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn += d;
     *hvx += d;
     *hvy += d;
     *hvz += d;
     *ht += d;
     *hz += d;
     return *this;
 }
operator+=() [18/23]
Hydro1D & Hydro1D::operator+= (const valarray< double > & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1451 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn += other;
     *hvx += other;
     *hvy += other;
     *hvz += other;
     *ht += other;
     *hz += other;
     return *this;
 }
operator+=() [19/23]
Hydro1D & Hydro1D::operator+= (const Hydro1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1460 of file state.cpp.
References Hydro1D::densityarray(), Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, Hydro1D::hz, Hydro1D::temperaturearray(), Hydro1D::vxarray(), Hydro1D::vyarray(), Hydro1D::vzarray(), and Hydro1D::Zarray().
{
     if (this != &other) {   //self-assignment
         *hn += other.densityarray();
         *hvx += other.vxarray();
         *hvy += other.vyarray();
         *hvz += other.vzarray();
         *ht += other.temperaturearray();
         *hz += other.Zarray();
     }
     return *this;
 }
operator+=() [20/23]
State1D & State1D::operator+= (const State1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1594 of file state.cpp.
References State1D::DF(), State1D::EMF(), State1D::flds, State1D::hydro, State1D::HYDRO(), and State1D::ns.
{
     for(size_t s(0); s < ns; ++s){
         (*sp)[s] += other.DF(s);
     }
     *flds += other.EMF();
     *hydro += other.HYDRO();
     return *this;
 }
operator+=() [21/23]
State1D & State1D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1603 of file state.cpp.
References State1D::hydro, and State1D::ns.
{
     for(size_t s(0); s < ns; ++s){
         (*sp)[s] += d;
     }
     (*flds) += d;
     *hydro  += d.real();
     return *this;
 }
operator+=() [22/23]
State2D & State2D::operator+= (const State2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1717 of file state.cpp.
References State2D::DF(), State2D::EMF(), State2D::flds, State2D::ns, and State2D::sp.
{
     for(size_t s(0); s < ns; ++s) (*sp)[s] += other.DF(s);
     *flds += other.EMF();
     return *this;
 }
operator+=() [23/23]
State2D & State2D::operator+= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1723 of file state.cpp.
References State2D::flds, State2D::ns, and State2D::sp.
{
     for(size_t s(0); s < ns; ++s) (*sp)[s] += d;
     *flds += d;
     return *this;
 }
operator-=() [1/23]
SHarmonic1D & SHarmonic1D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 110 of file state.cpp.
Referenced by EMF1D::Bz(), EMF2D::Bz(), State2D::FLD(), State1D::HYDRO(), DistFunc1D::indx(), SHarmonic2D::operator()(), Field1D::operator()(), Field2D::operator()(), DistFunc2D::operator()(), SHarmonic1D::xVec(), and Hydro1D::Zarray().
{
     (*sh) -=d;
     return *this;
 }
operator-=() [2/23]
SHarmonic1D & SHarmonic1D::operator-= (const SHarmonic1D & shmin)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 114 of file state.cpp.
References SHarmonic1D::array().
{
     (*sh) -= shmin.array();
     return *this;
 }
operator-=() [3/23]
SHarmonic2D & SHarmonic2D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 291 of file state.cpp.
{
     (*sh) -=d;
     return *this;
 }
operator-=() [4/23]
SHarmonic2D & SHarmonic2D::operator-= (const SHarmonic2D & shmin)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 295 of file state.cpp.
References SHarmonic2D::array().
{
     (*sh) -= shmin.array();
     return *this;
 }
operator-=() [5/23]
Field1D & Field1D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 431 of file state.cpp.
{
     (*fi) -=d;
     return *this;
 }
operator-=() [6/23]
Field1D & Field1D::operator-= (const Field1D & fimin)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 435 of file state.cpp.
References Field1D::array().
{
     (*fi) -= fimin.array();
     return *this;
 }
operator-=() [7/23]
Field2D & Field2D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 546 of file state.cpp.
{
     (*fi) -=d;
     return *this;
 }
operator-=() [8/23]
Field2D & Field2D::operator-= (const Field2D & fimin)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 550 of file state.cpp.
References Field2D::array().
{
     (*fi) -= fimin.array();
     return *this;
 }
operator-=() [9/23]
EMF1D & EMF1D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 646 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] -= d;
     return *this;
 }
operator-=() [10/23]
EMF1D & EMF1D::operator-= (const EMF1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 651 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] -= other(i);
     }
     return *this;
 }
operator-=() [11/23]
EMF2D & EMF2D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 729 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] -= d;
     return *this;
 }
operator-=() [12/23]
EMF2D & EMF2D::operator-= (const EMF2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 734 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] -= other(i);
     }
     return *this;
 }
operator-=() [13/23]
DistFunc1D & DistFunc1D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 919 of file state.cpp.
References DistFunc1D::dim().
{
     for(size_t i(0); i < dim() ; ++i) {
         (*df)[i] -= d;
     }
     return *this;
 }
operator-=() [14/23]
DistFunc1D & DistFunc1D::operator-= (const DistFunc1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 925 of file state.cpp.
References DistFunc1D::dim().
{
     if (this != &other) {   //self-assignment
         for(size_t i(0); i < dim() ; ++i) {
             (*df)[i] -= other(i);
         }
     }
     return *this;
 }
operator-=() [15/23]
DistFunc2D & DistFunc2D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1298 of file state.cpp.
References DistFunc2D::dim().
{
     for(size_t i(0); i < dim() ; ++i) {
         (*df)[i] -= d;
     }
     return *this;
 }
operator-=() [16/23]
DistFunc2D & DistFunc2D::operator-= (const DistFunc2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1304 of file state.cpp.
References DistFunc2D::dim().
{
     if (this != &other) {   //self-assignment
 // MORE L AND M STUFF TO CHECK AGAINST ORIGINAL
 //            // for(size_t i(0); i < dim() ; ++i) {
 //            size_t i(0);
 //               for(size_t l(0); l < ldim() ; ++l)
 //            {
 //                for(size_t m(0); m < mdim() ; ++m)
 //                {
 //                    (*df)[i] *= *(other(l,m));
 //                    ++i;
 //                }
         for(size_t i(0); i < dim() ; ++i) {
             (*df)[i] -= *(other(i));
         }
     }
     return *this;
 }
operator-=() [17/23]
Hydro1D & Hydro1D::operator-= (const double & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1474 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn -= d;
     *hvx -= d;
     *hvy -= d;
     *hvz -= d;
     *ht -= d;
     *hz -= d;
     return *this;
 }
operator-=() [18/23]
Hydro1D & Hydro1D::operator-= (const valarray< double > & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1483 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn -= other;
     *hvx -= other;
     *hvy -= other;
     *hvz -= other;
     *ht -= other;
     *hz -= other;
     return *this;
 }
operator-=() [19/23]
Hydro1D & Hydro1D::operator-= (const Hydro1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1493 of file state.cpp.
References Hydro1D::densityarray(), Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, Hydro1D::hz, Hydro1D::temperaturearray(), Hydro1D::vxarray(), Hydro1D::vyarray(), Hydro1D::vzarray(), and Hydro1D::Zarray().
{
     if (this != &other) {   //self-assignment
         *hn -= other.densityarray();
         *hvx -= other.vxarray();
         *hvy -= other.vyarray();
         *hvz -= other.vzarray();
         *ht -= other.temperaturearray();
         *hz -= other.Zarray();
     }
     return *this;
 }
operator-=() [20/23]
State1D & State1D::operator-= (const State1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1612 of file state.cpp.
References State1D::DF(), State1D::EMF(), State1D::flds, State1D::hydro, State1D::HYDRO(), and State1D::ns.
{
     for(size_t s(0); s < ns; ++s){
         (*sp)[s] -= other.DF(s);
     }
     *flds -= other.EMF();
     *hydro -= other.HYDRO();
     return *this;
 }
operator-=() [21/23]
State1D & State1D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1621 of file state.cpp.
References State1D::hydro, and State1D::ns.
{
     for(size_t s(0); s < ns; ++s){
         (*sp)[s] -= d;
     }
     (*flds) -= d;
     *hydro  -= d.real();
     return *this;
 }
operator-=() [22/23]
State2D & State2D::operator-= (const State2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1729 of file state.cpp.
References State2D::DF(), State2D::EMF(), State2D::flds, State2D::ns, and State2D::sp.
{
     for(size_t s(0); s < ns; ++s) (*sp)[s] -= other.DF(s);
     *flds -= other.EMF();
     return *this;
 }
operator-=() [23/23]
State2D & State2D::operator-= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1735 of file state.cpp.
References State2D::flds, State2D::ns, and State2D::sp.
{
     for(size_t s(0); s < ns; ++s) (*sp)[s] -= d;
     *flds -= d;
     return *this;
 }
operator=() [1/28]
SHarmonic1D & SHarmonic1D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 81 of file state.cpp.
References SHarmonic1D::sh.
Referenced by EMF1D::Bz(), EMF2D::Bz(), State2D::FLD(), State1D::HYDRO(), DistFunc1D::indx(), SHarmonic2D::operator()(), Field1D::operator()(), Field2D::operator()(), DistFunc2D::operator()(), SHarmonic1D::xVec(), and Hydro1D::Zarray().
{
     *sh = d;
     return *this;
 }
operator=() [2/28]
SHarmonic1D & SHarmonic1D::operator= (const SHarmonic1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 85 of file state.cpp.
References SHarmonic1D::array(), and SHarmonic1D::sh.
{
     if (this != &other) {   //self-assignment
         *sh = other.array();
     }
     return *this;
 }
operator=() [3/28]
SHarmonic2D & SHarmonic2D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 262 of file state.cpp.
References SHarmonic1D::sh.
{
     *sh = d;
     return *this;
 }
operator=() [4/28]
SHarmonic2D & SHarmonic2D::operator= (const SHarmonic2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 266 of file state.cpp.
References SHarmonic2D::array(), and SHarmonic1D::sh.
{
     if (this != &other) {   //self-assignment
         *sh = other.array();
     }
     return *this;
 }
operator=() [5/28]
Field1D & Field1D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 394 of file state.cpp.
{
     *fi = d;
     return *this;
 }
operator=() [6/28]
Field1D & Field1D::operator= (const valarray< complex< double > > & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 398 of file state.cpp.
{
     *fi = other;
     return *this;
 }
operator=() [7/28]
Field1D & Field1D::operator= (const Field1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 402 of file state.cpp.
References Field1D::array().
{
     if (this != &other) {   //self-assignment
         *fi = other.array();
     }
     return *this;
 }
operator=() [8/28]
Field2D & Field2D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 516 of file state.cpp.
{
     *fi = d;
     return *this;
 }
operator=() [9/28]
Field2D & Field2D::operator= (const Field2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 520 of file state.cpp.
References Field2D::array().
{
     if (this != &other) {   //self-assignment
         *fi = other.array();
     }
     return *this;
 }
operator=() [10/28]
EMF1D & EMF1D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 599 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] = d;
     return *this;
 }
operator=() [11/28]
EMF1D & EMF1D::operator= (const Field1D & h)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 604 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i){
         if (&((*fie)[i]) != &h) {   //self-assignment
             (*fie)[i] = h;
         }
     }
     return *this;
 }
operator=() [12/28]
EMF1D & EMF1D::operator= (const EMF1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 612 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] = other(i);
     }
     return *this;
 }
operator=() [13/28]
EMF2D & EMF2D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 682 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i)
         (*fie)[i] = d;
     return *this;
 }
operator=() [14/28]
EMF2D & EMF2D::operator= (const Field2D & h)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 687 of file state.cpp.
References SHarmonic1D::dim().
{
     for(int i=0; i < dim() ; ++i){
         if (&((*fie)[i]) != &h) {   //self-assignment
             (*fie)[i] = h;
         }
     }
     return *this;
 }
operator=() [15/28]
EMF2D & EMF2D::operator= (const EMF2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 695 of file state.cpp.
References SHarmonic1D::dim().
{
     if (this != &other) {   //self-assignment
         for(int i=0; i < dim() ; ++i)
             (*fie)[i] = other(i);
     }
     return *this;
 }
operator=() [16/28]
DistFunc1D & DistFunc1D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 866 of file state.cpp.
References DistFunc1D::dim().
{
     for(size_t i(0); i < dim() ; ++i){
         (*df)[i] = d;
     }
     return *this;
 }
operator=() [17/28]
DistFunc1D & DistFunc1D::operator= (const SHarmonic1D & h)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 872 of file state.cpp.
References DistFunc1D::df, and DistFunc1D::dim().
{
     for(size_t i(0); i < dim() ; ++i){
         if (&((*df)[i]) != &h) {   //self-assignment
             (*df)[i] = h;
         }
     }
     return *this;
 }
operator=() [18/28]
DistFunc1D & DistFunc1D::operator= (const DistFunc1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 880 of file state.cpp.
References DistFunc1D::dim().
{
     if (this != &other) {   //self-assignment
         for(size_t i(0); i < dim() ; ++i) {
             (*df)[i] = other(i);
         }
     }
     return *this;
 }
operator=() [19/28]
DistFunc2D & DistFunc2D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1219 of file state.cpp.
References DistFunc2D::dim().
{
     for(size_t i(0); i < dim() ; ++i){
         (*df)[i] = d;
     }
     return *this;
 }
operator=() [20/28]
DistFunc2D & DistFunc2D::operator= (const SHarmonic2D & h)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1225 of file state.cpp.
References DistFunc2D::df, and DistFunc2D::dim().
{
     for(size_t i(0); i < dim() ; ++i){
         if (&((*df)[i]) != &h) {   //self-assignment
             (*df)[i] = h;
         }
     }
     return *this;
 }
operator=() [21/28]
DistFunc2D & DistFunc2D::operator= (const DistFunc2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1233 of file state.cpp.
References DistFunc2D::ldim(), and DistFunc2D::mdim().
{
     if (this != &other) {   //self-assignment
         // for(size_t i(0); i < dim() ; ++i) {
         size_t i(0);
         for(size_t l(0); l < ldim() ; ++l)
         {
             for(size_t m(0); m < mdim() ; ++m)
             {
                 (*df)[i] = *(other(l,m));
                 ++i;
             }
         }
     }
     return *this;
 }
operator=() [22/28]
Hydro1D & Hydro1D::operator= (const double & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1377 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn = d;
     *hvx = d;
     *hvy = d;
     *hvz = d;
     *ht = d;
     *hz = d;
     return *this;
 }
operator=() [23/28]
Hydro1D & Hydro1D::operator= (const valarray< double > & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1386 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
{
     *hn  = other;
     *hvx = other;
     *hvy = other;
     *hvz = other;
     *ht  = other;
     *hz  = other;
     return *this;
 }
operator=() [24/28]
Hydro1D & Hydro1D::operator= (const Hydro1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1395 of file state.cpp.
References Hydro1D::densityarray(), Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, Hydro1D::hz, Hydro1D::temperaturearray(), Hydro1D::vxarray(), Hydro1D::vyarray(), Hydro1D::vzarray(), and Hydro1D::Zarray().
{
     if (this != &other) {   //self-assignment
         *hn = other.densityarray();
         *hvx = other.vxarray();
         *hvy = other.vyarray();
         *hvz = other.vzarray();
         *ht = other.temperaturearray();
         *hz = other.Zarray();
     }
     return *this;
 }
operator=() [25/28]
State1D & State1D::operator= (const State1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1554 of file state.cpp.
References State1D::DF(), State1D::EMF(), State1D::flds, State1D::hydro, State1D::HYDRO(), State1D::ns, and State1D::Species().
{
     if (this != &other) {   //self-assignment
         ns = other.Species();
         for(size_t s(0); s < ns; ++s){
             (*sp)[s] = other.DF(s);
         }
         *flds = other.EMF();
         *hydro = other.HYDRO();
     }
     return *this;
 }
operator=() [26/28]
State1D & State1D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1567 of file state.cpp.
References State1D::flds, State1D::hydro, and State1D::ns.
{
     for(size_t s(0); s < ns; ++s){
         (*sp)[s] = d;
     }
     *flds = d;
     *hydro = d.real();
     return *this;
 }
operator=() [27/28]
State2D & State2D::operator= (const State2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1689 of file state.cpp.
References State2D::DF(), State2D::EMF(), State2D::flds, and State2D::ns.
{
     if (this != &other) {   //self-assignment
         for(size_t s(0); s < ns; ++s){
             (*sp).push_back(other.DF(s));
         }
         *flds = other.EMF();
     }
     return *this;
 }
operator=() [28/28]
State2D & State2D::operator= (const complex< double > & d)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1699 of file state.cpp.
References State2D::flds, State2D::ns, and State2D::sp.
{
     for(size_t s(0); s < ns; ++s) (*sp)[s] = d;
     *flds = d;
     return *this;
 }
pmax()
double DistFunc1D::pmax () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 398 of file state.h.
Referenced by DistFunc1D::getcurrent(), DistFunc1D::getdensity(), and DistFunc1D::getpressure().
 {return pmx;   }
q() [1/2]
double DistFunc1D::q () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 399 of file state.h.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Magnetic_Field_1D::f1only(), Magnetic_Field_1D_f1::implicit(), Magnetic_Field_1D::implicit(), Electric_Field_1D_f1::Implicit_Ex(), Electric_Field_1D::Implicit_Ex(), Electric_Field_1D::Implicit_Ex_f1only(), Electric_Field_1D_f1::Implicit_Ey(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D::Implicit_Ez(), interspecies_f00_explicit_step::interspecies_f00_explicit_step(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Electric_Field_1D::operator()(), Electric_Field_1D_f1::operator()(), Magnetic_Field_1D_f1::operator()(), and Magnetic_Field_1D::operator()().
 {return charge;}
q() [2/2]
double DistFunc2D::q () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 473 of file state.h.
Referenced by State2D::State2D().
 {return charge;}
Re() [1/2]
SHarmonic1D & SHarmonic1D::Re ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 130 of file state.cpp.
References SHarmonic1D::dim(), and SHarmonic1D::sh.
Referenced by Electric_Field_1D::f1only(), Magnetic_Field_1D::f1only(), Electric_Field_1D_f1::Implicit_Ey(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D_f1::Implicit_Ez(), Electric_Field_1D::Implicit_Ez(), Electric_Field_1D::Implicit_Ez_f1only(), Electric_Field_1D::operator()(), Electric_Field_1D_f1::operator()(), Magnetic_Field_1D_f1::operator()(), Magnetic_Field_1D::operator()(), Field1D::operator()(), and SHarmonic1D::xVec().
{
     for (int i(0); i < dim(); ++i) {
         (*sh)(i) = (*sh)(i).real();
     }
     return *this;
 }
Re() [2/2]
Field1D & Field1D::Re ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 441 of file state.cpp.
References SHarmonic1D::numx().
                     {
 //--------------------------------------------------------------
     for (int i(0); i < numx(); ++i) {
         (*fi)[i] = (*fi)[i].real();
     }
     return *this;
 }
SH() [1/4]
SHarmonic1D& State1D::SH (size_t s, size_t lh, size_t mh) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 605 of file state.h.
Referenced by interspecies_collisions::advancef00(), Setup_Y::applyexternalfields(), Setup_Y::applytravelingwave(), Setup_Y::initialize(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Node_ImplicitE_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xleft(), Node_ImplicitE_Communications::mirror_bound_Xright(), Node_Communications::mirror_bound_Xright(), Output_Data::Output_Preprocessor_1D::n(), VlasovFunctor1D_explicitE::operator()(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::Qz(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_ImplicitE_Communications::sameNode_mirror_X(), Node_Communications::sameNode_mirror_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), and Output_Data::Output_Preprocessor_1D::vNz().
 {return ((*sp)[s])(lh,mh);} // Reference to spherical harmonic
SH() [2/4]
SHarmonic1D& State1D::SH (size_t s, size_t lh, size_t mh) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 606 of file state.h.
 {return ((*sp)[s])(lh,mh);}
SH() [3/4]
SHarmonic2D& State2D::SH (size_t s, size_t lh, size_t mh) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 659 of file state.h.
 {return *(((*sp)[s])(lh,mh));} // Reference to spherical harmonic
SH() [4/4]
SHarmonic2D& State2D::SH (size_t s, size_t lh, size_t mh) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 660 of file state.h.
 {return *(((*sp)[s])(lh,mh));}
SHarmonic1D() [1/2]
SHarmonic1D::SHarmonic1D (size_t nump, size_t numx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
The constructor requires nump, and numx as inputs.
Definition at line 63 of file state.cpp.
References SHarmonic1D::nump(), SHarmonic1D::numx(), and SHarmonic1D::sh.
{
     sh = new Array2D<complex<double> >(nump,numx);
 }
SHarmonic1D() [2/2]
SHarmonic1D::SHarmonic1D (const SHarmonic1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 67 of file state.cpp.
References SHarmonic1D::array(), SHarmonic1D::nump(), SHarmonic1D::numx(), and SHarmonic1D::sh.
{
     sh = new Array2D<complex<double> >(other.nump(),other.numx());
     *sh = other.array();
 }
SHarmonic2D() [1/2]
SHarmonic2D::SHarmonic2D (size_t nump, size_t numx, size_t numy)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 244 of file state.cpp.
References SHarmonic1D::nump(), SHarmonic1D::numx(), and SHarmonic1D::sh.
{
     sh = new Array3D <complex <double> >(nump,numx,numy);
 }
SHarmonic2D() [2/2]
SHarmonic2D::SHarmonic2D (const SHarmonic2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 248 of file state.cpp.
References SHarmonic2D::array(), SHarmonic2D::nump(), SHarmonic2D::numx(), SHarmonic2D::numy(), and SHarmonic1D::sh.
{
     sh = new Array3D < complex <double> >(other.nump(),other.numx(),other.numy());
     *sh = other.array();
 }
SHp() [1/2]
SHarmonic2D* State2D::SHp (size_t s, size_t lh, size_t mh) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 661 of file state.h.
 {return   ((*sp)[s])(lh,mh); } // Pointer to spherical harmonic
SHp() [2/2]
SHarmonic2D* State2D::SHp (size_t s, size_t lh, size_t mh) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 662 of file state.h.
 {return   ((*sp)[s])(lh,mh); }
Species() [1/2]
size_t State1D::Species () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 596 of file state.h.
Referenced by collisions::advance(), collisions::advancef0(), interspecies_collisions::advancef00(), collisions::advancef1(), collisions::advanceflm(), Electric_Field_Methods::Current_xyz::calculate_J(), collisions::collisions(), Output_Data::Output_Preprocessor_1D::f0(), Output_Data::Output_Preprocessor_1D::f10(), Output_Data::Output_Preprocessor_1D::f11(), Output_Data::Output_Preprocessor_1D::f20(), Output_Data::Output_Preprocessor_1D::fl0(), interspecies_collisions::interspecies_collisions(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Output_Data::Output_Preprocessor_1D::n(), VlasovFunctor1D_explicitE::operator()(), VlasovFunctor1D_spatialpush::operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_f1_explicitE::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_f1_explicitEB::operator()(), VlasovFunctor1D_implicitE_implicitB_p1::operator()(), VlasovFunctor1D_f1_implicitE_p1::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_f1_implicitEB_p1::operator()(), VlasovFunctor1D_f1_implicitE_p2::operator()(), State1D::operator=(), Output_Data::Output_Preprocessor_1D::px(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::Qz(), Export_Files::Restart_Facility::Read(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_mirror_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), Output_Data::Output_Preprocessor_1D::vNz(), and Export_Files::Restart_Facility::Write().
 {return ns;}
Species() [2/2]
size_t State2D::Species () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 651 of file state.h.
 {return ns;}
State1D() [1/2]
State1D::State1D (size_t nx, vector< size_t > l0, vector< size_t > m0, vector< size_t > np, vector< double > pmax, vector< double > q, vector< double > ma, double hydromass, double hydrocharge)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1512 of file state.cpp.
References State1D::flds, State1D::hydro, State1D::ns, and State1D::sp.
         : ns(l0.size()) {
     if (ns != np.size()) {
         cout << "ERROR:Overdetermined number of species\n";
         exit(1);
     }
     sp = new vector<DistFunc1D>;
     for(size_t s(0); s < ns; ++s){
         (*sp).push_back(DistFunc1D(l0[s],m0[s],np[s],pmax[s],nx,q[s],ma[s]));
     }
     flds = new EMF1D(nx);
     hydro = new Hydro1D(nx,_hydromass,_hydrocharge);
 }
State1D() [2/2]
State1D::State1D (const State1D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1531 of file state.cpp.
References Hydro1D::charge(), State1D::DF(), State1D::EMF(), State1D::FLD(), State1D::flds, State1D::hydro, State1D::HYDRO(), Hydro1D::mass(), State1D::ns, Field1D::numx(), and State1D::sp.
         : ns(other.Species()) {
     sp = new vector<DistFunc1D>;
     for(size_t s(0); s < ns; ++s){
         (*sp).push_back(DistFunc1D(other.DF(s)));
     }
     flds = new EMF1D(other.FLD(0).numx());
     *flds = other.EMF();
     hydro = new Hydro1D(other.FLD(0).numx(),other.HYDRO().mass(),other.HYDRO().charge());
     *hydro = other.HYDRO();
 }
State2D() [1/2]
State2D::State2D (size_t nx, size_t ny, vector< size_t > l0, vector< size_t > m0, vector< size_t > np, vector< double > q, vector< double > ma)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1654 of file state.cpp.
References State2D::flds, State2D::ns, and State2D::sp.
         : ns(l0.size()) {
     if (ns != np.size()) {
         cout << "ERROR:Overdetermined number of species\n";
         exit(1);
     }
     sp = new vector<DistFunc2D>;
     for(size_t s(0); s < ns; ++s){
         (*sp).push_back(DistFunc2D(l0[s],m0[s],np[s],nx,ny,q[s],ma[s]));
     }
     flds = new EMF2D(nx,ny);
 }
State2D() [2/2]
State2D::State2D (const State2D & other)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1669 of file state.cpp.
References State2D::DF(), State2D::EMF(), State2D::FLD(), State2D::flds, DistFunc2D::l0(), DistFunc2D::m0(), DistFunc2D::mass(), State2D::ns, Field2D::numx(), Field2D::numy(), DistFunc2D::q(), and State2D::sp.
{
     sp = new vector<DistFunc2D>;
     for(size_t s(0); s < ns; ++s){
         (*sp).push_back(DistFunc2D(other.DF(s).l0(),other.DF(s).m0(),
                                    other.DF(s)(0,0)->nump(),other.FLD(0).numx(),other.FLD(0).numy(),
                                    other.DF(s).q(),other.DF(s).mass()));
     }
     flds = new EMF2D(other.FLD(0).numx(),other.FLD(0).numy());
     *flds = other.EMF();
 }
temperature() [1/2]
double& Hydro1D::temperature (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 539 of file state.h.
Referenced by Setup_Y::initialize(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), Output_Data::Output_Preprocessor_1D::Ti(), and Fluid_Equation_1D::velocity().
 { return (*ht)[i];}             //1D-style
temperature() [2/2]
double Hydro1D::temperature (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 540 of file state.h.
 {return (*ht)[i];}
temperaturearray()
valarray<double >& Hydro1D::temperaturearray () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 549 of file state.h.
Referenced by Hydro1D::Hydro1D(), Setup_Y::initialize(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), and Hydro1D::operator=().
 {return (*ht);}
vx() [1/2]
double& Hydro1D::vx (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 530 of file state.h.
Referenced by Fluid_Equation_1D::density(), Setup_Y::initialize(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Hydro_Advection_1D::operator()(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_mirror_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), Output_Data::Output_Preprocessor_1D::Ux(), and Fluid_Equation_1D::velocity().
 { return (*hvx)[i];}
vx() [2/2]
double Hydro1D::vx (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 531 of file state.h.
 {return (*hvx)[i];}
vxarray()
valarray<double >& Hydro1D::vxarray () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 546 of file state.h.
Referenced by Hydro1D::Hydro1D(), Setup_Y::initialize(), Hydro_Advection_1D::operator()(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Fluid_Equation_1D::velocity().
 {return (*hvx);}
vy() [1/2]
double& Hydro1D::vy (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 533 of file state.h.
Referenced by Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), Output_Data::Output_Preprocessor_1D::Uy(), and Fluid_Equation_1D::velocity().
 { return (*hvy)[i];}
vy() [2/2]
double Hydro1D::vy (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 534 of file state.h.
 {return (*hvy)[i];}
vyarray()
valarray<double >& Hydro1D::vyarray () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 547 of file state.h.
Referenced by Hydro1D::Hydro1D(), Setup_Y::initialize(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), and Hydro1D::operator=().
 {return (*hvy);}
vz() [1/2]
double& Hydro1D::vz (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 536 of file state.h.
Referenced by Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), Output_Data::Output_Preprocessor_1D::Uz(), and Fluid_Equation_1D::velocity().
 { return (*hvz)[i];}
vz() [2/2]
double Hydro1D::vz (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 537 of file state.h.
 {return (*hvz)[i];}
vzarray()
valarray<double >& Hydro1D::vzarray () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 548 of file state.h.
Referenced by Hydro1D::Hydro1D(), Setup_Y::initialize(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), and Hydro1D::operator=().
 {return (*hvz);}
xVec()
vector<complex<double> > SHarmonic1D::xVec (size_t j) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 80 of file state.h.
References SHarmonic1D::checknan(), SHarmonic1D::Dp(), SHarmonic1D::Dx(), SHarmonic1D::Filterp(), SHarmonic1D::mpaxis(), SHarmonic1D::mxaxis(), SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), SHarmonic1D::operator=(), and SHarmonic1D::Re().
 {return (*sh).d2c(j);}       //1D-style
Z() [1/2]
double& Hydro1D::Z (size_t i) inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 542 of file state.h.
Referenced by Fluid_Equation_1D::chargefraction(), Setup_Y::initialize(), Node_Communications::mirror_bound_Xleft(), Node_Communications::mirror_bound_Xright(), Node_Communications::Recv_from_left_X(), Node_Communications::Recv_from_right_X(), Node_Communications::sameNode_periodic_X(), Node_Communications::Send_left_X(), Node_Communications::Send_right_X(), Fluid_Equation_1D::velocity(), and Output_Data::Output_Preprocessor_1D::Z().
 { return (*hz)[i];}             //1D-style
Z() [2/2]
double Hydro1D::Z (size_t i) const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 543 of file state.h.
 {return (*hz)[i];}
Zarray()
valarray<double >& Hydro1D::Zarray () const inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 550 of file state.h.
References SHarmonic1D::operator*=(), SHarmonic1D::operator+=(), SHarmonic1D::operator-=(), and SHarmonic1D::operator=().
Referenced by collisions::advancef0(), collisions::advancef1(), collisions::advanceflm(), Hydro1D::Hydro1D(), Setup_Y::initialize(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), and Hydro1D::operator=().
 {return (*hz);}
~DistFunc1D()
DistFunc1D::~DistFunc1D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 831 of file state.cpp.
References DistFunc1D::df.
{
     delete df;
 }
~DistFunc2D()
DistFunc2D::~DistFunc2D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1183 of file state.cpp.
References DistFunc2D::df.
{
     delete df;
 }
~EMF1D()
EMF1D::~EMF1D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 591 of file state.cpp.
               {
     delete fie;
 }
~EMF2D()
EMF2D::~EMF2D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 674 of file state.cpp.
               {
     delete fie;
 }
~Field1D()
Field1D::~Field1D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 386 of file state.cpp.
                   {
     delete fi;
 }
~Field2D()
Field2D::~Field2D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 508 of file state.cpp.
                   {
     delete fi;
 }
~Hydro1D()
Hydro1D::~Hydro1D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1367 of file state.cpp.
References Hydro1D::hn, Hydro1D::ht, Hydro1D::hvx, Hydro1D::hvy, Hydro1D::hvz, and Hydro1D::hz.
                   {
     delete hn;
     delete hvx;
     delete hvy;
     delete hvz;
     delete ht;
     delete hz;
 }
~SHarmonic1D()
SHarmonic1D::~SHarmonic1D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 72 of file state.cpp.
References SHarmonic1D::sh.
{
     delete sh;
 }
~SHarmonic2D()
SHarmonic2D::~SHarmonic2D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 253 of file state.cpp.
References SHarmonic1D::sh.
{
     delete sh;
 }
~State1D()
State1D::~State1D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1545 of file state.cpp.
References State1D::flds, State1D::hydro, and State1D::sp.
                   {
     delete sp;
     delete flds;
     delete hydro;
 }
~State2D()
State2D::~State2D ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/state.h>
Definition at line 1681 of file state.cpp.
References State2D::flds, and State2D::sp.
                   {
     delete sp;
     delete flds;
 }
Variable Documentation
charge [1/2]
double DistFunc1D::charge private
Definition at line 382 of file state.h.
Referenced by DistFunc1D::getcurrent().
charge [2/2]
double DistFunc2D::charge private
Definition at line 454 of file state.h.
df [1/2]
vector<SHarmonic1D>* DistFunc1D::df private
Definition at line 380 of file state.h.
Referenced by DistFunc1D::checknan(), DistFunc1D::DistFunc1D(), DistFunc1D::getcurrent(), DistFunc1D::getdensity(), DistFunc1D::getpressure(), DistFunc1D::operator()(), DistFunc1D::operator=(), and DistFunc1D::~DistFunc1D().
df [2/2]
vector<SHarmonic2D>* DistFunc2D::df private
Definition at line 452 of file state.h.
Referenced by DistFunc2D::DistFunc2D(), DistFunc2D::operator=(), and DistFunc2D::~DistFunc2D().
fi [1/2]
valarray<complex<double> >* Field1D::fi private
Definition at line 187 of file state.h.
fi [2/2]
Array2D< complex < double > >* Field2D::fi private
Definition at line 236 of file state.h.
fie [1/2]
vector<Field1D>* EMF1D::fie private
Definition at line 277 of file state.h.
fie [2/2]
vector<Field2D>* EMF2D::fie private
Definition at line 329 of file state.h.
filter_ceiling
valarray<int> DistFunc1D::filter_ceiling private
Definition at line 385 of file state.h.
Referenced by DistFunc1D::DistFunc1D().
flds [1/2]
EMF1D* State1D::flds private
Definition at line 580 of file state.h.
Referenced by State1D::operator*=(), State1D::operator+=(), State1D::operator-=(), State1D::operator=(), State1D::State1D(), and State1D::~State1D().
flds [2/2]
EMF2D* State2D::flds private
Definition at line 640 of file state.h.
Referenced by State2D::operator*=(), State2D::operator+=(), State2D::operator-=(), State2D::operator=(), State2D::State2D(), and State2D::~State2D().
hn
valarray<double>* Hydro1D::hn private
Definition at line 510 of file state.h.
Referenced by Hydro1D::Hydro1D(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Hydro1D::~Hydro1D().
ht
valarray<double> * Hydro1D::ht private
Definition at line 510 of file state.h.
Referenced by Hydro1D::Hydro1D(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Hydro1D::~Hydro1D().
hvx
valarray<double> * Hydro1D::hvx private
Definition at line 510 of file state.h.
Referenced by Hydro1D::Hydro1D(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Hydro1D::~Hydro1D().
hvy
valarray<double> * Hydro1D::hvy private
Definition at line 510 of file state.h.
Referenced by Hydro1D::Hydro1D(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Hydro1D::~Hydro1D().
hvz
valarray<double> * Hydro1D::hvz private
Definition at line 510 of file state.h.
Referenced by Hydro1D::Hydro1D(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Hydro1D::~Hydro1D().
hydro
Hydro1D* State1D::hydro private
Definition at line 581 of file state.h.
Referenced by State1D::operator*=(), State1D::operator+=(), State1D::operator-=(), State1D::operator=(), State1D::State1D(), and State1D::~State1D().
hydrocharge
double Hydro1D::hydrocharge private
Definition at line 512 of file state.h.
hydromass
double Hydro1D::hydromass private
Definition at line 512 of file state.h.
hz
valarray<double> * Hydro1D::hz private
Definition at line 510 of file state.h.
Referenced by Hydro1D::Hydro1D(), Hydro1D::operator*=(), Hydro1D::operator+=(), Hydro1D::operator-=(), Hydro1D::operator=(), and Hydro1D::~Hydro1D().
ind [1/2]
Array2D<int> DistFunc1D::ind private
Definition at line 384 of file state.h.
Referenced by DistFunc1D::DistFunc1D(), and DistFunc1D::operator()().
ind [2/2]
Array2D<int> DistFunc2D::ind private
Definition at line 457 of file state.h.
Referenced by DistFunc2D::DistFunc2D().
lmax [1/2]
size_t DistFunc1D::lmax private
Definition at line 381 of file state.h.
Referenced by DistFunc1D::DistFunc1D().
lmax [2/2]
size_t DistFunc2D::lmax private
Definition at line 453 of file state.h.
Referenced by DistFunc2D::DistFunc2D().
ma [1/2]
double DistFunc1D::ma private
Definition at line 382 of file state.h.
Referenced by DistFunc1D::getcurrent(), and DistFunc1D::getpressure().
ma [2/2]
double DistFunc2D::ma private
Definition at line 454 of file state.h.
mmax [1/2]
size_t DistFunc1D::mmax private
Definition at line 381 of file state.h.
Referenced by DistFunc1D::DistFunc1D().
mmax [2/2]
size_t DistFunc2D::mmax private
Definition at line 453 of file state.h.
Referenced by DistFunc2D::DistFunc2D().
ns [1/2]
size_t State1D::ns private
Definition at line 586 of file state.h.
Referenced by State1D::checknan(), State1D::operator*=(), State1D::operator+=(), State1D::operator-=(), State1D::operator=(), and State1D::State1D().
ns [2/2]
size_t State2D::ns private
Definition at line 642 of file state.h.
Referenced by State2D::operator*=(), State2D::operator+=(), State2D::operator-=(), State2D::operator=(), and State2D::State2D().
pmx
double DistFunc1D::pmx private
Definition at line 382 of file state.h.
sh [1/2]
Array2D<complex<double> >* SHarmonic1D::sh private
Definition at line 60 of file state.h.
Referenced by SHarmonic1D::checknan(), SHarmonic1D::Dp(), SHarmonic1D::Dx(), SHarmonic2D::Dx(), SHarmonic2D::Dy(), SHarmonic1D::Filterp(), SHarmonic2D::Filterp(), SHarmonic2D::mxy_matrix(), SHarmonic1D::operator=(), SHarmonic2D::operator=(), SHarmonic1D::Re(), SHarmonic1D::SHarmonic1D(), SHarmonic2D::SHarmonic2D(), SHarmonic1D::~SHarmonic1D(), and SHarmonic2D::~SHarmonic2D().
sh [2/2]
Array3D<complex <double> >* SHarmonic2D::sh private
Definition at line 125 of file state.h.
sp [1/2]
vector<DistFunc1D>* State1D::sp private
Definition at line 579 of file state.h.
Referenced by State1D::State1D(), and State1D::~State1D().
sp [2/2]
vector<DistFunc2D>* State2D::sp private
Definition at line 639 of file state.h.
Referenced by State2D::operator*=(), State2D::operator+=(), State2D::operator-=(), State2D::operator=(), State2D::State2D(), and State2D::~State2D().
sz [1/2]
size_t DistFunc1D::sz private
Definition at line 381 of file state.h.
Referenced by DistFunc1D::DistFunc1D().
sz [2/2]
size_t DistFunc2D::sz private
Definition at line 453 of file state.h.
Referenced by DistFunc2D::DistFunc2D().