OSHUN: VlasovFunctor1D_implicitE_p2 Class Reference
VlasovFunctor1D_implicitE_p2 Class Reference
#include <functors.h>
Public Member Functions
VlasovFunctor1D_implicitE_p2 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_implicitE_p2 ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Electric_Field_1D > EF
vector< Faraday_1D > FA
Detailed Description
Definition at line 180 of file functors.h.
Constructor & Destructor Documentation
VlasovFunctor1D_implicitE_p2()
VlasovFunctor1D_implicitE_p2::VlasovFunctor1D_implicitE_p2 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 430 of file functors.cpp.
References VlasovFunctor1D_explicitE::EF, and VlasovFunctor1D_explicitE::FA.
{
 // //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
         EF.push_back( Electric_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_implicitE_p2()
VlasovFunctor1D_implicitE_p2::~VlasovFunctor1D_implicitE_p2 () inline
Definition at line 187 of file functors.h.
References VlasovFunctor1D_explicitE::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_implicitE_p2::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 443 of file functors.cpp.
References State1D::DF(), VlasovFunctor1D_explicitE::EF, State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), VlasovFunctor1D_explicitE::FA, DistFunc1D::Filterp(), DistFunc1D::l0(), and State1D::Species().
{
 // //---------------------------------------------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         FA[s](Yin.EMF(),Yslope.EMF());
         if (Yin.DF(s).l0() == 1) EF[s].f1only(Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         else                     EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_implicitE_p2::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
operator()() [3/3]
void VlasovFunctor1D_implicitE_p2::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 461 of file functors.cpp.
References State1D::DF(), VlasovFunctor1D_explicitE::EF, State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), DistFunc1D::Filterp(), DistFunc1D::l0(), and State1D::Species().
{
 //--------------------------------------------------------------------------------------------------
     Yslope = 0.0;
     if (direction == 1)
     {
         for (size_t s(0); s < Yin.Species(); ++s) {
             if (Yin.DF(s).l0() == 1) EF[s].Implicit_Ex_f1only(Yin.DF(s),Yin.EMF().Ex(),Yslope.DF(s));
             else                     EF[s].Implicit_Ex(Yin.DF(s),Yin.EMF().Ex(),Yslope.DF(s));
             Yslope.DF(s) = Yslope.DF(s).Filterp();
         }
     }
     else if (direction == 2)
     {
         for (size_t s(0); s < Yin.Species(); ++s) {
             if (Yin.DF(s).l0() == 1) EF[s].Implicit_Ey_f1only(Yin.DF(s),Yin.EMF().Ey(),Yslope.DF(s));
             else                     EF[s].Implicit_Ey(Yin.DF(s),Yin.EMF().Ey(),Yslope.DF(s));
             Yslope.DF(s) = Yslope.DF(s).Filterp();
         }
     }
     else
     {
         // complex<double> ii(0.0,1.0);
         for (size_t s(0); s < Yin.Species(); ++s) {
             if (Yin.DF(s).l0() == 1) EF[s].Implicit_Ez_f1only(Yin.DF(s),Yin.EMF().Ez(),Yslope.DF(s));
             else                     EF[s].Implicit_Ez(Yin.DF(s),Yin.EMF().Ez(),Yslope.DF(s));
             Yslope.DF(s) = Yslope.DF(s).Filterp();
         }
     }
 }
Field Documentation
EF
vector<Electric_Field_1D> VlasovFunctor1D_implicitE_p2::EF private
Definition at line 197 of file functors.h.
FA
vector<Faraday_1D> VlasovFunctor1D_implicitE_p2::FA private
Definition at line 201 of file functors.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.cpp