OSHUN: VlasovFunctor1D_f1_implicitE_p2 Class Reference
VlasovFunctor1D_f1_implicitE_p2 Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov_f1.h>
Public Member Functions
VlasovFunctor1D_f1_implicitE_p2 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_f1_implicitE_p2 ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Electric_Field_1D_f1 > EF
vector< Faraday_1D > FA
Detailed Description
Definition at line 218 of file vlasov_f1.h.
Constructor & Destructor Documentation
VlasovFunctor1D_f1_implicitE_p2()
VlasovFunctor1D_f1_implicitE_p2::VlasovFunctor1D_f1_implicitE_p2 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 892 of file vlasov_f1.cpp.
{
 // //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         double pmin( pmax[s] / ( double(Np[s] * 2 - 1)) );
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
         EF.push_back( Electric_Field_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_f1_implicitE_p2()
VlasovFunctor1D_f1_implicitE_p2::~VlasovFunctor1D_f1_implicitE_p2 () inline
Definition at line 225 of file vlasov_f1.h.
References Spatial_Advection_1D_f1::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_f1_implicitE_p2::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 908 of file vlasov_f1.cpp.
References State1D::DF(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), DistFunc1D::Filterp(), and State1D::Species().
{
 // //---------------------------------------------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         FA[s](Yin.EMF(),Yslope.EMF());
         EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_f1_implicitE_p2::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
Definition at line 952 of file vlasov_f1.cpp.
 {}
operator()() [3/3]
void VlasovFunctor1D_f1_implicitE_p2::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 923 of file vlasov_f1.cpp.
References State1D::DF(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), DistFunc1D::Filterp(), and State1D::Species().
{
 // //--------------------------------------------------------------------------------------------------
     Yslope = 0.0;
     if (direction == 1)
     {
         for (size_t s(0); s < Yin.Species(); ++s) {
             EF[s].Implicit_Ex(Yin.DF(s),Yin.EMF().Ex(),Yslope.DF(s));
             Yslope.DF(s) = Yslope.DF(s).Filterp();
         }
     }
     else if (direction == 2)
     {
         for (size_t s(0); s < Yin.Species(); ++s) {
             EF[s].Implicit_Ey(Yin.DF(s),Yin.EMF().Ey(),Yslope.DF(s));
             Yslope.DF(s) = Yslope.DF(s).Filterp();
         }
     }
     else
     {
         // complex<double> ii(0.0,1.0);
         for (size_t s(0); s < Yin.Species(); ++s) {
             EF[s].Implicit_Ez(Yin.DF(s),Yin.EMF().Ez(),Yslope.DF(s));
             Yslope.DF(s) = Yslope.DF(s).Filterp();
         }
     }
 }
Field Documentation
EF
vector<Electric_Field_1D_f1> VlasovFunctor1D_f1_implicitE_p2::EF private
Definition at line 235 of file vlasov_f1.h.
FA
vector<Faraday_1D> VlasovFunctor1D_f1_implicitE_p2::FA private
Definition at line 239 of file vlasov_f1.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.cpp