OSHUN: Export_Files::Restart_Facility Class Reference
Export_Files::Restart_Facility Class Reference
#include <export.h>
Public Member Functions
Restart_Facility (const int rank, string homedir="")
void Read (const int rank, const size_t re_step, State1D &Y)
void Write (const int rank, const size_t re_step, State1D &Y)
Private Member Functions
string rFextension (const int rank, const size_t rstep)
Private Attributes
string hdir
Detailed Description
Definition at line 213 of file export.h.
Constructor & Destructor Documentation
Restart_Facility()
Export_Files::Restart_Facility::Restart_Facility (const int rank, string homedir = "")
Definition at line 708 of file export.cpp.
References Export_Files::Makefolder().
{
     hdir = homedir;
     if (!rank) Makefolder(hdir+"RESTART/");
 //        if (Makefolder(hdir+"RESTART/") != 0) cout<<"Warning: Folder "<< hdir+"RESTART/"<<" exists\n";
 }
Member Function Documentation
Read()
void Export_Files::Restart_Facility::Read (const int rank, const size_t re_step, State1D & Y)
Definition at line 718 of file export.cpp.
References State1D::DF(), DistFunc1D::dim(), State1D::EMF(), EMF1D::Ex(), Field1D::numx(), and State1D::Species().
{
 //      Generate filename
     string   filename(hdir+"RESTART/re_1D_");
     filename.append(rFextension(rank,re_step));
 //      Open file
     ifstream  fin(filename.c_str(), ios::binary);
     if (fin)
     {
     //      Read distribution functions
         for(size_t s(0); s < Y.Species(); ++s) {
             for(size_t nh(0); nh < Y.DF(s).dim(); ++nh) {
                 for(size_t i(0); i < (Y.DF(s))(nh).dim(); ++i) {
                     fin.read((char *)&(Y.DF(s))(nh)(i), sizeof((Y.DF(s))(nh)(i)));
                 }
             }
         }
     }
     else {
         if (!rank) std::cout << "\n\n ERROR :: No files to read! \n\n";
         exit(1);
     }
 //      Read Ex
     for(size_t i(0); i < Y.EMF().Ex().numx(); ++i){
         fin.read((char *)(&Y.EMF().Ex()(i)), sizeof(Y.EMF().Ex()(i)));
     }
     fin.close();
 }
rFextension()
string Export_Files::Restart_Facility::rFextension (const int rank, const size_t rstep) private
Definition at line 789 of file export.cpp.
References Export_Files::ofconventions::rank_digits, Export_Files::ofconventions::rfile_digits, Export_Files::ofconventions::rfile_extension, and Export_Files::stringify().
{
     stringstream sFilename;
     // Number of zeros to add to the filename
     int Nzeros(ofconventions::rank_digits - stringify(rank).length());
     while (Nzeros-- > 0) {
         sFilename << "0";
     }
     sFilename << rank << "_";
     // Number of zeros to add to the filename
     Nzeros = ofconventions::rfile_digits - stringify(rstep).length();
     while (Nzeros-- > 0) {
         sFilename << "0";
     }
     sFilename << rstep << ofconventions::rfile_extension;
     return sFilename.str();
 }
Write()
void Export_Files::Restart_Facility::Write (const int rank, const size_t re_step, State1D & Y)
Definition at line 756 of file export.cpp.
References State1D::DF(), DistFunc1D::dim(), State1D::EMF(), EMF1D::Ex(), Field1D::numx(), and State1D::Species().
{
 //      Generate filename
     string   filename(hdir+"RESTART/re_1D_");
     filename.append(rFextension(rank,re_step));
 //      Open file
     ofstream  fout(filename.c_str(), ios::binary);
 //      Write distribution functions
     for(size_t s(0); s < Y.Species(); ++s) {
         for (size_t s(0); s < Y.Species(); ++s) {
             for (size_t nh(0); nh < Y.DF(s).dim(); ++nh) {
                 for (size_t i(0); i < (Y.DF(s))(nh).dim(); ++i) {
                     fout.write((char *) &(Y.DF(s))(nh)(i), sizeof((Y.DF(s))(nh)(i)));
                 }
             }
         }
     }
 //      Write Ex
     for(size_t i(0); i < Y.EMF().Ex().numx(); ++i) {
         fout.write((char *)(&Y.EMF().Ex()(i)), sizeof(Y.EMF().Ex()(i)));
     }
     fout.flush();
     fout.close();
 }
Field Documentation
hdir
string Export_Files::Restart_Facility::hdir private
Definition at line 222 of file export.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/export.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/export.cpp