OSHUN: VlasovFunctor1D_implicitEB_p1 Class Reference
VlasovFunctor1D_implicitEB_p1 Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov.h>
Public Member Functions
VlasovFunctor1D_implicitEB_p1 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_implicitEB_p1 ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D > SA
Detailed Description
Definition at line 268 of file vlasov.h.
Constructor & Destructor Documentation
VlasovFunctor1D_implicitEB_p1()
VlasovFunctor1D_implicitEB_p1::VlasovFunctor1D_implicitEB_p1 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 1640 of file vlasov.cpp.
{
 // //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         SA.push_back( Spatial_Advection_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_implicitEB_p1()
VlasovFunctor1D_implicitEB_p1::~VlasovFunctor1D_implicitEB_p1 () inline
Definition at line 275 of file vlasov.h.
References Spatial_Advection_1D::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_implicitEB_p1::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 1655 of file vlasov.cpp.
References State1D::DF(), DistFunc1D::Filterp(), DistFunc1D::l0(), and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         if (Yin.DF(s).l0() == 1)    SA[s].f1only(Yin.DF(s),Yslope.DF(s));
         else                        SA[s](Yin.DF(s),Yslope.DF(s));
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_implicitEB_p1::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 1671 of file vlasov.cpp.
 {}
operator()() [3/3]
void VlasovFunctor1D_implicitEB_p1::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 1670 of file vlasov.cpp.
 {}
Field Documentation
SA
vector<Spatial_Advection_1D> VlasovFunctor1D_implicitEB_p1::SA private
Definition at line 283 of file vlasov.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.cpp