OSHUN: VlasovFunctor1D_explicitE Class Reference
VlasovFunctor1D_explicitE Class Reference
#include <functors.h>
Public Member Functions
VlasovFunctor1D_explicitE (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_explicitE ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D > SA
vector< Electric_Field_1D > EF
vector< Current_1D > JX
vector< Ampere_1D > AM
vector< Magnetic_Field_1D > BF
vector< Faraday_1D > FA
Detailed Description
Definition at line 16 of file functors.h.
Constructor & Destructor Documentation
VlasovFunctor1D_explicitE()
VlasovFunctor1D_explicitE::VlasovFunctor1D_explicitE (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 42 of file functors.cpp.
References AM, BF, EF, FA, JX, and SA.
{
 //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         SA.push_back( Spatial_Advection_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         EF.push_back( Electric_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         JX.push_back( Current_1D(0.0, pmax[s], Np[s], Nx) );
         BF.push_back( Magnetic_Field_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
         AM.push_back( Ampere_1D(xmin, xmax, Nx) );
         FA.push_back( Faraday_1D(xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_explicitE()
VlasovFunctor1D_explicitE::~VlasovFunctor1D_explicitE () inline
Definition at line 23 of file functors.h.
References operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_explicitE::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 67 of file functors.cpp.
References AM, BF, EMF1D::Bx(), EMF1D::By(), EMF1D::Bz(), State1D::DF(), EF, State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), FA, JX, DistFunc1D::l0(), DistFunc1D::m0(), SHarmonic1D::nump(), SHarmonic1D::numx(), SA, State1D::SH(), and State1D::Species().
Referenced by ~VlasovFunctor1D_explicitE(), VlasovFunctor1D_explicitE_implicitB::~VlasovFunctor1D_explicitE_implicitB(), VlasovFunctor1D_implicitE_implicitB_p1::~VlasovFunctor1D_implicitE_implicitB_p1(), VlasovFunctor1D_implicitE_p1::~VlasovFunctor1D_implicitE_p1(), VlasovFunctor1D_implicitE_p2::~VlasovFunctor1D_implicitE_p2(), VlasovFunctor1D_momentumpush::~VlasovFunctor1D_momentumpush(), and VlasovFunctor1D_spatialpush::~VlasovFunctor1D_spatialpush().
{
 //--------------------------------------------------------------
     bool debug(0);
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         if (Yin.DF(s).l0() == 1) {
             SA[s].f1only(Yin.DF(s),Yslope.DF(s));
             EF[s].f1only(Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
             BF[s].f1only(Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
             JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
             AM[s](Yin.EMF(),Yslope.EMF());
             FA[s](Yin.EMF(),Yslope.EMF());
         }
         else if (Yin.DF(s).m0() == 0) {
             if (debug)
             {
                 std::cout << "\n\n f at start:";
                 for (size_t ip(0); ip < Yin.SH(0,0,0).nump(); ++ip){
                     std::cout << "\nf(" << ip << ") = " << Yin.SH(0,1,0)(ip,4);
                 }
                 std::cout << "\n\n E at start:";
                 for (size_t ix(0); ix < Yin.SH(0,0,0).numx(); ++ix){
                     std::cout << "\nEx(" << ix << ") = " << Yin.EMF().Ex()(ix);
                 }
             }
             EF[s].es1d(Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
             if (debug)
             {
                 std::cout << "\n\nf after E:";
                 for (size_t ip(0); ip < Yin.SH(0,0,0).nump(); ++ip){
                     std::cout << "\nf(" << ip << ") = " << Yslope.SH(0,1,0)(ip,4);
                 }
             }
             JX[s].es1d(Yin.DF(s),Yslope.EMF().Ex());
             if (debug)
             {
                 std::cout << "\n\n after J:";
                 for (size_t ix(0); ix < Yin.SH(0,0,0).numx(); ++ix){
                     std::cout << "\nEx(" << ix << ") = " << Yslope.EMF().Ex()(ix);
                 }
             }
             SA[s].es1d(Yin.DF(s),Yslope.DF(s));
             if (debug)
             {
                 std::cout << "\n\n after SA:";
                 for (size_t ip(0); ip < Yin.SH(0,0,0).nump(); ++ip){
                     std::cout << "\nf(" << ip << ") = " << Yslope.SH(0,1,0)(ip,4);
                 }
             }
         }
         else {
             SA[s](Yin.DF(s),Yslope.DF(s));
             EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
             BF[s](Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
             JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
             AM[s](Yin.EMF(),Yslope.EMF());
             FA[s](Yin.EMF(),Yslope.EMF());
         }
         // Yslope.DF(s) = Yslope.DF(s).Filterp();
         // exit(1);
     }
 }
operator()() [2/3]
void VlasovFunctor1D_explicitE::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
operator()() [3/3]
void VlasovFunctor1D_explicitE::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 159 of file functors.cpp.
 {}
Field Documentation
AM
vector<Ampere_1D> VlasovFunctor1D_explicitE::AM private
Definition at line 38 of file functors.h.
Referenced by operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_explicitE(), VlasovFunctor1D_explicitE_implicitB::VlasovFunctor1D_explicitE_implicitB(), and VlasovFunctor1D_momentumpush::VlasovFunctor1D_momentumpush().
BF
vector<Magnetic_Field_1D> VlasovFunctor1D_explicitE::BF private
Definition at line 39 of file functors.h.
Referenced by operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_explicitE(), VlasovFunctor1D_implicitE_p1::VlasovFunctor1D_implicitE_p1(), and VlasovFunctor1D_momentumpush::VlasovFunctor1D_momentumpush().
EF
vector<Electric_Field_1D> VlasovFunctor1D_explicitE::EF private
Definition at line 36 of file functors.h.
Referenced by operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_explicitE(), VlasovFunctor1D_explicitE_implicitB::VlasovFunctor1D_explicitE_implicitB(), VlasovFunctor1D_implicitE_p2::VlasovFunctor1D_implicitE_p2(), and VlasovFunctor1D_momentumpush::VlasovFunctor1D_momentumpush().
FA
vector<Faraday_1D> VlasovFunctor1D_explicitE::FA private
Definition at line 40 of file functors.h.
Referenced by operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_implicitE_p2::operator()(), VlasovFunctor1D_explicitE(), VlasovFunctor1D_explicitE_implicitB::VlasovFunctor1D_explicitE_implicitB(), VlasovFunctor1D_implicitE_p2::VlasovFunctor1D_implicitE_p2(), and VlasovFunctor1D_momentumpush::VlasovFunctor1D_momentumpush().
JX
vector<Current_1D> VlasovFunctor1D_explicitE::JX private
Definition at line 37 of file functors.h.
Referenced by operator()(), VlasovFunctor1D_momentumpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_explicitE(), VlasovFunctor1D_explicitE_implicitB::VlasovFunctor1D_explicitE_implicitB(), and VlasovFunctor1D_momentumpush::VlasovFunctor1D_momentumpush().
SA
vector<Spatial_Advection_1D> VlasovFunctor1D_explicitE::SA private
Definition at line 35 of file functors.h.
Referenced by operator()(), VlasovFunctor1D_spatialpush::operator()(), VlasovFunctor1D_explicitE_implicitB::operator()(), VlasovFunctor1D_implicitE_p1::operator()(), VlasovFunctor1D_implicitE_implicitB_p1::operator()(), VlasovFunctor1D_explicitE(), VlasovFunctor1D_explicitE_implicitB::VlasovFunctor1D_explicitE_implicitB(), VlasovFunctor1D_implicitE_implicitB_p1::VlasovFunctor1D_implicitE_implicitB_p1(), VlasovFunctor1D_implicitE_p1::VlasovFunctor1D_implicitE_p1(), and VlasovFunctor1D_spatialpush::VlasovFunctor1D_spatialpush().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.cpp