OSHUN: Formulary Class Reference
Formulary Class Reference
#include <formulary.h>
Public Member Functions
Formulary ()
units Units (string key)
units Units (string key1, string key2)
string Label (string key)
string Label (string key1, string key2)
double Uconv (string key)
double Uconv (string key1, string key2)
double LOGee (double ne, double Te)
double LOGee (double ne, string un, double Te, string uT)
double LOGei (double ne, double Te, double Z)
double LOGei (double ne, string un, double Te, string uT, double Z)
double LOGii (double m1, double Z1, double n1, double T1, double m2, double Z2, double n2, double T2)
double vth (double Te)
double vth (double Te, string uT)
double Tau_e (double ne, double Te)
double Tau_e (double ne, string un, double Te, string uT)
double Tau_i (double ne, double Te, double Zeta)
double MFP (double ne, double Te)
double MFP (double ne, string un, double Te, string uT)
Data Fields
double n
double wp
double skindepth
double B0
double T0
double Zeta
Static Public Attributes
static constexpr double pi =3.141592653589793238
static constexpr double cL = 299792458
static constexpr double eps0 =8.854187817e-12
static constexpr double qe = -1.60217662e-19
static constexpr double me = 9.10938356e-31
static constexpr double me_over_mp = 0.000544617024
static constexpr double keVnorm = 510.9989461
static constexpr double c = 2.99792458*1.0e+10
static constexpr double e = 4.80320425*1.0e-10
static constexpr double m = 9.10938215*1.0e-28
Private Attributes
map< string, units > D
Static Private Attributes
static constexpr double nmin = 1.0e-8
Detailed Description
Definition at line 68 of file formulary.h.
Constructor & Destructor Documentation
Formulary()
Formulary::Formulary ()
Definition at line 43 of file formulary.cpp.
References c, D, e, m, n, and wp.
                      : n(Input::List().density_np),
                         wp(5.64*1.0e+4*sqrt(n)),
                         skindepth(cL/wp),
                         B0(-1.0*wp*me/qe),
                         T0(pow(Input::List().pth_ref,2.0)*keVnorm*1e3),
                         Zeta(Input::List().hydrocharge)
                         // ref_nuei(sqrt(2.0/pi)*LOGei(1.0,Input::List().pth_ref,Zeta)/exp(LOGei(1.0,Input::List().pth_ref,Zeta)) * wp)
{
     // Physically: label * d = const in any system
     // velocity - c
     D["Velocity"]     = units("c",1.0);
     D["Velocity_cgs"] = units("cm/sec", c );
     D["Velocity_si"]  = units("m/sec",  c * 0.01 );
     D["v"]     = units("c",1.0);
     D["v_cgs"] = units("cm/sec", c );
     D["v_si"]  = units("m/sec",  c * 0.01 );
     D["vx"]     = units("c",1.0);
     D["vx_cgs"] = units("cm/sec", c );
     D["vx_si"]  = units("m/sec",  c * 0.01 );
     D["vy"]     = units("c",1.0);
     D["vy_cgs"] = units("cm/sec", c );
     D["vy_si"]  = units("m/sec",  c * 0.01 );
     D["vz"]     = units("c",1.0);
     D["vz_cgs"] = units("cm/sec", c );
     D["vz_si"]  = units("m/sec",  c * 0.01 );
     // time - 1/wp
     D["Time"]     = units("1/wp",1.0);
     D["Time_cgs"] = units("sec", 1.0/wp);
     D["Time_si"]  = units("sec", 1.0/wp);
     D["Time_fs"]  = units("fsec", 1.0/wp*1.0e+15);
     D["Time_ps"]  = units("psec", 1.0/wp*1.0e+12);
     D["t"]     = units("1/wp",1.0);
     D["t_cgs"] = units("sec", 1.0/wp);
     D["t_si"]  = units("sec", 1.0/wp);
     // space - c/wp
     D["Space"]     = units("c/wp",1.0);
     D["Space_cgs"] = units("cm",       c/wp);
     D["Space_si"]  = units("m", 0.01 * c/wp); // 1 cm = 0.01 m
     D["x"]     = units("c/wp",1.0);
     D["x_cgs"] = units("cm",       c/wp);
     D["x_si"]  = units("m", 0.01 * c/wp); // 1 cm = 0.01 m
     D["y"]     = units("c/wp",1.0);
     D["y_cgs"] = units("cm",       c/wp);
     D["y_si"]  = units("m", 0.01 * c/wp); // 1 cm = 0.01 m
     D["z"]     = units("c/wp",1.0);
     D["z_cgs"] = units("cm",       c/wp);
     D["z_si"]  = units("m", 0.01 * c/wp); // 1 cm = 0.01 m
     // density - n
     D["Density"]     = units("n",1.0);
     D["Density_cgs"] = units("cm^-3",         n);
     D["Density_si"]  = units("m^-3", 1.0e+6 * n);   // cm^-3 = 10^6 m^-3
     D["n"]     = units("n",1.0);
     D["n_cgs"] = units("cm^-3",         n);
     D["n_si"]  = units("m^-3", 1.0e+6 * n);   // cm^-3 = 10^6 m^-3
     // charge - e
     D["Charge"]     = units("e",1.0);
     D["Charge_cgs"] = units("Fr",           e);
     D["Charge_si"]  = units("C", (10.0/c) * e);  // 1 Fr = (10/c) * C
     D["q"]     = units("e",1.0);
     D["q_cgs"] = units("Fr",           e);
     D["q_si"]  = units("C", (10.0/c) * e);  // 1 Fr = (10/c) * C
     // momentum - mc
     D["Momentum"]     = units("mc",1.0);
     D["Momentum_cgs"] = units("gr*cm/sec", m*c );
     D["Momentum_si"]  = units("kg*m/sec",  m*c * 1.0e-5 );
     D["p"]     = units("mc",1.0);
     D["p_cgs"] = units("gr*cm/sec", m*c );
     D["p_si"]  = units("kg*m/sec",  m*c * 1.0e-5 );
     D["px"]     = units("mc",1.0);
     D["px_cgs"] = units("gr*cm/sec", m*c );
     D["px_si"]  = units("kg*m/sec",  m*c * 1.0e-5 );
     D["py"]     = units("mc",1.0);
     D["py_cgs"] = units("gr*cm/sec", m*c );
     D["py_si"]  = units("kg*m/sec",  m*c * 1.0e-5 );
     D["pz"]     = units("mc",1.0);
     D["pz_cgs"] = units("gr*cm/sec", m*c );
     D["pz_si"]  = units("kg*m/sec",  m*c * 1.0e-5 );
 //-----
     // energy - mc^2
     D["Energy"]     = units("mc^2",1.0);
     D["Energy_cgs"] = units("erg",          m*pow(c,2)   );
     D["Energy_si"]  = units("J",   1.0e-7 * m*pow(c,2)   );  // erg = 10^-7 J
     D["Energy_eV"]  = units("eV",  1.0e-7 * m*pow(c,2)/((10.0/c) * e) );
     D["T"]     = units("mc^2",1.0);
     D["T_cgs"] = units("erg",          m*pow(c,2)   );
     D["T_si"]  = units("J",   1.0e-7 * m*pow(c,2)   );  // erg = 10^-7 J
     D["T_eV"]  = units("eV",  1.0e-7 * m*pow(c,2)/((10.0/c) * e) );
     // current - ewp
     D["Current"]     = units("ewp",1.0);
     D["Current_cgs"] = units("Fr/s",        e*wp );
     D["Current_si"]  = units("A",  10.0/c * e*wp );  // Fr/s = 10/c A
     D["Jx"]     = units("ewp",1.0);
     D["Jx_cgs"] = units("Fr/s",        e*wp );
     D["Jx_si"]  = units("A",  10.0/c * e*wp );  // Fr/s = 10/c A
     D["Jy"]     = units("ewp",1.0);
     D["Jy_cgs"] = units("Fr/s",        e*wp );
     D["Jy_si"]  = units("A",  10.0/c * e*wp );  // Fr/s = 10/c A
     D["Jz"]     = units("ewp",1.0);
     D["Jz_cgs"] = units("Fr/s",        e*wp );
     D["Jz_si"]  = units("A",  10.0/c * e*wp );  // Fr/s = 10/c A
     // pressure - n*mc^2
     D["Pressure"]      = units("n*mc^2",1.0);
     D["Pressure_cgs"]  = units("Ba",             n*m*c*c );
     D["Pressure_si"]   = units("Pa",       0.1 * n*m*c*c ); // Ba = 0.1 Pa
     D["Pressure_Mbar"] = units("Mbar", 1.0e-12 * n*m*c*c ); // Ba = 10^-12Mbar
     D["P"]      = units("n*mc^2",1.0);
     D["P_cgs"]  = units("Ba",             n*m*c*c );
     D["P_si"]   = units("Pa",       0.1 * n*m*c*c ); // Ba = 0.1 Pa
     D["P_Mbar"] = units("Mbar", 1.0e-12 * n*m*c*c ); // Ba = 10^-12Mbar
 //-----
     // Electric field - mcwp/e
     D["Efield"]     = units("mcwp/e",1.0);
     D["Efield_cgs"] = units("statV/cm",       m*c*wp/e);
     D["Efield_si"]  = units("V/m", c*1.0e-6 * m*c*wp/e);  // statV/m = 10^-6*c * V/m
     D["Ex"]     = units("mcwp/e",1.0);
     D["Ex_cgs"] = units("statV/cm",       m*c*wp/e);
     D["Ex_si"]  = units("V/m", c*1.0e-6 * m*c*wp/e);  // statV/m = 10^-6*c * V/m
     D["Ey"]     = units("mcwp/e",1.0);
     D["Ey_cgs"] = units("statV/cm",       m*c*wp/e);
     D["Ey_si"]  = units("V/m", c*1.0e-6 * m*c*wp/e);  // statV/m = 10^-6*c * V/m
     D["Ez"]     = units("mcwp/e",1.0);
     D["Ez_cgs"] = units("statV/cm",       m*c*wp/e);
     D["Ez_si"]  = units("V/m", c*1.0e-6 * m*c*wp/e);  // statV/m = 10^-6*c * V/m
     // Magnetic field - mcwp/e
     D["Bfield"]     = units("mcwp/e",1.0);
     D["Bfield_cgs"] = units("Gauss",          m*c*wp/e);
     D["Bfield_si"]  = units("Tesla", 1.0e-4 * m*c*wp/e);  // Gauss = 10^-4 Tesla
     D["Bx"]     = units("mcwp/e",1.0);
     D["Bx_cgs"] = units("Gauss",          m*c*wp/e);
     D["Bx_si"]  = units("Tesla", 1.0e-4 * m*c*wp/e);  // Gauss = 10^-4 Tesla
     D["By"]     = units("mcwp/e",1.0);
     D["By_cgs"] = units("Gauss",          m*c*wp/e);
     D["By_si"]  = units("Tesla", 1.0e-4 * m*c*wp/e);  // Gauss = 10^-4 Tesla
     D["Bz"]     = units("mcwp/e",1.0);
     D["Bz_cgs"] = units("Gauss",          m*c*wp/e);
     D["Bz_si"]  = units("Tesla", 1.0e-4 * m*c*wp/e);  // Gauss = 10^-4 Tesla
     // force - mcwp
     D["Force"]     = units("mcwp",1.0);
     D["Force_cgs"] = units("dyne",       m*c*wp);
     D["Force_si"]  = units("N", 1.0e-5 * m*c*wp ); // dyne = 10^-5 N
 }
Member Function Documentation
Label() [1/2]
string Formulary::Label (string key) inline
Definition at line 76 of file formulary.h.
Referenced by Export_Files::Xport::Xport().
 { return D[key].label; }
Label() [2/2]
string Formulary::Label (string key1, string key2) inline
Definition at line 77 of file formulary.h.
 { return D[key1+"_"+key2].label; }
LOGee() [1/2]
double Formulary::LOGee (double ne, double Te)
Definition at line 226 of file formulary.cpp.
References units::d, nmin, and Units().
Referenced by self_f00_implicit_step::getleftside(), LOGee(), interspecies_flm_implicit_step::reset_coeff(), self_flm_implicit_step::reset_coeff(), startmessages(), self_f00_implicit_step::takestep(), self_f00_explicit_step::takestep(), Tau_e(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
{
 //   ne =  density/np, Te = energy/mc^2
 //   Note: we assume nonrelativistic distribution functions
     if (ne < nmin) return 2.0;
     // Te /= (3.0*ne);
     Te *= Units("Energy","eV").d; // Temperature in eV
     ne *= Units("Density","cgs").d;
     Te = log(Te);
     ne = log(ne);
     return max(2.0,23.5 - 0.5*ne + 1.25*Te - sqrt(0.00001+0.0625*(Te-2.0)*(Te-2.0)));
 }
LOGee() [2/2]
double Formulary::LOGee (double ne, string un, double Te, string uT)
Definition at line 241 of file formulary.cpp.
References units::d, LOGee(), and Units().
{
 //   where "un" are the units of ne, and uT of Te
     Te /= Units("Energy",uT).d;
     ne /= Units("Density",un).d;
     return LOGee(ne,Te);
 }
LOGei() [1/2]
double Formulary::LOGei (double ne, double Te, double Z)
Definition at line 249 of file formulary.cpp.
References units::d, nmin, and Units().
Referenced by self_f00_implicit_step::getleftside(), IB_f00::Getslope(), LOGei(), interspecies_flm_implicit_step::reset_coeff(), self_flm_implicit_step::reset_coeff(), startmessages(), self_f00_implicit_step::takestep(), Tau_i(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
{
 //   ne =  density/np, Te = energy/mc^2
 //   Note: we assume nonrelativistic distribution functions
     if (ne < nmin) return 2.0;
     Te *= Units("Energy","eV").d; // Temperature in eV
     ne *= Units("Density","cgs").d;
     if ( Te > 10.0*Z*Z ) {
         return max(2.0, 24.0 - 0.5*log(ne) + log(Te));
     }
     return max(2.0, 23.0 - 0.5*log(ne) + 1.5*log(Te) - log(Z));
 }
LOGei() [2/2]
double Formulary::LOGei (double ne, string un, double Te, string uT, double Z)
Definition at line 263 of file formulary.cpp.
References units::d, LOGei(), and Units().
{
 //   where "un" are the units of ne, and uT of Te
     Te /= Units("Energy",uT).d; // Temperature in eV
     ne /= Units("Density",un).d;
     return LOGei(ne,Te,Z);
 }
LOGii()
double Formulary::LOGii (double m1, double Z1, double n1, double T1, double m2, double Z2, double n2, double T2)
Definition at line 271 of file formulary.cpp.
References units::d, nmin, and Units().
Referenced by interspecies_f00_explicit_step::takestep().
{
 //   ne =  density/np, Te = energy/mc^2
 //   Note: we assume nonrelativistic distribution functions
     double mp=1;
     if (n1 < nmin || n2 < nmin) return 2.0;
     T1 *= Units("Energy","eV").d; // Temperature in eV
     T2 *= Units("Energy","eV").d; // Temperature in eV
     n1 *= Units("Density","cgs").d;
     n2 *= Units("Density","cgs").d;
     return max(2.0, 23.0 - log(Z1*Z2*(m1/mp+m2/mp)/(m1/mp*T2+m2/mp*T1)*sqrt(n1*Z1*Z1/T1+n2*Z2*Z2/T2)));
 }
MFP() [1/2]
double Formulary::MFP (double ne, double Te)
Definition at line 318 of file formulary.cpp.
References Tau_e(), and vth().
Referenced by MFP().
{
     return vth(Te)*Tau_e(ne,Te);
 }
MFP() [2/2]
double Formulary::MFP (double ne, string un, double Te, string uT)
Definition at line 321 of file formulary.cpp.
References units::d, MFP(), and Units().
{
     Te /= Units("Energy",uT).d;
     ne /= Units("Density",un).d;
     return MFP(ne,Te);
 }
Tau_e() [1/2]
double Formulary::Tau_e (double ne, double Te)
Units("Time","cgs").d;
Definition at line 306 of file formulary.cpp.
References units::d, LOGee(), and Units().
Referenced by MFP(), startmessages(), and Tau_e().
{
     return 3.44e+5*(pow(sqrt(Te*Units("Energy","eV").d),3)/
             (ne*Units("Density","cgs").d*LOGee(ne,Te))) ; //
 }
Tau_e() [2/2]
double Formulary::Tau_e (double ne, string un, double Te, string uT)
Definition at line 311 of file formulary.cpp.
References units::d, Tau_e(), and Units().
{
     Te /= Units("Energy",uT).d;
     ne /= Units("Density",un).d;
     return Tau_e(ne,Te);
 }
Tau_i()
double Formulary::Tau_i (double ne, double Te, double Zeta)
Definition at line 300 of file formulary.cpp.
References units::d, LOGei(), me_over_mp, and Units().
{
     return 2.09e+7*(pow(sqrt(Te/Zeta*Units("Energy","eV").d),3)/
             (ne*Units("Density","cgs").d*LOGei(ne,Te,Zeta))) /sqrt(me_over_mp);
 }
Uconv() [1/2]
double Formulary::Uconv (string key) inline
Definition at line 78 of file formulary.h.
Referenced by Export_Files::Xport::Xport().
 { return D[key].d; }
Uconv() [2/2]
double Formulary::Uconv (string key1, string key2) inline
Definition at line 79 of file formulary.h.
 { return D[key1+"_"+key2].d; }
Units() [1/2]
units Formulary::Units (string key) inline
Definition at line 74 of file formulary.h.
Referenced by LOGee(), LOGei(), LOGii(), MFP(), Tau_e(), Tau_i(), and vth().
 { return D[key]; }
Units() [2/2]
units Formulary::Units (string key1, string key2) inline
Definition at line 75 of file formulary.h.
 { return D[key1+"_"+key2]; }
vth() [1/2]
double Formulary::vth (double Te)
Definition at line 291 of file formulary.cpp.
References c, units::d, and Units().
Referenced by MFP(), and vth().
{
     Te *= Units("Energy","eV").d;
     return sqrt(Te)*4.19e+7/c;
 }
vth() [2/2]
double Formulary::vth (double Te, string uT)
Definition at line 295 of file formulary.cpp.
References units::d, Units(), and vth().
{
     Te /= Units("Energy", uT).d;
     return vth(Te);
 }
Field Documentation
B0
double Formulary::B0
Definition at line 102 of file formulary.h.
Referenced by startmessages().
c
constexpr double Formulary::c = 2.99792458*1.0e+10 static
Definition at line 119 of file formulary.h.
Referenced by Formulary(), and vth().
cL
constexpr double Formulary::cL = 299792458 static
Definition at line 112 of file formulary.h.
Referenced by startmessages().
D
map<string,units> Formulary::D private
Definition at line 124 of file formulary.h.
Referenced by Formulary().
e
constexpr double Formulary::e = 4.80320425*1.0e-10 static
Definition at line 120 of file formulary.h.
Referenced by Formulary().
eps0
constexpr double Formulary::eps0 =8.854187817e-12 static
Definition at line 113 of file formulary.h.
keVnorm
constexpr double Formulary::keVnorm = 510.9989461 static
Definition at line 117 of file formulary.h.
m
constexpr double Formulary::m = 9.10938215*1.0e-28 static
Definition at line 121 of file formulary.h.
Referenced by Formulary().
me
constexpr double Formulary::me = 9.10938356e-31 static
Definition at line 115 of file formulary.h.
me_over_mp
constexpr double Formulary::me_over_mp = 0.000544617024 static
Definition at line 116 of file formulary.h.
Referenced by Tau_i().
n
double Formulary::n
Definition at line 99 of file formulary.h.
Referenced by Formulary(), and startmessages().
nmin
constexpr double Formulary::nmin = 1.0e-8 static private
Definition at line 126 of file formulary.h.
Referenced by LOGee(), LOGei(), and LOGii().
pi
constexpr double Formulary::pi =3.141592653589793238 static
Definition at line 110 of file formulary.h.
Referenced by startmessages().
qe
constexpr double Formulary::qe = -1.60217662e-19 static
Definition at line 114 of file formulary.h.
skindepth
double Formulary::skindepth
Definition at line 101 of file formulary.h.
Referenced by startmessages().
T0
double Formulary::T0
Definition at line 103 of file formulary.h.
Referenced by startmessages().
wp
double Formulary::wp
Definition at line 100 of file formulary.h.
Referenced by Formulary(), and startmessages().
Zeta
double Formulary::Zeta
Definition at line 104 of file formulary.h.
Referenced by self_f00_implicit_step::getleftside(), IB_f00::Getslope(), interspecies_flm_implicit_step::reset_coeff(), self_flm_implicit_step::reset_coeff(), startmessages(), self_f00_implicit_step::takestep(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/formulary.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/formulary.cpp