OSHUN: VlasovFunctor1D_spatialpush Class Reference
VlasovFunctor1D_spatialpush Class Reference
#include <functors.h>
Public Member Functions
VlasovFunctor1D_spatialpush (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_spatialpush ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D > SA
Detailed Description
Definition at line 47 of file functors.h.
Constructor & Destructor Documentation
VlasovFunctor1D_spatialpush()
VlasovFunctor1D_spatialpush::VlasovFunctor1D_spatialpush (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 166 of file functors.cpp.
References VlasovFunctor1D_explicitE::SA.
{
 //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         SA.push_back( Spatial_Advection_1D(Nl[s], Nm[s], 0.0, pmax[s], Np[s], xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_spatialpush()
VlasovFunctor1D_spatialpush::~VlasovFunctor1D_spatialpush () inline
Definition at line 54 of file functors.h.
References VlasovFunctor1D_explicitE::operator()().
 { };
Member Function Documentation
operator()() [1/2]
void VlasovFunctor1D_spatialpush::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 181 of file functors.cpp.
References State1D::DF(), DistFunc1D::Filterp(), DistFunc1D::l0(), DistFunc1D::m0(), VlasovFunctor1D_explicitE::SA, and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         if (Yin.DF(s).l0() == 1) {
             SA[s].f1only(Yin.DF(s),Yslope.DF(s));
         }
         else if (Yin.DF(s).m0() == 0) {
             SA[s].es1d(Yin.DF(s),Yslope.DF(s));
         }
         else {
             SA[s](Yin.DF(s),Yslope.DF(s));
         }
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/2]
void VlasovFunctor1D_spatialpush::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 210 of file functors.cpp.
 {}
Field Documentation
SA
vector<Spatial_Advection_1D> VlasovFunctor1D_spatialpush::SA private
Definition at line 61 of file functors.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/functors.cpp