OSHUN: Fluid_Equation_1D Class Reference
Fluid_Equation_1D Class Reference
#include <fluid.h>
Public Member Functions
Fluid_Equation_1D (double xmin, double xmax, size_t Nx)
Constructors/Destructors.
void density (const Hydro1D &Hin, Hydro1D &Hslope)
Momentum (and Energy and Density?) Update.
void chargefraction (const Hydro1D &Hin, Hydro1D &Hslope)
void velocity (const State1D &Yin, Hydro1D &Hslope, valarray< double > &electrondensity, valarray< double > &electronpressure, Array2D< double > &electroncurrent)
void updateE (Hydro1D &HYDRO, EMF1D &EMF)
Electric Field Update.
Private Attributes
double idx
Evaluate Quantities from Distribution Functions.
size_t szx
size_t Nbc
valarray< double > dummy
Detailed Description
Definition at line 5 of file fluid.h.
Constructor & Destructor Documentation
Fluid_Equation_1D()
Fluid_Equation_1D::Fluid_Equation_1D (double xmin, double xmax, size_t Nx)
Constructors/Destructors.
Definition at line 65 of file fluid.cpp.
References Input::Input_List::BoundaryCells, Input::List(), and Nbc.
   : idx(Nx/(xmax-xmin)), szx(Nx), dummy(0.0,Nx)
     {
         Nbc = Input::List().BoundaryCells;
     }
Member Function Documentation
chargefraction()
void Fluid_Equation_1D::chargefraction (const Hydro1D & Hin, Hydro1D & Hslope)
Definition at line 93 of file fluid.cpp.
References Hydro1D::densityarray(), df_4thorder(), idx, szx, and Hydro1D::Z().
Referenced by Hydro_Functor::operator()().
{
     valarray<double> d_nZx(Hin.densityarray());
     for (size_t ix(0);ix<szx;++ix)
         d_nZx[ix] = d_nZx[ix] * Hin.Z(ix);
     d_nZx = df_4thorder(d_nZx);
     Hslope.Z(0)       -= idx * d_nZx[0];
     for (size_t ix(1);ix<szx-1;++ix)
     {
         Hslope.Z(ix)  -= idx * d_nZx[ix];
     }
     Hslope.Z(szx - 1) -= idx *  d_nZx[szx-1];
 }
density()
void Fluid_Equation_1D::density (const Hydro1D & Hin, Hydro1D & Hslope)
Momentum (and Energy and Density?) Update.
Definition at line 74 of file fluid.cpp.
References Hydro1D::density(), Hydro1D::densityarray(), df_4thorder(), idx, szx, and Hydro1D::vx().
Referenced by Hydro_Functor::operator()().
{
     valarray<double> d_nvx(Hin.densityarray());
     for (size_t ix(0);ix<szx;++ix)
         d_nvx[ix] = d_nvx[ix] * Hin.vx(ix);
     d_nvx = df_4thorder(d_nvx);
     Hslope.density(0)       -= idx * d_nvx[0];
     for (size_t ix(1);ix<szx-1;++ix)
     {
         Hslope.density(ix)  -= idx * d_nvx[ix];
     }
     Hslope.density(szx - 1) -= idx * d_nvx[szx-1];
 }
updateE()
void Fluid_Equation_1D::updateE (Hydro1D & HYDRO, EMF1D & EMF)
Electric Field Update.
Definition at line 215 of file fluid.cpp.
References szx.
Referenced by Hydro_Functor::operator()().
{
     for (size_t ix(0);ix<szx;++ix){
         // EMF.Ex()(ix) -= 0.0;//dCdt[ix]; //+0.5*dC2xdx[ix]+(hydrocharge*electrondensity[ix]-hydrodensity[ix]); // Needs JxB in 2D
         // EMF.Ey()(ix) += -1.0*HYDRO.Z(ix)*HYDRO.charge()*HYDRO.vx(ix)*EMF.Bz()(ix);//+jx[ix]*Bz(ix)-jz[ix]*Bx(ix);
         // EMF.Ez()(ix) += HYDRO.Z(ix)*HYDRO.charge()*HYDRO.vx(ix)*EMF.By()(ix);//-jx[ix]*By(ix)-jy[ix]*Bx(ix);
         // EMF.Ex()(ix) += HYDRO.Z(ix)*HYDRO.charge()*HYDRO.vx(ix)*HYDRO.density(ix);
         // EMF.Ey()(ix) += HYDRO.Z(ix)*HYDRO.charge()*HYDRO.vy(ix)*HYDRO.density(ix);
         // EMF.Ez()(ix) += HYDRO.Z(ix)*HYDRO.charge()*HYDRO.vz(ix)*HYDRO.density(ix);
     }
 }
velocity()
void Fluid_Equation_1D::velocity (const State1D & Yin, Hydro1D & Hslope, valarray< double > & electrondensity, valarray< double > & electronpressure, Array2D< double > & electroncurrent)
Momentum equation - y direction
Momentum equation - z direction
Definition at line 112 of file fluid.cpp.
References EMF1D::Bx(), EMF1D::By(), EMF1D::Bz(), Hydro1D::charge(), Hydro1D::density(), Hydro1D::densityarray(), df_4thorder(), State1D::EMF(), EMF1D::Ex(), EMF1D::Ey(), EMF1D::Ez(), State1D::HYDRO(), idx, Hydro1D::mass(), szx, Hydro1D::temperature(), Hydro1D::vx(), Hydro1D::vxarray(), Hydro1D::vy(), Hydro1D::vz(), and Hydro1D::Z().
Referenced by Hydro_Functor::operator()().
{
     double Zeovermi = Yin.HYDRO().charge()/Yin.HYDRO().mass();
     valarray<double> eventuallynetPovern(Yin.HYDRO().densityarray()), d_vx(Yin.HYDRO().vxarray()), d_vy(Yin.HYDRO().vxarray()), d_vz(Yin.HYDRO().vxarray());
     valarray<double> eventuallychargeseparation(electronpressure);
     Array2D<double> netcurrent(3,szx);
     for (size_t ix(0);ix<szx;++ix){
         eventuallynetPovern[ix] = eventuallynetPovern[ix] * Yin.HYDRO().temperature(ix);
     }
     eventuallynetPovern = df_4thorder(eventuallynetPovern);
     eventuallychargeseparation = df_4thorder(eventuallychargeseparation);
     for (size_t ix(0);ix<szx;++ix){
         // Net pressure
         eventuallynetPovern[ix] = eventuallynetPovern[ix] / Yin.HYDRO().density(ix) + eventuallychargeseparation[ix] / electrondensity[ix];
         // Net current
         netcurrent(0,ix) = Yin.HYDRO().Z(ix)*Yin.HYDRO().charge()*Yin.HYDRO().density(ix)*Yin.HYDRO().vx(ix) - electroncurrent(0,ix);
         netcurrent(1,ix) = Yin.HYDRO().Z(ix)*Yin.HYDRO().charge()*Yin.HYDRO().density(ix)*Yin.HYDRO().vy(ix) - electroncurrent(1,ix);
         netcurrent(2,ix) = Yin.HYDRO().Z(ix)*Yin.HYDRO().charge()*Yin.HYDRO().density(ix)*Yin.HYDRO().vz(ix) - electroncurrent(2,ix);
         // Net charge separation
         eventuallychargeseparation[ix] = Yin.HYDRO().Z(ix)*Yin.HYDRO().charge()*Yin.HYDRO().density(ix)-electrondensity[ix];
     }
     d_vx = df_4thorder(d_vx);
     d_vy = df_4thorder(d_vy);
     d_vz = df_4thorder(d_vz);
     Hslope.vx(0)  += - idx * eventuallynetPovern[0] / Yin.HYDRO().mass()
                                     +   Zeovermi * eventuallychargeseparation[0] * (Yin.EMF().Ex()(0).real()
                                     +   netcurrent(1,0) * Yin.EMF().Bz()(0).real()
                                     -   netcurrent(2,0) * Yin.EMF().By()(0).real()); //+ Rie/ni;
     Hslope.vx(0) -= netcurrent(0,0) * (idx * d_vx[0]);
     for (size_t ix(1);ix<szx-1;++ix)
     {
         Hslope.vx(ix)  += -0.5 * idx * eventuallynetPovern[ix] / Yin.HYDRO().mass()
                                     +   Zeovermi * eventuallychargeseparation[ix] * (Yin.EMF().Ex()(ix).real()
                                     +   netcurrent(1,ix) * Yin.EMF().Bz()(ix).real()
                                     -   netcurrent(2,ix) * Yin.EMF().By()(ix).real()); //+ Rie/ni;
         Hslope.vx(ix) -= netcurrent(0,ix) * (idx * d_vx[ix]);
     }
     Hslope.vx(szx - 1) += -idx * eventuallynetPovern[szx - 1] / Yin.HYDRO().mass()
                                     +   Zeovermi * eventuallychargeseparation[szx - 1] * (Yin.EMF().Ex()(szx - 1).real()
                                     +   netcurrent(1,szx - 1) * Yin.EMF().Bz()(szx - 1).real()
                                     -   netcurrent(2,szx - 1) * Yin.EMF().By()(szx - 1).real()); //+ Rie/ni
     Hslope.vx(szx - 1) -= netcurrent(0,szx - 1) * (idx * d_vx[szx - 1]);
     Hslope.vy(0) +=  Zeovermi *
                             (   netcurrent(2,0) * Yin.EMF().Bx()(0).real()
                             -   netcurrent(0,0) * Yin.EMF().Bz()(0).real()
                             +   eventuallychargeseparation[0] * Yin.EMF().Ey()(0).real());
     for (size_t ix(1);ix<szx-1;++ix)
     {
         Hslope.vy(ix) +=  Zeovermi *
                             (   netcurrent(2,ix) * Yin.EMF().Bx()(ix).real()
                             -   netcurrent(0,ix) * Yin.EMF().Bz()(ix).real()
                             +   eventuallychargeseparation[ix] * Yin.EMF().Ey()(ix).real());
     }
     Hslope.vy(szx - 1) +=  Zeovermi *
                             (   netcurrent(2,szx - 1) * Yin.EMF().Bx()(szx - 1).real()
                             -   netcurrent(0,szx - 1) * Yin.EMF().Bz()(szx - 1).real()
                             +   eventuallychargeseparation[szx - 1] * Yin.EMF().Ey()(szx - 1).real());
     Hslope.vz(0) +=  Zeovermi *
                             (   netcurrent(0,0) * Yin.EMF().By()(0).real()
                             -   netcurrent(1,0) * Yin.EMF().Bx()(0).real()
                             +   eventuallychargeseparation[0] * Yin.EMF().Ez()(0).real());
     for (size_t ix(1);ix<szx-1;++ix)
     {
         Hslope.vz(ix) +=  Zeovermi *
                             (   netcurrent(0,ix) * Yin.EMF().By()(ix).real()
                             -   netcurrent(1,ix) * Yin.EMF().Bx()(ix).real()
                             +   eventuallychargeseparation[ix] * Yin.EMF().Ez()(ix).real());
     }
     Hslope.vz(szx - 1) +=  Zeovermi *
                             (   netcurrent(0,szx - 1) * Yin.EMF().By()(szx - 1).real()
                             -   netcurrent(1,szx - 1) * Yin.EMF().Bx()(szx - 1).real()
                             +   eventuallychargeseparation[szx - 1] * Yin.EMF().Ez()(szx - 1).real());
 }
Field Documentation
dummy
valarray<double> Fluid_Equation_1D::dummy private
Definition at line 34 of file fluid.h.
idx
double Fluid_Equation_1D::idx private
Evaluate Quantities from Distribution Functions.
Definition at line 31 of file fluid.h.
Referenced by chargefraction(), density(), and velocity().
Nbc
size_t Fluid_Equation_1D::Nbc private
Definition at line 32 of file fluid.h.
Referenced by Fluid_Equation_1D().
szx
size_t Fluid_Equation_1D::szx private
Definition at line 32 of file fluid.h.
Referenced by chargefraction(), density(), updateE(), and velocity().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/fluid.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/fluid.cpp