OSHUN: Array3D< T > Class Template Reference
Array3D< T > Class Template Reference
#include <lib-array.h>
Public Member Functions
Array3D (size_t x, size_t y, size_t z)
Array3D (const Array3D &other)
~Array3D ()
size_t dim () const
size_t dim1 () const
size_t dim2 () const
size_t dim3 () const
valarray< T > & array () const
T & operator() (size_t i, size_t j, size_t k)
T operator() (size_t i, size_t j, size_t k) const
T & operator() (size_t i)
T operator() (size_t i) const
GSlice_iter< T > d1c (size_t b, size_t e)
GSlice_iter< T > d2c (size_t b, size_t e)
GSlice_iter< T > d3c (size_t b, size_t e)
GSlice_iter< T > SubArray3D (size_t st, size_t nx, size_t ny, size_t nz)
CGSlice_iter< T > d1c (size_t b, size_t e) const
CGSlice_iter< T > d2c (size_t b, size_t e) const
CGSlice_iter< T > d3c (size_t b, size_t e) const
CGSlice_iter< T > SubArray3D (size_t st, size_t nx, size_t ny, size_t nz) const
Array3D & operator= (const T &d)
Array3D & operator= (const Array3D &other)
Array3D & operator*= (const T &d)
Array3D & operator*= (const Array3D &vmulti)
Array3D & operator+= (const T &d)
Array3D & operator+= (const Array3D &vadd)
Array3D & operator-= (const T &d)
Array3D & operator-= (const Array3D &vmin)
Array3D & multid1 (const valarray< T > &vmulti)
Array3D & multid2 (const valarray< T > &vmulti)
Array3D & multid3 (const valarray< T > &vmulti)
Array3D & multid2d3 (const Array2D< T > &vd2d3)
Array3D & Dd1 ()
Array3D & Dd2 ()
Array3D & Dd3 ()
Array3D & Filterd1 (size_t N)
Private Attributes
valarray< T > * v
size_t d1
size_t d2
size_t d3
size_t d1d2
Detailed Description
template<class T>
class Array3D< T >
Definition at line 1036 of file lib-array.h.
Constructor & Destructor Documentation
Array3D() [1/2]
template<class T > Array3D< T >::Array3D (size_t x, size_t y, size_t z)
Definition at line 1112 of file lib-array.h.
Referenced by Array3D< complex< double > >::array().
                                       : d1(x), d2(y), d3(z) {
     v = new valarray<T>(d1*d2*d3);
     d1d2 = d1*d2;
 }
Array3D() [2/2]
template<class T > Array3D< T >::Array3D (const Array3D< T > & other)
Definition at line 1117 of file lib-array.h.
{
     d1  = other.dim1();
     d2  = other.dim2();
     d3  = other.dim3();
     d1d2 = d1*d2;
     v = new valarray<T>(d1*d2*d3);
     (*v) = other.array();
 }
~Array3D()
template<class T > Array3D< T >::~Array3D ()
Definition at line 1126 of file lib-array.h.
{
     delete v;
 }
Member Function Documentation
array()
template<class T> valarray<T>& Array3D< T >::array () const inline
Definition at line 1056 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), Export_Files::Xport::Export_h5(), Array4D< T >::multid2d3d4(), Array4D_cmplx< T >::multid2d3d4(), Array3D< complex< double > >::operator*=(), Array3D_cmplx< T >::operator*=(), Array3D< complex< double > >::operator+=(), Array3D_cmplx< T >::operator+=(), Array3D< complex< double > >::operator-=(), Array3D_cmplx< T >::operator-=(), Array3D< complex< double > >::operator=(), and Array3D_cmplx< T >::operator=().
 {return *v;};
d1c() [1/2]
template<class T > GSlice_iter< T > Array3D< T >::d1c (size_t b, size_t e) inline
Definition at line 1162 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     valarray<size_t> sz(3), str(3);
     str[2] = d1; str[1] = d1d2; str[0] = 1;
     sz[2]  = d2; sz[1]  = d3;    sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(b,sz,str));
 }
d1c() [2/2]
template<class T > CGSlice_iter< T > Array3D< T >::d1c (size_t b, size_t e) const inline
Definition at line 1170 of file lib-array.h.
{
     valarray<size_t> sz(3), str(3);
     str[2] = d1; str[1] = d1d2; str[0] = 1;
     sz[2]  = d2; sz[1]  = d3;    sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(b,sz,str));
 }
d2c() [1/2]
template<class T > GSlice_iter< T > Array3D< T >::d2c (size_t b, size_t e) inline
Definition at line 1178 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;  str[1] = d1d2;  str[0] = d1;
     sz[2]  = d1; sz[1]  = d3;    sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(d1*b,sz,str));
 }
d2c() [2/2]
template<class T > CGSlice_iter< T > Array3D< T >::d2c (size_t b, size_t e) const inline
Definition at line 1186 of file lib-array.h.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;  str[1] = d1d2;  str[0] = d1;
     sz[2]  = d1; sz[1]  = d3;    sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(d1*b,sz,str));
 }
d3c() [1/2]
template<class T > GSlice_iter< T > Array3D< T >::d3c (size_t b, size_t e) inline
Definition at line 1194 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1; str[0] = d1d2;
     sz[1]  = d1d2; sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(d1d2*b,sz,str));
 }
d3c() [2/2]
template<class T > CGSlice_iter< T > Array3D< T >::d3c (size_t b, size_t e) const inline
Definition at line 1202 of file lib-array.h.
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1; str[0] = d1d2;
     sz[1]  = d1d2; sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(d1d2*b,sz,str));
 }
Dd1()
template<class T > Array3D< T > & Array3D< T >::Dd1 ()
Definition at line 1325 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     for(long i(0); i< d1*d2*d3-2; ++i) {
         (*v)[i] -= (*v)[i+2];
     }
     for(long i(d1*d2*d3-3); i>-1; --i) {
         (*v)[i+1] = (*v)[i];
     }
     return *this;
 }
Dd2()
template<class T > Array3D< T > & Array3D< T >::Dd2 ()
Definition at line 1336 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     long twod1 = 2*d1;
     for(long i(0); i< d1*d2*d3-twod1; ++i) {
         (*v)[i] -= (*v)[i+twod1];
     }
     for(long i(d1*d2*d3-twod1-1); i>-1; --i) {
         (*v)[i+d1] = (*v)[i];
     }
     return *this;
 }
Dd3()
template<class T > Array3D< T > & Array3D< T >::Dd3 ()
Definition at line 1348 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     long twod1d2 = 2*d1d2;
     for(long i(0); i< d1*d2*d3-twod1d2; ++i) {
         (*v)[i] -= (*v)[i+twod1d2];
     }
     for(long i(d1*d2*d3-twod1d2-1); i>-1; --i) {
         (*v)[i+d1d2] = (*v)[i];
     }
     return *this;
 }
dim()
template<class T> size_t Array3D< T >::dim () const inline
Definition at line 1052 of file lib-array.h.
 {return d1*d2*d3;}
dim1()
template<class T> size_t Array3D< T >::dim1 () const inline
Definition at line 1053 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), Export_Files::Xport::Export_h5(), and Array3D< complex< double > >::SubArray3D().
 {return d1;}
dim2()
template<class T> size_t Array3D< T >::dim2 () const inline
Definition at line 1054 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), and Export_Files::Xport::Export_h5().
 {return d2;}
dim3()
template<class T> size_t Array3D< T >::dim3 () const inline
Definition at line 1055 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), and Export_Files::Xport::Export_h5().
 {return d3;}
Filterd1()
template<class T > Array3D< T > & Array3D< T >::Filterd1 (size_t N)
Definition at line 1361 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     for (size_t j(0); j < d2*d3; ++j ){
         for (size_t i(j*d1); i< j*d1+N; ++i ){
             (*v)[i] = 0.0;
         }
     }
     return *this;
 }
multid1()
template<class T> Array3D< T > & Array3D< T >::multid1 (const valarray< T > & vmulti)
Definition at line 1278 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     for (size_t j(0); j< d1*d2*d3; j+=d1 ){
         for (size_t i(0); i< d1; ++i ){
             (*v)[i+j] *= vmulti[i];
         }
     }
     return *this;
 }
multid2()
template<class T> Array3D< T > & Array3D< T >::multid2 (const valarray< T > & vmulti)
Definition at line 1288 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     for (size_t k(0); k< d3*d2*d1; k+=d1*d2 ) {
         for (size_t j(0); j< d2; ++j ) {
             for (size_t i(j*d1); i< (j+1)*d1; ++i ){
                 (*v)[i+k] *= vmulti[j];
             }
         }
     }
     return *this;
 }
multid2d3()
template<class T> Array3D< T > & Array3D< T >::multid2d3 (const Array2D< T > & vd2d3)
Definition at line 1311 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     for (size_t j(0); j < d2*d3; ++j ){
         for (size_t i(j*d1); i< (j+1)*d1; ++i ){
             (*v)[i] *= vd2d3.array()[j];
         }
     }
     return *this;
 }
multid3()
template<class T> Array3D< T > & Array3D< T >::multid3 (const valarray< T > & vmulti)
Definition at line 1300 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     for (size_t k(0); k< d3; ++k) {
         for (size_t i(k*d1*d2); i< (k+1)*d1*d2; ++i ){
             (*v)[i] *= vmulti[k];
         }
     }
     return *this;
 }
operator()() [1/4]
template<class T > T & Array3D< T >::operator() (size_t i, size_t j, size_t k) inline
Definition at line 1136 of file lib-array.h.
{
     return (*v)[i+j*d1+k*d1d2];
 }
operator()() [2/4]
template<class T > T Array3D< T >::operator() (size_t i, size_t j, size_t k) const inline
Definition at line 1142 of file lib-array.h.
{
     return (*v)[i+j*d1+k*d1d2];
 }
operator()() [3/4]
template<class T > T & Array3D< T >::operator() (size_t i) inline
Definition at line 1148 of file lib-array.h.
{
     return (*v)[i];
 }
operator()() [4/4]
template<class T > T Array3D< T >::operator() (size_t i) const inline
Definition at line 1154 of file lib-array.h.
{
     return (*v)[i];
 }
operator*=() [1/2]
template<class T> Array3D< T > & Array3D< T >::operator*= (const T & d)
Definition at line 1246 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     (*v) *=d;
     return *this;
 }
operator*=() [2/2]
template<class T> Array3D< T > & Array3D< T >::operator*= (const Array3D< T > & vmulti)
Definition at line 1250 of file lib-array.h.
{
     (*v) *= vmulti.array();
     return *this;
 }
operator+=() [1/2]
template<class T> Array3D< T > & Array3D< T >::operator+= (const T & d)
Definition at line 1256 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     (*v) +=d;
     return *this;
 }
operator+=() [2/2]
template<class T> Array3D< T > & Array3D< T >::operator+= (const Array3D< T > & vadd)
Definition at line 1260 of file lib-array.h.
{
     (*v) += vadd.array();
     return *this;
 }
operator-=() [1/2]
template<class T> Array3D< T > & Array3D< T >::operator-= (const T & d)
Definition at line 1266 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     (*v) -=d;
     return *this;
 }
operator-=() [2/2]
template<class T> Array3D< T > & Array3D< T >::operator-= (const Array3D< T > & vmin)
Definition at line 1270 of file lib-array.h.
{
     (*v) -= vmin.array();
     return *this;
 }
operator=() [1/2]
template<class T> Array3D< T > & Array3D< T >::operator= (const T & d)
Definition at line 1233 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     (*v) = d;
     return *this;
 }
operator=() [2/2]
template<class T> Array3D< T > & Array3D< T >::operator= (const Array3D< T > & other)
Definition at line 1238 of file lib-array.h.
{
     if (this != &other) {   //self-assignment
         (*v) = other.array();
     }
     return *this;
 }
SubArray3D() [1/2]
template<class T > GSlice_iter< T > Array3D< T >::SubArray3D (size_t st, size_t nx, size_t ny, size_t nz) inline
Definition at line 1212 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array().
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;  str[1] = dim1(); str[0] = d1d2;
     sz[2]  = nx;  sz[1] = ny;      sz[0] = nz;
     return GSlice_iter<T>(v,gslice(st,sz,str));
 }
SubArray3D() [2/2]
template<class T > CGSlice_iter< T > Array3D< T >::SubArray3D (size_t st, size_t nx, size_t ny, size_t nz) const inline
Definition at line 1221 of file lib-array.h.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;  str[1] = dim1(); str[0] = d1d2;
     sz[2]  = nx;  sz[1] = ny;      sz[0] = nz;
     return CGSlice_iter<T>(v,gslice(st,sz,str));
 }
Field Documentation
d1
template<class T> size_t Array3D< T >::d1 private
Definition at line 1042 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), Array3D< complex< double > >::d1c(), Array3D< complex< double > >::d2c(), Array3D< complex< double > >::Dd1(), Array3D< complex< double > >::Dd2(), Array3D< complex< double > >::Dd3(), Array3D_cmplx< T >::dim1(), Array3D< complex< double > >::Filterd1(), Array3D< complex< double > >::multid1(), Array3D< complex< double > >::multid2(), Array3D< complex< double > >::multid2d3(), Array3D< complex< double > >::multid3(), and Array3D< complex< double > >::operator()().
d1d2
template<class T> size_t Array3D< T >::d1d2 private
Definition at line 1043 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), Array3D< complex< double > >::d1c(), Array3D< complex< double > >::d2c(), Array3D< complex< double > >::d3c(), Array3D< complex< double > >::Dd3(), Array3D< complex< double > >::operator()(), and Array3D< complex< double > >::SubArray3D().
d2
template<class T> size_t Array3D< T >::d2 private
Definition at line 1042 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), Array3D< complex< double > >::d1c(), Array3D< complex< double > >::Dd1(), Array3D< complex< double > >::Dd2(), Array3D< complex< double > >::Dd3(), Array3D_cmplx< T >::dim2(), Array3D< complex< double > >::Filterd1(), Array3D< complex< double > >::multid1(), Array3D< complex< double > >::multid2(), Array3D< complex< double > >::multid2d3(), and Array3D< complex< double > >::multid3().
d3
template<class T> size_t Array3D< T >::d3 private
Definition at line 1042 of file lib-array.h.
Referenced by Array3D< complex< double > >::Array3D(), Array3D< complex< double > >::d1c(), Array3D< complex< double > >::d2c(), Array3D< complex< double > >::Dd1(), Array3D< complex< double > >::Dd2(), Array3D< complex< double > >::Dd3(), Array3D_cmplx< T >::dim(), Array3D_cmplx< T >::dim3(), Array3D< complex< double > >::Filterd1(), Array3D< complex< double > >::multid1(), Array3D< complex< double > >::multid2(), Array3D< complex< double > >::multid2d3(), and Array3D< complex< double > >::multid3().
v
template<class T> valarray<T>* Array3D< T >::v private
Definition at line 1041 of file lib-array.h.
Referenced by Array3D_cmplx< T >::array(), Array3D< complex< double > >::Array3D(), Array3D< complex< double > >::d1c(), Array3D< complex< double > >::d2c(), Array3D< complex< double > >::d3c(), Array3D< complex< double > >::operator()(), Array3D< complex< double > >::SubArray3D(), and Array3D< complex< double > >::~Array3D().
The documentation for this class was generated from the following file:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/lib-array.h