OSHUN: VlasovFunctor1D_f1_implicitE_p1 Class Reference
VlasovFunctor1D_f1_implicitE_p1 Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov_f1.h>
Public Member Functions
VlasovFunctor1D_f1_implicitE_p1 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
~VlasovFunctor1D_f1_implicitE_p1 ()
void operator() (const State1D &Yin, State1D &Yslope)
void operator() (const State1D &Yin, const State1D &Y2in, State1D &Yslope)
void operator() (const State1D &Yin, State1D &Yslope, size_t dir)
Private Attributes
vector< Spatial_Advection_1D_f1 > SA
vector< Magnetic_Field_1D_f1 > BF
Detailed Description
Definition at line 166 of file vlasov_f1.h.
Constructor & Destructor Documentation
VlasovFunctor1D_f1_implicitE_p1()
VlasovFunctor1D_f1_implicitE_p1::VlasovFunctor1D_f1_implicitE_p1 (vector< size_t > Nl, vector< size_t > Nm, vector< double > pmax, vector< size_t > Np, double xmin, double xmax, size_t Nx)
Definition at line 764 of file vlasov_f1.cpp.
References Spatial_Advection_1D_f1::Spatial_Advection_1D_f1().
{
 // //--------------------------------------------------------------
     for (size_t s(0); s < Nl.size(); ++s){
         double pmin( pmax[s] / ( double(Np[s] * 2 - 1)) );
         SA.push_back( Spatial_Advection_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         // EF.push_back( Electric_Field_1D(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         // JX.push_back( Current_1D(pmin, pmax[s], Np[s], Nx) );
         // AM.push_back( Ampere_1D(xmin, xmax, Nx) );
 //        HA.push_back( Hydro_Advection_1D(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
         BF.push_back( Magnetic_Field_1D_f1(Nl[s], Nm[s], pmin, pmax[s], Np[s], xmin, xmax, Nx) );
 //        FA.push_back( Faraday_1D(xmin, xmax, Nx) );
     }
 }
~VlasovFunctor1D_f1_implicitE_p1()
VlasovFunctor1D_f1_implicitE_p1::~VlasovFunctor1D_f1_implicitE_p1 () inline
Definition at line 173 of file vlasov_f1.h.
References Spatial_Advection_1D_f1::operator()().
 { };
Member Function Documentation
operator()() [1/3]
void VlasovFunctor1D_f1_implicitE_p1::operator() (const State1D & Yin, State1D & Yslope) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 793 of file vlasov_f1.cpp.
References EMF1D::Bx(), EMF1D::By(), EMF1D::Bz(), State1D::DF(), State1D::EMF(), DistFunc1D::Filterp(), and State1D::Species().
{
 //--------------------------------------------------------------
     Yslope = 0.0;
     for (size_t s(0); s < Yin.Species(); ++s) {
         // Yslope.DF(s).checknan();std::cout << "Vlasov 1 \n";
         SA[s](Yin.DF(s),Yslope.DF(s));
         // Yslope.DF(s).checknan();std::cout << "Vlasov 2 \n";
         // Yslope.DF(s).checknan();std::cout << "Vlasov 3 \n";
         // EF[s](Yin.DF(s),Yin.EMF().Ex(),Yin.EMF().Ey(),Yin.EMF().Ez(),Yslope.DF(s));
         // JX[s](Yin.DF(s),Yslope.EMF().Ex(),Yslope.EMF().Ey(),Yslope.EMF().Ez());
         // AM[s](Yin.EMF(),Yslope.EMF());
 //       if (Input::List().hydromotion) HA[s](Yin.DF(s),Yin.HYDRO(),Yslope.DF(s));
         BF[s](Yin.DF(s),Yin.EMF().Bx(),Yin.EMF().By(),Yin.EMF().Bz(),Yslope.DF(s));
         // Yslope.DF(s).checknan();std::cout << "Vlasov 4 \n";
 //       FA[s](Yin.EMF(),Yslope.EMF());
         // Yslope.DF(s).checknan();std::cout << "Vlasov 5 \n";
         Yslope.DF(s) = Yslope.DF(s).Filterp();
     }
 }
operator()() [2/3]
void VlasovFunctor1D_f1_implicitE_p1::operator() (const State1D & Yin, const State1D & Y2in, State1D & Yslope)
Definition at line 825 of file vlasov_f1.cpp.
 {}
operator()() [3/3]
void VlasovFunctor1D_f1_implicitE_p1::operator() (const State1D & Yin, State1D & Yslope, size_t dir) virtual
Implements Algorithms::AbstFunctor< State1D >.
Definition at line 824 of file vlasov_f1.cpp.
 {}
Field Documentation
BF
vector<Magnetic_Field_1D_f1> VlasovFunctor1D_f1_implicitE_p1::BF private
Definition at line 185 of file vlasov_f1.h.
SA
vector<Spatial_Advection_1D_f1> VlasovFunctor1D_f1_implicitE_p1::SA private
Definition at line 181 of file vlasov_f1.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.cpp