OSHUN: Array3D_cmplx< T > Class Template Reference
Array3D_cmplx< T > Class Template Reference
#include <lib-array.h>
Public Member Functions
Array3D_cmplx (size_t x, size_t y, size_t z)
Array3D_cmplx (const Array3D_cmplx &other)
~Array3D_cmplx ()
size_t dim () const
size_t dim1 () const
size_t dim2 () const
size_t dim3 () const
valarray< T > & array () const
T & operator[] (size_t i)
T operator[] (size_t i) const
T & real (size_t i, size_t j, size_t k)
T real (size_t i, size_t j, size_t k) const
T & imag (size_t i, size_t j, size_t k)
T imag (size_t i, size_t j, size_t k) const
GSlice_iter< T > d1c (size_t b, size_t e)
GSlice_iter< T > d2c (size_t b, size_t e)
GSlice_iter< T > d3c (size_t b, size_t e)
GSlice_iter< T > SubArray3D (size_t st, size_t nx, size_t ny, size_t nz)
CGSlice_iter< T > d1c (size_t b, size_t e) const
CGSlice_iter< T > d2c (size_t b, size_t e) const
CGSlice_iter< T > d3c (size_t b, size_t e) const
CGSlice_iter< T > SubArray3D (size_t st, size_t nx, size_t ny, size_t nz) const
Array3D_cmplx & operator= (const T &d)
Array3D_cmplx & operator= (const complex< T > &c)
Array3D_cmplx & operator= (const Array3D< T > &other)
Array3D_cmplx & operator= (const Array3D_cmplx &other)
Array3D_cmplx & operator*= (const T &d)
Array3D_cmplx & operator*= (const complex< T > &c)
Array3D_cmplx & operator*= (const Array3D< T > &vmulti)
Array3D_cmplx & operator*= (const Array3D_cmplx &vmulti)
Array3D_cmplx & operator+= (const T &d)
Array3D_cmplx & operator+= (const complex< T > &c)
Array3D_cmplx & operator+= (const Array3D< T > &vadd)
Array3D_cmplx & operator+= (const Array3D_cmplx &vadd)
Array3D_cmplx & operator-= (const T &d)
Array3D_cmplx & operator-= (const complex< T > &c)
Array3D_cmplx & operator-= (const Array3D< T > &vmin)
Array3D_cmplx & operator-= (const Array3D_cmplx &vmin)
Array3D_cmplx & multid1 (const valarray< T > &vmulti)
Array3D_cmplx & multid1 (const valarray< complex< T > > &vmulti)
Array3D_cmplx & multid2 (const valarray< T > &vmulti)
Array3D_cmplx & multid2 (const valarray< complex< T > > &vmulti)
Array3D_cmplx & multid3 (const valarray< T > &vmulti)
Array3D_cmplx & multid3 (const valarray< complex< T > > &vmulti)
Array3D_cmplx & multid2d3 (const Array2D< T > &vd2d3)
Array3D_cmplx & multid2d3 (const Array2D_cmplx< T > &vd2d3)
Array3D_cmplx & Dd1 ()
Array3D_cmplx & Dd2 ()
Array3D_cmplx & Dd3 ()
Array3D_cmplx & Filterd1 (size_t N)
Private Attributes
valarray< T > * v
size_t d1
size_t d2
size_t d3
size_t td1
size_t td1d2
Detailed Description
template<class T>
class Array3D_cmplx< T >
Definition at line 1379 of file lib-array.h.
Constructor & Destructor Documentation
Array3D_cmplx() [1/2]
template<class T > Array3D_cmplx< T >::Array3D_cmplx (size_t x, size_t y, size_t z)
Definition at line 1469 of file lib-array.h.
References Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
                                                                              : d1(x), d2(y), d3(z) {
     v = new valarray<T>(2*d1*d2*d3);
     td1 = 2*d1;
     td1d2 = 2*d1*d2;
 }
Array3D_cmplx() [2/2]
template<class T > Array3D_cmplx< T >::Array3D_cmplx (const Array3D_cmplx< T > & other)
Definition at line 1475 of file lib-array.h.
References Array3D_cmplx< T >::array(), Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::dim1(), Array3D_cmplx< T >::dim2(), Array3D_cmplx< T >::dim3(), Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     d1  = other.dim1();
     d2  = other.dim2();
     d3  = other.dim3();
     td1 = 2*d1;
     td1d2 = 2*d1*d2;
     v = new valarray<T>(2*d1*d2*d3);
     (*v) = other.array();
 }
~Array3D_cmplx()
template<class T > Array3D_cmplx< T >::~Array3D_cmplx ()
Definition at line 1485 of file lib-array.h.
References Array3D_cmplx< T >::v.
{
     delete v;
 }
Member Function Documentation
array()
template<class T> valarray<T>& Array3D_cmplx< T >::array () const inline
Definition at line 1400 of file lib-array.h.
References Array3D< T >::d1c(), Array3D< T >::d2c(), Array3D< T >::d3c(), Array3D< T >::Dd1(), Array3D< T >::Dd2(), Array3D< T >::Dd3(), Array3D< T >::Filterd1(), Array3D< T >::multid1(), Array3D< T >::multid2(), Array3D< T >::multid2d3(), Array3D< T >::multid3(), Array3D< T >::operator*=(), Array3D< T >::operator+=(), Array3D< T >::operator-=(), Array3D< T >::operator=(), Array3D< T >::SubArray3D(), and Array3D< T >::v.
Referenced by Array3D_cmplx< T >::Array3D_cmplx(), Array4D_cmplx< T >::multid2d3d4(), Array3D_cmplx< T >::operator*=(), Array3D_cmplx< T >::operator+=(), Array3D_cmplx< T >::operator-=(), and Array3D_cmplx< T >::operator=().
 {return *v;};
d1c() [1/2]
template<class T > GSlice_iter< T > Array3D_cmplx< T >::d1c (size_t b, size_t e) inline
Definition at line 1521 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
Referenced by Array4D< T >::array().
{
     valarray<size_t> sz(4), str(4);
     str[3] = 1, str[2] = td1; str[1] = td1d2; str[0] = 2;
     sz[3]  = 2, sz[2]  = d2;  sz[1]  = d3;    sz[0]  = e-b+1;
     return GSlice_iter<T>(v,gslice(2*b,sz,str));
 }
d1c() [2/2]
template<class T > CGSlice_iter< T > Array3D_cmplx< T >::d1c (size_t b, size_t e) const inline
Definition at line 1529 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     valarray<size_t> sz(4), str(4);
     str[3] = 1, str[2] = td1; str[1] = td1d2; str[0] = 2;
     sz[3]  = 2, sz[2]  = d2;  sz[1]  = d3;    sz[0]  = e-b+1;
     return CGSlice_iter<T>(v,gslice(2*b,sz,str));
 }
d2c() [1/2]
template<class T > GSlice_iter< T > Array3D_cmplx< T >::d2c (size_t b, size_t e) inline
Definition at line 1537 of file lib-array.h.
References Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
Referenced by Array4D< T >::array().
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;  str[1] = td1d2;  str[0] = td1;
     sz[2]  = td1; sz[1]  = d3;    sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(td1*b,sz,str));
 }
d2c() [2/2]
template<class T > CGSlice_iter< T > Array3D_cmplx< T >::d2c (size_t b, size_t e) const inline
Definition at line 1545 of file lib-array.h.
References Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;  str[1] = td1d2;  str[0] = td1;
     sz[2]  = td1; sz[1]  = d3;    sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(td1*b,sz,str));
 }
d3c() [1/2]
template<class T > GSlice_iter< T > Array3D_cmplx< T >::d3c (size_t b, size_t e) inline
Definition at line 1553 of file lib-array.h.
References Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
Referenced by Array4D< T >::array().
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1; str[0] = td1d2;
     sz[1]  = td1d2; sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(td1d2*b,sz,str));
 }
d3c() [2/2]
template<class T > CGSlice_iter< T > Array3D_cmplx< T >::d3c (size_t b, size_t e) const inline
Definition at line 1561 of file lib-array.h.
References Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1; str[0] = td1d2;
     sz[1]  = td1d2; sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(td1d2*b,sz,str));
 }
Dd1()
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::Dd1 ()
Definition at line 1823 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for(long i(0); i< td1*d2*d3-4; ++i) {
         (*v)[i] -= (*v)[i+4];
     }
     for(long i(td1*d2*d3-5); i>-1; --i) {
         (*v)[i+2] = (*v)[i];
     }
     return *this;
 }
Dd2()
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::Dd2 ()
Definition at line 1834 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     long twotd1 = 2*td1;
     for(long i(0); i< td1*d2*d3-twotd1; ++i) {
         (*v)[i] -= (*v)[i+twotd1];
     }
     for(long i(td1*d2*d3-twotd1-1); i>-1; --i) {
         (*v)[i+td1] = (*v)[i];
     }
     return *this;
 }
Dd3()
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::Dd3 ()
Definition at line 1846 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, and Array3D_cmplx< T >::td1d2.
Referenced by Array4D< T >::array().
{
     long twotd1d2 = 2*td1d2;
     for(long i(0); i< long(td1*d2*d3)-twotd1d2; ++i) {
         (*v)[i] -= (*v)[i+twotd1d2];
     }
     for(long i(td1*d2*d3-twotd1d2-1); i>-1; --i) {
         (*v)[i+td1d2] = (*v)[i];
     }
     return *this;
 }
dim()
template<class T> size_t Array3D_cmplx< T >::dim () const inline
Definition at line 1396 of file lib-array.h.
References Array3D< T >::d3.
 {return d1*d2*d3;}
dim1()
template<class T> size_t Array3D_cmplx< T >::dim1 () const inline
Definition at line 1397 of file lib-array.h.
References Array3D< T >::d1.
Referenced by Array3D_cmplx< T >::Array3D_cmplx().
 {return d1;}
dim2()
template<class T> size_t Array3D_cmplx< T >::dim2 () const inline
Definition at line 1398 of file lib-array.h.
References Array3D< T >::d2.
Referenced by Array3D_cmplx< T >::Array3D_cmplx().
 {return d2;}
dim3()
template<class T> size_t Array3D_cmplx< T >::dim3 () const inline
Definition at line 1399 of file lib-array.h.
References Array3D< T >::d3.
Referenced by Array3D_cmplx< T >::Array3D_cmplx().
 {return d3;}
Filterd1()
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::Filterd1 (size_t N)
Definition at line 1859 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for (size_t j(0); j < d2*d3; ++j ){
         for (size_t i(j*td1); i< j*td1+2*N; ++i ){
             (*v)[i] = 0.0;
         }
     }
     return *this;
 }
imag() [1/2]
template<class T > T & Array3D_cmplx< T >::imag (size_t i, size_t j, size_t k) inline
Definition at line 1509 of file lib-array.h.
References Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
Referenced by Array3D_cmplx< T >::multid1(), Array3D_cmplx< T >::multid2(), and Array3D_cmplx< T >::multid3().
{
     return (*v)[2*i+1+j*td1+k*td1d2];
 }
imag() [2/2]
template<class T > T Array3D_cmplx< T >::imag (size_t i, size_t j, size_t k) const inline
Definition at line 1513 of file lib-array.h.
References Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     return (*v)[2*i+1+j*td1+k*td1d2];
 }
multid1() [1/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid1 (const valarray< T > & vmulti)
Definition at line 1718 of file lib-array.h.
References Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for (size_t j(0); j< td1*d2*d3; j+=td1 ){
         for (size_t i(0); i< d1; ++i ){
             (*v)[2*i+j]   *= vmulti[i];
             (*v)[2*i+1+j] *= vmulti[i];
         }
     }
     return *this;
 }
multid1() [2/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid1 (const valarray< complex< T > > & vmulti)
Definition at line 1729 of file lib-array.h.
References Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::imag(), Array3D_cmplx< T >::td1, and Array3D_cmplx< T >::v.
{
     for (size_t j(0); j< td1*d2*d3; j+=td1 ){
         for (size_t i(0); i< d1; ++i ){
             T vi((*v)[2*i+j]*vmulti[i].imag());
             (*v)[2*i+j]    *= vmulti[i].real();                     // v[i]   = Aa
             (*v)[2*i+j]    -= (*v)[2*i+1+j] * vmulti[i].imag();     // v[i]   = Aa - Bb
             (*v)[2*i+1+j]  *= vmulti[i].real();                     // v[i+1] = Ba
             (*v)[2*i+1+j]  += vi;                       // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
multid2() [1/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid2 (const valarray< T > & vmulti)
Definition at line 1743 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for (size_t k(0); k< d3*d2*td1; k+=td1*d2 ) {
         for (size_t j(0); j< d2; ++j ) {
             for (size_t i(j*td1); i< (j+1)*td1; ++i ){
                 (*v)[i+k] *= vmulti[j];
             }
         }
     }
     return *this;
 }
multid2() [2/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid2 (const valarray< complex< T > > & vmulti)
Definition at line 1755 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::imag(), Array3D_cmplx< T >::td1, and Array3D_cmplx< T >::v.
{
     for (size_t k(0); k< d3*d2*td1; k+=td1*d2 ) {
         for (size_t j(0); j< d2; ++j ) {
             for (size_t i(j*td1); i< (j+1)*td1; i+=2 ){
                 T vi((*v)[i+k]* vmulti[j].imag());
                 (*v)[i+k]    *= vmulti[j].real();                 // v[i]   = Aa
                 (*v)[i+k]    -= (*v)[i+k+1] * vmulti[j].imag();   // v[i]   = Aa - Bb
                 (*v)[i+k+1]  *= vmulti[j].real();                 // v[i+1] = Ba
                 (*v)[i+k+1]  += vi;                        // v[i+1] = Ba + Ab
             }
         }
     }
     return *this;
 }
multid2d3() [1/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid2d3 (const Array2D< T > & vd2d3)
Definition at line 1796 of file lib-array.h.
References Array2D< T >::array(), Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
{
     for (size_t j(0); j < d2*d3; ++j ){
         for (size_t i(j*td1); i< (j+1)*td1; ++i ){
             (*v)[i] *= vd2d3.array()[j];
         }
     }
     return *this;
 }
multid2d3() [2/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid2d3 (const Array2D_cmplx< T > & vd2d3)
Definition at line 1807 of file lib-array.h.
References Array2D_cmplx< T >::array(), Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, and Array3D_cmplx< T >::v.
{
     for (size_t j(0); j < d2*d3; ++j ){
         for (size_t i(j*td1); i< (j+1)*td1; i+=2 ){
             T vi((*v)[i]*vd2d3.array()[2*j+1]);
             (*v)[i]    *= vd2d3.array()[2*j];               // v[i]   = Aa
             (*v)[i]    -= (*v)[i+1]*vd2d3.array()[2*j+1];   // v[i]   = Aa - Bb
             (*v)[i+1]  *= vd2d3.array()[2*j];               // v[i+1] = Ba
             (*v)[i+1]  += vi;                            // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
multid3() [1/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid3 (const valarray< T > & vmulti)
Definition at line 1771 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for (size_t k(0); k< d3; ++k) {
         for (size_t i(k*td1*d2); i< (k+1)*td1*d2; ++i ){
             (*v)[i] *= vmulti[k];
         }
     }
     return *this;
 }
multid3() [2/2]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::multid3 (const valarray< complex< T > > & vmulti)
Definition at line 1781 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::imag(), Array3D_cmplx< T >::td1, and Array3D_cmplx< T >::v.
{
     for (size_t k(0); k< d3; ++k) {
         for (size_t i(k*td1*d2); i< (k+1)*td1*d2; i+=2 ){
             T vi((*v)[i]* vmulti[k].imag());
             (*v)[i]    *= vmulti[k].real();               // v[i]   = Aa
             (*v)[i]    -= (*v)[i+1] * vmulti[k].imag();   // v[i]   = Aa - Bb
             (*v)[i+1]  *= vmulti[k].real();               // v[i+1] = Ba
             (*v)[i+1]  += vi;                          // v[i+1] = Ba + Ab
         }
     }
     return *this;
 }
operator*=() [1/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator*= (const T & d)
Definition at line 1621 of file lib-array.h.
Referenced by Array4D< T >::array().
{
     (*v) *=d;
     return *this;
 }
operator*=() [2/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator*= (const complex< T > & c)
Definition at line 1626 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::real(), Array3D_cmplx< T >::td1, and Array3D_cmplx< T >::v.
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {            // suppose v[i]+iv[i+1]=A+iB,   c=a+ib
         T vi((*v)[i]*c.imag());
         (*v)[i]    *= c.real();                     // v[i]   = Aa
         (*v)[i]    -= (*v)[i+1]*c.imag();           // v[i]   = Aa - Bb
         (*v)[i+1]  *= c.real();                     // v[i+1] = Ba
         (*v)[i+1]  += vi;                           // v[i+1] = Ba + Ab
     }
     return *this;
 }
operator*=() [3/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator*= (const Array3D< T > & vmulti)
Definition at line 1637 of file lib-array.h.
References Array3D< T >::array(), Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, and Array3D_cmplx< T >::d3.
{
     for (size_t i(0); i< d1*d2*d3; ++i) {
         (*v)[2*i]   *= vmulti.array()[i];
         (*v)[2*i+1] *= vmulti.array()[i];
     }
     return *this;
 }
operator*=() [4/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator*= (const Array3D_cmplx< T > & vmulti)
Definition at line 1645 of file lib-array.h.
References Array3D_cmplx< T >::array(), Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::td1, and Array3D_cmplx< T >::v.
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {            // suppose v[i]+iv[i+1]=A+iB,   vmulti[i] + ivmulti[i+1] = a+ib
         T vi((*v)[i] * vmulti.array()[i+1]);
         (*v)[i]    *=  vmulti.array()[i];              // v[i]   = Aa
         (*v)[i]    -= (*v)[i+1]*vmulti.array()[i+1];   // v[i]   = Aa - Bb
         (*v)[i+1]  *= vmulti.array()[i];               // v[i+1] = Ba
         (*v)[i+1]  += vi;                              // v[i+1] = Ba + Ab
     }
     return *this;
 }
operator+=() [1/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator+= (const T & d)
Definition at line 1658 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {
         (*v)[i] +=d;
     }
     return *this;
 }
operator+=() [2/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator+= (const complex< T > & c)
Definition at line 1665 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::real(), and Array3D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {
         (*v)[i]   +=c.real();
         (*v)[i+1] +=c.imag();
     }
     return *this;
 }
operator+=() [3/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator+= (const Array3D< T > & vadd)
Definition at line 1673 of file lib-array.h.
References Array3D< T >::array(), Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, and Array3D_cmplx< T >::d3.
{
     for (size_t i(0); i< d1*d2*d3; ++i) {
         (*v)[2*i]   += vadd.array()[i];
     }
     return *this;
 }
operator+=() [4/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator+= (const Array3D_cmplx< T > & vadd)
Definition at line 1680 of file lib-array.h.
References Array3D_cmplx< T >::array().
{
     (*v) += vadd.array();
     return *this;
 }
operator-=() [1/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator-= (const T & d)
Definition at line 1687 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {
         (*v)[i] -=d;
     }
     return *this;
 }
operator-=() [2/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator-= (const complex< T > & c)
Definition at line 1694 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::real(), and Array3D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {
         (*v)[i]   -=c.real();
         (*v)[i+1] -=c.imag();
     }
     return *this;
 }
operator-=() [3/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator-= (const Array3D< T > & vmin)
Definition at line 1702 of file lib-array.h.
References Array3D< T >::array(), Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, and Array3D_cmplx< T >::d3.
{
     for (size_t i(0); i< d1*d2*d3; ++i) {
         (*v)[2*i]   -= vmin.array()[i];
     }
     return *this;
 }
operator-=() [4/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator-= (const Array3D_cmplx< T > & vmin)
Definition at line 1709 of file lib-array.h.
References Array3D_cmplx< T >::array().
{
     (*v) -= vmin.array();
     return *this;
 }
operator=() [1/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator= (const T & d)
Definition at line 1591 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, and Array3D_cmplx< T >::td1.
Referenced by Array4D< T >::array().
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {
         (*v)[i] = d;
         (*v)[i+1] = 0.0;
     }
     return *this;
 }
operator=() [2/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator= (const complex< T > & c)
Definition at line 1598 of file lib-array.h.
References Array3D_cmplx< T >::d2, Array3D_cmplx< T >::d3, Array3D_cmplx< T >::real(), and Array3D_cmplx< T >::td1.
{
     for (size_t i(0); i< td1*d2*d3; i+=2) {
         (*v)[i]   =c.real();
         (*v)[i+1] =c.imag();
     }
     return *this;
 }
operator=() [3/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator= (const Array3D< T > & other)
Definition at line 1605 of file lib-array.h.
References Array3D< T >::array(), Array3D_cmplx< T >::d1, Array3D_cmplx< T >::d2, and Array3D_cmplx< T >::d3.
{
     for (size_t i(0); i< d1*d2*d3; ++i) {
         (*v)[2*i]   = other.array()[i];
         (*v)[2*i+1] = 0.0;
     }
     return *this;
 }
operator=() [4/4]
template<class T > Array3D_cmplx< T > & Array3D_cmplx< T >::operator= (const Array3D_cmplx< T > & other)
Definition at line 1612 of file lib-array.h.
References Array3D_cmplx< T >::array().
{
     if (this != &other) {   //self-assignment
         (*v) = other.array();
     }
     return *this;
 }
operator[]() [1/2]
template<class T > T & Array3D_cmplx< T >::operator[] (size_t i) inline
Definition at line 1493 of file lib-array.h.
References Array3D_cmplx< T >::v.
{
     return (*v)[i];
 }
operator[]() [2/2]
template<class T > T Array3D_cmplx< T >::operator[] (size_t i) const inline
Definition at line 1497 of file lib-array.h.
References Array3D_cmplx< T >::v.
{
     return (*v)[i];
 }
real() [1/2]
template<class T > T & Array3D_cmplx< T >::real (size_t i, size_t j, size_t k) inline
Definition at line 1501 of file lib-array.h.
References Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
Referenced by Array3D_cmplx< T >::operator*=(), Array3D_cmplx< T >::operator+=(), Array3D_cmplx< T >::operator-=(), and Array3D_cmplx< T >::operator=().
{
     return (*v)[2*i+j*td1+k*td1d2];
 }
real() [2/2]
template<class T > T Array3D_cmplx< T >::real (size_t i, size_t j, size_t k) const inline
Definition at line 1505 of file lib-array.h.
References Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     return (*v)[2*i+j*td1+k*td1d2];
 }
SubArray3D() [1/2]
template<class T > GSlice_iter< T > Array3D_cmplx< T >::SubArray3D (size_t st, size_t nx, size_t ny, size_t nz) inline
Definition at line 1571 of file lib-array.h.
References Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;    str[1] = td1;  str[0] = td1d2;
     sz[2]  = 2*nx;  sz[1] = ny;    sz[0] = nz;
     return GSlice_iter<T>(v,gslice(2*st,sz,str));
 }
SubArray3D() [2/2]
template<class T > CGSlice_iter< T > Array3D_cmplx< T >::SubArray3D (size_t st, size_t nx, size_t ny, size_t nz) const inline
Definition at line 1580 of file lib-array.h.
References Array3D_cmplx< T >::td1, Array3D_cmplx< T >::td1d2, and Array3D_cmplx< T >::v.
{
     valarray<size_t> sz(3), str(3);
     str[2] = 1;    str[1] = td1;  str[0] = td1d2;
     sz[2]  = 2*nx;  sz[1] = ny;    sz[0] = nz;
     return CGSlice_iter<T>(v,gslice(2*st,sz,str));
 }
Field Documentation
d1
template<class T> size_t Array3D_cmplx< T >::d1 private
Definition at line 1385 of file lib-array.h.
Referenced by Array3D_cmplx< T >::Array3D_cmplx(), Array4D< T >::dim1(), Array3D_cmplx< T >::multid1(), Array3D_cmplx< T >::operator*=(), Array3D_cmplx< T >::operator+=(), Array3D_cmplx< T >::operator-=(), and Array3D_cmplx< T >::operator=().
d2
template<class T> size_t Array3D_cmplx< T >::d2 private
Definition at line 1385 of file lib-array.h.
Referenced by Array3D_cmplx< T >::Array3D_cmplx(), Array3D_cmplx< T >::d1c(), Array3D_cmplx< T >::Dd1(), Array3D_cmplx< T >::Dd2(), Array3D_cmplx< T >::Dd3(), Array4D< T >::dim2(), Array3D_cmplx< T >::Filterd1(), Array3D_cmplx< T >::multid1(), Array3D_cmplx< T >::multid2(), Array3D_cmplx< T >::multid2d3(), Array3D_cmplx< T >::multid3(), Array3D_cmplx< T >::operator*=(), Array3D_cmplx< T >::operator+=(), Array3D_cmplx< T >::operator-=(), and Array3D_cmplx< T >::operator=().
d3
template<class T> size_t Array3D_cmplx< T >::d3 private
Definition at line 1385 of file lib-array.h.
Referenced by Array3D_cmplx< T >::Array3D_cmplx(), Array3D_cmplx< T >::d1c(), Array3D_cmplx< T >::d2c(), Array3D_cmplx< T >::Dd1(), Array3D_cmplx< T >::Dd2(), Array3D_cmplx< T >::Dd3(), Array4D< T >::dim3(), Array3D_cmplx< T >::Filterd1(), Array3D_cmplx< T >::multid1(), Array3D_cmplx< T >::multid2(), Array3D_cmplx< T >::multid2d3(), Array3D_cmplx< T >::multid3(), Array3D_cmplx< T >::operator*=(), Array3D_cmplx< T >::operator+=(), Array3D_cmplx< T >::operator-=(), and Array3D_cmplx< T >::operator=().
td1
template<class T> size_t Array3D_cmplx< T >::td1 private
Definition at line 1386 of file lib-array.h.
Referenced by Array3D_cmplx< T >::Array3D_cmplx(), Array3D_cmplx< T >::d1c(), Array3D_cmplx< T >::d2c(), Array3D_cmplx< T >::Dd1(), Array3D_cmplx< T >::Dd2(), Array3D_cmplx< T >::Dd3(), Array3D_cmplx< T >::Filterd1(), Array3D_cmplx< T >::imag(), Array3D_cmplx< T >::multid1(), Array3D_cmplx< T >::multid2(), Array3D_cmplx< T >::multid2d3(), Array3D_cmplx< T >::multid3(), Array3D_cmplx< T >::operator*=(), Array3D_cmplx< T >::operator+=(), Array3D_cmplx< T >::operator-=(), Array3D_cmplx< T >::operator=(), Array3D_cmplx< T >::real(), and Array3D_cmplx< T >::SubArray3D().
td1d2
template<class T> size_t Array3D_cmplx< T >::td1d2 private
Definition at line 1387 of file lib-array.h.
Referenced by Array3D_cmplx< T >::Array3D_cmplx(), Array3D_cmplx< T >::d1c(), Array3D_cmplx< T >::d2c(), Array3D_cmplx< T >::d3c(), Array3D_cmplx< T >::Dd3(), Array3D_cmplx< T >::imag(), Array3D_cmplx< T >::real(), and Array3D_cmplx< T >::SubArray3D().
v
template<class T> valarray<T>* Array3D_cmplx< T >::v private
Definition at line 1384 of file lib-array.h.
Referenced by Array4D< T >::array(), Array3D_cmplx< T >::Array3D_cmplx(), Array3D_cmplx< T >::d1c(), Array3D_cmplx< T >::d2c(), Array3D_cmplx< T >::d3c(), Array3D_cmplx< T >::imag(), Array3D_cmplx< T >::multid1(), Array3D_cmplx< T >::multid2(), Array3D_cmplx< T >::multid2d3(), Array3D_cmplx< T >::multid3(), Array3D_cmplx< T >::operator*=(), Array3D_cmplx< T >::operator[](), Array3D_cmplx< T >::real(), Array3D_cmplx< T >::SubArray3D(), and Array3D_cmplx< T >::~Array3D_cmplx().
The documentation for this class was generated from the following file:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/lib-array.h