OSHUN: Hydro_Advection_1D Class Reference
Hydro_Advection_1D Class Reference
#include <fluid.h>
Public Member Functions
Hydro_Advection_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
void operator() (const DistFunc1D &Din, const Hydro1D &hydro, DistFunc1D &Dh)
Private Member Functions
void MakeGH (SHarmonic1D &f, size_t l)
void MakeG00 (SHarmonic1D &f)
Private Attributes
SHarmonic1D H
SHarmonic1D G
SHarmonic1D TMP
SHarmonic1D fd1
SHarmonic1D fd2
Array2D< complex< double > > XX1
Array2D< complex< double > > XX2
Array2D< complex< double > > XX3
Array2D< complex< double > > XX4
Array2D< complex< double > > A1
Array2D< complex< double > > A2
valarray< complex< double > > pr
valarray< complex< double > > invpr
valarray< complex< double > > Hp0
size_t szx
size_t Nbc
double idp
double idx
Detailed Description
Definition at line 61 of file fluid.h.
Constructor & Destructor Documentation
Hydro_Advection_1D()
Hydro_Advection_1D::Hydro_Advection_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
Definition at line 259 of file fluid.cpp.
References A2, Input::Input_List::BoundaryCells, Hp0, idp, idx, invpr, Input::List(), Nbc, pr, XX1, XX2, XX3, and XX4.
    : XX1(Nl+1,Nm+1), XX2(Nl+1,Nm+1), XX3(Nl+1,Nm+1), XX4(Nl+1,Nm+1),
      A1(Nl+1,Nm+1), A2(Nl+1,Nm+1), fd1(Nl+1,Nm+1), fd2(Nl+1,Nm+1),
      Hp0(Nl+1), H(Np,Nx), G(Np,Nx), TMP(Np,Nx),
      pr(Algorithms::MakeCAxis(static_cast<complex<double> >(pmin),
                              static_cast<complex<double> >(pmax),
                              Np)),
      invpr(pr), szx(Nx)
      {
 //      - - - - - - - - - - - - - - - - - - - - - - - - - - -
          complex<double> lc, mc;
 //       Inverted momentum axis
          for (size_t i(0); i < pr.size(); ++i) {
              invpr[i] = 1.0/pr[i];
          }
          idp = (-1.0)/ (2.0*(pmax-pmin)/double(Np)); // -1/(2dp)
          idx = (-1.0) / (2.0*(xmax-xmin)/double(Nx)); // -1/(2dx)
          Nbc = Input::List().BoundaryCells;
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "A1, A2" parameters
          for (size_t l(0); l < Nl+1; ++l){
              for (size_t m=0; m<((Nm<l)?Nm:l)+1; ++m){
                  lc = static_cast< complex<double> >(l);
                  mc = static_cast< complex<double> >(m);
                  XX1(l,m) = (lc+mc    ) * (lc-mc    ) / (2.0*lc-1.0) / (2.0*lc+1.0) ;
                  XX2(l,m) = (lc-mc+1.0) * (lc+mc+1.0) / (2.0*lc+3.0) / (2.0*lc+1.0) ;
                  XX3(l,m) = (lc-mc+1.0) * (lc-mc+2.0) / (2.0*lc+3.0) / (2.0*lc+1.0) ;
                  XX4(l,m) = (lc+mc-1.0) * (lc+mc    ) / (2.0*lc-1.0) / (2.0*lc+1.0) ; //idx *(-1.0) * (lc-mc+1.0) / (2.0*lc+1.0);
              }
          }
          A2(0,0) = 1.0;
          //       -2*Dp*H at the 0 momentum cell
          Hp0[0] = 1.0 / pr[0];
          for (size_t l(1); l < Nl+1; ++l) {
              double ld(l);
              Hp0[l] = Hp0[l-1] * (pr[0]/pr[1]) * (2.0*ld+1.0)/(2.0*ld-1.0);
          }
          Hp0 *= (-2.0)*(pr[1]-pr[0]);
     }
Member Function Documentation
MakeG00()
void Hydro_Advection_1D::MakeG00 (SHarmonic1D & f) private
Definition at line 464 of file fluid.cpp.
References SHarmonic1D::Dp(), G, SHarmonic1D::numx(), and pr.
Referenced by operator()().
{
 //--------------------------------------------------------------
         G = f; G = G.Dp();
         complex<double> p0p1_sq( pr[0]*pr[0]/(pr[1]*pr[1]) ),
                inv_mp0p1_sq( 1.0/(1.0-p0p1_sq) ),
                g_r = -4.0*(pr[1]-pr[0]) * pr[0]/(pr[1]*pr[1]),
                f00;
         for (size_t i(0); i < f.numx(); ++i) {
              f00    = ( f(0,i) - f(1,i) * p0p1_sq) * inv_mp0p1_sq;
              G(0,i) = ( f(1,i) - f00) * g_r;
         }
     }
MakeGH()
void Hydro_Advection_1D::MakeGH (SHarmonic1D & f, size_t l) private
Definition at line 445 of file fluid.cpp.
References SHarmonic1D::Dp(), G, H, Hp0, invpr, SHarmonic1D::mpaxis(), SHarmonic1D::numx(), and pr.
Referenced by operator()().
{
 //--------------------------------------------------------------
         valarray<complex<double> > invpax(invpr);
         complex<double> ld(el);
         invpax *= (-2.0)*(ld+1.0) * (pr[1]-pr[0]);
         G = f;                   H = f;
         G = G.Dp();
                                  H  = H.mpaxis(invpax);
                                  H += G;
         G *= -(2.0*ld+1.0)/ld;
         G += H;
         for (size_t i(0); i < G.numx(); ++i) G(0,i) = 0.0;
         for (size_t i(0); i < H.numx(); ++i) H(0,i) = f(1,i) * Hp0[el];
     }
operator()()
void Hydro_Advection_1D::operator() (const DistFunc1D & Din, const Hydro1D & hydro, DistFunc1D & Dh)
Definition at line 311 of file fluid.cpp.
References G, H, idx, DistFunc1D::l0(), DistFunc1D::m0(), MakeG00(), MakeGH(), DistFunc1D::mass(), pr, szx, TMP, Hydro1D::vx(), Hydro1D::vxarray(), XX1, XX2, XX3, and XX4.
{
 //--------------------------------------------------------------
         valarray<complex<double> > vt(pr); vt *= 1.0/Din.mass();
         valarray<complex<double> > tempv(vt);
         valarray<complex<double> > Ux(0.0,(hydro.vxarray()).size());
         valarray<complex<double> > dUxdx(0.0,(hydro.vxarray()).size());
         Ux[0] = hydro.vx(0);
         dUxdx[0] = idx*(hydro.vx(1)-hydro.vx(0));
         Ux[szx-1] = hydro.vx(szx-1);
         dUxdx[szx-1] = idx*(hydro.vx(szx-1)-hydro.vx(szx-2));
         for (size_t i(1);i<szx-1;++i)
         {
             Ux[i] = hydro.vx(i);
             // dUxdx[i] = idx/12.0*(-hydro.vx(i+2)+8.0*(hydro.vx(i+1)-hydro.vx(i-1))+hydro.vx(i-2));
             dUxdx[i] = idx*0.5*(hydro.vx(i+1)-hydro.vx(i-1));
             // dUxdx[i] = idx/3.0*(-Cx[i+3]+6.0*Cx[i+2]-3.0*Cx[i+1]-2.0*Cx[i]);
         }
         // vt += fluidvx;
         size_t l0(Din.l0());
         size_t m0(Din.m0());
         SHarmonic1D tG(G), tH(H);
         // dCdx df/dv term
         TMP = Din(0,0);     //fd1 = fd1.Dx();
         MakeGH(TMP, 0);            MakeG00(TMP);     tH=H;tG=G;
         tempv = vt *  XX1(0,0);    tH.mpaxis(tempv); tH.mxaxis(dUxdx);   Dh(0,0) += tH; tH = H;
         tempv = vt *  XX2(0,0);    tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(0,0) += tG; tG = G;
         tempv = vt *  XX3(0,0);    tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(2,0) += tG;
         // Dh.checknan();
         TMP = Din(1,0);     //fd1 = fd1.Dx();
         MakeGH(TMP,1);             tH=H;tG=G;
         tempv = vt *  XX1(1,0);    tH.mpaxis(tempv); tH.mxaxis(dUxdx);   Dh(1,0) += tH; tH = H;
         tempv = vt *  XX2(1,0);    tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(1,0) += tG; tG = G;
         tempv = vt *  XX3(1,0);    tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(3,0) += tG;
         // Dh.checknan();
         TMP = Din(1,1);
         MakeGH(TMP,1);              tH=H;tG=G;
         tempv = vt *  XX1(1,1);     tH.mpaxis(tempv); tH.mxaxis(dUxdx);   Dh(1,1) += tH; tH = H;
         tempv = vt *  XX2(1,1);     tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(1,1) += tG; tG = G;
         tempv = vt *  XX3(1,1);     tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(3,1) += tG; tG = G;
         // tempv = vt *  1.0;
         MakeGH(TMP,l0);             tH=H;tG=G;
         for (size_t m(0); m<((m0<l0-1)?(m0+1):(l0-1)); ++m){
             TMP = Din(l0,m);
             tempv = vt *  XX1(l0,m);   tH.mpaxis(tempv); tH.mxaxis(dUxdx);   Dh(l0,m) += tH; tH = H;
             tempv = vt *  XX2(l0,m);   tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(l0,m) += tG; tG = G;
             tempv = vt *  XX4(l0,m);   tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(l0-2,m) += tG; tG = G;
             // tempv = vt *  1.0);
         }
         for (size_t m(l0-2); m<((m0<l0)?(m0):(l0+1)); ++m){
             // TMP = Din(l0,m);     //fd1 = fd1.Dx();
             tempv = vt *  XX1(l0,m);   tH.mpaxis(tempv); tH.mxaxis(dUxdx);   Dh(l0,m) += tH; tH = H;
             tempv = vt *  XX2(l0,m);   tG.mpaxis(tempv); tG.mxaxis(dUxdx);   Dh(l0,m) += tG; tG = G;
             // tempv = vt *  XX4(l0,m));      TMP =  H.mpaxis(tempv);            Dh(l0-2,m) += TMP;
             // tempv = vt *  1.0);
         }
         MakeGH(TMP,l0-1);       tH=H;tG=G;
         for (size_t m(0); m<((m0<l0-2)?(m0+1):(l0-2)); ++m){
             // TMP = Din(l0-1,m);     //fd1 = fd1.Dx();
             tempv = vt *  XX1(l0-1,m);  tH.mpaxis(tempv); tH.mxaxis(dUxdx);  Dh(l0-1,m) += tH; tH = H;
             tempv = vt *  XX2(l0-1,m);  tG.mpaxis(tempv); tG.mxaxis(dUxdx);  Dh(l0-1,m) += tG; tG = G;
             tempv = vt *  XX4(l0-1,m);  tH.mpaxis(tempv); tH.mxaxis(dUxdx);  Dh(l0-3,m) += tH; tH = H;
             // tempv = vt *  1.0;
         }
         for (size_t m(l0-3); m<((m0<l0)?(m0+1):(l0+1)); ++m){
             // TMP = Din(l0-1,m);     //fd1 = fd1.Dx();
             tempv = vt *  XX1(l0-1,m);  tH.mpaxis(tempv); tH.mxaxis(dUxdx);  Dh(l0-1,m) += tH; tH = H;
             tempv = vt *  XX2(l0-1,m);  tG.mpaxis(tempv); tG.mxaxis(dUxdx);  Dh(l0-1,m) += tG; tG = G;
             // tempv = vt *  1.0,m);
         }
         for (size_t l(2); l<l0-1; ++l){
             MakeGH(TMP,l);      tH=H;tG=G;
             for (size_t m(0); m < ((m0<l+1)?(m0+1):(l+1)); ++m){
                 tempv = vt *  XX1(l,m);  tH.mpaxis(tempv); tH.mxaxis(dUxdx);  Dh(l,m) += tH; tH = H;
                 tempv = vt *  XX2(l,m);  tG.mpaxis(tempv); tG.mxaxis(dUxdx);  Dh(l,m) += tG; tG = G;
                 // tempv = vt *  1.0;
             }
             for (size_t m(0); m < ((m0<l-1)?(m0+1):(l-1)); ++m){
                 tempv = vt *  XX4(l,m);  tH.mpaxis(tempv); tH.mxaxis(dUxdx);  Dh(l-2,m) += tH; tH = H;
             }
             for (size_t m(0); m < ((m0<l+3)?(m0+1):(l+3)); ++m){
                 tempv = vt *  XX3(l,m);  tH.mpaxis(tempv); tH.mxaxis(dUxdx);  Dh(l+2,m) += tH; tH = H;
                 // tempv = vt *  1.0;
             }
         }
         // C df/dr term
         for (size_t m(0); m < ((m0<l0)?(m0+1):m0); ++m){
             tH = Din(m,m);                             tH = tH.Dx();
             for (int ip(0); ip<tH.nump(); ++ip) tH(ip,Din(0,0).numx()-1)  = 0.0;
             Dh(m,m) += tH.mxaxis(Ux);
             for (size_t l(m+1); l < l0; ++l) {
                tH = Din(l,m);                          tH = tH.Dx();
                for (int ip(0); ip<tH.nump(); ++ip) tH(ip,Din(0,0).numx()-1)  = 0.0;
                Dh(l,m) += tH.mxaxis(Ux);
             }
             tH = Din(l0,m);                            tH = tH.Dx();
             for (int ip(0); ip<tH.nump(); ++ip) tH(ip,Din(0,0).numx()-1)  = 0.0;
             Dh(l0,m) += tH.mxaxis(Ux);
         }
 }
Field Documentation
A1
Array2D< complex<double> > Hydro_Advection_1D::A1 private
Definition at line 79 of file fluid.h.
A2
Array2D< complex<double> > Hydro_Advection_1D::A2 private
Definition at line 79 of file fluid.h.
Referenced by Hydro_Advection_1D().
fd1
SHarmonic1D Hydro_Advection_1D::fd1 private
Definition at line 77 of file fluid.h.
fd2
SHarmonic1D Hydro_Advection_1D::fd2 private
Definition at line 77 of file fluid.h.
G
SHarmonic1D Hydro_Advection_1D::G private
Definition at line 76 of file fluid.h.
Referenced by MakeG00(), MakeGH(), and operator()().
H
SHarmonic1D Hydro_Advection_1D::H private
Definition at line 76 of file fluid.h.
Referenced by MakeGH(), and operator()().
Hp0
valarray< complex<double> > Hydro_Advection_1D::Hp0 private
Definition at line 80 of file fluid.h.
Referenced by Hydro_Advection_1D(), and MakeGH().
idp
double Hydro_Advection_1D::idp private
Definition at line 82 of file fluid.h.
Referenced by Hydro_Advection_1D().
idx
double Hydro_Advection_1D::idx private
Definition at line 82 of file fluid.h.
Referenced by Hydro_Advection_1D(), and operator()().
invpr
valarray< complex<double> > Hydro_Advection_1D::invpr private
Definition at line 80 of file fluid.h.
Referenced by Hydro_Advection_1D(), and MakeGH().
Nbc
size_t Hydro_Advection_1D::Nbc private
Definition at line 81 of file fluid.h.
Referenced by Hydro_Advection_1D().
pr
valarray< complex<double> > Hydro_Advection_1D::pr private
Definition at line 80 of file fluid.h.
Referenced by Hydro_Advection_1D(), MakeG00(), MakeGH(), and operator()().
szx
size_t Hydro_Advection_1D::szx private
Definition at line 81 of file fluid.h.
Referenced by operator()().
TMP
SHarmonic1D Hydro_Advection_1D::TMP private
Definition at line 76 of file fluid.h.
Referenced by operator()().
XX1
Array2D< complex<double> > Hydro_Advection_1D::XX1 private
Definition at line 78 of file fluid.h.
Referenced by Hydro_Advection_1D(), and operator()().
XX2
Array2D< complex<double> > Hydro_Advection_1D::XX2 private
Definition at line 78 of file fluid.h.
Referenced by Hydro_Advection_1D(), and operator()().
XX3
Array2D< complex<double> > Hydro_Advection_1D::XX3 private
Definition at line 78 of file fluid.h.
Referenced by Hydro_Advection_1D(), and operator()().
XX4
Array2D< complex<double> > Hydro_Advection_1D::XX4 private
Definition at line 78 of file fluid.h.
Referenced by Hydro_Advection_1D(), and operator()().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/fluid.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/fluid.cpp