OSHUN: Vlasov-Fokker-Planck operators in 1D
Vlasov-Fokker-Planck operators in 1D
Data Structures
class self_f00_implicit_step
class self_f00_implicit_collisions
class self_f00_explicit_step
The top-level container for collisions on l=0.
class self_f00_explicit_collisions
class self_flm_implicit_step
Collisions for l >= 1.
class self_flm_implicit_collisions
class self_collisions
The top-level container for self collisions over all species on l=0.
class collisions
class interspecies_f00_explicit_step
The top-level container for collisions on l=0.
class interspecies_f00_RKfunctor
class interspecies_f00_explicit_collisions
class interspecies_flm_implicit_step
Collisions for l >= 1.
class interspecies_flm_implicit_collisions
class interspecies_collisions
The top-level container for interspecies collisions over all species on l=0.
class Spatial_Advection_1D
class Electric_Field_1D
class Magnetic_Field_1D
class Current_1D
class Faraday_1D
class Ampere_1D
class Spatial_Advection_1D_f1
class Electric_Field_1D_f1
class Magnetic_Field_1D_f1
class VlasovFunctor1D_f1_explicitE
class VlasovFunctor1D_f1_explicitEB
class VlasovFunctor1D_f1_implicitE_p1
class VlasovFunctor1D_f1_implicitEB_p1
class VlasovFunctor1D_f1_implicitE_p2
class f00_step
Collisions for l=0.
class Anisotropic_Collisions
Middle container for collisions on l >= 1.
class explicit_f00
The top-level container for collisions on l=0.
Functions
void self_f00_implicit_step::update_C_Rosenbluth (valarray< double > &fin)
double self_f00_implicit_step::update_D_Rosenbluth (const size_t &k, valarray< double > &fin, const double &delta)
void self_f00_implicit_step::update_D_and_delta (valarray< double > &fin)
void self_f00_implicit_step::update_D_inversebremsstrahlung (const double &Z0, const double &heatingcoefficient, const double &vos)
double self_f00_implicit_step::calc_delta_ChangCooper (const size_t &k, const double &C, const double &D)
self_f00_implicit_step::self_f00_implicit_step (const size_t &nump, const double &pmax, const double &_mass, const double &_deltat, bool &_ib)
void self_f00_implicit_step::takestep (valarray< double > &fin, valarray< double > &fh, const double &Z0, const double &heating, const double &cooling)
void self_f00_implicit_step::getleftside (valarray< double > &fin, const double &Z0, const double &heating, const double &cooling, Array2D< double > &LHStemp)
self_f00_implicit_collisions::self_f00_implicit_collisions (const DistFunc1D &DFin, const double &deltat)
Constructors/Destructors.
void self_f00_implicit_collisions::loop (SHarmonic1D &SHin, valarray< double > &Zarray, const double time, SHarmonic1D &SHout)
double self_f00_explicit_step::G (const int &n, const valarray< double > &fin)
self_f00_explicit_step::self_f00_explicit_step (const size_t &nump, const double &pmax, const double &_mass)
Constructor that needs a distribution function input.
void self_f00_explicit_step::takestep (const valarray< double > &fin, valarray< double > &fh)
self_f00_RKfunctor::self_f00_RKfunctor (const size_t &nump, const double &pmax, const double &mass)
Constructor for RK4 method on f00.
self_f00_RKfunctor::~self_f00_RKfunctor ()
void self_f00_RKfunctor::operator() (const valarray< double > &fin, valarray< double > &fslope)
void self_f00_RKfunctor::operator() (const valarray< double > &fin, valarray< double > &fslope, size_t dir)
void self_f00_RKfunctor::operator() (const valarray< double > &fin, const valarray< double > &f2in, valarray< double > &fslope)
self_f00_explicit_collisions::self_f00_explicit_collisions (const DistFunc1D &DFin, const double &deltat)
Constructors/Destructors.
void self_f00_explicit_collisions::loop (SHarmonic1D &SHin, SHarmonic1D &SHout)
self_flm_implicit_step::self_flm_implicit_step (double pmax, size_t nump, double mass)
void self_flm_implicit_step::reset_coeff (const valarray< double > &f00, double Zvalue, const double Delta_t)
Resets coefficients and integrals to use in the matrix solve.
void self_flm_implicit_step::advance (valarray< complex< double > > &fin, const int el)
Perform a matrix solve to calculate effect of collisions on f >= 1.
self_flm_implicit_collisions::self_flm_implicit_collisions (const DistFunc1D &DFin, const double &deltat)
Constructors/Destructors.
void self_flm_implicit_collisions::advancef1 (DistFunc1D &DF, valarray< double > &Zarray, DistFunc1D &DFh)
Advance f1_loop for 2D code.
void self_flm_implicit_collisions::advanceflm (DistFunc1D &DF, valarray< double > &Zarray, DistFunc1D &DFh)
Advance flm_loop for 2D code.
self_collisions::self_collisions (const DistFunc1D &DFin, const double &deltat)
Constructors/Destructors.
void self_collisions::advancef00 (SHarmonic1D &f00, valarray< double > &Zarray, const double time, SHarmonic1D &f00h)
void self_collisions::advancef1 (DistFunc1D &DF, valarray< double > &Zarray, DistFunc1D &DFh)
void self_collisions::advanceflm (DistFunc1D &DF, valarray< double > &Zarray, DistFunc1D &DFh)
collisions::collisions (const State1D &Yin, const double &deltat)
Constructors/Destructors.
void collisions::advance (State1D &Y, const Clock &W)
void collisions::advancef0 (State1D &Y, const Clock &W, State1D &Yh)
void collisions::advancef1 (State1D &Y, State1D &Yh)
void collisions::advanceflm (State1D &Y, State1D &Yh)
vector< self_collisions > collisions::self ()
interspecies_f00_explicit_step::interspecies_f00_explicit_step (const DistFunc1D &DF1, const DistFunc1D &DF2, const double &deltat)
Constructors/Destructors.
valarray< double > interspecies_f00_explicit_step::takestep (const valarray< double > &f1in, const valarray< double > &f2in)
Collisions between species 1 and 2 in 0,0 harmonic.
void interspecies_f00_explicit_step::calculateintegrals (const valarray< double > &f1in, const valarray< double > &f2in)
Remap Distribution to momentum grid of colliding particles.
void interspecies_f00_explicit_step::remapintegrals ()
Remap Distribution to momentum grid of colliding particles.
interspecies_f00_RKfunctor::interspecies_f00_RKfunctor (const DistFunc1D &DF1, const DistFunc1D &DF2, const double &smalldt)
Constructor for RK4 method on f00.
interspecies_f00_RKfunctor::~interspecies_f00_RKfunctor ()
void interspecies_f00_RKfunctor::operator() (const valarray< double > &fin1, valarray< double > &fslope)
void interspecies_f00_RKfunctor::operator() (const valarray< double > &fin1, const valarray< double > &fin2, valarray< double > &fslope)
void interspecies_f00_RKfunctor::operator() (const valarray< double > &fin1, valarray< double > &fslope, size_t dir)
interspecies_f00_explicit_collisions::interspecies_f00_explicit_collisions (const DistFunc1D &DF1, const DistFunc1D &DF2, const double &deltat)
Constructors/Destructors.
void interspecies_f00_explicit_collisions::rkloop (SHarmonic1D &SH1, const SHarmonic1D &SH2)
interspecies_flm_implicit_step::interspecies_flm_implicit_step (double pmax, size_t nump)
void interspecies_flm_implicit_step::reset_coeff (const valarray< double > &f00, const double Delta_t)
Resets coefficients and integrals to use in the matrix solve.
void interspecies_flm_implicit_step::advance (valarray< complex< double > > &fin, const int el)
Perform a matrix solve to calculate effect of collisions on f >= 1.
interspecies_flm_implicit_collisions::interspecies_flm_implicit_collisions (const DistFunc1D &DFin, const double &deltat)
Constructors/Destructors.
void interspecies_flm_implicit_collisions::advancef1 (DistFunc1D &DF)
Advance f1_loop for 2D code.
void interspecies_flm_implicit_collisions::advanceflm (DistFunc1D &DF)
Advance flm_loop for 2D code.
interspecies_collisions::interspecies_collisions (const State1D &Yin, const size_t &sind, const double &deltat)
Constructors/Destructors.
void interspecies_collisions::advancef00 (State1D &Y, const size_t &sind)
Remap Distribution to momentum grid of colliding particles.
Spatial_Advection_1D::Spatial_Advection_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
void Spatial_Advection_1D::operator() (const DistFunc1D &Din, DistFunc1D &Dh)
void Spatial_Advection_1D::es1d (const DistFunc1D &Din, DistFunc1D &Dh)
void Spatial_Advection_1D::f1only (const DistFunc1D &Din, DistFunc1D &Dh)
Electric_Field_1D::Electric_Field_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
void Electric_Field_1D::operator() (const DistFunc1D &Din, const Field1D &FEx, const Field1D &FEy, const Field1D &FEz, DistFunc1D &Dh)
void Electric_Field_1D::es1d (const DistFunc1D &Din, const Field1D &FEx, const Field1D &FEy, const Field1D &FEz, DistFunc1D &Dh)
void Electric_Field_1D::f1only (const DistFunc1D &Din, const Field1D &FEx, const Field1D &FEy, const Field1D &FEz, DistFunc1D &Dh)
void Electric_Field_1D::Implicit_Ex (const DistFunc1D &Din, const Field1D &FEx, DistFunc1D &Dh)
void Electric_Field_1D::Implicit_Ey (const DistFunc1D &Din, const Field1D &FEy, DistFunc1D &Dh)
void Electric_Field_1D::Implicit_Ez (const DistFunc1D &Din, const Field1D &FEz, DistFunc1D &Dh)
void Electric_Field_1D::Implicit_Ex_f1only (const DistFunc1D &Din, const Field1D &FEx, DistFunc1D &Dh)
void Electric_Field_1D::Implicit_Ey_f1only (const DistFunc1D &Din, const Field1D &FEy, DistFunc1D &Dh)
void Electric_Field_1D::Implicit_Ez_f1only (const DistFunc1D &Din, const Field1D &FEz, DistFunc1D &Dh)
void Electric_Field_1D::MakeG00 (SHarmonic1D &f)
void Electric_Field_1D::MakeGH (SHarmonic1D &f, size_t l)
Magnetic_Field_1D::Magnetic_Field_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
void Magnetic_Field_1D::operator() (const DistFunc1D &Din, const Field1D &FBx, const Field1D &FBy, const Field1D &FBz, DistFunc1D &Dh)
void Magnetic_Field_1D::f1only (const DistFunc1D &Din, const Field1D &FBx, const Field1D &FBy, const Field1D &FBz, DistFunc1D &Dh)
void Magnetic_Field_1D::implicit (DistFunc1D &Din, const Field1D &FBx, const Field1D &FBy, const Field1D &FBz, double dt)
Current_1D::Current_1D (double pmin, double pmax, size_t Np, size_t Nx)
void Current_1D::operator() (const DistFunc1D &Din, Field1D &FExh, Field1D &FEyh, Field1D &FEzh)
void Current_1D::es1d (const DistFunc1D &Din, Field1D &FExh)
Faraday_1D::Faraday_1D (double xmin, double xmax, size_t Nx)
void Faraday_1D::operator() (EMF1D &EMFin, EMF1D &EMFh)
Ampere_1D::Ampere_1D (double xmin, double xmax, size_t Nx)
void Ampere_1D::operator() (EMF1D &EMFin, EMF1D &EMFh)
Variables
double self_f00_implicit_step::mass
double self_f00_implicit_step::dt
bool self_f00_implicit_step::ib
valarray< double > self_f00_implicit_step::vr
Define the velocity axis.
valarray< double > self_f00_implicit_step::dvr
valarray< double > self_f00_implicit_step::vrh
valarray< double > self_f00_implicit_step::dtoverv2
valarray< double > self_f00_implicit_step::p2dp
Various coefficients for the integrals.
valarray< double > self_f00_implicit_step::p2dpm1
valarray< double > self_f00_implicit_step::phdp
valarray< double > self_f00_implicit_step::phdpm1
valarray< double > self_f00_implicit_step::p4dp
valarray< double > self_f00_implicit_step::laser_Inv_Uav6
valarray< double > self_f00_implicit_step::C_RB
Rosenbluth Potentials.
valarray< double > self_f00_implicit_step::D_RB
double self_f00_implicit_step::I4_Lnee
valarray< double > self_f00_implicit_step::delta_CC
Chang-Cooper weighting delta.
double self_f00_implicit_step::c_kpre
Constants.
double self_f00_implicit_step::vw_coeff_cube
Formulary self_f00_implicit_step::formulas
valarray< double > self_f00_implicit_collisions::fin
valarray< double > self_f00_implicit_collisions::fout
valarray< double > self_f00_implicit_collisions::xgrid
bool self_f00_implicit_collisions::ib
self_f00_implicit_step self_f00_implicit_collisions::collide
bool self_f00_implicit_collisions::IB_heating
Switches for inverse bremsstrahlung and maxwellian cooling.
bool self_f00_implicit_collisions::MX_cooling
valarray< double > self_f00_implicit_collisions::heatingprofile
valarray< double > self_f00_implicit_collisions::coolingprofile
int self_f00_implicit_collisions::Nbc
Number of boundary cells in each direction.
int self_f00_implicit_collisions::szx
Total cells including boundary cells in x-direction.
double self_f00_explicit_step::mass
Array output by getslope.
valarray< double > self_f00_explicit_step::vr
Define the velocity axis.
valarray< double > self_f00_explicit_step::U4
Various coefficients for the integrals.
valarray< double > self_f00_explicit_step::U4m1
valarray< double > self_f00_explicit_step::U2
valarray< double > self_f00_explicit_step::U2m1
valarray< double > self_f00_explicit_step::U1
valarray< double > self_f00_explicit_step::U1m1
valarray< double > self_f00_explicit_step::U3
valarray< double > self_f00_explicit_step::Qn
valarray< double > self_f00_explicit_step::Pn
valarray< double > self_f00_explicit_step::J1
The integrals.
valarray< double > self_f00_explicit_step::I2
valarray< double > self_f00_explicit_step::I4
double self_f00_explicit_step::c_kpre
Constants.
int self_f00_explicit_step::NB
Formulary self_f00_explicit_step::formulas
self_f00_explicit_step self_f00_RKfunctor::collide
valarray< double > self_f00_explicit_collisions::fin
Algorithms::RK4< valarray< double > > self_f00_explicit_collisions::RK
self_f00_RKfunctor self_f00_explicit_collisions::rkf00
size_t self_f00_explicit_collisions::num_h
double self_f00_explicit_collisions::h
int self_f00_explicit_collisions::Nbc
Number of boundary cells in each direction.
int self_f00_explicit_collisions::szx
Total cells including boundary cells in x-direction.
valarray< double > self_flm_implicit_step::vr
valarray< double > self_flm_implicit_step::U4
valarray< double > self_flm_implicit_step::U4m1
valarray< double > self_flm_implicit_step::U2
valarray< double > self_flm_implicit_step::U2m1
valarray< double > self_flm_implicit_step::U1
valarray< double > self_flm_implicit_step::U1m1
valarray< double > self_flm_implicit_step::J1m
valarray< double > self_flm_implicit_step::I0
valarray< double > self_flm_implicit_step::I2
valarray< double > self_flm_implicit_step::df0
valarray< double > self_flm_implicit_step::ddf0
valarray< double > self_flm_implicit_step::Scattering_Term
Array2D< double > self_flm_implicit_step::Alpha_Tri
bool self_flm_implicit_step::if_tridiagonal
double self_flm_implicit_step::mass
double self_flm_implicit_step::I0_density
double self_flm_implicit_step::I2_temperature
double self_flm_implicit_step::_ZLOGei
double self_flm_implicit_step::_LOGee
double self_flm_implicit_step::kpre
double self_flm_implicit_step::Dt
Formulary self_flm_implicit_step::formulas
double self_flm_implicit_collisions::Dt
int self_flm_implicit_collisions::Nbc
Number of boundary cells in each direction.
int self_flm_implicit_collisions::szx
Total cells including boundary cells in x-direction.
int self_flm_implicit_collisions::f1_m_upperlimit
size_t self_flm_implicit_collisions::l0
Number of m harmonics.
size_t self_flm_implicit_collisions::m0
Number of m harmonics.
valarray< complex< double > > self_flm_implicit_collisions::fc
Dummy array.
valarray< double > self_flm_implicit_collisions::f00
Array for isotropic component distribution function. Needed for calculating coefficients.
self_flm_implicit_step self_flm_implicit_collisions::implicit_step
The object that is responsible for performing the algebra required for the integrals.
self_f00_explicit_collisions self_collisions::self_f00_exp_collisions
self_f00_implicit_collisions self_collisions::self_f00_imp_collisions
self_flm_implicit_collisions self_collisions::self_flm_collisions
State1D collisions::Yh
vector< self_collisions > collisions::self_coll
valarray< double > interspecies_f00_explicit_step::fslope
double interspecies_f00_explicit_step::dt
Formulary interspecies_f00_explicit_step::formulary
double interspecies_f00_explicit_step::m1
double interspecies_f00_explicit_step::m2
double interspecies_f00_explicit_step::z1
double interspecies_f00_explicit_step::z2
double interspecies_f00_explicit_step::n1
double interspecies_f00_explicit_step::n2
double interspecies_f00_explicit_step::T1
double interspecies_f00_explicit_step::T2
double interspecies_f00_explicit_step::Gamma12
double interspecies_f00_explicit_step::kpre
valarray< double > interspecies_f00_explicit_step::pgrid_s1
valarray< double > interspecies_f00_explicit_step::pgrid_s2
valarray< double > interspecies_f00_explicit_step::df0
valarray< double > interspecies_f00_explicit_step::U4
valarray< double > interspecies_f00_explicit_step::U4m1
valarray< double > interspecies_f00_explicit_step::U2
valarray< double > interspecies_f00_explicit_step::U2m1
valarray< double > interspecies_f00_explicit_step::U1
valarray< double > interspecies_f00_explicit_step::U1m1
valarray< double > interspecies_f00_explicit_step::U3
valarray< double > interspecies_f00_explicit_step::Qn
valarray< double > interspecies_f00_explicit_step::Pn
valarray< double > interspecies_f00_explicit_step::J1_s2
The integrals.
valarray< double > interspecies_f00_explicit_step::I2_s2
valarray< double > interspecies_f00_explicit_step::I4_s2
valarray< double > interspecies_f00_explicit_step::J1_s1
The integrals.
valarray< double > interspecies_f00_explicit_step::I2_s1
valarray< double > interspecies_f00_explicit_step::I4_s1
int interspecies_f00_explicit_step::Nbc
Number of boundary cells in each direction.
int interspecies_f00_explicit_step::szx
Total cells including boundary cells in x-direction.
interspecies_f00_explicit_step interspecies_f00_RKfunctor::collide
interspecies_f00_RKfunctor interspecies_f00_explicit_collisions::rkf00
valarray< double > interspecies_f00_explicit_collisions::fin1
valarray< double > interspecies_f00_explicit_collisions::fin2
Algorithms::RK4< valarray< double > > interspecies_f00_explicit_collisions::RK4
size_t interspecies_f00_explicit_collisions::num_h
double interspecies_f00_explicit_collisions::h
int interspecies_f00_explicit_collisions::Nbc
Number of boundary cells in each direction.
int interspecies_f00_explicit_collisions::szx
Total cells including boundary cells in x-direction.
valarray< double > interspecies_flm_implicit_step::vr
valarray< double > interspecies_flm_implicit_step::U4
valarray< double > interspecies_flm_implicit_step::U4m1
valarray< double > interspecies_flm_implicit_step::U2
valarray< double > interspecies_flm_implicit_step::U2m1
valarray< double > interspecies_flm_implicit_step::U1
valarray< double > interspecies_flm_implicit_step::U1m1
valarray< double > interspecies_flm_implicit_step::J1m
valarray< double > interspecies_flm_implicit_step::I0
valarray< double > interspecies_flm_implicit_step::I2
valarray< double > interspecies_flm_implicit_step::df0
valarray< double > interspecies_flm_implicit_step::ddf0
valarray< double > interspecies_flm_implicit_step::Scattering_Term
Array2D< double > interspecies_flm_implicit_step::Alpha_Tri
bool interspecies_flm_implicit_step::if_tridiagonal
double interspecies_flm_implicit_step::I0_density
double interspecies_flm_implicit_step::I2_temperature
double interspecies_flm_implicit_step::_ZLOGei
double interspecies_flm_implicit_step::_LOGee
double interspecies_flm_implicit_step::kpre
double interspecies_flm_implicit_step::Dt
Formulary interspecies_flm_implicit_step::formulas
double interspecies_flm_implicit_collisions::Dt
int interspecies_flm_implicit_collisions::Nbc
Number of boundary cells in each direction.
int interspecies_flm_implicit_collisions::szx
Total cells including boundary cells in x-direction.
size_t interspecies_flm_implicit_collisions::l0
Number of m harmonics.
size_t interspecies_flm_implicit_collisions::m0
Number of m harmonics.
valarray< complex< double > > interspecies_flm_implicit_collisions::fc
Dummy array.
valarray< double > interspecies_flm_implicit_collisions::f00
Array for isotropic component distribution function. Needed for calculating coefficients.
interspecies_flm_implicit_step interspecies_flm_implicit_collisions::implicit_step
The object that is responsible for performing the algebra required for the integrals.
vector< interspecies_f00_explicit_collisions > interspecies_collisions::interspecies_f00_collisions
SHarmonic1D Spatial_Advection_1D::fd1
SHarmonic1D Spatial_Advection_1D::fd2
complex< double > Spatial_Advection_1D::A00
complex< double > Spatial_Advection_1D::A10
complex< double > Spatial_Advection_1D::A20
Array2D< complex< double > > Spatial_Advection_1D::A1
Array2D< complex< double > > Spatial_Advection_1D::A2
valarray< complex< double > > Spatial_Advection_1D::vr
SHarmonic1D Electric_Field_1D::H
SHarmonic1D Electric_Field_1D::G
SHarmonic1D Electric_Field_1D::TMP
complex< double > Electric_Field_1D::A100
complex< double > Electric_Field_1D::C100
complex< double > Electric_Field_1D::A210
complex< double > Electric_Field_1D::B211
complex< double > Electric_Field_1D::C311
complex< double > Electric_Field_1D::A310
Array2D< complex< double > > Electric_Field_1D::A1
Array2D< complex< double > > Electric_Field_1D::A2
valarray< complex< double > > Electric_Field_1D::B1
valarray< complex< double > > Electric_Field_1D::B2
valarray< complex< double > > Electric_Field_1D::C1
valarray< complex< double > > Electric_Field_1D::C3
Array2D< complex< double > > Electric_Field_1D::C2
Array2D< complex< double > > Electric_Field_1D::C4
valarray< complex< double > > Electric_Field_1D::pr
valarray< complex< double > > Electric_Field_1D::invpr
valarray< complex< double > > Electric_Field_1D::Hp0
SHarmonic1D Magnetic_Field_1D::FLM
valarray< complex< double > > Magnetic_Field_1D::A1
valarray< complex< double > > Magnetic_Field_1D::B1
Array2D< complex< double > > Magnetic_Field_1D::A2
complex< double > Magnetic_Field_1D::A3
Field1D Current_1D::Jx
Field1D Current_1D::Jy
Field1D Current_1D::Jz
double Current_1D::small
Field1D Faraday_1D::tmpE
complex< double > Faraday_1D::idx
size_t Faraday_1D::numx
Field1D Ampere_1D::tmpB
complex< double > Ampere_1D::idx
size_t Ampere_1D::numx
Detailed Description
These are all the VFP objects used to describe the evolution of distribution function in the 1D code
Spatial Advection
Electric Field
Electron-electron collisions on
Electron-ion and electron-electron collisions on
Function Documentation
advance() [1/3]
void interspecies_flm_implicit_step::advance (valarray< complex< double > > & fin, const int el)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Perform a matrix solve to calculate effect of collisions on f >= 1.
Parameters
fin Input distribution function
[in] el Number of elements in matrix (?)
Definition at line 568 of file interspeciescollisions.cpp.
References interspecies_flm_implicit_step::_LOGee, interspecies_flm_implicit_step::Alpha_Tri, interspecies_flm_implicit_step::ddf0, interspecies_flm_implicit_step::df0, Array2D< T >::dim1(), Array2D< T >::dim2(), interspecies_flm_implicit_step::Dt, Gauss_Seidel(), interspecies_flm_implicit_step::if_tridiagonal, interspecies_flm_implicit_step::kpre, interspecies_flm_implicit_step::Scattering_Term, Thomas_Tridiagonal(), and interspecies_flm_implicit_step::vr.
Referenced by interspecies_flm_implicit_collisions::advancef1(), and interspecies_flm_implicit_collisions::advanceflm().
{
 //-------------------------------------------------------------------
 //  Collisions
 //-------------------------------------------------------------------
         Array2D<double> Alpha(Alpha_Tri);
         valarray<complex<double> > fout(fin);
 //      ZEROTH CELL FOR TRIDIAGONAL ARRAY
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         if (el > 1) {
             Alpha(0,0) = 0.0;
         }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        if ( !(if_tridiagonal) ) {
 //         CONSTRUCT COEFFICIENTS and then full array
 //         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
            double LL(el);
            double A1(         (LL+1.0)*(LL+2.0) / ((2.0*LL+1.0)*(2.0*LL+3.0)) );
            double A2( (-1.0) *(LL-1.0)* LL      / ((2.0*LL+1.0)*(2.0*LL-1.0)) );
            double B1( (-1.0) *( 0.5 *LL*(LL+1.0) +(LL+1.0) ) / ((2.0*LL+1.0)*(2.0*LL+3.0)) );
            double B2( (       (-0.5)*LL*(LL+1.0) +(LL+2.0) ) / ((2.0*LL+1.0)*(2.0*LL+3.0)) );
            double B3(         ( 0.5 *LL*(LL+1.0) +(LL-1.0) ) / ((2.0*LL+1.0)*(2.0*LL-1.0)) );
            double B4(         ( 0.5 *LL*(LL+1.0) - LL      ) / ((2.0*LL+1.0)*(2.0*LL-1.0)) );
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
            for (int i(0); i < Alpha.dim1()-1; ++i){
                double t1( A1*ddf0[i] + B1*df0[i] );
                       t1 *= (-1.0) * _LOGee * kpre * Dt;
                double t2( A1*ddf0[i] + B2*df0[i] );
                       t2 *= (-1.0) * _LOGee * kpre * Dt;
                double t3( A2*ddf0[i] + B3*df0[i] );
                       t3 *= (-1.0) * _LOGee * kpre * Dt;
                double t4( A2*ddf0[i] + B4*df0[i] );
                       t4 *= (-1.0) * _LOGee * kpre * Dt;
                Alpha(i,0) += t1 * ( 2.0*M_PI*pow(vr[0]/vr[i],el+2)*vr[0]*vr[0]*(vr[1]-vr[0]) );
                Alpha(i,0) += t3 * ( 2.0*M_PI*pow(vr[0]/vr[i],el)  *vr[0]*vr[0]*(vr[1]-vr[0]) );
                for (int j(1); j < i; ++j){
                    Alpha(i,j) += t1 * ( 2.0*M_PI*pow(vr[j]/vr[i],el+2)*vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
                    Alpha(i,j) += t3 * ( 2.0*M_PI*pow(vr[j]/vr[i],el)  *vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
                }
                Alpha(i,i) += t1 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i]-vr[i-1]) );
                Alpha(i,i) += t3 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i]-vr[i-1]) );
                Alpha(i,i) += t2 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i+1]-vr[i]) );
                Alpha(i,i) += t4 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i+1]-vr[i]) );
                for (int j(i+1); j < Alpha.dim2()-1; ++j){
                    Alpha(i,j) += t2 * ( 2.0*M_PI*pow(vr[j]/vr[i],-el-1)*vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
                    Alpha(i,j) += t4 * ( 2.0*M_PI*pow(vr[j]/vr[i],-el+1)*vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
                }
            }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        }
 //      INCLUDE SCATTERING TERM
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         double ll1(static_cast<double>(el));
         ll1 *= (-0.5)*(ll1 + 1.0);
         for (int i(0); i < Alpha.dim1(); ++i){
             Alpha(i,i) += 1.0 - ll1 * Scattering_Term[i];
         }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      SOLVE A * Fout  = Fin
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         //for (int i(0); i < fin.size(); ++i){   // Estimate Fout = Fin /  A(i,i)
         //    fout[i] /= Alpha(i,i);
         //}
         if ( if_tridiagonal ) {
             if ( !(Thomas_Tridiagonal(Alpha, fin, fout)) ) {  // Invert A * fout = fin
                 cout << "WARNING: Matrix is not diagonally dominant" << endl;
             }
         }
         else {
             if ( !(Gauss_Seidel(Alpha, fin, fout)) ) {  // Invert A * fout = fin
                  cout << "WARNING: Matrix is not diagonally dominant" << endl;
              }
         }
         fin = fout;
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     }
advance() [2/3]
void self_flm_implicit_step::advance (valarray< complex< double > > & fin, const int el)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Perform a matrix solve to calculate effect of collisions on f >= 1.
Parameters
fin Input distribution function
[in] el Number of elements in matrix (?)
SOLVE A * Fout = Fin
Definition at line 1126 of file collisions.cpp.
References self_flm_implicit_step::_LOGee, self_flm_implicit_step::Alpha_Tri, self_flm_implicit_step::ddf0, self_flm_implicit_step::df0, Array2D< T >::dim1(), Array2D< T >::dim2(), self_flm_implicit_step::Dt, Gauss_Seidel(), self_flm_implicit_step::if_tridiagonal, self_flm_implicit_step::kpre, self_flm_implicit_step::Scattering_Term, Thomas_Tridiagonal(), and self_flm_implicit_step::vr.
Referenced by self_flm_implicit_collisions::advancef1(), and self_flm_implicit_collisions::advanceflm().
{
 //-------------------------------------------------------------------
 //  Collisions
 //-------------------------------------------------------------------
     Array2D<double> Alpha(Alpha_Tri);
     valarray<complex<double> > fout(fin);
 //      ZEROTH CELL FOR TRIDIAGONAL ARRAY
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     if (el > 1) {
         Alpha(0,0) = 0.0;
     }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     if ( !(if_tridiagonal) ) {
 //         CONSTRUCT COEFFICIENTS and then full array
 //         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         double LL(el);
         double A1(         (LL+1.0)*(LL+2.0) / ((2.0*LL+1.0)*(2.0*LL+3.0)) );
         double A2( (-1.0) *(LL-1.0)* LL      / ((2.0*LL+1.0)*(2.0*LL-1.0)) );
         double B1( (-1.0) *( 0.5 *LL*(LL+1.0) +(LL+1.0) ) / ((2.0*LL+1.0)*(2.0*LL+3.0)) );
         double B2( (       (-0.5)*LL*(LL+1.0) +(LL+2.0) ) / ((2.0*LL+1.0)*(2.0*LL+3.0)) );
         double B3(         ( 0.5 *LL*(LL+1.0) +(LL-1.0) ) / ((2.0*LL+1.0)*(2.0*LL-1.0)) );
         double B4(         ( 0.5 *LL*(LL+1.0) - LL      ) / ((2.0*LL+1.0)*(2.0*LL-1.0)) );
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         for (int i(0); i < Alpha.dim1()-1; ++i){
             double t1( A1*ddf0[i] + B1*df0[i] );
             t1 *= (-1.0) * _LOGee * kpre * Dt;
             double t2( A1*ddf0[i] + B2*df0[i] );
             t2 *= (-1.0) * _LOGee * kpre * Dt;
             double t3( A2*ddf0[i] + B3*df0[i] );
             t3 *= (-1.0) * _LOGee * kpre * Dt;
             double t4( A2*ddf0[i] + B4*df0[i] );
             t4 *= (-1.0) * _LOGee * kpre * Dt;
             Alpha(i,0) += t1 * ( 2.0*M_PI*pow(vr[0]/vr[i],el+2)*vr[0]*vr[0]*(vr[1]-vr[0]) );
             Alpha(i,0) += t3 * ( 2.0*M_PI*pow(vr[0]/vr[i],el)  *vr[0]*vr[0]*(vr[1]-vr[0]) );
             for (int j(1); j < i; ++j){
                 Alpha(i,j) += t1 * ( 2.0*M_PI*pow(vr[j]/vr[i],el+2)*vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
                 Alpha(i,j) += t3 * ( 2.0*M_PI*pow(vr[j]/vr[i],el)  *vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
             }
             Alpha(i,i) += t1 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i]-vr[i-1]) );
             Alpha(i,i) += t3 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i]-vr[i-1]) );
             Alpha(i,i) += t2 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i+1]-vr[i]) );
             Alpha(i,i) += t4 * ( 2.0*M_PI *vr[i]*vr[i]*(vr[i+1]-vr[i]) );
             for (int j(i+1); j < Alpha.dim2()-1; ++j){
                 Alpha(i,j) += t2 * ( 2.0*M_PI*pow(vr[j]/vr[i],-el-1)*vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
                 Alpha(i,j) += t4 * ( 2.0*M_PI*pow(vr[j]/vr[i],-el+1)*vr[j]*vr[j]*(vr[j+1]-vr[j-1]) );
             }
         }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     }
 //      INCLUDE SCATTERING TERM
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     double ll1(static_cast<double>(el));
     ll1 *= (-0.5)*(ll1 + 1.0);
     for (int i(0); i < Alpha.dim1(); ++i){
         Alpha(i,i) += 1.0 - ll1 * Scattering_Term[i];
     }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //    for (int i(0); i < fin.size(); ++i){   // Estimate Fout = Fin /  A(i,i)
 //        fout[i] /= Alpha(i,i);
 //    }
     if ( if_tridiagonal ) {
         if ( !(Thomas_Tridiagonal(Alpha, fin, fout)) ) {  // Invert A * fout = fin
             cout << "WARNING: Matrix is not diagonally dominant" << endl;
         }
     }
     else {
         if ( !(Gauss_Seidel(Alpha, fin, fout)) ) {  // Invert A * fout = fin
             cout << "WARNING: Matrix is not diagonally dominant" << endl;
         }
     }
     fin = fout;
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
advance() [3/3]
void collisions::advance (State1D & Y, const Clock & W)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1417 of file collisions.cpp.
References collisions::advancef0(), collisions::advancef1(), collisions::advanceflm(), State1D::DF(), DistFunc1D::dim(), Input::List(), State1D::Species(), and collisions::Yh.
Referenced by main().
 {
     Yh = complex<double>(0.0,0.0);
     if (Input::List().f00_implicitorexplicit > 0) advancef0(Yin,W,Yh);
     if (Input::List().flm_collisions){
         advancef1(Yin,Yh);
         advanceflm(Yin,Yh);
     }
     for (size_t s(0); s < Yin.Species(); ++s){
         for (size_t i(0); i < Yin.DF(s).dim(); ++i){
             Yin.DF(s)(i) = Yh.DF(s)(i);
         }
     }
 }
advancef0()
void collisions::advancef0 (State1D & Y, const Clock & W, State1D & Yh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1436 of file collisions.cpp.
References State1D::DF(), State1D::HYDRO(), collisions::self_coll, State1D::Species(), Clock::time(), and Hydro1D::Zarray().
Referenced by collisions::advance().
 {
     size_t sdummy(0);
     for(size_t s(0); s < Yin.Species(); ++s)
     {
         self_coll[s].advancef00(Yin.DF(s)(0,0),Yin.HYDRO().Zarray(),W.time(),Yh.DF(s)(0,0));
         if (Yin.Species() > 1)
         {
             for (size_t sind(0); sind < Yin.Species(); ++sind){
                 // std::cout << "\n\n sdummy = " << sdummy << ",sind = " << sind << ", s = " << s << "\n\n";
                 if (s!=sind)  {
                     // std::cout << "\n\n12\n\n";
                     // unself_f00_coll[sdummy].rkloop(Yin.SH(s,0,0),Yin.SH(sind,0,0)); ++sdummy;
                 }
             }
         }
         // Yin.DF(s).checknan();
     }
 }
advancef00() [1/2]
void interspecies_collisions::advancef00 (State1D & Yin, const size_t & sind)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Remap Distribution to momentum grid of colliding particles.
Advance f00 collisions for all species
Definition at line 837 of file interspeciescollisions.cpp.
References State1D::SH(), and State1D::Species().
{
 // //-------------------------------------------------------------------
       // size_t sind(0);
       for (size_t s(0); s<Yin.Species(); ++s){
             if (s!=sind) {
               interspecies_f00_collisions[sind].rkloop(Yin.SH(sind,0,0),Yin.SH(s,0,0));
               std::cout << "\n\n sind,s = " << sind << "," << s << "\n\n";
               // ++sind;
           }
       }
 }
advancef00() [2/2]
void self_collisions::advancef00 (SHarmonic1D & f00, valarray< double > & Zarray, const double time, SHarmonic1D & f00h)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1369 of file collisions.cpp.
References Input::List(), self_f00_implicit_collisions::loop(), self_f00_explicit_collisions::loop(), self_collisions::self_f00_exp_collisions, and self_collisions::self_f00_imp_collisions.
{
 //-------------------------------------------------------------------
     if (Input::List().f00_implicitorexplicit){
         if (Input::List().f00_implicitorexplicit == 2) {
             self_f00_imp_collisions.loop(f00,Zarray,time,f00h);
         }
         else if (Input::List().f00_implicitorexplicit == 1) {
             self_f00_exp_collisions.loop(f00,f00h);
         }
     }
 }
advancef1() [1/4]
void interspecies_flm_implicit_collisions::advancef1 (DistFunc1D & DF)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Advance f1_loop for 2D code.
Definition at line 694 of file interspeciescollisions.cpp.
References interspecies_flm_implicit_step::advance(), interspecies_flm_implicit_collisions::Dt, interspecies_flm_implicit_collisions::f00, interspecies_flm_implicit_collisions::fc, interspecies_flm_implicit_collisions::implicit_step, interspecies_flm_implicit_collisions::Nbc, interspecies_flm_implicit_step::reset_coeff(), and interspecies_flm_implicit_collisions::szx.
{
 //-------------------------------------------------------------------
 //  This is the calculation for the harmonics f10, f11
 //    To be specific, this routine does just l=1
 //    To be specific, this routine differs from 'f1_loop1D' above only in one place: the loop is on m=0 and m=1
 //-------------------------------------------------------------------
         // For every location in space within the domain of this node
       for (size_t ix(0); ix < szx-2*Nbc; ++ix){
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                // "00" harmonic --> Valarray
             for (size_t ip(0); ip < fc.size(); ++ip){
               f00[ip] = (DF(0,0)(ip,ix+Nbc)).real();
             }
                // Reset the integrals and coefficients
             implicit_step.reset_coeff(f00, Dt);
                // Loop over the harmonics for this (x,y)
             for(int m(0); m < 2; ++m){
                   // This harmonic --> Valarray
                   for (int ip(0); ip < DF(1,m).nump(); ++ip) {
                       fc[ip] = DF(1,m)(ip,ix+Nbc);
                   }
         // Take an implicit step
                   implicit_step.advance(fc, 1);
           //  Valarray --> This harmonic
                   for (int ip(0); ip < DF(1,m).nump(); ++ip) {
                       DF(1,m)(ip,ix+Nbc) = fc[ip];
                   }
             }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           }
     }
advancef1() [2/4]
void self_flm_implicit_collisions::advancef1 (DistFunc1D & DF, valarray< double > & Zarray, DistFunc1D & DFh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Advance f1_loop for 2D code.
Definition at line 1266 of file collisions.cpp.
References self_flm_implicit_step::advance(), self_flm_implicit_collisions::Dt, self_flm_implicit_collisions::f00, self_flm_implicit_collisions::f1_m_upperlimit, self_flm_implicit_collisions::fc, self_flm_implicit_collisions::implicit_step, self_flm_implicit_step::reset_coeff(), and self_flm_implicit_collisions::szx.
Referenced by self_collisions::advancef1().
{
 //-------------------------------------------------------------------
 //  This is the collision calculation for the harmonics f10, f11
 //-------------------------------------------------------------------
 // For every location in space within the domain of this node
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t ix(0); ix < szx; ++ix){
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         // "00" harmonic --> Valarray
         for (size_t ip(0); ip < fc.size(); ++ip){
             f00[ip] = (DF(0,0)(ip,ix)).real();
         }
         // Reset the integrals and coefficients
         implicit_step.reset_coeff(f00, Zarray[ix], Dt);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         // Loop over the harmonics for this (x,y)
         for(int m(0); m < f1_m_upperlimit; ++m){
             // This harmonic --> Valarray
             for (int ip(0); ip < DF(1,m).nump(); ++ip) {
                 fc[ip] = DF(1,m)(ip,ix);
             }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
             // Take an implicit step
             implicit_step.advance(fc, 1);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
             //  Valarray --> This harmonic
             for (int ip(0); ip < DF(1,m).nump(); ++ip) {
                 DFh(1,m)(ip,ix) = fc[ip];
             }
         }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     }
 }
advancef1() [3/4]
void self_collisions::advancef1 (DistFunc1D & DF, valarray< double > & Zarray, DistFunc1D & DFh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1389 of file collisions.cpp.
References self_flm_implicit_collisions::advancef1(), and self_collisions::self_flm_collisions.
{
 //-------------------------------------------------------------------
     self_flm_collisions.advancef1(DFin,Zarray,DFh);
 }
advancef1() [4/4]
void collisions::advancef1 (State1D & Y, State1D & Yh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1467 of file collisions.cpp.
References State1D::DF(), State1D::HYDRO(), collisions::self_coll, State1D::Species(), and Hydro1D::Zarray().
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), and collisions::advance().
 {
     size_t sdummy(0);
     for(size_t s(0); s < Yin.Species(); ++s)
     {
         self_coll[s].advancef1(Yin.DF(s), Yin.HYDRO().Zarray(), Yh.DF(s) );
         if (Yin.Species() > 1)
         {
             for (size_t sind(0); sind < Yin.Species(); ++sind){
                 if (s!=sind)  {
                 }
             }
         }
     }
 }
advanceflm() [1/4]
void interspecies_flm_implicit_collisions::advanceflm (DistFunc1D & DF)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Advance flm_loop for 2D code.
Definition at line 737 of file interspeciescollisions.cpp.
References interspecies_flm_implicit_step::advance(), interspecies_flm_implicit_collisions::Dt, interspecies_flm_implicit_collisions::f00, interspecies_flm_implicit_collisions::fc, interspecies_flm_implicit_collisions::implicit_step, interspecies_flm_implicit_collisions::l0, interspecies_flm_implicit_collisions::m0, interspecies_flm_implicit_collisions::Nbc, interspecies_flm_implicit_step::reset_coeff(), and interspecies_flm_implicit_collisions::szx.
     {
 //-------------------------------------------------------------------
 //  This is the calculation for the high order harmonics
 //    To be specific, this routine does l=2 to l0
 //    To be specific, this routine differs from 'flm_loop1D' aboe only in one place: the loop over m all m from 0 to ((m0 < l)? m0:l)
 //-------------------------------------------------------------------
         // For every location in space within the domain of this node
         for (size_t ix(0); ix < szx-2*Nbc; ++ix){
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                // "00" harmonic --> Valarray
             for (size_t ip(0); ip < fc.size(); ++ip){
                 f00[ip] = (DF(0,0)(ip,ix+Nbc)).real();
             }
             // Reset the integrals and coefficients
             // --> Assume you did that when you called f1_loop
             implicit_step.reset_coeff(f00, Dt);
             // Loop over the harmonics for this (x,y)
             for(int l(2); l < l0+1 ; ++l){
                 for(int m(0); m < ((m0 < l)? m0:l)+1; ++m){
                     // This harmonic --> Valarray
                     for (size_t ip(0); ip < fc.size(); ++ip){
                         fc[ip] = (DF(l,m))(ip,ix+Nbc);
                     }
                     // Take an implicit step
                     implicit_step.advance(fc, l);
                     //  Valarray --> This harmonic
                     for (size_t ip(0); ip < fc.size(); ++ip){
                         DF(l,m)(ip,ix+Nbc) = fc[ip];
                     }
                 }
         }
     }
     return;
     }
advanceflm() [2/4]
void self_flm_implicit_collisions::advanceflm (DistFunc1D & DF, valarray< double > & Zarray, DistFunc1D & DFh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Advance flm_loop for 2D code.
Definition at line 1310 of file collisions.cpp.
References self_flm_implicit_step::advance(), self_flm_implicit_collisions::Dt, self_flm_implicit_collisions::f00, self_flm_implicit_collisions::fc, self_flm_implicit_collisions::implicit_step, self_flm_implicit_collisions::l0, self_flm_implicit_collisions::m0, self_flm_implicit_step::reset_coeff(), and self_flm_implicit_collisions::szx.
Referenced by self_collisions::advanceflm().
 {
 //-------------------------------------------------------------------
 //  This is the calculation for the high order harmonics
 //    To be specific, this routine does l=2 to l0
 //    To be specific, this routine differs from 'flm_loop1D' aboe only in one place: the loop over m all m from 0 to ((m0 < l)? m0:l)
 //-------------------------------------------------------------------
     // For every location in space within the domain of this node
     for (size_t ix(0); ix < szx; ++ix){
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         // "00" harmonic --> Valarray
         for (size_t ip(0); ip < fc.size(); ++ip){
             f00[ip] = (DF(0,0)(ip,ix)).real();
         }
         // Reset the integrals and coefficients
         // --> Assume you did that when you called f1_loop
         implicit_step.reset_coeff(f00, Zarray[ix], Dt);
         // Loop over the harmonics for this (x,y)
         for(int l(2); l < l0+1 ; ++l){
             for(int m(0); m < ((m0 < l)? m0:l)+1; ++m){
 //                std::cout << "(l,m) = " << l << "," << m << "\n";
                 // This harmonic --> Valarray
                 for (size_t ip(0); ip < fc.size(); ++ip){
                     fc[ip] = (DF(l,m))(ip,ix);
                 }
                 // Take an implicit step
                 implicit_step.advance(fc, l);
                 //  Valarray --> This harmonic
                 for (size_t ip(0); ip < fc.size(); ++ip){
                     DFh(l,m)(ip,ix) = fc[ip];
                 }
             }
         }
     }
     // return;
 }
advanceflm() [3/4]
void self_collisions::advanceflm (DistFunc1D & DF, valarray< double > & Zarray, DistFunc1D & DFh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1383 of file collisions.cpp.
References self_flm_implicit_collisions::advanceflm(), and self_collisions::self_flm_collisions.
{
 //-------------------------------------------------------------------
     self_flm_collisions.advanceflm(DFin,Zarray,DFh);
 }
advanceflm() [4/4]
void collisions::advanceflm (State1D & Y, State1D & Yh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1492 of file collisions.cpp.
References State1D::DF(), State1D::HYDRO(), collisions::self_coll, State1D::Species(), and Hydro1D::Zarray().
Referenced by collisions::advance().
 {
     size_t sdummy(0);
     for(size_t s(0); s < Yin.Species(); ++s)
     {
         self_coll[s].advanceflm(Yin.DF(s), Yin.HYDRO().Zarray(), Yh.DF(s) );
         if (Yin.Species() > 1)
         {
             for (size_t sind(0); sind < Yin.Species(); ++sind){
                 if (s!=sind)  {
                 }
             }
         }
         // Yin.DF(s).checknan();
     }
 }
Ampere_1D()
Ampere_1D::Ampere_1D (double xmin, double xmax, size_t Nx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1379 of file vlasov.cpp.
References Ampere_1D::idx.
         : tmpB(Nx), numx(Nx) {
     idx = complex<double>((-1.0)/ (2.0*(xmax-xmin)/double(Nx))); // -1/(2dx)
 }
calc_delta_ChangCooper()
double self_f00_implicit_step::calc_delta_ChangCooper (const size_t & k, const double & C, const double & D) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 224 of file collisions.cpp.
References self_f00_implicit_step::dvr.
Referenced by self_f00_implicit_step::update_D_and_delta().
{
     double answer(0.5);
     double W = 0.5*(dvr[k-1]+dvr[k])*C/D;
     if (W > 1.0e-8){
         answer = 1.0/W - 1.0/(exp(W)-1.0);
     }
     return answer;
 }
calculateintegrals()
void interspecies_f00_explicit_step::calculateintegrals (const valarray< double > & f1in, const valarray< double > & f2in) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Remap Distribution to momentum grid of colliding particles.
Pause for density and temperature
The other density and temperature
Definition at line 198 of file interspeciescollisions.cpp.
References interspecies_f00_explicit_step::I2_s2, interspecies_f00_explicit_step::I4_s2, interspecies_f00_explicit_step::J1_s2, interspecies_f00_explicit_step::m1, interspecies_f00_explicit_step::m2, Algorithms::moment(), interspecies_f00_explicit_step::n1, interspecies_f00_explicit_step::n2, interspecies_f00_explicit_step::pgrid_s1, interspecies_f00_explicit_step::T1, interspecies_f00_explicit_step::T2, interspecies_f00_explicit_step::U1, interspecies_f00_explicit_step::U1m1, interspecies_f00_explicit_step::U2, interspecies_f00_explicit_step::U2m1, interspecies_f00_explicit_step::U4, and interspecies_f00_explicit_step::U4m1.
Referenced by interspecies_f00_explicit_step::takestep().
{
 //     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //     Evaluate the integrals in a standard manner
        I4_s2[0] = 0;
        for (int n(1); n < I4_s2.size(); ++n) {
            I4_s2[n]  = U4[n]*f2in[n]+U4m1[n]*f2in[n-1];
            I4_s2[n] += I4_s2[n-1];
             // std::cout << "\n I4= " << I4_s2[n] << "\n\n";
        }
        I2_s2[0] = 0;
        for (int n(1); n < I2_s2.size(); ++n) {
            I2_s2[n]  = U2[n]*f2in[n]+U2m1[n]*f2in[n-1];
            I2_s2[n] += I2_s2[n-1];
            // std::cout << "\n I2= " << I2_s2[n] << "\n\n";
        }
        n2 = (4.0*M_PI*I2_s2[I2_s2.size()-1]);
        T2 = m2*(I4_s2[I4_s2.size()-1]/3.0/I2_s2[I2_s2.size()-1]);
        // std::cout << "\n n2= " << n2 << "\n\n";
        // std::cout << "\n T2= " << T2 << "\n\n";
        J1_s2[J1_s2.size()-1] = 0;
        for (int n(J1_s2.size()-2); n > -1; --n) {
            J1_s2[n]  = U1[n+1]*f2in[n+1]+U1m1[n+1]*f2in[n];
            J1_s2[n] += J1_s2[n+1];
        }
        // for (int k(0); k < I2_s2.size(); ++k){
        //     I4_s2[k] /= pgrid_s2[k]*pgrid_s2[k];
        //     J1_s2[k] *= pgrid_s2[k];
        // }
        I4_s2 *= 4.0 * M_PI;
        I2_s2 *= 4.0 * M_PI;
        J1_s2 *= 4.0 * M_PI;
        // for (size_t ip(0); ip < f1in.size() ; ++ip)
        // {
        //    std::cout << "f1[" << pgrid_s1[ip] << "] = " << f1in[ip] << "\n";
        //    // f1[ip]=f1in[ip];
        // }
        n1 = 4.0*M_PI*(Algorithms::moment(f1in,pgrid_s1,2.0));
        T1 = 4.0*M_PI*m1*(Algorithms::moment(f1in,pgrid_s1,4.0))/3.0/n1;
        // exit(1);
 }
collisions()
collisions::collisions (const State1D & Yin, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Constructors/Destructors.
Definition at line 1395 of file collisions.cpp.
References State1D::DF(), collisions::self_coll, and State1D::Species().
                                                               :Yh(Yin)
 //-------------------------------------------------------------------
 //  Constructor
 //-------------------------------------------------------------------
 {
     for(size_t s(0); s < Yin.Species(); ++s){
         self_coll.push_back( self_collisions(Yin.DF(s),deltat)  );
         if (Yin.Species() > 1){
             for (size_t sind(0); sind < Yin.Species(); ++sind){
 //                if (s!=sind) unself_f00_coll.push_back(interspecies_f00_explicit_collisions(Yin.DF(s),Yin.DF(sind),deltat));
             }
         }
     }
     // exit(1);
 }
Current_1D()
Current_1D::Current_1D (double pmin, double pmax, size_t Np, size_t Nx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 38 of file vlasov.cpp.
References Current_1D::small.
         : Jx(Nx), Jy(Nx), Jz(Nx), small(0.5*pmax/Np) {
 //          pr(Algorithms::MakeAxis(complex<double>(pmin),
 //                                  complex<double>(pmax),
 //                                  Np)),
 //          invg(pr) {
     small *= small; small *= small; small *= 0.5*pmax/Np;
     small *= 0.2; small *= 1.0/(1.5*pmax/Np);
 //    for (size_t i(0); i < pr.size(); ++i) {
 //        invg[i] = 1.0 / (sqrt(1.0+pr[i]*pr[i]));
 //    }
 };
Electric_Field_1D()
Electric_Field_1D::Electric_Field_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 90 of file vlasov.cpp.
References Electric_Field_1D::A1, Electric_Field_1D::A100, Electric_Field_1D::A2, Electric_Field_1D::A210, Electric_Field_1D::A310, Electric_Field_1D::B1, Electric_Field_1D::B2, Electric_Field_1D::B211, Electric_Field_1D::C1, Electric_Field_1D::C100, Electric_Field_1D::C2, Electric_Field_1D::C3, Electric_Field_1D::C311, Electric_Field_1D::C4, Electric_Field_1D::Hp0, Electric_Field_1D::invpr, and Electric_Field_1D::pr.
         : A1(Nl+1,Nm+1), A2(Nl+1,Nm+1),
           B1(Nl+1), B2(Nl+1),
           C1(Nl+1), C2(Nl+1,Nm+1), C3(Nl+1), C4(Nl+1,Nm+1),
           Hp0(Nl+1),
           H(Np,Nx), G(Np,Nx), TMP(Np,Nx),
          // pr(Algorithms::MakeAxis(complex<double>(complex<double>(pmax/2.0/Np)),
          //                         complex<double>(pmax),
          //                         Np)),
           pr(Algorithms::MakeCAxis(complex<double>(0.0),
                                   complex<double>(pmax),
                                   Np)),
           invpr(pr)
 {
 //      - - - - - - - - - - - - - - - - - - - - - - - - - - -
     complex<double> lc, mc;
 //       Inverted momentum axis
     for (size_t i(0); i < pr.size(); ++i) {
         invpr[i] = 1.0/pr[i];
     }
     double idp = (-1.0)/ (2.0*(pmax-pmin)/double(Np)); // -1/(2dp)
     // double idp = (-1.0)/ (2.0*(pmax-pmax/2.0/double(Np))/double(Np-1));
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the A1 * l/(l+1) * 1/(2Dp), A2 * (-1)/(2Dp) parameters
     for (size_t l(1); l < Nl+1; ++l){
         for (size_t m(0); m<((Nm<l)?Nm:l)+1; ++m){
             lc = complex<double>(l);
             mc = complex<double>(m);
             A1(l,m) = idp *(-1.0) *  (lc+1.0-mc)/(2.0*lc+1.0)  * lc/(lc+1.0);
             A2(l,m) = idp *              (lc+mc)/(2.0*lc+1.0);
         }
     }
     A1(0,0) = idp;
     // A2[0] is not used
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "B1, B2" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(1); l<Nl+1; ++l){
         lc = complex<double>(l);
         B1[l] = idp * lc* lc     /(2.0*lc+1.0);
         B2[l] = idp * lc*(lc+1.0)/(2.0*lc+1.0);
     }
     B2[0] = 1.0;
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "C1, C3" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(1); l<Nl+1; ++l){
         lc = complex<double>(l);
         C1[l] = (-0.5) * idp * lc /((2.0*lc+1.0)*(lc+1.0));
         C3[l] = (-0.5) * idp /(2.0*lc+1.0);
     }
     C1[0] = 0.5 * idp;
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "C2, C4" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(2); l<Nl+1; ++l){
         for (size_t m(2); m<((Nm<l)?Nm:l)+1; ++m){
             lc = complex<double>(l);
             mc = complex<double>(m);
             C2(l,m) = (0.5) * idp * lc * (lc-mc+2.0)*(lc-mc+1.0)/((2.0*lc+1.0)*(lc+1.0));
             C4(l,m) = (0.5) * idp * (lc+mc-1.0)*(lc+mc)/(2.0*lc+1.0);
         }
     }
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       -2*Dp*H at the 0 momentum cell
     Hp0[0] = 1.0 / pr[0];
     for (size_t l(1); l < Nl+1; ++l) {
         double ld(l);
         Hp0[l] = Hp0[l-1] * (pr[0]/pr[1]) * (2.0*ld+1.0)/(2.0*ld-1.0);
     }
     Hp0 *= (-2.0)*(pr[1]-pr[0]);
     A100 = complex<double>(idp);
     C100 = complex<double>(0.5*idp);
     A210 = complex<double>(1.0/3.0*idp);
     B211 = complex<double>(2.0/3.0);
     A310 = complex<double>(2.0/5.0*idp);
     C311 = complex<double>(-0.5*idp/5.0);
 }
es1d() [1/3]
void Spatial_Advection_1D::es1d (const DistFunc1D & Din, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1280 of file vlasov.cpp.
References Spatial_Advection_1D::A1, Spatial_Advection_1D::A2, Spatial_Advection_1D::fd1, Spatial_Advection_1D::fd2, DistFunc1D::l0(), DistFunc1D::mass(), SHarmonic1D::mpaxis(), and Spatial_Advection_1D::vr.
{
 //--------------------------------------------------------------
     valarray<complex<double> > vt(vr); vt *= 1.0/Din.mass();
     size_t l0(Din.l0());
     fd1 = Din(0,0);     fd1 = fd1.Dx();
     vt *= A1(0,0);                          Dh(1,0) += fd1.mpaxis(vt);
     for (size_t l(1); l < l0; ++l) {
         fd1 = Din(l,0);  //std::cout << "\n \n before dx, l = " << l << " \n";
         fd1 = fd1.Dx(); //std::cout << " \n after dx\n";
         vt *= A2(l,0)/A1(l-1,0);    fd2 = fd1;  Dh(l-1,0) += fd1.mpaxis(vt);
         vt *= A1(l,0)/A2(l  ,0);                Dh(l+1,0) += fd2.mpaxis(vt);
     }
     fd1 = Din(l0,0);            fd1 = fd1.Dx();
     vt *= A2(l0,0)/A1(l0-1,0);                 Dh(l0-1,0) += fd1.mpaxis(vt);
     // vt *= 1.0/A2(l0,0);
 }
es1d() [2/3]
void Electric_Field_1D::es1d (const DistFunc1D & Din, const Field1D & FEx, const Field1D & FEy, const Field1D & FEz, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 379 of file vlasov.cpp.
References Electric_Field_1D::A1, Electric_Field_1D::A2, Field1D::array(), Electric_Field_1D::G, Electric_Field_1D::H, DistFunc1D::l0(), Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), and Electric_Field_1D::TMP.
{
 //--------------------------------------------------------------
 //  This is the core calculation for the electric field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Ex(FEx.array());
     // valarray<complex<double> > Em(FEz.array());
     // Em *= (-1.0)*ii;
     // Em += FEy.array();
     // valarray<complex<double> > Ep(FEz.array());
     // Ep *= ii;
     // Ep += FEy.array();
     Ex *= Din.q();
     // Em *= Din.q();
     // Ep *= Din.q();
     size_t l0(Din.l0());
     // size_t m0(Din.m0());
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeG00(Din(0,0));
     Ex *= A1(0,0); TMP = G; Dh(1,0) += G.mxaxis(Ex);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(1,0),1);
     Ex *= A2(1,0) / A1(0,0);          Dh(0,0) += H.mxaxis(Ex);
     Ex *= A1(1,0) / A2(1,0); TMP = G; Dh(2,0) += G.mxaxis(Ex);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, 1 < l < l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(2); l < l0; ++l){
         MakeGH(Din(l,0),l);
         Ex *= A2(l,0) / A1(l-1,0); TMP = H;  Dh(l-1,0) += H.mxaxis(Ex);
         Ex *= A1(l,0) / A2(l,0);   TMP = G;  Dh(l+1,0) += G.mxaxis(Ex);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0,  l = l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(l0,0),l0);
     Ex *= A2(l0,0) / A1(l0-1,0); TMP = H;  Dh(l0-1,0) += H.mxaxis(Ex);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
es1d() [3/3]
void Current_1D::es1d (const DistFunc1D & Din, Field1D & FExh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 71 of file vlasov.cpp.
References DistFunc1D::getcurrent(), Current_1D::Jx, and Field1D::numx().
{
     valarray<double> temp(Din(0).numx());
     temp = Din.getcurrent(0);
     for (size_t i(0); i < Jx.numx(); ++i) {
         Jx(i) = complex<double >(temp[i]);//+4.0/3.0*3.1415926*small*Din(1,0)(1,i);
     }
     Exh += Jx;
 }
f1only() [1/3]
void Spatial_Advection_1D::f1only (const DistFunc1D & Din, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1306 of file vlasov.cpp.
References Spatial_Advection_1D::A00, Spatial_Advection_1D::A10, SHarmonic1D::Dx(), Spatial_Advection_1D::fd1, DistFunc1D::mass(), SHarmonic1D::mpaxis(), and Spatial_Advection_1D::vr.
{
 //--------------------------------------------------------------
     valarray<complex<double> > vt(vr); vt *= 1.0/Din.mass();
     fd1 = Din(0,0);
     fd1 = fd1.Dx();     vt *= A00;
     Dh(1,0) += (fd1.mpaxis(vt));
     fd1 = Din(1,0);
     fd1 = fd1.Dx();     vt *= A10/A00;
     Dh(0,0) += (fd1.mpaxis(vt));
 //    fd1 = Din(0,0);     fd1 *= complex<double>(1.0/3.0);
 //    fd1 = fd1.Dx();     vt *= A20/A10;
 //    Dh(1,0) += (fd1.mpaxis(vt));
 }
f1only() [2/3]
void Electric_Field_1D::f1only (const DistFunc1D & Din, const Field1D & FEx, const Field1D & FEy, const Field1D & FEz, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 633 of file vlasov.cpp.
References Electric_Field_1D::A100, Electric_Field_1D::A210, Field1D::array(), Electric_Field_1D::B211, Electric_Field_1D::C100, Electric_Field_1D::G, Electric_Field_1D::H, DistFunc1D::l0(), DistFunc1D::m0(), Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), SHarmonic1D::Re(), and Electric_Field_1D::TMP.
{
 //--------------------------------------------------------------
 //  This is the core calculation for the electric field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Ex(FEx.array());
     valarray<complex<double> > Em(FEz.array());
     Em *= (-1.0)*ii;
     Em += FEy.array();
     valarray<complex<double> > Ep(FEz.array());
     Ep *= ii;
     Ep += FEy.array();
     Ex *= Din.q();
     Em *= Din.q();
     Ep *= Din.q();
     size_t l0(Din.l0());
     size_t m0(Din.m0());
     SHarmonic1D f20(Din(0,0));
     f20 *= complex<double>(1.0/3.0);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeG00(Din(0,0));
     Ex *= A100; TMP = G; Dh(1,0) += G.mxaxis(Ex);
     Em *= C100;            Dh(1,1) += TMP.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(1,0),1);
     Ex *= A210 / A100;          Dh(0,0) += H.mxaxis(Ex);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, 1 < l < l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     MakeGH(f20,2);
 //     Ex *= A310 / A210;      TMP = H;      Dh(1,0) += H.mxaxis(Ex);
 //     Em *= C311 / C100;                    Dh(1,1) += TMP.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(1,1),1);
     Ep *= B211;              H = H.mxaxis(Ep);     Dh(0,0) += H.Re();
 }
f1only() [3/3]
void Magnetic_Field_1D::f1only (const DistFunc1D & Din, const Field1D & FBx, const Field1D & FBy, const Field1D & FBz, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1120 of file vlasov.cpp.
References Magnetic_Field_1D::A1, Magnetic_Field_1D::A3, Field1D::array(), Magnetic_Field_1D::B1, Magnetic_Field_1D::FLM, SHarmonic1D::mxaxis(), DistFunc1D::q(), and SHarmonic1D::Re().
{
 //--------------------------------------------------------------
 //  This is the core calculation for the magnetic field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Bx(FBx.array());
     valarray<complex<double> > Bm(FBy.array());
     Bm *= (-1.0)*ii;
     Bm += FBz.array();
     valarray<complex<double> > Bp(FBy.array());
     Bp *= ii;
     Bp += FBz.array();
     Bx *= Din.q();
     Bm *= Din.q();
     Bp *= Din.q();
     size_t l0(B1.size()-1);
     size_t m0(A1.size()-1);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, 1 < l < l0+1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     Bp *= A3;
     for (size_t l(1); l < l0+1; ++l){
         FLM = Din(l,0);      Dh(l,1) += FLM.mxaxis(Bp);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     FLM = Din(1,1); Bx *= A1[1];                           Dh(1,1) += FLM.mxaxis(Bx);
     FLM = Din(1,1); Bm *= B1[1]; FLM = FLM.mxaxis(Bm);     Dh(1,0) += FLM.Re();
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // //      m = 1, l > 1
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     for (size_t l(2); l < l0+1; ++l){
 //         FLM = Din(l,1);                                                Dh(l,2) += FLM.mxaxis(Bp);
 //         FLM = Din(l,1);                                                Dh(l,1) += FLM.mxaxis(Bx);
 //         FLM = Din(l,1); Bm *= B1[l]/B1[l-1]; FLM = FLM.mxaxis(Bm); Dh(l,0) += FLM.Re();
 //     }
 //     Bm *= 1.0/B1[l0];
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // //      m > 1, l = m
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     for (size_t m(2); m < m0; ++m){
 //         FLM = Din(m,m); Bx *= A1[m]/A1[m-1];                   Dh(m,m  ) += FLM.mxaxis(Bx);
 //         FLM = Din(m,m); Bm *= A2(m,m);                         Dh(m,m-1) += FLM.mxaxis(Bm);
 //         for (size_t l(m+1); l < l0+1; ++l){
 //             FLM = Din(l,m);                                    Dh(l,m+1) += FLM.mxaxis(Bp);
 //             FLM = Din(l,m);                                    Dh(l,m  ) += FLM.mxaxis(Bx);
 //             FLM = Din(l,m); Bm *= A2(l,m)/A2(l-1,m);           Dh(l,m-1) += FLM.mxaxis(Bm);
 //         }
 //         Bm *= 1.0/A2(l0,m);
 //     }
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // //      m = m0, l >= m0
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     FLM = Din(m0,m0); Bx *= A1[m0]/A1[m0-1];                   Dh(m0,m0)   += FLM.mxaxis(Bx);
 //     FLM = Din(m0,m0); Bm *= A2(m0,m0)/*/A2(l0,m0-1)*/;             Dh(m0,m0-1) += FLM.mxaxis(Bm);
 //     for (size_t l(m0+1); l < l0+1; ++l){
 //         FLM = Din(l,m0);                                     Dh(l,m0  )  += FLM.mxaxis(Bx);
 //         FLM = Din(l,m0); Bm *= A2(l,m0)/A2(l-1,m0);          Dh(l,m0-1)  += FLM.mxaxis(Bm);
 //     }
 }
Faraday_1D()
Faraday_1D::Faraday_1D (double xmin, double xmax, size_t Nx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1330 of file vlasov.cpp.
References Faraday_1D::idx.
         : tmpE(Nx), numx(Nx) {
     idx = complex<double>((-1.0)/ (2.0*(xmax-xmin)/double(Nx))); // -1/(2dx)
 }
G()
double self_f00_explicit_step::G (const int & n, const valarray< double > & fin) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Calculate G for low momentum cells
Parameters
[in] n Number of low momentum cells being treated differently.
[in] fin Input distribution function.
Returns
Returns G value for n cells.
Definition at line 621 of file collisions.cpp.
References self_f00_explicit_step::J1, and self_f00_explicit_step::vr.
Referenced by self_f00_explicit_step::takestep().
{
 //-------------------------------------------------------------------
     double i2s, i4s;
     double f00( (fin[0] - fin[1]*(vr[0]*vr[0])/(vr[1]*vr[1]))/
                 (1.0 - (vr[0]*vr[0])/(vr[1]*vr[1])) );
     i2s = f00*pow(vr[n],3)/3.0 + (fin[1]-f00)*pow(vr[n],5)/(vr[1]*vr[1])*0.2;
     i4s = f00*pow(vr[n],5)*0.2 + (fin[1]-f00)*pow(vr[n],7)/(vr[1]*vr[1]*7.0);
     return fin[n]*i4s + (pow(vr[n],3)*fin[n]-3.0*i2s) * J1[n];
 }
getleftside()
void self_f00_implicit_step::getleftside (valarray< double > & fin, const double & Z0, const double & heating, const double & cooling, Array2D< double > & LHStemp)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Calculate Rosenbluth and Chang-Cooper quantities
Also fills in I4_Lnee (the temperature for the Lnee calculation)
And takes care of boundaries
Normalizing quantities (Inspired by previous collision routines and OSHUN notes by M. Tzoufras)
< ZLogLambda
Fill in matrix
Boundaries by hand – This operates on f(0)
Definition at line 343 of file collisions.cpp.
References self_f00_implicit_step::c_kpre, self_f00_implicit_step::C_RB, self_f00_implicit_step::D_RB, self_f00_implicit_step::delta_CC, self_f00_implicit_step::dtoverv2, self_f00_implicit_step::dvr, self_f00_implicit_step::formulas, self_f00_implicit_step::I4_Lnee, self_f00_implicit_step::ib, Formulary::LOGee(), Formulary::LOGei(), self_f00_implicit_step::update_C_Rosenbluth(), self_f00_implicit_step::update_D_and_delta(), self_f00_implicit_step::update_D_inversebremsstrahlung(), and Formulary::Zeta.
Referenced by self_f00_implicit_collisions::loop().
{
     double collisional_coefficient;
     double heating_coefficient;
 //    Array2D<double> LHS(fin.size(),fin.size());
     update_C_Rosenbluth(fin);
     update_D_and_delta(fin);
     collisional_coefficient  = formulas.LOGee(C_RB[C_RB.size()-1],I4_Lnee/3.0/C_RB[C_RB.size()-1]);
     collisional_coefficient *= 4.0*M_PI/3.0*c_kpre;
     heating_coefficient  = formulas.Zeta*Z0*formulas.LOGei(C_RB[C_RB.size()-1],I4_Lnee/3.0/C_RB[C_RB.size()-1],Z0*formulas.Zeta);
     heating_coefficient *= c_kpre / 6.0 * pow(vos,2.0) * C_RB[C_RB.size()-1];
     heating_coefficient /= collisional_coefficient;
     if (ib) update_D_inversebremsstrahlung(Z0, heating_coefficient,vos);
     size_t ip(0);
     LHStemp(ip, ip + 1) = - dtoverv2[ip] * collisional_coefficient
                       * (C_RB[ip + 1] * (1.0 - delta_CC[ip + 1])
                          + D_RB[ip + 1] / dvr[ip + 1]);
     LHStemp(ip    , ip) = 1.0 - dtoverv2[ip] * collisional_coefficient
                             * (C_RB[ip + 1] * delta_CC[ip + 1] - D_RB[ip + 1] / dvr[ip + 1]
                                - C_RB[ip] * (1.0 - delta_CC[ip]) - D_RB[ip] / dvr[ip]);
     for (ip = 1; ip < fin.size() - 1; ++ip){
         LHStemp(ip, ip + 1) = - dtoverv2[ip] * collisional_coefficient
                           * (C_RB[ip + 1] * (1.0 - delta_CC[ip + 1])
                              + D_RB[ip + 1] / dvr[ip + 1]);
         LHStemp(ip    , ip) = 1.0 - dtoverv2[ip] * collisional_coefficient
                                 * (C_RB[ip + 1] * delta_CC[ip + 1] - D_RB[ip + 1] / dvr[ip + 1]
                                    - C_RB[ip] * (1.0 - delta_CC[ip]) - D_RB[ip] / dvr[ip]);
         LHStemp(ip, ip - 1) = dtoverv2[ip] * collisional_coefficient
                           * (C_RB[ip] * delta_CC[ip]
                              - D_RB[ip] / dvr[ip]);
     }
     ip = fin.size() - 1;
     LHStemp(ip    , ip) = 1.0 - dtoverv2[ip] * collisional_coefficient
                             * (C_RB[ip + 1] * delta_CC[ip + 1]
                                - C_RB[ip] * (1.0 - delta_CC[ip]) - D_RB[ip] / dvr[ip]);
     LHStemp(ip, ip - 1) = dtoverv2[ip] * collisional_coefficient
                       * (C_RB[ip] * delta_CC[ip]
                          - D_RB[ip] / dvr[ip]);
 //    std::cout << "\n\n LHS = \n";
 //    for (size_t i(0); i < LHS.dim1(); ++i) {
 //        std::cout << "i = " << i << " :::: ";
 //        for (size_t j(0); j < LHS.dim2(); ++j) {
 //            std::cout << LHS(i, j) << "   ";
 //        }
 //        std::cout << "\n";
 //    }
 //
 //    Thomas_Tridiagonal(LHS,fin,fh);
 }
implicit()
void Magnetic_Field_1D::implicit (DistFunc1D & Din, const Field1D & FBx, const Field1D & FBy, const Field1D & FBz, double dt)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Distribution function vector. 1 Nmx1 vector per momentum cell
Multiply Right Side to create right side vector
Unpack
Definition at line 973 of file vlasov.cpp.
References Field1D::array(), DistFunc1D::q(), and Thomas_Tridiagonal().
{
 //--------------------------------------------------------------
 //  This is the core calculation for the magnetic field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Bx(FBx.array());
     valarray<complex<double> > Bm(FBy.array());
     Bm *= (-1.0)*ii;
     Bm += FBz.array();
     valarray<complex<double> > Bp(FBy.array());
     Bp *= ii;
     Bp += FBz.array();
     Bx *= Din.q();//Din.mass();
     Bm *= Din.q();//Din.mass();
     Bp *= Din.q();//Din.mass();
     size_t l0(1);
     size_t m0(1);
     int Nm(0);
     size_t ind(0);
     size_t indp(0);
     complex<double> temp(0.0,0.0);
     for (size_t i(0); i<Din(0,0).numx(); ++i)
     {
         for (size_t l(1); l < l0+1; ++l)
         {
             Nm = (l<m0?l:m0);
             valarray<complex<double>> fin((0.0,0.0),2*Nm+1);
             valarray<complex<double>> RHSv((0.0,0.0),2*Nm+1);
             Array2D<complex<double>>  LHS(2*Nm+1,2*Nm+1);
             Array2D<complex<double>>  RHS(2*Nm+1,2*Nm+1);
             //* The matrices corresponding to RHS and LHS are computed
             //  They apply to the vector
             //  [ f_l^m  ]          -> 0 index but applies to Nm th harmonic
             //     ...
             //  [ f_l^2  ]
             //  [ f_l^1  ]
             //  [ f_l^0  ]          -> Nm index but applies to 0th harmonic
             //  [ f_l^-1 ]
             //  [ f_l^-2 ]
             //     ...
             //  [ f_l^-m ]          *//
             RHS(0,0)           = 1.0-ii*double(Nm)*dt/2.0*Bx[i];
             LHS(0,0)           = conj(RHS(0,0));
             RHS(0,1)           =  0.25*dt*Bp[i];
             LHS(0,1)           = -0.25*dt*Bp[i];
             for (int m(Nm-1);m>0;--m)
             {
                 ind = Nm-m;
                 RHS(ind,ind)   = 1.0-ii*double(m)*dt/2.0*Bx[i];
                 LHS(ind,ind)   = conj(RHS(ind,ind));
                 RHS(ind,ind+1) =  0.25*dt*Bp[i];
                 LHS(ind,ind+1) = -0.25*dt*Bp[i];
                 RHS(ind,ind-1) = -0.25*dt*(l-m)*(l+m+1)*Bm[i];
                 LHS(ind,ind-1) =  0.25*dt*(l-m)*(l+m+1)*Bm[i];
             }
             RHS(Nm,Nm)         = 1.0;
             LHS(Nm,Nm)         = 1.0;
             RHS(Nm,Nm-1)       = -0.25*dt*(l)*(l+1)*Bm[i];
             LHS(Nm,Nm-1)       =  0.25*dt*(l)*(l+1)*Bm[i];
             //* Fill in bottom half which is a series of reflections and complex conjugates
             RHS(Nm,Nm+1)       = conj(RHS(Nm,Nm-1));
             LHS(Nm,Nm+1)       = conj(LHS(Nm,Nm-1));
             for (int m(-1);m>-Nm;--m)
             {
                 ind  = Nm-m;
                 indp = Nm-abs(m);
                 RHS(ind,ind)   = conj(RHS(indp,indp));
                 LHS(ind,ind)   = conj(LHS(indp,indp));
                 RHS(ind,ind+1) = conj(RHS(indp,indp-1));
                 LHS(ind,ind+1) = conj(LHS(indp,indp-1));
                 RHS(ind,ind-1) = conj(RHS(indp,indp+1));
                 LHS(ind,ind-1) = conj(LHS(indp,indp+1));
             }
             RHS(2*Nm,2*Nm)     = conj(RHS(0,0));
             LHS(2*Nm,2*Nm)     = conj(LHS(0,0));
             RHS(2*Nm,2*Nm-1)   = conj(RHS(0,1));
             LHS(2*Nm,2*Nm-1)   = conj(LHS(0,1));
             for (size_t k(0); k < Din(0,0).nump(); ++k) {
                 fin[0] = Din(l, Nm)(k, i);
                 for (int m(Nm - 1); m > 1; --m) {
                     ind = Nm - m;
                     fin[ind] = Din(l, m)(k, i);
                 }
                 fin[Nm] = Din(l, 0)(k, i);
                 for (int m(-1); m > -Nm; --m) {
                     ind = Nm - m;
                     fin[ind] = conj(Din(l, abs(m))(k, i));
                 }
                 fin[2 * Nm] = conj(Din(l, Nm)(k, i));
                 RHSv[0] = fin[0] * RHS(0, 0) + fin[1] * RHS(0, 1);
                 for (size_t mm(1); mm < 2 * Nm; ++mm) {
                     RHSv[mm] = fin[mm - 1] * RHS(mm, mm - 1) + fin[mm] * RHS(mm, mm) + fin[mm + 1] * RHS(mm, mm + 1);
                 }
                 RHSv[2 * Nm] = fin[2 * Nm - 1] * RHS(2 * Nm, 2 * Nm - 1) + fin[2 * Nm] * RHS(2 * Nm, 2 * Nm);
 //                std::cout << "\n\n LHS = \n";
 //                for (size_t i(0); i < LHS.dim1(); ++i) {
 //                    std::cout << "i = " << i << " :::: ";
 //                    for (size_t j(0); j < LHS.dim2(); ++j) {
 //                        std::cout << LHS(i, j) << "   ";
 //                    }
 //                    std::cout << "\n";
 //                }
                 Thomas_Tridiagonal(LHS,RHSv,fin);
                 Din(l,Nm)(k,i)     = fin[0];
                 for (int m(Nm-1);m>1;--m)
                 {
                     ind = Nm-m;
                     Din(l,m)(k,i)  = fin[ind];
                 }
                 Din(l,0)(k,i)     = fin[Nm];
             }
         }
     }
 }
Implicit_Ex()
void Electric_Field_1D::Implicit_Ex (const DistFunc1D & Din, const Field1D & FEx, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 443 of file vlasov.cpp.
References Electric_Field_1D::A1, Electric_Field_1D::A2, Field1D::array(), Electric_Field_1D::G, Electric_Field_1D::H, Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), and DistFunc1D::q().
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in x,
 //  which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     valarray<complex<double> > Ex(FEx.array());
     Ex *= Din.q();
 //      m = 0, l = 0
     MakeG00(Din(0,0));
     Ex *= A1(0,0);             Dh(1,0) += G.mxaxis(Ex);
 //      m = 0, l = 1
     MakeGH(Din(1,0),1);
     Ex *= A2(1,0) / A1(0,0);   Dh(0,0) += H.mxaxis(Ex);
     Ex *= A1(1,0) / A2(1,0);   Dh(2,0) += G.mxaxis(Ex);
 //      m = 0, l = 2
     MakeGH(Din(2,0),2);
     Ex *= A2(2,0) / A1(1,0);   Dh(1,0) += H.mxaxis(Ex);
 //      m = 0, l = 3
     MakeGH(Din(3,0),3);
     Ex *= A2(3,0) / A2(2,0);   Dh(2,0) += H.mxaxis(Ex);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
     MakeGH(Din(1,1),1);
     Ex *= A1(1,1) / A2(3,0);   Dh(2,1) += G.mxaxis(Ex);
 //      m = 1, l = 2
     MakeGH(Din(2,1),2);
     Ex *= A2(2,1) / A1(1,1);   Dh(1,1) += H.mxaxis(Ex);
 //      m = 1, l = 3
     MakeGH(Din(3,1),3);
     Ex *= A2(3,1) / A2(2,1);   Dh(2,1) += H.mxaxis(Ex);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
Implicit_Ex_f1only()
void Electric_Field_1D::Implicit_Ex_f1only (const DistFunc1D & Din, const Field1D & FEx, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 693 of file vlasov.cpp.
References Electric_Field_1D::A100, Electric_Field_1D::A210, Field1D::array(), Electric_Field_1D::G, Electric_Field_1D::H, Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), and DistFunc1D::q().
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in x,
 //  which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     valarray<complex<double> > Ex(FEx.array());
     Ex *= Din.q();
     SHarmonic1D f20(Din(0,0));
     f20 *= complex<double>(1.0/3.0);
 //      m = 0, l = 0
     MakeG00(Din(0,0));
     Ex *= A100;             Dh(1,0) += G.mxaxis(Ex);
 //      m = 0, l = 1
     MakeGH(Din(1,0),1);
     Ex *= A210 / A100;   Dh(0,0) += H.mxaxis(Ex);
     // Ex *= A1(1,0) / A2(1,0);   Dh(2,0) += G.mxaxis(Ex);
 //      m = 0, l = 2
 //     MakeGH(f20,2);
 //     Ex *= A310 / A210;      TMP = H;      Dh(1,0) += H.mxaxis(Ex);
 }
Implicit_Ey()
void Electric_Field_1D::Implicit_Ey (const DistFunc1D & Din, const Field1D & FEy, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 488 of file vlasov.cpp.
References Field1D::array(), Electric_Field_1D::B1, Electric_Field_1D::B2, Electric_Field_1D::C1, Electric_Field_1D::C3, Electric_Field_1D::C4, Electric_Field_1D::G, Electric_Field_1D::H, DistFunc1D::m0(), Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), SHarmonic1D::Re(), and Electric_Field_1D::TMP.
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in y
 //  and z, which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     valarray<complex<double> > Em(FEy.array());
     valarray<complex<double> > Ep(FEy.array());
     Em *= Din.q();;
     Ep *= Din.q();;
 //      m = 0, l = 0
     MakeG00(Din(0,0));
     Em *= C1[0];            Dh(1,1) += G.mxaxis(Em);
 //      m = 0, l = 1
     MakeGH(Din(1,0),1);
     Em *= C1[1]   / C1[0];  Dh(2,1) += G.mxaxis(Em);
 //      m = 0, 1 < l < l0
     MakeGH(Din(2,0),2);
     Em *= C3[2]   / C1[1];  Dh(1,1) += H.mxaxis(Em);
 //      m = 0,  l = 3
     MakeGH(Din(3,0),3);
     Em *= C3[3]   / C3[2];  Dh(2,1) += H.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
     MakeGH(Din(1,1),1);
     Ep *= B2[1];             H = H.mxaxis(Ep); Dh(0,0) += H.Re();
     Em *= C1[1] / C3[3];     TMP = G;          Dh(2,2) += TMP.mxaxis(Em);
     Ep *= B1[1] / B2[1];     G = G.mxaxis(Ep); Dh(2,0) += G.Re();
 //      m = 1, l = 2
     MakeGH(Din(2,1),2);
     Ep *= B2[2]   / B1[1];   H = H.mxaxis(Ep); Dh(1,0) += H.Re();
 //      m = 1, l = 3
     MakeGH(Din(3,1),3);
     Em *= C3[3]   / C1[1];   TMP = H;          Dh(2,2) += TMP.mxaxis(Em);
     Ep *= B2[3]   / B2[2];   H = H.mxaxis(Ep); Dh(2,0) += H.Re();
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 2, l = 2
     MakeGH(Din(2,2),2);
     Ep *= C4(2,2) / B2[3];        Dh(1,1) += H.mxaxis(Ep);
 //      m = 2, l = 3
     MakeGH(Din(3,2),3);
     Ep *= C4(3,2) / C4(2,2);      Dh(2,1)  += H.mxaxis(Ep);
     size_t m0(Din.m0());
     if ( m0 > 2) {
 //          m = 3, l = 3
         MakeGH(Din(3,3),3);
         Ep *= C4(3,3) / C4(3,2);  Dh(2,2)  += H.mxaxis(Ep);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
Implicit_Ey_f1only()
void Electric_Field_1D::Implicit_Ey_f1only (const DistFunc1D & Din, const Field1D & FEy, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 722 of file vlasov.cpp.
References Field1D::array(), Electric_Field_1D::B211, Electric_Field_1D::C100, Electric_Field_1D::G, Electric_Field_1D::H, Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), and SHarmonic1D::Re().
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in y
 //  and z, which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     valarray<complex<double> > Em(FEy.array());
     valarray<complex<double> > Ep(FEy.array());
     SHarmonic1D f20(Din(0,0));
     f20 *= complex<double>(1.0/3.0);
     Em *= Din.q();
     Ep *= Din.q();
 //      m = 0, l = 0
     MakeG00(Din(0,0));
     Em *= C100;            Dh(1,1) += G.mxaxis(Em);
 //      m = 0, l = 1
     // MakeGH(Din(1,0),1);
     // Em *= C1[1]   / C1[0];  Dh(2,1) += G.mxaxis(Em);
 //      m = 0, 1 < l < l0
 //     MakeGH(f20,2);
 //     Em *= C311 / C100;                    Dh(1,1) += TMP.mxaxis(Em);
 //      m = 0,  l = 3
     // MakeGH(Din(3,0),3);
     // Em *= C3[3]   / C3[2];  Dh(2,1) += H.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
     MakeGH(Din(1,1),1);
     Ep *= B211;             H = H.mxaxis(Ep); Dh(0,0) += H.Re();
 }
Implicit_Ez()
void Electric_Field_1D::Implicit_Ez (const DistFunc1D & Din, const Field1D & FEz, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 556 of file vlasov.cpp.
References Field1D::array(), Electric_Field_1D::B1, Electric_Field_1D::B2, Electric_Field_1D::C1, Electric_Field_1D::C3, Electric_Field_1D::C4, Electric_Field_1D::G, Electric_Field_1D::H, DistFunc1D::m0(), Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), SHarmonic1D::Re(), and Electric_Field_1D::TMP.
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in y
 //  and z, which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Em(FEz.array());
     Em *= (-1.0)*ii;
     valarray<complex<double> > Ep(FEz.array());
     Ep *= ii;
     // Ep += FEy.array();
     //
     // Ex *= Din.q();;
     Em *= Din.q();
     Ep *= Din.q();
 //      m = 0, l = 0
     MakeG00(Din(0,0));
     Em *= C1[0];            Dh(1,1) += G.mxaxis(Em);
 //      m = 0, l = 1
     MakeGH(Din(1,0),1);
     Em *= C1[1]   / C1[0];  Dh(2,1) += G.mxaxis(Em);
 //      m = 0, 1 < l < l0
     MakeGH(Din(2,0),2);
     Em *= C3[2]   / C1[1];  Dh(1,1) += H.mxaxis(Em);
 //      m = 0,  l = 3
     MakeGH(Din(3,0),3);
     Em *= C3[3]   / C3[2];  Dh(2,1) += H.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
     MakeGH(Din(1,1),1);
     Ep *= B2[1];             H = H.mxaxis(Ep); Dh(0,0) += H.Re();
     Em *= C1[1] / C3[3];     TMP = G;              Dh(2,2) += TMP.mxaxis(Em);
     Ep *= B1[1] / B2[1];     G = G.mxaxis(Ep); Dh(2,0) += G.Re();
 //      m = 1, l = 2
     MakeGH(Din(2,1),2);
     Ep *= B2[2]   / B1[1];   H = H.mxaxis(Ep); Dh(1,0) += H.Re();
 //      m = 1, l = 3
     MakeGH(Din(3,1),3);
     Em *= C3[3]   / C1[1];   TMP = H;              Dh(2,2) += TMP.mxaxis(Em);
     Ep *= B2[3]   / B2[2];   H = H.mxaxis(Ep); Dh(2,0) += H.Re();
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 2, l = 2
     MakeGH(Din(2,2),2);
     Ep *= C4(2,2) / B2[3];        Dh(1,1) += H.mxaxis(Ep);
 //      m = 2, l = 3
     MakeGH(Din(3,2),3);
     Ep *= C4(3,2) / C4(2,2);      Dh(2,1)  += H.mxaxis(Ep);
     size_t m0(Din.m0());
     if ( m0 > 2) {
 //          m = 3, l = 3
         MakeGH(Din(3,3),3);
         Ep *= C4(3,3) / C4(3,2);  Dh(2,2)  += H.mxaxis(Ep);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
Implicit_Ez_f1only()
void Electric_Field_1D::Implicit_Ez_f1only (const DistFunc1D & Din, const Field1D & FEz, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 762 of file vlasov.cpp.
References Field1D::array(), Electric_Field_1D::B211, Electric_Field_1D::C100, Electric_Field_1D::G, Electric_Field_1D::H, Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), and SHarmonic1D::Re().
{
 //--------------------------------------------------------------
 //  This is the calculation for the implicit electric field in y
 //  and z, which is to say Ex as it acts on the first few harmonics.
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     SHarmonic1D f20(Din(0,0));
     f20 *= complex<double>(1.0/3.0);
     valarray<complex<double> > Em(FEz.array());
     Em *= (-1.0)*ii;
     valarray<complex<double> > Ep(FEz.array());
     Ep *= ii;
     //      m = 0, l = 0
     MakeG00(Din(0,0));
     Em *= C100;            Dh(1,1) += G.mxaxis(Em);
 //      m = 0, l = 1
     // MakeGH(Din(1,0),1);
     // Em *= C1[1]   / C1[0];  Dh(2,1) += G.mxaxis(Em);
 //      m = 0, 1 < l < l0
 //    Din(2,0)  = Din(0,0);
 //    Din(2,0) *= complex<double>(1.0/3.0);
 //
 //    MakeGH(f20,2);
 //    Em *= C311 / C100;                    Dh(1,1) += TMP.mxaxis(Em);
 // //      m = 0,  l = 3
 //         MakeGH(Din(3,0),3);
 //         Em *= C3[3]   / C3[2];  Dh(2,1) += H.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
     MakeGH(Din(1,1),1);
     Ep *= B211;             H = H.mxaxis(Ep); Dh(0,0) += H.Re();
 }
interspecies_collisions()
interspecies_collisions::interspecies_collisions (const State1D & Yin, const size_t & sind, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Constructors/Destructors.
Definition at line 785 of file interspeciescollisions.cpp.
References State1D::DF(), and State1D::Species().
     {
         // size_t sind(0);
         for (size_t s(0); s<Yin.Species(); ++s){
             if (s!=sind) {
               interspecies_f00_collisions.push_back(interspecies_f00_explicit_collisions(Yin.DF(sind),Yin.DF(s),deltat));
               std::cout << "\n\n sind,s = " << sind << "," << s << ", size = " <<interspecies_f00_collisions.size() << "\n\n";
             }
         }
     }
interspecies_f00_explicit_collisions()
interspecies_f00_explicit_collisions::interspecies_f00_explicit_collisions (const DistFunc1D & DF1, const DistFunc1D & DF2, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Constructors/Destructors.
Definition at line 313 of file interspeciescollisions.cpp.
References Input::Input_List::BoundaryCells, interspecies_f00_explicit_collisions::h, Input::List(), interspecies_f00_explicit_collisions::Nbc, interspecies_f00_explicit_collisions::num_h, Input::Input_List::NxLocal, and interspecies_f00_explicit_collisions::szx.
       :
         rkf00(DF1, DF2, deltat),
         fin1(0.0,DF1(0,0).nump()), fin2(0.0,DF2(0,0).nump()),
         RK4(fin1),
         num_h(size_t(deltat/Input::List().small_dt)+1)
         // h(Input::List().small_dt)
         {
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           h = deltat/static_cast<double>(num_h);
         Nbc = Input::List().BoundaryCells;
         szx = Input::List().NxLocal[0];  //Input::List().numx;      // size of useful x axis
     }
interspecies_f00_explicit_step()
interspecies_f00_explicit_step::interspecies_f00_explicit_step (const DistFunc1D & DF1, const DistFunc1D & DF2, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Constructors/Destructors.
Definition at line 39 of file interspeciescollisions.cpp.
References Input::Input_List::BoundaryCells, interspecies_f00_explicit_step::kpre, Input::List(), interspecies_f00_explicit_step::m1, interspecies_f00_explicit_step::m2, DistFunc1D::mass(), interspecies_f00_explicit_step::Nbc, Input::Input_List::NxLocal, interspecies_f00_explicit_step::pgrid_s2, interspecies_f00_explicit_step::Pn, DistFunc1D::q(), interspecies_f00_explicit_step::Qn, interspecies_f00_explicit_step::szx, interspecies_f00_explicit_step::U1, interspecies_f00_explicit_step::U1m1, interspecies_f00_explicit_step::U2, interspecies_f00_explicit_step::U2m1, interspecies_f00_explicit_step::U3, interspecies_f00_explicit_step::U4, interspecies_f00_explicit_step::U4m1, interspecies_f00_explicit_step::z1, and interspecies_f00_explicit_step::z2.
         : dt(deltat),
 //        pgrid_s1(Algorithms::MakeAxis(DF1.pmax()/(2.0*DF1(0,0).nump()-1.0),DF1.pmax(),DF1(0,0).nump())),
 //        pgrid_s2(Algorithms::MakeAxis(DF2.pmax()/(2.0*DF2(0,0).nump()-1.0),DF2.pmax(),DF2(0,0).nump())),
         pgrid_s1(Algorithms::MakeCAxis(0.0,DF1.pmax(),DF1(0,0).nump())),
         pgrid_s2(Algorithms::MakeCAxis(0.0,DF2.pmax(),DF2(0,0).nump())),
         // f1(DF1(0,0)),f2(DF2(0,0)),
         fslope(0.0, DF1(0,0).nump()),
         // f0(0.0, DF1(0,0).nump()),
         df0(0.0, DF1(0,0).nump()),
         U4(0.0,  DF2(0,0).nump()),
          U4m1(0.0, DF2(0,0).nump()),
          U2(0.0, DF2(0,0).nump()),
          U2m1(0.0, DF2(0,0).nump()),
          U1(0.0, DF2(0,0).nump()),
          U1m1(0.0, DF2(0,0).nump()),
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          J1_s2(0.0, DF2(0,0).nump()),
          I2_s2(0.0, DF2(0,0).nump()),
          I4_s2(0.0, DF2(0,0).nump()),
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          U3(0.0, DF2(0,0).nump()),
          Qn(0.0, DF2(0,0).nump()),
          Pn(0.0, DF2(0,0).nump()),
          J1_s1(0.0, DF2(0,0).nump()),
          I2_s1(0.0, DF2(0,0).nump()),
          I4_s1(0.0, DF2(0,0).nump())
         {
         Nbc = Input::List().BoundaryCells;
         szx = Input::List().NxLocal[0];
         m2 = DF2.mass()  ; m1 = DF1.mass();
         z2 = DF2.q();      z1 = DF1.q();
         double re(2.8179402894e-13);           //classical electron radius
         double kp(sqrt(4.0*M_PI*(Input::List().density_np)*re));
         kpre = re*kp;
         // f1.reserve(DF1(0,0).nump());
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          // Determine U4, U4m1, U2, U2m1, U1, U1m1
          for (size_t i(1); i < DF2(0,0).nump(); ++i) {
              U4[i]   = 0.5 * pow(pgrid_s2[i],4)     * (pgrid_s2[i]-pgrid_s2[i-1]);
              U4m1[i] = 0.5 * pow(pgrid_s2[i-1],4)   * (pgrid_s2[i]-pgrid_s2[i-1]);
              U2[i]   = 0.5 * pgrid_s2[i]*pgrid_s2[i]      * (pgrid_s2[i]-pgrid_s2[i-1]);
              U2m1[i] = 0.5 * pgrid_s2[i-1]*pgrid_s2[i-1]  * (pgrid_s2[i]-pgrid_s2[i-1]);
              U1[i]   = 0.5 * pgrid_s2[i]            * (pgrid_s2[i]-pgrid_s2[i-1]);
              U1m1[i] = 0.5 * pgrid_s2[i-1]          * (pgrid_s2[i]-pgrid_s2[i-1]);
          }
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          // Determine U3
          for (size_t i(0); i < U3.size(); ++i) {
              U3[i] = pow(pgrid_s2[i],3);
          }
          // Determine Qn
          Qn[0] = 1.0 / ((pgrid_s2[0]*pgrid_s2[0]*pgrid_s2[1])/2.0);
          for (size_t i(1); i < Qn.size()-1; ++i) {
              Qn[i] = 1.0 / (pgrid_s2[i]*pgrid_s2[i]*(pgrid_s2[i+1]-pgrid_s2[i-1])/2.0);
          }
          // Determine Pn
          for (size_t i(0); i < Pn.size()-1; ++i) {
              Pn[i] = 1.0 / ((pgrid_s2[i+1]-pgrid_s2[i])/2.0*(pgrid_s2[i+1]+pgrid_s2[i]));
          }
     }
interspecies_f00_RKfunctor()
interspecies_f00_RKfunctor::interspecies_f00_RKfunctor (const DistFunc1D & DF1, const DistFunc1D & DF2, const double & smalldt)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Constructor for RK4 method on f00.
Parameters
fin Input distribution
[in] tout_start Hmm...
Definition at line 302 of file interspeciescollisions.cpp.
         :collide(DF1,DF2,smalldt){}
interspecies_flm_implicit_collisions()
interspecies_flm_implicit_collisions::interspecies_flm_implicit_collisions (const DistFunc1D & DFin, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Constructors/Destructors.
Definition at line 673 of file interspeciescollisions.cpp.
References Input::Input_List::BoundaryCells, Input::List(), interspecies_flm_implicit_collisions::Nbc, Input::Input_List::NxLocal, and interspecies_flm_implicit_collisions::szx.
        : f00(0.0, DFin(0).nump()),
          fc(0.0,DFin(0).nump()),
          l0(DFin.l0()),
          m0(DFin.m0()),//Yin.SH(0,0).m0())
          implicit_step(DFin.pmax(),DFin(0).nump()),
          Dt(deltat)    //
          {
         Nbc = Input::List().BoundaryCells;
         szx = Input::List().NxLocal[0];
     }
interspecies_flm_implicit_step()
interspecies_flm_implicit_step::interspecies_flm_implicit_step (double pmax, size_t nump)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Definition at line 376 of file interspeciescollisions.cpp.
References interspecies_flm_implicit_step::kpre, Input::List(), interspecies_flm_implicit_step::U1, interspecies_flm_implicit_step::U1m1, interspecies_flm_implicit_step::U2, interspecies_flm_implicit_step::U2m1, interspecies_flm_implicit_step::U4, interspecies_flm_implicit_step::U4m1, and interspecies_flm_implicit_step::vr.
        :
 //       Pre-Calculated Constants
 //      INCLUDED pmax[0] here only because pmax currently is vector having elements for two species
 //         vr(Algorithms::MakeAxis(pmax/(2.0*nump-1.0),pmax,nump)),
         vr(Algorithms::MakeCAxis(0.0,pmax,nump)),
 //       Constants for Integrals
          U4(0.0,  nump),
          U4m1(0.0,nump),
          U2(0.0,  nump),
          U2m1(0.0,nump),
          U1(0.0,  nump),
          U1m1(0.0,nump),
 //       Integrals
          J1m(0.0,  nump),
          I0(0.0,  nump),
          I2(0.0,  nump),
          Scattering_Term(0.0, nump),
          df0(0.0,  nump),
          ddf0(0.0,  nump),
 //       Matrices
          Alpha_Tri(nump, nump),
          if_tridiagonal(Input::List().if_tridiagonal)
 //       Make matrix vk/vn
          {
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
          double re(2.8179402894e-13);           //classical electron radius
          double kp(sqrt(4.0*M_PI*(Input::List().density_np)*re));
          kpre = re*kp;
          // Determine vr
          for (size_t i(0); i < vr.size(); ++i) {
              vr[i] = vr[i] / (sqrt(1.0+vr[i]*vr[i]));
          }
          // Determine U4, U4m1, U2, U2m1, U1, U1m1 for the integrals
          for (size_t i(1); i < U4.size(); ++i) {
              U4[i]   = 0.5 * pow(vr[i],4)     * (vr[i]-vr[i-1]);
              U4m1[i] = 0.5 * pow(vr[i-1],4)   * (vr[i]-vr[i-1]);
              U2[i]   = 0.5 * vr[i]*vr[i]      * (vr[i]-vr[i-1]);
              U2m1[i] = 0.5 * vr[i-1]*vr[i-1]  * (vr[i]-vr[i-1]);
              U1[i]   = 0.5 * vr[i]            * (vr[i]-vr[i-1]);
              U1m1[i] = 0.5 * vr[i-1]          * (vr[i]-vr[i-1]);
          }
     }
loop() [1/2]
void self_f00_implicit_collisions::loop (SHarmonic1D & SHin, valarray< double > & Zarray, const double time, SHarmonic1D & SHout)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
This loop calls the RK4_f00 private member that is responsible for setting up the RK4 algorithm to advance the collision step.
Get time and heating profile Ray-trace would go here
Make vos(x,t)
Unpack
Definition at line 442 of file collisions.cpp.
References self_f00_implicit_collisions::collide, self_f00_implicit_collisions::coolingprofile, self_f00_implicit_collisions::fin, self_f00_implicit_step::getleftside(), self_f00_implicit_collisions::heatingprofile, self_f00_implicit_collisions::ib, self_f00_implicit_collisions::IB_heating, Input::Input_List::lambda_0, Input::List(), SHarmonic1D::nump(), SHarmonic1D::numx(), Setup_Y::parseprofile(), self_f00_implicit_collisions::szx, Thomas_Tridiagonal(), and self_f00_implicit_collisions::xgrid.
Referenced by self_collisions::advancef00().
{
     //-------------------------------------------------------------------
     //  This loop scans all the locations in configuration space
     //  and calls the implicit Chang-Cooper/Langdon/Epperlein algorithm
     //-------------------------------------------------------------------
     //      Initialization
     //-------------------------------------------------------------------
     int ixtimesnump;
     Array2D<double> LHS(f00.numx()*f00.nump(),f00.numx()*f00.nump());
     valarray<double> RHSv(0.0,f00.numx()*f00.nump());
     valarray<double> solution(0.0,f00.numx()*f00.nump());
     Array2D<double> LHStemp(f00.nump(),f00.nump());
     double timecoeff;
     if (IB_heating && ib){
         Setup_Y::parseprofile(xgrid, Input::List().intensity_profile_str, heatingprofile);
         Setup_Y::parseprofile(time, Input::List().intensity_time_profile_str, timecoeff);
         heatingprofile *= (Input::List().lambda_0 * sqrt(7.3e-19*Input::List().I_0))*timecoeff;
     }
     for (size_t ix(0); ix < szx; ++ix){
         // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         // Copy data for a specific location in space to valarray
         // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         for (size_t ip(0); ip < fin.size(); ++ip){
             fin[ip] = (f00(ip,ix)).real();
 //            std::cout << "fin[" << ip << "] = " << fin[ip] << "\n";
         }
 //
 //        collide.takestep(fin,fout,Zarray[ix],heatingprofile[ix],coolingprofile[ix]);
         collide.getleftside(fin,Zarray[ix],heatingprofile[ix],coolingprofile[ix],LHStemp);
         ixtimesnump = ix * f00.nump();
         for (size_t ip(0); ip < fin.size(); ++ip){
             if (ip == 0)
             {
                 LHS(ip + ixtimesnump, ip + 1 + ixtimesnump) = LHStemp(ip, ip + 1);
             }
             else if (ip == f00.nump() - 1)
             {
                 LHS(ip + ixtimesnump, ip - 1 + ixtimesnump) = LHStemp(ip, ip - 1);
             }
             else {
                 LHS(ip + ixtimesnump, ip - 1 + ixtimesnump) = LHStemp(ip, ip - 1);
                 LHS(ip + ixtimesnump, ip + 1 + ixtimesnump) = LHStemp(ip, ip + 1);
             }
             LHS(ip + ixtimesnump, ip + ixtimesnump) = LHStemp(ip, ip);
             RHSv[ip + ixtimesnump] = fin[ip];
 //            std::cout << "fin[" << ip << "] = " << fin[ip] << "\n";
         }
         // Return updated data to the harmonic
         /*for (size_t ip(0); ip < fin.size(); ++ip){
             f00h(ip,ix) = fout[ip];
 //            std::cout << "fout[" << ip << "] = " << fout[ip] << "\n";
         }*/
     }
     Thomas_Tridiagonal(LHS,RHSv,solution);
     for (size_t ix(0); ix < szx; ++ix){
         ixtimesnump = ix * f00.nump();
         for (size_t ip(0); ip < fin.size(); ++ip){
             f00h(ip,ix) = solution[ip + ixtimesnump];
         }
     }
     //-------------------------------------------------------------------
 }
loop() [2/2]
void self_f00_explicit_collisions::loop (SHarmonic1D & SHin, SHarmonic1D & SHout)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
This loop calls the RK4_f00 private member that is responsible for setting up the RK4 algorithm to advance the collision step.
Definition at line 787 of file collisions.cpp.
References self_f00_explicit_collisions::fin, self_f00_explicit_collisions::h, self_f00_explicit_collisions::num_h, self_f00_explicit_collisions::RK, self_f00_explicit_collisions::rkf00, and self_f00_explicit_collisions::szx.
Referenced by self_collisions::advancef00().
{
     //-------------------------------------------------------------------
     //  This loop scans all the locations in configuration space
     //  and calls the RK4 for explicit integration at each location
     //-------------------------------------------------------------------
     //      Initialization
     for (size_t ix(0); ix < szx; ++ix){
         // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         // Copy data for a specific location in space to valarray
         for (size_t ip(0); ip < fin.size(); ++ip){
             fin[ip] = (f00(ip,ix)).real();
         }
         // std::cout << "\n\n h = " << num_h << ", \n \n";
         // Time loop: Update the valarray
         for (size_t h_step(0); h_step < num_h; ++h_step){
             fin = RK(fin,h,&rkf00);
         }
         // Return updated data to the harmonic
         for (int ip(0); ip < fin.size(); ++ip){
             f00h(ip,ix) = fin[ip];
         }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     }
 }
Magnetic_Field_1D()
Magnetic_Field_1D::Magnetic_Field_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 849 of file vlasov.cpp.
References Magnetic_Field_1D::A1, Magnetic_Field_1D::A2, Magnetic_Field_1D::A3, and Magnetic_Field_1D::B1.
         : A1(Nm+1), B1(Nl+1), A2(Nl+1,Nm+1), A3(0.5),
           FLM(Np,Nx)
 {
 //      - - - - - - - - - - - - - - - - - - - - - - - - - - -
     complex<double> lc, mc;
     complex<double> c01(0.0,1.0);
 //       Calculate the "A1" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t m(0); m < Nm+1; ++m){
         mc = complex<double>(m);
         A1[m] = (-1.0)*c01*mc;
     }
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "A2" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(1); l < Nl+1; ++l)
         for (size_t m=0; m<((Nm<l)?Nm:l)+1; ++m){
             lc = complex<double>(l);
             mc = complex<double>(m);
             A2(l,m) = (-0.5)*(lc+1.0-mc)*(lc+mc);
         }
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "A3" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     A3 = 0.5;
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "B1" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(0); l < Nl+1; ++l){
         lc = complex<double>(l);
         B1[l] = (-1.0)*lc*(lc+1.0);
     }
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
MakeG00()
void Electric_Field_1D::MakeG00 (SHarmonic1D & f) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 828 of file vlasov.cpp.
References SHarmonic1D::Dp(), Electric_Field_1D::G, SHarmonic1D::numx(), and Electric_Field_1D::pr.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ex(), Electric_Field_1D::Implicit_Ex_f1only(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D::Implicit_Ez(), Electric_Field_1D::Implicit_Ez_f1only(), and Electric_Field_1D::operator()().
{
 //--------------------------------------------------------------
     G = f; G = G.Dp();
     complex<double> p0p1_sq( pr[0]*pr[0]/(pr[1]*pr[1]) ),
             inv_mp0p1_sq( 1.0/(1.0-p0p1_sq) ),
             g_r = -4.0*(pr[1]-pr[0]) * pr[0]/(pr[1]*pr[1]),
             // g_r = 2.0*(pr[0]/pr[1]/pr[1]),
             f00;
     for (size_t i(0); i < f.numx(); ++i) {
         f00    = ( f(0,i) - f(1,i) * p0p1_sq) * inv_mp0p1_sq;
         G(0,i) = ( f(1,i) - f00) * g_r;
     }
 }
MakeGH()
void Electric_Field_1D::MakeGH (SHarmonic1D & f, size_t l) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 807 of file vlasov.cpp.
References SHarmonic1D::Dp(), Electric_Field_1D::G, Electric_Field_1D::H, Electric_Field_1D::Hp0, Electric_Field_1D::invpr, SHarmonic1D::mpaxis(), SHarmonic1D::numx(), and Electric_Field_1D::pr.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ex(), Electric_Field_1D::Implicit_Ex_f1only(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D::Implicit_Ez(), Electric_Field_1D::Implicit_Ez_f1only(), and Electric_Field_1D::operator()().
{
 //--------------------------------------------------------------
     valarray<complex<double> > invpax(invpr);
     complex<double> ld(el);
     invpax *= (-2.0)*(ld+1.0) * (pr[1]-pr[0]);
     G = f;                   H = f;
     G = G.Dp();
     H  = H.mpaxis(invpax);
     H += G;
     G *= -(2.0*ld+1.0)/ld;
     G += H;
     for (size_t i(0); i < G.numx(); ++i) G(0,i) = 0.0;
     for (size_t i(0); i < H.numx(); ++i) H(0,i) = f(1,i) * Hp0[el];
 }
operator()() [1/12]
void Spatial_Advection_1D::operator() (const DistFunc1D & Din, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1249 of file vlasov.cpp.
References Spatial_Advection_1D::A1, Spatial_Advection_1D::A2, SHarmonic1D::Dx(), Spatial_Advection_1D::fd1, Spatial_Advection_1D::fd2, DistFunc1D::l0(), DistFunc1D::m0(), DistFunc1D::mass(), SHarmonic1D::mpaxis(), and Spatial_Advection_1D::vr.
{
 //--------------------------------------------------------------
     valarray<complex<double> > vt(vr); vt *= 1.0/Din.mass();
     size_t l0(Din.l0());
     size_t m0(Din.m0());
     for (size_t m(0); m < ((m0<l0)?(m0+1):m0); ++m){
         fd1 = Din(m,m);     fd1 = fd1.Dx();
         vt *= A1(m,m);                          Dh(m+1,m) += fd1.mpaxis(vt);
         for (size_t l(m+1); l < l0; ++l) {
             fd1 = Din(l,m);            fd1 = fd1.Dx();
             vt *= A2(l,m)/A1(l-1,m);    fd2 = fd1;  Dh(l-1,m) += fd1.mpaxis(vt);
             vt *= A1(l,m)/A2(l  ,m);                Dh(l+1,m) += fd2.mpaxis(vt);
         }
         fd1 = Din(l0,m);            fd1 = fd1.Dx();
         vt *= A2(l0,m)/A1(l0-1,m);                 Dh(l0-1,m) += fd1.mpaxis(vt);
         vt *= 1.0/A2(l0,m);
     }
 }
operator()() [2/12]
void Electric_Field_1D::operator() (const DistFunc1D & Din, const Field1D & FEx, const Field1D & FEy, const Field1D & FEz, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 187 of file vlasov.cpp.
References Electric_Field_1D::A1, Electric_Field_1D::A2, Field1D::array(), Electric_Field_1D::B1, Electric_Field_1D::B2, Electric_Field_1D::C1, Electric_Field_1D::C2, Electric_Field_1D::C3, Electric_Field_1D::C4, Electric_Field_1D::G, Electric_Field_1D::H, DistFunc1D::l0(), DistFunc1D::m0(), Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), SHarmonic1D::mxaxis(), DistFunc1D::q(), SHarmonic1D::Re(), and Electric_Field_1D::TMP.
{
 //--------------------------------------------------------------
 //  This is the core calculation for the electric field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Ex(FEx.array());
     valarray<complex<double> > Em(FEz.array());
     Em *= (-1.0)*ii;
     Em += FEy.array();
     valarray<complex<double> > Ep(FEz.array());
     Ep *= ii;
     Ep += FEy.array();
     Ex *= Din.q();
     Em *= Din.q();
     Ep *= Din.q();
     size_t l0(Din.l0());
     size_t m0(Din.m0());
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeG00(Din(0,0));
     Ex *= A1(0,0); TMP = G; Dh(1,0) += G.mxaxis(Ex);
     Em *= C1[0];            Dh(1,1) += TMP.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(1,0),1);
     Ex *= A2(1,0) / A1(0,0);          Dh(0,0) += H.mxaxis(Ex);
     Ex *= A1(1,0) / A2(1,0); TMP = G; Dh(2,0) += G.mxaxis(Ex);
     Em *= C1[1]   / C1[0]  ;          Dh(2,1) += TMP.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, 1 < l < l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(2); l < l0; ++l){
         MakeGH(Din(l,0),l);
         Ex *= A2(l,0) / A1(l-1,0); TMP = H;  Dh(l-1,0) += H.mxaxis(Ex);
         Em *= C3[l]   / C1[l-1];             Dh(l-1,1) += TMP.mxaxis(Em);
         Ex *= A1(l,0) / A2(l,0);   TMP = G;  Dh(l+1,0) += G.mxaxis(Ex);
         Em *= C1[l]   / C3[l];               Dh(l+1,1) += TMP.mxaxis(Em);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0,  l = l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(l0,0),l0);
     Ex *= A2(l0,0) / A1(l0-1,0); TMP = H;  Dh(l0-1,0) += H.mxaxis(Ex);
     Em *= C3[l0]   / C1[l0-1];             Dh(l0-1,1) += TMP.mxaxis(Em);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(1,1),1);
     Ep *= B2[1];              H = H.mxaxis(Ep);     Dh(0,0) += H.Re();
     Ex *= A1(1,1) / A2(l0,0); TMP = G;              Dh(2,1) += G.mxaxis(Ex);
     Em *= C1[1] / C3[l0];     G = TMP;              Dh(2,2) += TMP.mxaxis(Em);
     Ep *= B1[1] / B2[1];      G = G.mxaxis(Ep);     Dh(2,0) += G.Re();
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 2
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(2,1),2);
     Ex *= A2(2,1) / A1(1,1); TMP = H;               Dh(1,1) += TMP.mxaxis(Ex);
     Ep *= B2[2]   / B1[1];   H = H.mxaxis(Ep);      Dh(1,0) += H.Re();
     Ex *= A1(2,1) / A2(2,1); TMP = G;               Dh(3,1) += G.mxaxis(Ex);
     Em *= C1[2]   / C1[1];   G = TMP;               Dh(3,2) += TMP.mxaxis(Em);
     Ep *= B1[2]   / B2[2];   G = G.mxaxis(Ep);      Dh(3,0) += G.Re();
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, 1 < l < l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(3); l < l0; ++l){
         MakeGH(Din(l,1),l);
         Ex *= A2(l,1) / A1(l-1,1); TMP = H;             Dh(l-1,1) += H.mxaxis(Ex);
         Em *= C3[l]   / C1[l-1];   H = TMP;             Dh(l-1,2) += TMP.mxaxis(Em);
         Ep *= B2[l]   / B1[l-1];   H = H.mxaxis(Ep);    Dh(l-1,0) += H.Re();
         Ex *= A1(l,1) / A2(l,1);   TMP = G;             Dh(l+1,1) += G.mxaxis(Ex);
         Em *= C1[l]   / C3[l];     G = TMP;             Dh(l+1,2) += TMP.mxaxis(Em);
         Ep *= B1[l]   / B2[l];     G = G.mxaxis(Ep);    Dh(l+1,0) += G.Re();
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       m = 1,  l = l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(l0,1),l0);
     Ex *= A2(l0,1) / A1(l0-1,1); TMP = H;              Dh(l0-1,1) += H.mxaxis(Ex);
     Em *= C3[l0]   / C1[l0-1];   H = TMP;              Dh(l0-1,2) += TMP.mxaxis(Em);
     Ep *= B2[l0]   / B1[l0-1];   H = H.mxaxis(Ep);     Dh(l0-1,0) += H.Re();
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     C4(l0,1) = B2[l0];
     for (size_t m(2); m < m0; ++m){
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //          m > 1 , l = m
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         MakeGH(Din(m,m),m);
         Ep *= C4(m,m) / C4(l0,m-1);              Dh(m-1,m-1) += H.mxaxis(Ep);
         Ex *= A1(m,m) / A2(l0,m-1); TMP = G;     Dh(m+1,m  ) += G.mxaxis(Ex);
         Em *= C1[m]   / C3[l0];     G = TMP;     Dh(m+1,m+1) += TMP.mxaxis(Em);
         Ep *= C2(m,m) / C4(m,m);                 Dh(m+1,m-1) += G.mxaxis(Ep);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //          m > 1 , l = m+1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         MakeGH(Din(m+1,m),m+1);
         Ex *= A2(m+1,m) / A1(m,m);   TMP = H;     Dh(m  ,m  ) += TMP.mxaxis(Ex);
         Ep *= C4(m+1,m) / C2(m,m);                Dh(m  ,m-1) += H.mxaxis(Ep);
         if ( m+1 < l0) { //always true except when m = m0-1 = l0-1
             Ex *= A1(m+1,m) / A2(m+1,m); TMP = G;     Dh(m+2,m  ) += G.mxaxis(Ex);
             Em *= C1[m+1]   / C1[m];     G = TMP;     Dh(m+2,m+1) += TMP.mxaxis(Em);
             Ep *= C2(m+1,m) / C4(m+1,m);              Dh(m+2,m-1) += G.mxaxis(Ep);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //              m > 1, 1 < l < l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
             for (size_t l(m+2); l < l0; ++l){
                 MakeGH(Din(l,m),l);
                 Ex *= A2(l,m) / A1(l-1,m); TMP = H;   Dh(l-1,m  ) += H.mxaxis(Ex);
                 Em *= C3[l]   / C1[l-1];   H = TMP;   Dh(l-1,m+1) += TMP.mxaxis(Em);
                 Ep *= C4(l,m) / C2(l-1,m);            Dh(l-1,m-1) += H.mxaxis(Ep);
                 Ex *= A1(l,m) / A2(l,m);   TMP = G;   Dh(l+1,m  ) += G.mxaxis(Ex);
                 Em *= C1[l]   / C3[l];     G = TMP;   Dh(l+1,m+1) += TMP.mxaxis(Em);
                 Ep *= C2(l,m) / C4(l,m);              Dh(l+1,m-1) += G.mxaxis(Ep);
             }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //               m > 1,  l = l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
             MakeGH(Din(l0,m),l0);
             Ex *= A2(l0,m) / A1(l0-1,m); TMP = H;    Dh(l0-1,m  ) += H.mxaxis(Ex);
             Em *= C3[l0]   / C1[l0-1];   H = TMP;    Dh(l0-1,m+1) += TMP.mxaxis(Em);
             Ep *= C4(l0,m) / C2(l0-1,m);             Dh(l0-1,m-1) += H.mxaxis(Ep);
         }
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     MakeGH(Din(m0,m0),m0);
     Ep *= C4(m0,m0) / C4(l0,m0-1);              Dh(m0-1,m0-1) += H.mxaxis(Ep);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       m = m0, l0 > l > m0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     if ( m0 < l0) {
         Ex *= A1(m0,m0) / A2(l0,m0-1); TMP = G;  Dh(m0+1,m0  ) += TMP.mxaxis(Ex);
         Ep *= C2(m0,m0) / C4(m0,m0);             Dh(m0+1,m0-1) += G.mxaxis(Ep);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //          m = m0 , l = m0+1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
         MakeGH(Din(m0+1,m0),m0+1);
         Ex *= A2(m0+1,m0) / A1(m0,m0); TMP = H;        Dh(m0,m0  )  += TMP.mxaxis(Ex);
         Ep *= C4(m0+1,m0) / C2(m0,m0);                 Dh(m0,m0-1)  += H.mxaxis(Ep);
         if ( m0+1 < l0) {
             Ex *= A1(m0+1,m0) / A2(m0+1,m0); TMP = G;  Dh(m0+2,m0  )+= TMP.mxaxis(Ex);
             Ep *= C2(m0+1,m0) / C4(m0+1,m0);           Dh(m0+2,m0-1)+= G.mxaxis(Ep);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //              m = m0, m0+2 < l < l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
             for (size_t l(m0+2); l < l0; ++l){
                 MakeGH(Din(l,m0),l);
                 Ex *= A2(l,m0) / A1(l-1,m0); TMP = H;  Dh(l-1,m0)   += TMP.mxaxis(Ex);
                 Ep *= C4(l,m0) / C2(l-1,m0);           Dh(l-1,m0-1) += H.mxaxis(Ep);
                 Ex *= A1(l,m0) / A2(l,  m0); TMP = G;  Dh(l+1,m0  ) += TMP.mxaxis(Ex);
                 Ep *= C2(l,m0) / C4(l,  m0);           Dh(l+1,m0-1) += G.mxaxis(Ep);
             }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //               m > 1,  l = l0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
             MakeGH(Din(l0,m0),l0);
             Ex *= A2(l0,m0) / A1(l0-1,m0); TMP = H;    Dh(l0-1,m0)   += TMP.mxaxis(Ex);
             Ep *= C4(l0,m0) / C2(l0-1,m0);             Dh(l0-1,m0-1) += H.mxaxis(Ep);
         }
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
operator()() [3/12]
void interspecies_f00_RKfunctor::operator() (const valarray< double > & fin1, valarray< double > & fslope) virtual
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Implements Algorithms::AbstFunctor< valarray< double > >.
Definition at line 308 of file interspeciescollisions.cpp.
 {}
operator()() [4/12]
void interspecies_f00_RKfunctor::operator() (const valarray< double > & fin1, const valarray< double > & fin2, valarray< double > & fslope)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Definition at line 305 of file interspeciescollisions.cpp.
References interspecies_f00_RKfunctor::collide, and interspecies_f00_explicit_step::takestep().
{
         fslope = collide.takestep(fin1,fin2);
     }
operator()() [5/12]
void interspecies_f00_RKfunctor::operator() (const valarray< double > & fin1, valarray< double > & fslope, size_t dir) virtual
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Implements Algorithms::AbstFunctor< valarray< double > >.
Definition at line 309 of file interspeciescollisions.cpp.
 {}
operator()() [6/12]
void Magnetic_Field_1D::operator() (const DistFunc1D & Din, const Field1D & FBx, const Field1D & FBy, const Field1D & FBz, DistFunc1D & Dh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 898 of file vlasov.cpp.
References Magnetic_Field_1D::A1, Magnetic_Field_1D::A2, Magnetic_Field_1D::A3, Field1D::array(), Magnetic_Field_1D::B1, Magnetic_Field_1D::FLM, SHarmonic1D::mxaxis(), DistFunc1D::q(), and SHarmonic1D::Re().
{
 //--------------------------------------------------------------
 //  This is the core calculation for the magnetic field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Bx(FBx.array());
     valarray<complex<double> > Bm(FBy.array());
     Bm *= (-1.0)*ii;
     Bm += FBz.array();
     valarray<complex<double> > Bp(FBy.array());
     Bp *= ii;
     Bp += FBz.array();
     Bx *= Din.q();
     Bm *= Din.q();
     Bp *= Din.q();
     size_t l0(B1.size()-1);
     size_t m0(A1.size()-1);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, 1 < l < l0+1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     Bp *= A3;
     for (size_t l(1); l < l0+1; ++l){
         FLM = Din(l,0);      Dh(l,1) += FLM.mxaxis(Bp);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     FLM = Din(1,1); Bx *= A1[1];                           Dh(1,1) += FLM.mxaxis(Bx);
     FLM = Din(1,1); Bm *= B1[1]; FLM = FLM.mxaxis(Bm); Dh(1,0) += FLM.Re();
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l > 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(2); l < l0+1; ++l){
         FLM = Din(l,1);                                                Dh(l,2) += FLM.mxaxis(Bp);
         FLM = Din(l,1);                                                Dh(l,1) += FLM.mxaxis(Bx);
         FLM = Din(l,1); Bm *= B1[l]/B1[l-1]; FLM = FLM.mxaxis(Bm); Dh(l,0) += FLM.Re();
     }
     Bm *= 1.0/B1[l0];
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m > 1, l = m
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t m(2); m < m0; ++m){
         FLM = Din(m,m); Bx *= A1[m]/A1[m-1];                   Dh(m,m  ) += FLM.mxaxis(Bx);
         FLM = Din(m,m); Bm *= A2(m,m);                         Dh(m,m-1) += FLM.mxaxis(Bm);
         for (size_t l(m+1); l < l0+1; ++l){
             FLM = Din(l,m);                                    Dh(l,m+1) += FLM.mxaxis(Bp);
             FLM = Din(l,m);                                    Dh(l,m  ) += FLM.mxaxis(Bx);
             FLM = Din(l,m); Bm *= A2(l,m)/A2(l-1,m);           Dh(l,m-1) += FLM.mxaxis(Bm);
         }
         Bm *= 1.0/A2(l0,m);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = m0, l >= m0
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     FLM = Din(m0,m0); Bx *= A1[m0]/A1[m0-1];                   Dh(m0,m0)   += FLM.mxaxis(Bx);
     FLM = Din(m0,m0); Bm *= A2(m0,m0)/*/A2(l0,m0-1)*/;             Dh(m0,m0-1) += FLM.mxaxis(Bm);
     for (size_t l(m0+1); l < l0+1; ++l){
         FLM = Din(l,m0);                                     Dh(l,m0  )  += FLM.mxaxis(Bx);
         FLM = Din(l,m0); Bm *= A2(l,m0)/A2(l-1,m0);          Dh(l,m0-1)  += FLM.mxaxis(Bm);
     }
 }
operator()() [7/12]
void Current_1D::operator() (const DistFunc1D & Din, Field1D & FExh, Field1D & FEyh, Field1D & FEzh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 53 of file vlasov.cpp.
References DistFunc1D::getcurrent(), Current_1D::Jx, Current_1D::Jy, Current_1D::Jz, and Field1D::numx().
{
     Array2D<double> temp(3,Din(0).numx());
     temp = Din.getcurrent();
     for (size_t i(0); i < Jx.numx(); ++i) {
         Jx(i) = complex<double >(temp(0,i));
         Jy(i) = complex<double >(temp(1,i));
         Jz(i) = complex<double >(temp(2,i));
     }
     Exh += Jx;
     Eyh += Jy;
     Ezh += Jz;
 }
operator()() [8/12]
void Faraday_1D::operator() (EMF1D & EMFin, EMF1D & EMFh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1342 of file vlasov.cpp.
References EMF1D::By(), EMF1D::Bz(), Field1D::Dx(), EMF1D::Ey(), EMF1D::Ez(), Faraday_1D::idx, and Faraday_1D::tmpE.
{
 //--------------------------------------------------------------
 //  This is the core calculation for Faraday's Law
 //--------------------------------------------------------------
 //      dBx/dt += - dEz/dy
 //         tmpE          = Fin.Ez();
 //         tmpE         *= (-1.0) * idy;
 //         Yh.EMF().Bx() += tmpE.Dy();
 //      dBy/dt +=   dEz/dx
     tmpE                 = EMFin.Ez();
     tmpE                *= idx;
     EMFh.By()           += tmpE.Dx();
     // EMFh.By()(numx-1)    = 0.0;
 //      dBz/dt +=   dEx/dy
 //         tmpE          = Ein.Ex();
 //         tmpE         *= idy;
 //         Yh.EMF().Bz() += tmpE.Dy();
 //      dBz/dt += - dEy/dx
     tmpE                 = EMFin.Ey();
     tmpE                *= (-1.0) * idx;
     EMFh.Bz()           += tmpE.Dx();
     // EMFh.Bz()(numx-1)    = 0.0;
 }
operator()() [9/12]
void Ampere_1D::operator() (EMF1D & EMFin, EMF1D & EMFh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1391 of file vlasov.cpp.
References EMF1D::By(), EMF1D::Bz(), Field1D::Dx(), EMF1D::Ey(), EMF1D::Ez(), Ampere_1D::idx, and Ampere_1D::tmpB.
{
 //--------------------------------------------------------------
 //  This is the core calculation for Ampere's Law
 //--------------------------------------------------------------
 //      dEx/dt +=   dBz/dy
 //         tmpB          = Fin.Bz();
 //         tmpB         *= idy;
 //         Fh.Ex() += tmpB.Dy();
 //      dEy/dt +=  - dBz/dx
     tmpB                 = EMFin.Bz();
     tmpB                *= (-1.0) * idx;
     EMFh.Ey()           += tmpB.Dx();
     //.Dx();
     // EMFh.Ey()(numx-1)    = 0.0;
 //      dEz/dt +=  - dBx/dy
 //         tmpB          = Fin.Bx();
 //         tmpB         *= (-1.0) * idy;
 //         Fh.Ez() += tmpB.Dy();
 //      dEz/dt += dBy/dx
     tmpB                 = EMFin.By();
     tmpB                *=  idx;
     EMFh.Ez()           += tmpB.Dx();
     // EMFh.Ez()(numx-1)    = 0.0;
 }
operator()() [10/12]
void self_f00_RKfunctor::operator() (const valarray< double > & fin, valarray< double > & fslope) virtual
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
{ item_description }
Implements Algorithms::AbstFunctor< valarray< double > >.
Definition at line 753 of file collisions.cpp.
References self_f00_RKfunctor::collide, and self_f00_explicit_step::takestep().
{
     collide.takestep(fin,fslope);
 }
operator()() [11/12]
void self_f00_RKfunctor::operator() (const valarray< double > & fin, valarray< double > & fslope, size_t dir) virtual
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Implements Algorithms::AbstFunctor< valarray< double > >.
Definition at line 757 of file collisions.cpp.
 {}
operator()() [12/12]
void self_f00_RKfunctor::operator() (const valarray< double > & fin, const valarray< double > & f2in, valarray< double > & fslope)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 758 of file collisions.cpp.
 {}
remapintegrals()
void interspecies_f00_explicit_step::remapintegrals () private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Remap Distribution to momentum grid of colliding particles.
Initialize
Find nearest cell and distance from it
Interpolate
Definition at line 262 of file interspeciescollisions.cpp.
References interspecies_f00_explicit_step::I2_s1, interspecies_f00_explicit_step::I2_s2, interspecies_f00_explicit_step::I4_s1, interspecies_f00_explicit_step::I4_s2, interspecies_f00_explicit_step::J1_s1, interspecies_f00_explicit_step::J1_s2, interspecies_f00_explicit_step::pgrid_s1, and interspecies_f00_explicit_step::pgrid_s2.
Referenced by interspecies_f00_explicit_step::takestep().
{
         double cell_s2            = 0;
         double dp_s2              = pgrid_s2[2]-pgrid_s2[1];
         double dist               = 0.0;
         I4_s1[0] = 0.0;
         I2_s1[0] = 0.0;
         J1_s1[J1_s1.size()-1] = 0.0;
         int n(0);
         while ( (n < pgrid_s1.size()) && (pgrid_s1[n] < pgrid_s2[pgrid_s2.size()-1]))
         {
             dist      = modf(   pgrid_s1[n]/dp_s2 , &cell_s2            );
             // std::cout << "p[" << n << "]=" << pgrid_s1[n] << ", dist=" << dist << ", cell_s2 = " << cell_s2 << "\n";
             I4_s1[n]  = I4_s2[static_cast<size_t>(cell_s2)]*(1.0-dist) + I4_s2[static_cast<size_t>(cell_s2)+1]*dist;
             I2_s1[n]  = I2_s2[static_cast<size_t>(cell_s2)]*(1.0-dist) + I2_s2[static_cast<size_t>(cell_s2)+1]*dist;
             J1_s1[n]  = J1_s2[static_cast<size_t>(cell_s2)]*(1.0-dist) + J1_s2[static_cast<size_t>(cell_s2)+1]*dist;
             ++n;
         }
         while (n < pgrid_s1.size())
         {
             I4_s1[n]  = I4_s2[I4_s2.size()];
             I2_s1[n]  = I2_s2[I2_s2.size()];
             J1_s1[n]  = 0.0;
             ++n;
         }
     }
reset_coeff() [1/2]
void interspecies_flm_implicit_step::reset_coeff (const valarray< double > & fin, const double Delta_t)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Resets coefficients and integrals to use in the matrix solve.
Parameters
[in] fin Input distribution function
[in] Delta_t timestep
Definition at line 433 of file interspeciescollisions.cpp.
References interspecies_flm_implicit_step::_LOGee, interspecies_flm_implicit_step::_ZLOGei, interspecies_flm_implicit_step::Alpha_Tri, interspecies_flm_implicit_step::ddf0, interspecies_flm_implicit_step::df0, interspecies_flm_implicit_step::Dt, interspecies_flm_implicit_step::formulas, interspecies_flm_implicit_step::I0, interspecies_flm_implicit_step::I0_density, interspecies_flm_implicit_step::I2, interspecies_flm_implicit_step::I2_temperature, interspecies_flm_implicit_step::J1m, interspecies_flm_implicit_step::kpre, Formulary::LOGee(), Formulary::LOGei(), interspecies_flm_implicit_step::Scattering_Term, interspecies_flm_implicit_step::U1, interspecies_flm_implicit_step::U1m1, interspecies_flm_implicit_step::U2, interspecies_flm_implicit_step::U2m1, interspecies_flm_implicit_step::U4, interspecies_flm_implicit_step::U4m1, interspecies_flm_implicit_step::vr, and Formulary::Zeta.
Referenced by interspecies_flm_implicit_collisions::advancef1(), and interspecies_flm_implicit_collisions::advanceflm().
{
 //-------------------------------------------------------------------
 //  Reset the coefficients based on f_0^0
 //-------------------------------------------------------------------
 //     Calculate Dt
        Dt = Delta_t;
 //     INTEGRALS
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     Temperature integral I2 = 4*pi / (v^2) * int_0^v f(u)*u^4du
        I2[0] = 0;
        for (int k(1); k < I2.size(); ++k) {
            I2[k]  = U4[k]*fin[k]+U4m1[k]*fin[k-1];
            I2[k] += I2[k-1];
        }
        I2 *= 4.0 * M_PI;
        I2_temperature = I2[I2.size()-1];
        for (int k(0); k < I2.size(); ++k){
            I2[k] /=  vr[k]*vr[k];
        }
 //     Density integral I0 = 4*pi*int_0^v f(u)*u^2du
        I0[0] = 0;
        for (int k(1); k < I0.size(); ++k) {
            I0[k]  = U2[k]*fin[k]+U2m1[k]*fin[k-1];
            I0[k] += I0[k-1];
        }
        I0 *= 4.0 * M_PI;
        I0_density = I0[I0.size()-1];
 //     Integral J_(-1) = 4*pi * v * int_0^v f(u)*u^4du
        J1m[J1m.size()-1] = 0;
        for (int k(J1m.size()-2); k > -1; --k) {
            J1m[k]  = U1[k+1]*fin[k+1]+U1m1[k+1]*fin[k];
            J1m[k] += J1m[k+1];
        }
        for (int k(0); k < J1m.size(); ++k){
            J1m[k] *= 4.0 * M_PI *vr[k];
        }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     COULOMB LOGARITHMS
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        _LOGee  = formulas.LOGee(I0_density,I2_temperature/I0_density);
        _ZLOGei = formulas.Zeta*formulas.LOGei(I0_density,I2_temperature/I0_density,formulas.Zeta);
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     BASIC INTEGRALS FOR THE TRIDIAGONAL PART
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     Temporary arrays
        valarray<double>  TriI1(fin), TriI2(fin);
        for (int i(0); i < TriI1.size(); ++i){
            TriI1[i] = I0[i] + (2.0*J1m[i] - I2[i]) / 3.0 ;   // (-I2 + 2*J_{-1} + 3*I0) / 3
            TriI2[i] = ( I2[i] + J1m[i] ) / 3.0 ;             // ( I2 + J_{-1} ) / 3
        }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     SCATTERING TERM
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        Scattering_Term    = TriI1;
        Scattering_Term   *= _LOGee;                        // Electron-electron contribution
        Scattering_Term[0] = 0.0;
        Scattering_Term   += _ZLOGei * I0_density;          // Ion-electron contribution
        for (int i(0); i < Scattering_Term.size(); ++i){    // Multiply by 1/v^3
            Scattering_Term[i] /= pow(vr[i],3);
        }
        Scattering_Term *=  kpre * Dt;
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     MAKE TRIDIAGONAL ARRAY
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        Alpha_Tri = 0.0;
        double IvDnDm1, IvDnDp1, Ivsq2Dn;
        Alpha_Tri(0,0) = 8.0 * M_PI * fin[0];                                         //  8*pi*f0[0]
        for (int i(1); i < TriI1.size()-1; ++i){
           IvDnDm1 = 1.0 / (vr[i] * 0.5*(vr[i+1]-vr[i-1]) * (vr[i]  -vr[i-1]));       //  ( v*D_n*D_{n-1/2} )^(-1)
           IvDnDp1 = 1.0 / (vr[i] * 0.5*(vr[i+1]-vr[i-1]) * (vr[i+1]-vr[i]  ));       //  ( v*D_n*D_{n+1/2} )^(-1)
           Ivsq2Dn = 1.0 / (vr[i] * vr[i]                 * (vr[i+1]-vr[i-1]));       //  ( v^2 * 2*D_n )^(-1)
           Alpha_Tri(i, i  ) = 8.0 * M_PI * fin[i] - TriI2[i] * (IvDnDm1 + IvDnDp1);
           Alpha_Tri(i, i-1) = TriI2[i] * IvDnDm1 - TriI1[i] * Ivsq2Dn;
           Alpha_Tri(i, i+1) = TriI2[i] * IvDnDp1 + TriI1[i] * Ivsq2Dn;
        }
        Alpha_Tri *=  (-1.0) * _LOGee * kpre * Dt;         // (-1) because the matrix moves to the LHS in the equation
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     CALCULATE DERIVATIVES
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     Evaluate the derivative
        for (int n(1); n < fin.size()-1; ++n) {
            df0[n]  = fin[n+1]-fin[n-1];
            df0[n] /= vr[n+1]-vr[n-1];
        }
 //     Evaluate the second derivative
 //        -df/dv_{n-1/2}
        for (int n(1); n < fin.size(); ++n) {
            ddf0[n]  = (fin[n-1]-fin[n]) ;
            ddf0[n] /= vr[n] - vr[n-1] ;
        }
 //        D(df/dv)/Dv
        for (int n(1); n < fin.size()-1; ++n) {
            ddf0[n] -= ddf0[n+1];
            ddf0[n]  /= 0.5*(vr[n+1]-vr[n-1]);
        }
 //     Calculate zeroth cell
        double f00 = ( fin[0] - ( (vr[0]*vr[0])/(vr[1]*vr[1]) ) *fin[1] )
                        / (1.0 - (vr[0]*vr[0])/(vr[1]*vr[1]));
        ddf0[0] = 2.0 * (fin[1] - f00) / (vr[1]*vr[1]);
         df0[0] = ddf0[0] * vr[0];
 //     Calculate 1/(2v)*(d^2f)/(dv^2),  1/v^2*df/dv
        for (int n(0); n < fin.size()-1; ++n) {
            df0[n]  /= vr[n]*vr[n];
            ddf0[n] /= 2.0  *vr[n];
        }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     }
reset_coeff() [2/2]
void self_flm_implicit_step::reset_coeff (const valarray< double > & fin, double Zvalue, const double Delta_t)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Resets coefficients and integrals to use in the matrix solve.
Parameters
[in] fin Input distribution function
[in] Delta_t timestep
Definition at line 898 of file collisions.cpp.
References self_flm_implicit_step::_LOGee, self_flm_implicit_step::_ZLOGei, self_flm_implicit_step::Alpha_Tri, self_flm_implicit_step::ddf0, self_flm_implicit_step::df0, self_flm_implicit_step::Dt, self_flm_implicit_step::formulas, self_flm_implicit_step::I0, self_flm_implicit_step::I0_density, self_flm_implicit_step::I2, self_flm_implicit_step::I2_temperature, self_flm_implicit_step::J1m, self_flm_implicit_step::kpre, Formulary::LOGee(), Formulary::LOGei(), self_flm_implicit_step::Scattering_Term, self_flm_implicit_step::U1, self_flm_implicit_step::U1m1, self_flm_implicit_step::U2, self_flm_implicit_step::U2m1, self_flm_implicit_step::U4, self_flm_implicit_step::U4m1, self_flm_implicit_step::vr, and Formulary::Zeta.
Referenced by self_flm_implicit_collisions::advancef1(), and self_flm_implicit_collisions::advanceflm().
{
 //-------------------------------------------------------------------
 //  Reset the coefficients based on f_0^0
 //-------------------------------------------------------------------
 //     Calculate Dt
     Dt = Delta_t;
     double idp = 1.0/(vr[2] - vr[1]);
 //     INTEGRALS
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     Temperature integral I2 = 4*pi / (v^2) * int_0^v f(u)*u^4du
 //     Density integral I0 = 4*pi*int_0^v f(u)*u^2du
 //    I2[0] = U4[0]*fin[0];
 //    I0[0] = U2[0]*fin[0];
     I2[0] = 0;
     I0[0] = 0;
     for (int k(1); k < I2.size(); ++k) {
         I2[k]  = U4[k]*fin[k]+U4m1[k]*fin[k-1];
         I2[k] += I2[k-1];
         I0[k]  = U2[k]*fin[k]+U2m1[k]*fin[k-1];
         I0[k] += I0[k-1];
 //        I2[k]  = U4[k]*fin[k];
 //        I2[k] += I2[k-1];
 //
 //        I0[k]  = U2[k]*fin[k];
 //        I0[k] += I0[k-1];
     }
     I0_density = 4.0*M_PI*I0[I0.size()-1];
     I2_temperature = I2[I2.size()-1]/3.0/I0[I0.size()-1];
     //     Integral J_(-1) = 4*pi * v * int_0^v f(u)*u^4du
     J1m[J1m.size()-1] = 0;
     for (int k(J1m.size()-2); k > -1; --k) {
         J1m[k]  = U1[k+1]*fin[k+1]+U1m1[k+1]*fin[k];
         J1m[k] += J1m[k+1];
     }
     /*J1m[J1m.size()-1] = fin[J1m.size()-1]*U1[U1.size()-1];
     *//*std::cout << "\nI2[" << U1.size()-1 << "] = " << I2[U1.size()-1] << endl;
     std::cout << "I0[" << U1.size()-1 << "] = " << I0[U1.size()-1] << endl;
     std::cout << "J1[" << U1.size()-1 << "] = " << J1m[U1.size()-1] << endl;
     std::cout << "\n\n";*//*
     for (int k(J1m.size()-2); k > -1; --k) {
         J1m[k]  = U1[k]*fin[k];//+U1m1[k+1]*fin[k];
         J1m[k] += J1m[k+1];
         *//*std::cout << "\nI2[" << k << "] = " << I2[k] << endl;
         std::cout << "I0[" << k << "] = " << I0[k] << endl;
         std::cout << "J1[" << k << "] = " << J1m[k] << endl;
         std::cout << "\n\n";*//*
     }*/
     for (int k(0); k < J1m.size(); ++k){
         I2[k]  /=  vr[k] * vr[k] / 4.0 / M_PI;
         I0[k]  *= 4.0 * M_PI;
         J1m[k] *= 4.0 * M_PI * vr[k];
     }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     COULOMB LOGARITHMS
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     _LOGee  = formulas.LOGee(I0_density,I2_temperature);
     _ZLOGei = (formulas.Zeta*Zvalue)*formulas.LOGei(I0_density,I2_temperature,(formulas.Zeta*Zvalue));
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     BASIC INTEGRALS FOR THE TRIDIAGONAL PART
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     Temporary arrays
     valarray<double>  TriI1(fin), TriI2(fin);
     for (int i(0); i < TriI1.size(); ++i){
         TriI1[i] = I0[i] + (2.0*J1m[i] - I2[i]) / 3.0 ;   // (-I2 + 2*J_{-1} + 3*I0) / 3
         TriI2[i] = ( I2[i] + J1m[i] ) / 3.0 ;             // ( I2 + J_{-1} ) / 3
     }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     SCATTERING TERM
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     Scattering_Term    = TriI1;
     Scattering_Term   *= _LOGee;                        // Electron-electron contribution
     Scattering_Term[0] = 0.0;
     Scattering_Term   += _ZLOGei * I0_density;          // Ion-electron contribution
     for (int i(0); i < Scattering_Term.size(); ++i){    // Multiply by 1/v^3
         Scattering_Term[i] /= pow(vr[i],3);
     }
     Scattering_Term *=  kpre * Dt;
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     MAKE TRIDIAGONAL ARRAY
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     Alpha_Tri = 0.0;
     double IvDnDm1, IvDnDp1, Ivsq2Dn;
     Alpha_Tri(0,0) = 8.0 * M_PI * fin[0];                                         //  8*pi*f0[0]
     for (int i(1); i < TriI1.size()-1; ++i){
         IvDnDm1 = 1.0 / (vr[i] * 0.5*(vr[i+1]-vr[i-1]) * (vr[i]   - vr[i-1]));       //  ( v*D_n*D_{n-1/2} )^(-1)
         IvDnDp1 = 1.0 / (vr[i] * 0.5*(vr[i+1]-vr[i-1]) * (vr[i+1] - vr[i]  ));       //  ( v*D_n*D_{n+1/2} )^(-1)
         Ivsq2Dn = 1.0 / (vr[i] * vr[i]                 * (vr[i+1] - vr[i-1]));       //  ( v^2 * 2*D_n )^(-1)
         Alpha_Tri(i, i  ) = 8.0 * M_PI * fin[i] - TriI2[i] * (IvDnDm1 + IvDnDp1);
         Alpha_Tri(i, i-1) = TriI2[i] * IvDnDm1 - TriI1[i] * Ivsq2Dn;
         Alpha_Tri(i, i+1) = TriI2[i] * IvDnDp1 + TriI1[i] * Ivsq2Dn;
     }
     /*Alpha_Tri(0,0) = 8.0 * M_PI * fin[0];                                         //  8*pi*f0[0]
     for (int i(1); i < TriI1.size()-1; ++i){
         Alpha_Tri(i, i  ) = - 2.0 * TriI2[i] / vr[i] * idp * idp;
         Alpha_Tri(i, i-1) = TriI2[i] / vr[i] * idp * idp - TriI1[i] / 2.0 / vr[i] / vr[i] * idp;
         Alpha_Tri(i, i+1) = TriI2[i] / vr[i] * idp * idp + TriI1[i] / 2.0 / vr[i] / vr[i] * idp;
     }*/
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     Alpha_Tri *=  (-1.0) * _LOGee * kpre * Dt;         // (-1) because the matrix moves to the LHS in the equation
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 /*
 //     CALCULATE DERIVATIVES
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     df0[0]  = (fin[1] - fin[0]);
     df0[0] /= (vr[1] - vr[0]);
 //     Evaluate the derivative
     for (int n(1); n < fin.size()-1; ++n) {
         df0[n]  = fin[n+1] - fin[n-1];
         df0[n] /= vr[n+1] - vr[n-1];
     }
     df0[df0.size()-1]  = fin[df0.size()-1] - fin[df0.size()-2];
     df0[df0.size()-1] /= vr[df0.size()-1] - vr[df0.size()-2];
     ddf0[0]  = fin[0] - 2.0*fin[1] + fin[2];
     ddf0[0] /= vr[1] - vr[0];
     ddf0[0] /= vr[1] - vr[0];
 //     Evaluate the second derivative
 //        -df/dv_{n-1/2}
     for (int n(1); n < fin.size()-1; ++n) {
         ddf0[n]  = fin[n+1] - 2.0*fin[n] + fin[n-1];
         ddf0[n] /= vr[n] - vr[n-1];
         ddf0[n] /= vr[n] - vr[n-1];
 //        ddf0[n]  = (fin[n-1]-fin[n]) ;
 //        ddf0[n] /= vr[n] - vr[n-1] ;
     }
     ddf0[ddf0.size()-1] = fin[ddf0.size()-1] - 2.0*fin[ddf0.size()-2] + fin[ddf0.size()-3];
     ddf0[ddf0.size()-1] /= vr[vr.size()-1] - vr[vr.size()-2];
     ddf0[ddf0.size()-1] /= vr[vr.size()-1] - vr[vr.size()-2];
 //        D(df/dv)/Dv
 //    for (int n(1); n < fin.size()-1; ++n) {
 //        ddf0[n] -= ddf0[n+1];
 //        ddf0[n]  /= 0.5*(vr[n+1]-vr[n-1]);
 //    }
 //     Calculate zeroth cell
 //    double f00 = ( fin[0] - ( (vr[0]*vr[0])/(vr[1]*vr[1]) ) *fin[1] )
 //                 / (1.0 - (vr[0]*vr[0])/(vr[1]*vr[1]));
 //    ddf0[0] = 2.0 * (fin[1] - f00) / (vr[1]*vr[1]);
 //    df0[0] = ddf0[0] * vr[0];
 //     Calculate 1/(2v)*(d^2f)/(dv^2),  1/v^2*df/dv
     for (int n(0); n < fin.size()-1; ++n) {
         df0[n]  /= vr[n]*vr[n];
         ddf0[n] /= 2.0  *vr[n];
     }
 */
     //     Evaluate the derivative
     for (int n(1); n < fin.size()-1; ++n) {
         df0[n]  = fin[n+1]-fin[n-1];
         df0[n] /= vr[n+1]-vr[n-1];
     }
 //     Evaluate the second derivative
 //        -df/dv_{n-1/2}
     for (int n(1); n < fin.size(); ++n) {
         ddf0[n]  = (fin[n-1]-fin[n]) ;
         ddf0[n] /= vr[n] - vr[n-1] ;
     }
 //        D(df/dv)/Dv
     for (int n(1); n < fin.size()-1; ++n) {
         ddf0[n] -= ddf0[n+1];
         ddf0[n]  /= 0.5*(vr[n+1]-vr[n-1]);
     }
 //     Calculate zeroth cell
     double f00 = ( fin[0] - ( (vr[0]*vr[0])/(vr[1]*vr[1]) ) *fin[1] )
                  / (1.0 - (vr[0]*vr[0])/(vr[1]*vr[1]));
     ddf0[0] = 2.0 * (fin[1] - f00) / (vr[1]*vr[1]);
     df0[0] = ddf0[0] * vr[0];
 //     Calculate 1/(2v)*(d^2f)/(dv^2),  1/v^2*df/dv
     for (int n(0); n < fin.size()-1; ++n) {
         df0[n]  /= vr[n]*vr[n];
         ddf0[n] /= 2.0  *vr[n];
     }
 //     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
rkloop()
void interspecies_f00_explicit_collisions::rkloop (SHarmonic1D & SH1, const SHarmonic1D & SH2)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
This loop calls the RK4_f00 private member that is responsible for setting up the RK4 algorithm to advance the collision step.
Definition at line 333 of file interspeciescollisions.cpp.
References interspecies_f00_explicit_collisions::fin1, interspecies_f00_explicit_collisions::fin2, interspecies_f00_explicit_collisions::Nbc, interspecies_f00_explicit_collisions::num_h, and interspecies_f00_explicit_collisions::szx.
{
 //-------------------------------------------------------------------
 //  This loop scans all the locations in configuration space
 //  and calls the RK4 for explicit integration at each location
 //-------------------------------------------------------------------
       // std::cout << "\n\n DF1 = " << fin1.size();
       // std::cout << ", DF2 = " << fin2.size() << " \n\n";
       // valarray<double>                        fin1(0.0,SH1.nump()),fin2(0.0,SH2.nump());
       for (size_t ix(0); ix < szx-2*Nbc; ++ix){
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           // Copy data for a specific location in space to valarray
           for (size_t ip(0); ip < fin1.size(); ++ip){
               fin1[ip] = (SH1(ip,ix+Nbc)).real();
           }
           for (size_t ip(0); ip < fin2.size(); ++ip){
               fin2[ip] = (SH2(ip,ix+Nbc)).real();
           }
           // // Time loop: Update the valarray
           for (size_t h_step(0); h_step < num_h; ++h_step){
 //              fin1 = RK4(fin1,fin2,h,&rkf00);
           }
           // // std::cout << "\n\n 11 \n\n";
           // // Return updated data to the harmonic
           for (int ip(0); ip < fin1.size(); ++ip){
               // std::cout << "\n\nfin[" << ip << "] = "<< fin1[ip];
               SH1(ip,ix+Nbc) = fin1[ip];
           }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       }
     }
self()
vector< self_collisions > collisions::self ()
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 1523 of file collisions.cpp.
References collisions::self_coll.
{
     return self_coll;
 }
self_collisions()
self_collisions::self_collisions (const DistFunc1D & DFin, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Constructors/Destructors.
Definition at line 1358 of file collisions.cpp.
         : self_f00_exp_collisions(DFin, deltat),
           self_f00_imp_collisions(DFin, deltat),
           self_flm_collisions(DFin, deltat){}
self_f00_explicit_collisions()
self_f00_explicit_collisions::self_f00_explicit_collisions (const DistFunc1D & DFin, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Constructors/Destructors.
Definition at line 769 of file collisions.cpp.
References Input::Input_List::BoundaryCells, self_f00_explicit_collisions::h, Input::List(), self_f00_explicit_collisions::Nbc, self_f00_explicit_collisions::num_h, Input::Input_List::NxLocal, and self_f00_explicit_collisions::szx.
         : fin(0.0, DFin(0,0).nump()),
           RK(fin),
           rkf00(DFin(0,0).nump(), DFin.pmax(), DFin.mass()),
           num_h(size_t(deltat/Input::List().small_dt)+1)
 {
     h = deltat/static_cast<double>(num_h);
     Nbc = Input::List().BoundaryCells;
     szx = Input::List().NxLocal[0];  // size of useful x axis
 }
self_f00_explicit_step()
self_f00_explicit_step::self_f00_explicit_step (const size_t & nump, const double & pmax, const double & _mass)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Constructor that needs a distribution function input.
Parameters
fslope The distribution function that is input and transformed.Velocity axis < Integrals
Definition at line 536 of file collisions.cpp.
References self_f00_explicit_step::c_kpre, Input::List(), self_f00_explicit_step::NB, Input::Input_List::NB_algorithms, self_f00_explicit_step::Pn, self_f00_explicit_step::Qn, self_f00_explicit_step::U1, self_f00_explicit_step::U1m1, self_f00_explicit_step::U2, self_f00_explicit_step::U2m1, self_f00_explicit_step::U3, self_f00_explicit_step::U4, self_f00_explicit_step::U4m1, and self_f00_explicit_step::vr.
         :
         mass(_mass),
 //        vr(Algorithms::MakeAxis(pmax/(2.0*nump-1.0),pmax,nump)),
         vr(Algorithms::MakeCAxis(0.0,pmax,nump)),
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         U4(0.0, nump),
         U4m1(0.0, nump),
         U2(0.0, nump),
         U2m1(0.0, nump),
         U1(0.0, nump),
         U1m1(0.0, nump),
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         J1(0.0, nump),
         I2(0.0, nump),
         I4(0.0, nump),
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         U3(0.0, nump),
         Qn(0.0, nump),
         Pn(0.0, nump)
 {
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     //classical electron radius
     double re(2.8179402894e-13);   //< classical electron radius
     double kp(sqrt(4.0*M_PI*(Input::List().density_np)*re)); //< sqrt(4*pi*n_{e0}*re).
     c_kpre = 4.0*M_PI/3.0*re*kp; //< (4*pi*re)^1.5*sqrt(n_{e0})/3.
     NB = Input::List().NB_algorithms;
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     // Determine vr
     for (size_t i(0); i < vr.size(); ++i) {
         vr[i] = vr[i] / (sqrt(1.0+vr[i]*vr[i]));
     }
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     // Determine U4, U4m1, U2, U2m1, U1, U1m1
     for (size_t i(1); i < U4.size(); ++i) {
         U4[i]   = 0.5 * pow(vr[i],4)     * (vr[i]-vr[i-1]);
         U4m1[i] = 0.5 * pow(vr[i-1],4)   * (vr[i]-vr[i-1]);
         U2[i]   = 0.5 * vr[i]*vr[i]      * (vr[i]-vr[i-1]);
         U2m1[i] = 0.5 * vr[i-1]*vr[i-1]  * (vr[i]-vr[i-1]);
         U1[i]   = 0.5 * vr[i]            * (vr[i]-vr[i-1]);
         U1m1[i] = 0.5 * vr[i-1]          * (vr[i]-vr[i-1]);
     }
 //       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     // Determine U3
     for (size_t i(0); i < U3.size(); ++i) {
         U3[i] = pow(vr[i],3);
     }
     // Determine Qn
     Qn[0] = 1.0 / ((vr[0]*vr[0]*vr[1])/2.0);
     for (size_t i(1); i < Qn.size()-1; ++i) {
         Qn[i] = 1.0 / (vr[i]*vr[i]*(vr[i+1]-vr[i-1])/2.0);
     }
     // Determine Pn
     for (size_t i(0); i < Pn.size()-1; ++i) {
         Pn[i] = 1.0 / ((vr[i+1]-vr[i])/2.0*(vr[i+1]+vr[i]));
     }
 }
self_f00_implicit_collisions()
self_f00_implicit_collisions::self_f00_implicit_collisions (const DistFunc1D & DFin, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Constructors/Destructors.
Definition at line 423 of file collisions.cpp.
References Input::Input_List::BoundaryCells, Input::List(), self_f00_implicit_collisions::Nbc, Input::Input_List::NxLocal, and self_f00_implicit_collisions::szx.
         :   fin(0.0, DFin(0,0).nump()), fout(0.0, DFin(0,0).nump()),
             xgrid(Algorithms::MakeCAxis(Input::List().xminLocal[0],Input::List().xmaxLocal[0],Input::List().NxLocal[0])),
             IB_heating(Input::List().IB_heating), MX_cooling(Input::List().MX_cooling),
             heatingprofile(0.0,DFin(0,0).numx()), coolingprofile(0.0,DFin(0,0).numx()),
             ib(((DFin.q() == -1) && (DFin.mass() == 1))),
             collide(DFin(0,0).nump(),DFin.pmax(),DFin.mass(), deltat, ib)
 {
     Nbc = Input::List().BoundaryCells;
     szx = Input::List().NxLocal[0];  // size of useful x axis
 }
self_f00_implicit_step()
self_f00_implicit_step::self_f00_implicit_step (const size_t & nump, const double & pmax, const double & _mass, const double & _deltat, bool & _ib)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Collisions
Laser
Cooling
Definition at line 44 of file collisions.cpp.
References self_f00_implicit_step::c_kpre, self_f00_implicit_step::dt, self_f00_implicit_step::dtoverv2, self_f00_implicit_step::dvr, self_f00_implicit_step::laser_Inv_Uav6, Input::List(), self_f00_implicit_step::mass, self_f00_implicit_step::p2dp, self_f00_implicit_step::p2dpm1, self_f00_implicit_step::p4dp, self_f00_implicit_step::phdp, self_f00_implicit_step::phdpm1, self_f00_implicit_step::vr, self_f00_implicit_step::vrh, and self_f00_implicit_step::vw_coeff_cube.
                                                                                                                                            :
         vr(Algorithms::MakeCAxis(0.0,pmax,nump)), C_RB(0.0,nump+1), D_RB(0.0,nump+1), delta_CC(0.0,nump+1),
         mass(_mass), dt(_deltat),
         dvr(0.0,nump), vrh(0.0,nump), dtoverv2(nump),
         p2dp(0.0,nump),p2dpm1(0.0,nump),phdp(0.0,nump),phdpm1(0.0,nump), p4dp(0.0,nump), laser_Inv_Uav6(0.0,nump),
         I4_Lnee(0.0), ib(_ib)
 {
 //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     //classical electron radius
     double re(2.8179402894e-13);   //< classical electron radius
     double kp(sqrt(4.0*M_PI*(Input::List().density_np)*re)); //< sqrt(4*pi*n_{e0}*re).
     c_kpre = re*kp; //< (4*pi*re)^1.5*sqrt(n_{e0})/3.
     // Determine vr
     for (size_t i(0); i < vr.size(); ++i) {
         vr[i] /= mass;
     }
     for (size_t i(0); i < vr.size()-1; ++i) {
         vrh[i] = 0.5*(vr[i+1] - vr[i]);
         dvr[i] = (vr[i+1] - vr[i]);
     }
     vrh[vrh.size()-1] = 0.0;
     dvr[vrh.size()-1] = dvr[vrh.size()-2];
     for (size_t i(1); i < vr.size(); ++i) {
         p2dp[i]   = 0.5 * vr[i]*vr[i]      * (vr[i]-vr[i-1]);
         p2dpm1[i] = 0.5 * vr[i-1]*vr[i-1]  * (vr[i]-vr[i-1]);
         p4dp[i]   = 0.5 * pow(vr[i],4)     * (vr[i]-vr[i-1]);
 //        p4dpm1[i] = 0.5 * pow(vr[i-1],4)   * (vr[i]-vr[i-1]);
         phdp[i]   = 0.5 * vrh[i]           * (vrh[i]-vrh[i-1]);
         phdpm1[i] = 0.5 * vrh[i-1]         * (vrh[i]-vrh[i-1]);
     }
     for (size_t i(0); i < vr.size(); ++i) {
         dtoverv2[i] = dt / vr[i] / vr[i] / dvr[i];
     }
 //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t i(0); i < vr.size(); ++i) {
         laser_Inv_Uav6[i] = pow( 2.0/(vr[i+1]+vr[i]), 6);
     }
     double omega_0(3.0e+10*2.0*M_PI/(1.0e-4*Input::List().lambda_0));
     double omega_p(5.64 * 1.0e+4*sqrt(Input::List().density_np));
     vw_coeff_cube = omega_p/omega_0 * c_kpre;
 //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
self_f00_RKfunctor()
self_f00_RKfunctor::self_f00_RKfunctor (const size_t & nump, const double & pmax, const double & mass)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Constructor for RK4 method on f00.
Parameters
fin Input distribution
[in] tout_start Hmm...
Definition at line 743 of file collisions.cpp.
         :collide(nump,pmax,mass){}
self_flm_implicit_collisions()
self_flm_implicit_collisions::self_flm_implicit_collisions (const DistFunc1D & DFin, const double & deltat)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Constructors/Destructors.
Definition at line 1237 of file collisions.cpp.
References Input::Input_List::BoundaryCells, self_flm_implicit_collisions::f1_m_upperlimit, Input::List(), self_flm_implicit_collisions::m0, self_flm_implicit_collisions::Nbc, Input::Input_List::NxLocal, and self_flm_implicit_collisions::szx.
         : f00(0.0, DFin(0).nump()),
           fc(0.0,DFin(0).nump()),
           l0(DFin.l0()),
           m0(DFin.m0()),//Yin.SH(0,0).m0())
           implicit_step(DFin.pmax(),DFin(0).nump(),DFin.mass()),
           Dt(deltat)    //
 {
     Nbc = Input::List().BoundaryCells;
     szx = Input::List().NxLocal[0];
     if (m0 == 0) {
         f1_m_upperlimit = 1;
     }
     else {
         f1_m_upperlimit = 2;
     }
 }
self_flm_implicit_step()
self_flm_implicit_step::self_flm_implicit_step (double pmax, size_t nump, double mass)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 829 of file collisions.cpp.
References self_flm_implicit_step::kpre, Input::List(), self_flm_implicit_step::mass, self_flm_implicit_step::U1, self_flm_implicit_step::U1m1, self_flm_implicit_step::U2, self_flm_implicit_step::U2m1, self_flm_implicit_step::U4, self_flm_implicit_step::U4m1, and self_flm_implicit_step::vr.
         :
 //       Pre-Calculated Constants
 //        vr(Algorithms::MakeAxis(pmax/(2.0*nump-1.0),pmax,nump)),
         vr(Algorithms::MakeCAxis(0.0,pmax,nump)),
 //       Constants for Integrals
         U4(0.0,  nump),
         U4m1(0.0,nump),
         U2(0.0,  nump),
         U2m1(0.0,nump),
         U1(0.0,  nump),
         U1m1(0.0,nump),
 //       Integrals
         J1m(0.0,  nump),
         I0(0.0,  nump),
         I2(0.0,  nump),
         Scattering_Term(0.0, nump),
         df0(0.0,  nump),
         ddf0(0.0,  nump),
 //       Matrices
         Alpha_Tri(nump, nump),
         if_tridiagonal(Input::List().if_tridiagonal),
         mass(_mass)
 //       Make matrix vk/vn
 {
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     double re(2.8179402894e-13);           //classical electron radius
     double kp(sqrt(4.0*M_PI*(Input::List().density_np)*re));
     kpre = re*kp;
     // Determine vr
     for (size_t i(0); i < vr.size(); ++i) {
 //        vr[i] = vr[i] / (sqrt(1.0+vr[i]*vr[i]));
         vr[i] /= mass;
     }
 //    U4[0] = pow(vr[0],4)          * (vr[1]-vr[0]);
 //    U2[0] = vr[0]*vr[0]           * (vr[1]-vr[0]);
 //    U1[0] = vr[0]                 * (vr[1]-vr[0]);
     // Determine U4, U4m1, U2, U2m1, U1, U1m1 for the integrals
     for (size_t i(1); i < U4.size(); ++i) {
         U4[i]   = 0.5 * pow(vr[i],4)     * (vr[i]-vr[i-1]);
         U4m1[i] = 0.5 * pow(vr[i-1],4)   * (vr[i]-vr[i-1]);
         U2[i]   = 0.5 * vr[i]*vr[i]      * (vr[i]-vr[i-1]);
         U2m1[i] = 0.5 * vr[i-1]*vr[i-1]  * (vr[i]-vr[i-1]);
         U1[i]   = 0.5 * vr[i]            * (vr[i]-vr[i-1]);
         U1m1[i] = 0.5 * vr[i-1]          * (vr[i]-vr[i-1]);
 //        U4[i]   = pow(vr[i],4)          * (vr[i]-vr[i-1]);
 //        U2[i]   = vr[i]*vr[i]           * (vr[i]-vr[i-1]);
 //        U1[i]   = vr[i]                 * (vr[i]-vr[i-1]);
     }
 }
Spatial_Advection_1D()
Spatial_Advection_1D::Spatial_Advection_1D (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov.h>
Definition at line 1199 of file vlasov.cpp.
References Spatial_Advection_1D::A00, Spatial_Advection_1D::A1, Spatial_Advection_1D::A10, Spatial_Advection_1D::A2, Spatial_Advection_1D::A20, and Spatial_Advection_1D::vr.
         : A1(Nl+1,Nm+1), A2(Nl+1,Nm+1),
           fd1(Np,Nx), fd2(Np,Nx),
          // vr(Algorithms::MakeAxis(complex<double>(pmax/2.0/Np),
          //                         complex<double>(pmax),
          //                         Np)) {
           vr(Algorithms::MakeCAxis(complex<double>(0.0),
                                   complex<double>(pmax),
                                   Np)){
 //      - - - - - - - - - - - - - - - - - - - - - - - - - - -
     complex<double> lc, mc;
     for (size_t i(0); i < vr.size(); ++i) {
         vr[i] = vr[i]/(sqrt(1.0+vr[i]*vr[i]));
     }
     double idx = (-1.0) / (2.0*(xmax-xmin)/double(Nx)); // -1/(2dx)
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "A1, A2" parameters
     for (size_t l(0); l < Nl+1; ++l){
         for (size_t m=0; m<((Nm<l)?Nm:l)+1; ++m){
             lc = complex<double>(l);
             mc = complex<double>(m);
             A1(l,m) = idx *(-1.0) * (lc-mc+1.0) / (2.0*lc+1.0);
             A2(l,m) = idx *(-1.0) * (lc+mc)     / (2.0*lc+1.0);
         }
     }
     A2(0,0) = 1.0;
     //       Calculate the "A1, A2" parameters
     A00 = complex<double>(idx);
     A10 = complex<double>(idx/3.0);
     A20 = complex<double>(idx*2.0/5.0);
 }
takestep() [1/3]
valarray< double > interspecies_f00_explicit_step::takestep (const valarray< double > & f1in, const valarray< double > & f2in)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Collisions between species 1 and 2 in 0,0 harmonic.
Parameters
[in] f1in Input distribution function, the change to which is returned
[in] f2in Input distribution function, f1 collides with f2
[in] Delta_t timestep
[in] df1 the delta f1
Definition at line 125 of file interspeciescollisions.cpp.
References interspecies_f00_explicit_step::calculateintegrals(), interspecies_f00_explicit_step::df0, interspecies_f00_explicit_step::dt, interspecies_f00_explicit_step::formulary, interspecies_f00_explicit_step::fslope, interspecies_f00_explicit_step::Gamma12, interspecies_f00_explicit_step::I2_s1, interspecies_f00_explicit_step::I4_s1, interspecies_f00_explicit_step::J1_s1, interspecies_f00_explicit_step::kpre, Formulary::LOGii(), interspecies_f00_explicit_step::m1, interspecies_f00_explicit_step::m2, interspecies_f00_explicit_step::n1, interspecies_f00_explicit_step::n2, interspecies_f00_explicit_step::pgrid_s1, interspecies_f00_explicit_step::remapintegrals(), interspecies_f00_explicit_step::T1, interspecies_f00_explicit_step::T2, interspecies_f00_explicit_step::z1, and interspecies_f00_explicit_step::z2.
Referenced by interspecies_f00_RKfunctor::operator()().
{
         // valarray<double> temp(f1in.size());
         double temp = 0.0;
         double mu = m2/m1;
         calculateintegrals(f1in,f2in);
         remapintegrals();
         for (int n(1); n < f1in.size()-1; ++n) {
            df0[n]  = f1in[n+1]-f1in[n-1];
            df0[n] /= pgrid_s1[n+1]-pgrid_s1[n-1];
         }
         df0[0] = f1in[1]-f1in[0];
         df0[0]/= pgrid_s1[1]-pgrid_s1[0];
         df0[f1in.size()-1] = f1in[f1in.size()-1]-f1in[f1in.size()-2];
         df0[f1in.size()-1]/= pgrid_s1[f1in.size()-1]-pgrid_s1[f1in.size()-2];
         int ipp(1);
         int ipm(0);
         Gamma12 = -1.0*kpre*n2*(z1*z1*z2*z2)*formulary.LOGii(m1,z1,n1,T1,
                                                                   m2,z2,n2,T2);
         temp = (I4_s1[ipp]+J1_s1[ipp])*df0[ipp]*pgrid_s1[ipp]+3.0/mu*I2_s1[ipp]*f1in[ipp];
         temp -= (I4_s1[ipm]+J1_s1[ipm])*df0[ipm]*pgrid_s1[ipm]+3.0/mu*I2_s1[ipm]*f1in[ipm];
         temp /= pgrid_s1[ipp]-pgrid_s1[ipm];
         temp /= 3.0*(0.25*pow(pgrid_s1[ipm]+pgrid_s1[ipp],2.0));
         fslope[0] = temp;
         // std::cout << "\n fslope[0]=" <<  temp*Gamma12*dt << "\n\n";
         for (int ip(1);ip < f1in.size()-2;++ip)
         {
           ipp=ip+1;
           ipm=ip-1;
           temp  = (I4_s1[ipp]+J1_s1[ipp])*df0[ipp]*pgrid_s1[ipp]+3.0/mu*I2_s1[ipp]*f1in[ipp];
           // std::cout << "\n fslope1[ " << ip << "]="<<  temp << "\n\n";
           temp -= (I4_s1[ipm]+J1_s1[ipm])*df0[ipm]*pgrid_s1[ipm]+3.0/mu*I2_s1[ipm]*f1in[ipm];
           // std::cout << "\n fslope2[ " << ip << "]="<<  temp << "\n\n";
           temp /= pgrid_s1[ipp]-pgrid_s1[ipm];
           // std::cout << "\n fslope3[ " << ip << "]="<<  temp << "\n\n";
           temp /= 3.0*(0.25*pow(pgrid_s1[ipm]+pgrid_s1[ipp],2.0));
           // std::cout << "\n fslope4[ " << ip << "]="<<  temp << "\n\n";
           // temp *= Gamma12*dt;
           fslope[ip] = temp;
           // std::cout << "\n fslope[ " << ip << "]="<<  temp*Gamma12*dt << "\n\n";
         }
         // std::cout << "\n fslope5[ " <<  Gamma12 << "\n\n";
         ipp=f1in.size()-1;ipm=f1in.size()-2;
         temp  = (I4_s1[ipp]+J1_s1[ipp])*df0[ipp]*pgrid_s1[ipp]+3.0/mu*I2_s1[ipp]*f1in[ipp];
         temp -= (I4_s1[ipm]+J1_s1[ipm])*df0[ipm]*pgrid_s1[ipm]+3.0/mu*I2_s1[ipm]*f1in[ipm];
         temp /= pgrid_s1[ipp]-pgrid_s1[ipm];
         temp /= 3.0*(0.25*pow(pgrid_s1[ipm]+pgrid_s1[ipp],2.0));
         fslope[f1in.size()-1] = temp;
         // std::cout << "\n fslope[last]=" <<  temp*Gamma12*dt << "\n\n";
         fslope=fslope*Gamma12*dt;
         // fslope[f1in.size()-1] = 0.0;
           // }
         // exit(1);
       return fslope;
   }
takestep() [2/3]
void self_f00_implicit_step::takestep (valarray< double > & fin, valarray< double > & fh, const double & Z0, const double & heating, const double & cooling)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Calculate Rosenbluth and Chang-Cooper quantities
Also fills in I4_Lnee (the temperature for the Lnee calculation)
And takes care of boundaries
Normalizing quantities (Inspired by previous collision routines and OSHUN notes by M. Tzoufras)
< ZLogLambda
Fill in matrix
Boundaries by hand – This operates on f(0)
Definition at line 266 of file collisions.cpp.
References self_f00_implicit_step::c_kpre, self_f00_implicit_step::C_RB, self_f00_implicit_step::D_RB, self_f00_implicit_step::delta_CC, self_f00_implicit_step::dtoverv2, self_f00_implicit_step::dvr, self_f00_implicit_step::formulas, self_f00_implicit_step::I4_Lnee, self_f00_implicit_step::ib, Formulary::LOGee(), Formulary::LOGei(), Thomas_Tridiagonal(), self_f00_implicit_step::update_C_Rosenbluth(), self_f00_implicit_step::update_D_and_delta(), self_f00_implicit_step::update_D_inversebremsstrahlung(), and Formulary::Zeta.
{
     double collisional_coefficient;
     double heating_coefficient;
     Array2D<double> LHS(fin.size(),fin.size());
     update_C_Rosenbluth(fin);
     update_D_and_delta(fin);
     collisional_coefficient  = formulas.LOGee(C_RB[C_RB.size()-1],I4_Lnee/3.0/C_RB[C_RB.size()-1]);
     collisional_coefficient *= 4.0*M_PI/3.0*c_kpre;
     heating_coefficient  = formulas.Zeta*Z0*formulas.LOGei(C_RB[C_RB.size()-1],I4_Lnee/3.0/C_RB[C_RB.size()-1],Z0*formulas.Zeta);
     heating_coefficient *= c_kpre / 6.0 * pow(vos,2.0) * C_RB[C_RB.size()-1];
     heating_coefficient /= collisional_coefficient;
     if (ib) update_D_inversebremsstrahlung(Z0, heating_coefficient, vos);
     size_t ip(0);
     LHS(ip, ip + 1) = - dtoverv2[ip] * collisional_coefficient
                       * (C_RB[ip + 1] * (1.0 - delta_CC[ip + 1])
                          + D_RB[ip + 1] / dvr[ip + 1]);
     LHS(ip    , ip) = 1.0 - dtoverv2[ip] * collisional_coefficient
                             * (C_RB[ip + 1] * delta_CC[ip + 1] - D_RB[ip + 1] / dvr[ip + 1]
                                - C_RB[ip] * (1.0 - delta_CC[ip]) - D_RB[ip] / dvr[ip]);
     for (ip = 1; ip < fin.size() - 1; ++ip){
         LHS(ip, ip + 1) = - dtoverv2[ip] * collisional_coefficient
                           * (C_RB[ip + 1] * (1.0 - delta_CC[ip + 1])
                              + D_RB[ip + 1] / dvr[ip + 1]);
         LHS(ip    , ip) = 1.0 - dtoverv2[ip] * collisional_coefficient
                                 * (C_RB[ip + 1] * delta_CC[ip + 1] - D_RB[ip + 1] / dvr[ip + 1]
                                    - C_RB[ip] * (1.0 - delta_CC[ip]) - D_RB[ip] / dvr[ip]);
         LHS(ip, ip - 1) = dtoverv2[ip] * collisional_coefficient
                           * (C_RB[ip] * delta_CC[ip]
                              - D_RB[ip] / dvr[ip]);
     }
     ip = fin.size() - 1;
     LHS(ip    , ip) = 1.0 - dtoverv2[ip] * collisional_coefficient
                             * (C_RB[ip + 1] * delta_CC[ip + 1]
                                - C_RB[ip] * (1.0 - delta_CC[ip]) - D_RB[ip] / dvr[ip]);
     LHS(ip, ip - 1) = dtoverv2[ip] * collisional_coefficient
                       * (C_RB[ip] * delta_CC[ip]
                          - D_RB[ip] / dvr[ip]);
 //    std::cout << "\n\n LHS = \n";
 //    for (size_t i(0); i < LHS.dim1(); ++i) {
 //        std::cout << "i = " << i << " :::: ";
 //        for (size_t j(0); j < LHS.dim2(); ++j) {
 //            std::cout << LHS(i, j) << "   ";
 //        }
 //        std::cout << "\n";
 //    }
     Thomas_Tridiagonal(LHS,fin,fh);
 }
takestep() [3/3]
void self_f00_explicit_step::takestep (const valarray< double > & fin, valarray< double > & fh)
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Compute collision integrals and advance to next step
Parameters
[in] fin Input distribution function
Returns
Output distribution function
Definition at line 639 of file collisions.cpp.
References self_f00_explicit_step::c_kpre, self_f00_explicit_step::formulas, self_f00_explicit_step::G(), self_f00_explicit_step::I2, self_f00_explicit_step::I4, self_f00_explicit_step::J1, Formulary::LOGee(), self_f00_explicit_step::NB, self_f00_explicit_step::Pn, self_f00_explicit_step::Qn, self_f00_explicit_step::U1, self_f00_explicit_step::U1m1, self_f00_explicit_step::U2, self_f00_explicit_step::U2m1, self_f00_explicit_step::U3, self_f00_explicit_step::U4, self_f00_explicit_step::U4m1, and self_f00_explicit_step::vr.
Referenced by self_f00_RKfunctor::operator()().
{
 //-------------------------------------------------------------------
 //  Collisions
 //-------------------------------------------------------------------
     double Ln_ee;
 //     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //     Evaluate the integrals in a standard manner
     I4[0] = 0;
     for (int n(1); n < I4.size(); ++n) {
         I4[n]  = U4[n]*fin[n]+U4m1[n]*fin[n-1];
         I4[n] += I4[n-1];
     }
     I2[0] = 0;
     for (int n(1); n < I2.size(); ++n) {
         I2[n]  = U2[n]*fin[n]+U2m1[n]*fin[n-1];
         I2[n] += I2[n-1];
     }
     J1[J1.size()-1] = 0;
     for (int n(J1.size()-2); n > -1; --n) {
         J1[n]  = U1[n+1]*fin[n+1]+U1m1[n+1]*fin[n];
         J1[n] += J1[n+1];
     }
 //     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //     Use I2 and I4 to calculate the Coulomb logarithm now, the
 //     arrays I2 I4 will be modified later and it will be too late.
     // if (mass == 100.0){
     // std::cout<< "\n\n\n temp = " << mass*I4[I4.size()-1]/3.0/I2[I4.size()-1] << "\n\n\n";
     // }
     Ln_ee = formulas.LOGee(4.0*M_PI*I2[I2.size()-1],I4[I4.size()-1]/3.0/I2[I4.size()-1]);
     // // I2_temperature = I2[I2.size()-1];
     // for (int k(0); k < I4.size(); ++k){
     //    I4[k] /=  vr[k]*vr[k];
     // }
 //     <><><><><><><><><><><><><><><><><><>
 //     Tony's Energy Conserving Algorithm
 //     <><><><><><><><><><><><><><><><><><>
 //     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //     Evaluate G using the standard integrals
 //     J1 needs to be used again later so it is not modified!
     for (int n(0); n < I4.size(); ++n) {
         I2[n] *= J1[n];          // J1(n) * I2(n)
         I2[n] *= -3.0;           // -3 * J1(n) * I2(n)
         I4[n] += U3[n] * J1[n];  // I4(n) + u_n^3 * J1(n)
         I4[n] *= fin[n];         // fn * I4(n) + u_n^3 * fn * J1(n)
         I4[n] += I2[n];          // Gn = fn * I4(n) + u_n^3 * fn * J1(n) - 3 * J1(n) * I2(n)
         //
     }
 //     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //     Evaluate G assuming a parabolic f(v << vt)
     for (int n(0); n < NB; ++n) {
         I4[n] = G(n,fin);
     }
 //     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //     Find -DG
     fh[0]  = (-1.0)*I4[0];
     for (int n(0); n < I4.size()-1; ++n) I4[n] -= I4[n+1];
 //     Find -DG/(vDv)
     fh[0] *= 2.0/ (vr[0]*vr[0]);
     for (int n(0); n < I4.size()-1; ++n) I4[n] *= Pn[n];
 //     Find DDG/(vDv)
     fh[0] -= I4[0];
     for (int n(0); n < I4.size()-1; ++n) I4[n] -= I4[n+1];
 //     Find DDG/(v^3*DDv)
     fh[0] *= Qn[0];
     for (int n(0); n < I4.size()-1; ++n) fh[n+1] = Qn[n+1]*I4[n];
 //     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 //     Normalize
     fh *=  c_kpre *  Ln_ee;
 }
update_C_Rosenbluth()
void self_f00_implicit_step::update_C_Rosenbluth (valarray< double > & fin) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Remember that C is defined on the boundaries of the velocity grid Therefore, C[0] is C_{1/2} aka C(v=0) and, C[1] is C_{3/2} aka C(v[1st point, 0th index C style])
Definition at line 104 of file collisions.cpp.
References self_f00_implicit_step::C_RB, self_f00_implicit_step::dvr, self_f00_implicit_step::I4_Lnee, self_f00_implicit_step::p4dp, and self_f00_implicit_step::vr.
Referenced by self_f00_implicit_step::getleftside(), and self_f00_implicit_step::takestep().
{
     C_RB[0] = 0.0;
     I4_Lnee = 0.0;
     for (int n(1); n < C_RB.size(); ++n) {
 //        C_RB[n]  = p2dp[n-1] * fin[n-1] + p2dpm1[n-1] * fin[n - 2];
         C_RB[n]  = vr[n - 1] * vr[n - 1] * dvr[n - 1] * fin[n - 1];
         C_RB[n] += C_RB[n - 1];
         I4_Lnee  += p4dp[n - 1] * fin[n - 1];
     }
     C_RB *= 4.0 * M_PI;
     I4_Lnee *= 4.0 * M_PI;
 }
update_D_and_delta()
void self_f00_implicit_step::update_D_and_delta (valarray< double > & fin) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Remember that D and delta are defined on the boundaries of the velocity grid Therefore, D[0] = D_{1/2} = D(v=0) and, D[1] D = D_{3/2} D(v[1st point, 0th index C-style])
Definition at line 166 of file collisions.cpp.
References self_f00_implicit_step::C_RB, self_f00_implicit_step::calc_delta_ChangCooper(), self_f00_implicit_step::D_RB, self_f00_implicit_step::delta_CC, Input::List(), and self_f00_implicit_step::update_D_Rosenbluth().
Referenced by self_f00_implicit_step::getleftside(), and self_f00_implicit_step::takestep().
{
     size_t iterations(0);
     bool iteration_check(0);
     double D(0.0);
     double Dold(10.0);
     double delta(0.5);
     D_RB[0]             = 0.0;
     D_RB[D_RB.size()-1] = 0.0;
     delta_CC[0]             = 0.5;
     delta_CC[D_RB.size()-1] = 0.0;
     for (size_t k(1); k < fin.size(); ++k){
         delta = 0.5;
         D = 0.0;
         Dold = 10.0;
         iterations = 0;
         iteration_check = 0;
         do
         {
             D = update_D_Rosenbluth(k,fin,delta);
 //            std::cout << ", D[" << k << "] = " << D;
             if (fabs(D-Dold) < Input::List().RB_D_tolerance*(1.0+fabs(D+Dold))) iteration_check = 1;
             delta = calc_delta_ChangCooper(k, C_RB[k], D);
 //            std::cout << ", delta[" << k << "] = " << delta;
             ++iterations;
             if (iterations > Input::List().RB_D_itmax) iteration_check = 1;
             Dold = D;
         } while(!iteration_check);
 //        std::cout << "\n Chang-cooper iterations = " << iterations << "\n";
         D_RB[k]     = D;
         delta_CC[k] = delta;
 //        std::cout << "\n C[" << k << "] = " << C_RB[k];
 //        std::cout << ", D[" << k << "] = " << D;
 //        std::cout << ", delta[" << k << "] = " << delta;
     }
 //        exit(1);
 }
update_D_inversebremsstrahlung()
void self_f00_implicit_step::update_D_inversebremsstrahlung (const double & Z0, const double & heatingcoefficient, const double & vos) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
< ZLogLambda
Definition at line 235 of file collisions.cpp.
References self_f00_implicit_step::C_RB, self_f00_implicit_step::D_RB, self_f00_implicit_step::formulas, self_f00_implicit_step::I4_Lnee, self_f00_implicit_step::laser_Inv_Uav6, Formulary::LOGee(), Formulary::LOGei(), self_f00_implicit_step::vr, self_f00_implicit_step::vw_coeff_cube, and Formulary::Zeta.
Referenced by self_f00_implicit_step::getleftside(), and self_f00_implicit_step::takestep().
{
     double vw_cube;// = vw_coeff_cube; * ZLn_ei * 4.0*M_PI*I2;;
     double temperature = I4_Lnee/3.0/C_RB[C_RB.size()-1];
     vw_cube  = Z0*formulas.Zeta*formulas.LOGei(C_RB[C_RB.size()-1],temperature,Z0*formulas.Zeta);
     vw_cube *= vw_coeff_cube * C_RB[C_RB.size()-1];
     double ZLnee = Z0*formulas.Zeta*formulas.LOGee(C_RB[C_RB.size()-1],temperature);
     double g, b0, nueff, xsi;
 //    xsi     = 3.84+(142.59-65.48*vos/sqrt(temperature)/(27.3*vos/sqrt(temperature)+vos*vos/temperature);
     for (size_t ip(1); ip < D_RB.size()-1; ++ip){
 //        b0      = (vos*vos+5.0*vr[ip]*vr[ip])/(5.0*vr[ip]*vr[ip]);
 //        nueff   = ZLnee/pow(vr[ip]*vr[ip]+vos*vos/xsi,1.5);
 //        g       = 1.0 - b0*nueff*vw_cube/(1.0+b0*b0*nuOeff*vw_cube);
         g = laser_Inv_Uav6[ip] * vw_cube * vw_cube;
         g = 1.0 / (1.0 + g);
         D_RB[ip] += heating_coefficient * g / vr[ip];
     }
 }
update_D_Rosenbluth()
double self_f00_implicit_step::update_D_Rosenbluth (const size_t & k, valarray< double > & fin, const double & delta) private
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Only needs to be np-1
Initialize at last point, which is the sum from np-1 to np-1
Now n = np - 1
So innersum = f_{np} * (1-delta_{np-1/2})
f_{np-1} * (delta_{np-1/2})
Using indexing from Kingham2004. v is defined from 1 to nv, obviously So k = 1 is the first velocity cell and distribution function point. Therefore, all the l's should be referenced to with l - 1
Definition at line 127 of file collisions.cpp.
References self_f00_implicit_step::dvr, and self_f00_implicit_step::vr.
Referenced by self_f00_implicit_step::update_D_and_delta().
{
     double answer(0.0);
     valarray<double> innersum(fin.size() - 1);
     int n(innersum.size()-1);
     innersum[n]  = (1.0 - delta) * fin[n + 1] + delta * fin[n];
     innersum[n] *= (vr[n + 1] * vr[n + 1] - vr[n] * vr[n]);
     --n;
     for (n; n > -1; --n) {
         innersum[n] = (1.0 - delta) * fin[n + 1] + delta * fin[n];
         innersum[n] *= (vr[n + 1] * vr[n + 1] - vr[n] * vr[n]);
         innersum[n] += innersum[n + 1];
 //        std::cout << "\n innersum[" << n << "] = " << innersum[n] << "\n";
     }
     for (size_t l(1); l < k + 1; ++l) {
         answer += vr[l - 1] * vr[l - 1] * dvr[l - 1] * innersum[l - 1];
     }
     answer *= 4.0 * M_PI;
     answer *= 1.0 / (vr[k - 1] + vr[k]);
     return answer;
 }
~interspecies_f00_RKfunctor()
interspecies_f00_RKfunctor::~interspecies_f00_RKfunctor () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/interspeciescollisions.h>
Definition at line 74 of file interspeciescollisions.h.
References interspecies_f00_explicit_step::fslope.
 { };
~self_f00_RKfunctor()
self_f00_RKfunctor::~self_f00_RKfunctor () inline
#include </Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/collisions.h>
Definition at line 162 of file collisions.h.
 { };
Variable Documentation
_LOGee [1/2]
double interspecies_flm_implicit_step::_LOGee private
Definition at line 164 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), and interspecies_flm_implicit_step::reset_coeff().
_LOGee [2/2]
double self_flm_implicit_step::_LOGee private
Definition at line 262 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), and self_flm_implicit_step::reset_coeff().
_ZLOGei [1/2]
double interspecies_flm_implicit_step::_ZLOGei private
Definition at line 164 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::reset_coeff().
_ZLOGei [2/2]
double self_flm_implicit_step::_ZLOGei private
Definition at line 262 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff().
A00
complex<double> Spatial_Advection_1D::A00 private
Definition at line 32 of file vlasov.h.
Referenced by Spatial_Advection_1D::f1only(), and Spatial_Advection_1D::Spatial_Advection_1D().
A1 [1/3]
Array2D< complex<double> > Spatial_Advection_1D::A1 private
Definition at line 33 of file vlasov.h.
Referenced by Spatial_Advection_1D::es1d(), Spatial_Advection_1D::operator()(), and Spatial_Advection_1D::Spatial_Advection_1D().
A1 [2/3]
Array2D< complex<double> > Electric_Field_1D::A1 private
Definition at line 74 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::es1d(), Electric_Field_1D::Implicit_Ex(), and Electric_Field_1D::operator()().
A1 [3/3]
valarray< complex<double> > Magnetic_Field_1D::A1 private
Definition at line 106 of file vlasov.h.
Referenced by Magnetic_Field_1D::f1only(), Magnetic_Field_1D::Magnetic_Field_1D(), and Magnetic_Field_1D::operator()().
A10
complex<double> Spatial_Advection_1D::A10 private
Definition at line 32 of file vlasov.h.
Referenced by Spatial_Advection_1D::f1only(), and Spatial_Advection_1D::Spatial_Advection_1D().
A100
complex<double> Electric_Field_1D::A100 private
Definition at line 72 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::f1only(), and Electric_Field_1D::Implicit_Ex_f1only().
A2 [1/3]
Array2D< complex<double> > Spatial_Advection_1D::A2 private
Definition at line 33 of file vlasov.h.
Referenced by Spatial_Advection_1D::es1d(), Spatial_Advection_1D::operator()(), and Spatial_Advection_1D::Spatial_Advection_1D().
A2 [2/3]
Array2D< complex<double> > Electric_Field_1D::A2 private
Definition at line 74 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::es1d(), Electric_Field_1D::Implicit_Ex(), and Electric_Field_1D::operator()().
A2 [3/3]
Array2D< complex<double> > Magnetic_Field_1D::A2 private
Definition at line 107 of file vlasov.h.
Referenced by Magnetic_Field_1D::Magnetic_Field_1D(), and Magnetic_Field_1D::operator()().
A20
complex<double> Spatial_Advection_1D::A20 private
Definition at line 32 of file vlasov.h.
Referenced by Spatial_Advection_1D::Spatial_Advection_1D().
A210
complex<double> Electric_Field_1D::A210 private
Definition at line 72 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::f1only(), and Electric_Field_1D::Implicit_Ex_f1only().
A3
complex<double> Magnetic_Field_1D::A3 private
Definition at line 108 of file vlasov.h.
Referenced by Magnetic_Field_1D::f1only(), Magnetic_Field_1D::Magnetic_Field_1D(), and Magnetic_Field_1D::operator()().
A310
complex<double> Electric_Field_1D::A310 private
Definition at line 72 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D().
Alpha_Tri [1/2]
Array2D<double> interspecies_flm_implicit_step::Alpha_Tri private
Definition at line 159 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), and interspecies_flm_implicit_step::reset_coeff().
Alpha_Tri [2/2]
Array2D<double> self_flm_implicit_step::Alpha_Tri private
Definition at line 256 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), and self_flm_implicit_step::reset_coeff().
B1 [1/2]
valarray< complex<double> > Electric_Field_1D::B1 private
Definition at line 75 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ez(), and Electric_Field_1D::operator()().
B1 [2/2]
valarray< complex<double> > Magnetic_Field_1D::B1 private
Definition at line 106 of file vlasov.h.
Referenced by Magnetic_Field_1D::f1only(), Magnetic_Field_1D::Magnetic_Field_1D(), and Magnetic_Field_1D::operator()().
B2
valarray< complex<double> > Electric_Field_1D::B2 private
Definition at line 75 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ez(), and Electric_Field_1D::operator()().
B211
complex<double> Electric_Field_1D::B211 private
Definition at line 72 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ey_f1only(), and Electric_Field_1D::Implicit_Ez_f1only().
C1
valarray< complex<double> > Electric_Field_1D::C1 private
Definition at line 76 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ez(), and Electric_Field_1D::operator()().
C100
complex<double> Electric_Field_1D::C100 private
Definition at line 72 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ey_f1only(), and Electric_Field_1D::Implicit_Ez_f1only().
C2
Array2D< complex<double> > Electric_Field_1D::C2 private
Definition at line 77 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), and Electric_Field_1D::operator()().
C3
valarray< complex<double> > Electric_Field_1D::C3 private
Definition at line 76 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ez(), and Electric_Field_1D::operator()().
C311
complex<double> Electric_Field_1D::C311 private
Definition at line 72 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D().
C4
Array2D< complex<double> > Electric_Field_1D::C4 private
Definition at line 77 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ez(), and Electric_Field_1D::operator()().
c_kpre [1/2]
double self_f00_implicit_step::c_kpre private
Constants.
Definition at line 48 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), self_f00_implicit_step::self_f00_implicit_step(), and self_f00_implicit_step::takestep().
c_kpre [2/2]
double self_f00_explicit_step::c_kpre private
Constants.
Definition at line 138 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
C_RB
valarray<double> self_f00_implicit_step::C_RB private
Rosenbluth Potentials.
Definition at line 41 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), self_f00_implicit_step::takestep(), self_f00_implicit_step::update_C_Rosenbluth(), self_f00_implicit_step::update_D_and_delta(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
collide [1/3]
interspecies_f00_explicit_step interspecies_f00_RKfunctor::collide private
Definition at line 83 of file interspeciescollisions.h.
Referenced by interspecies_f00_RKfunctor::operator()().
collide [2/3]
self_f00_implicit_step self_f00_implicit_collisions::collide private
Definition at line 93 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop().
collide [3/3]
self_f00_explicit_step self_f00_RKfunctor::collide private
Definition at line 170 of file collisions.h.
Referenced by self_f00_RKfunctor::operator()().
coolingprofile
valarray<double> self_f00_implicit_collisions::coolingprofile private
Definition at line 100 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop().
D_RB
valarray<double> self_f00_implicit_step::D_RB private
Definition at line 41 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), self_f00_implicit_step::takestep(), self_f00_implicit_step::update_D_and_delta(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
ddf0 [1/2]
valarray<double> interspecies_flm_implicit_step::ddf0 private
Definition at line 155 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), and interspecies_flm_implicit_step::reset_coeff().
ddf0 [2/2]
valarray<double> self_flm_implicit_step::ddf0 private
Definition at line 252 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), and self_flm_implicit_step::reset_coeff().
delta_CC
valarray<double> self_f00_implicit_step::delta_CC private
Chang-Cooper weighting delta.
Definition at line 45 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), self_f00_implicit_step::takestep(), and self_f00_implicit_step::update_D_and_delta().
df0 [1/3]
valarray<double> interspecies_f00_explicit_step::df0 private
Definition at line 54 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::takestep().
df0 [2/3]
valarray<double> interspecies_flm_implicit_step::df0 private
Definition at line 155 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), and interspecies_flm_implicit_step::reset_coeff().
df0 [3/3]
valarray<double> self_flm_implicit_step::df0 private
Definition at line 252 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), and self_flm_implicit_step::reset_coeff().
dt [1/2]
double self_f00_implicit_step::dt private
Definition at line 28 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step().
dt [2/2]
double interspecies_f00_explicit_step::dt private
Definition at line 45 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::takestep().
Dt [1/4]
double interspecies_flm_implicit_step::Dt private
Definition at line 164 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), and interspecies_flm_implicit_step::reset_coeff().
Dt [2/4]
double interspecies_flm_implicit_collisions::Dt private
Definition at line 206 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advancef1(), and interspecies_flm_implicit_collisions::advanceflm().
Dt [3/4]
double self_flm_implicit_step::Dt private
Definition at line 262 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), and self_flm_implicit_step::reset_coeff().
Dt [4/4]
double self_flm_implicit_collisions::Dt private
Definition at line 305 of file collisions.h.
Referenced by self_flm_implicit_collisions::advancef1(), and self_flm_implicit_collisions::advanceflm().
dtoverv2
valarray<double> self_f00_implicit_step::dtoverv2 private
Definition at line 34 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), self_f00_implicit_step::self_f00_implicit_step(), and self_f00_implicit_step::takestep().
dvr
valarray<double> self_f00_implicit_step::dvr private
Definition at line 32 of file collisions.h.
Referenced by self_f00_implicit_step::calc_delta_ChangCooper(), self_f00_implicit_step::getleftside(), self_f00_implicit_step::self_f00_implicit_step(), self_f00_implicit_step::takestep(), self_f00_implicit_step::update_C_Rosenbluth(), and self_f00_implicit_step::update_D_Rosenbluth().
f00 [1/2]
valarray<double> interspecies_flm_implicit_collisions::f00 private
Array for isotropic component distribution function. Needed for calculating coefficients.
Definition at line 215 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advancef1(), and interspecies_flm_implicit_collisions::advanceflm().
f00 [2/2]
valarray<double> self_flm_implicit_collisions::f00 private
Array for isotropic component distribution function. Needed for calculating coefficients.
Definition at line 315 of file collisions.h.
Referenced by self_flm_implicit_collisions::advancef1(), and self_flm_implicit_collisions::advanceflm().
f1_m_upperlimit
int self_flm_implicit_collisions::f1_m_upperlimit private
Definition at line 309 of file collisions.h.
Referenced by self_flm_implicit_collisions::advancef1(), and self_flm_implicit_collisions::self_flm_implicit_collisions().
fc [1/2]
valarray<complex<double> > interspecies_flm_implicit_collisions::fc private
Dummy array.
Definition at line 214 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advancef1(), and interspecies_flm_implicit_collisions::advanceflm().
fc [2/2]
valarray<complex<double> > self_flm_implicit_collisions::fc private
Dummy array.
Definition at line 314 of file collisions.h.
Referenced by self_flm_implicit_collisions::advancef1(), and self_flm_implicit_collisions::advanceflm().
fd1
SHarmonic1D Spatial_Advection_1D::fd1 private
Definition at line 31 of file vlasov.h.
Referenced by Spatial_Advection_1D::es1d(), Spatial_Advection_1D::f1only(), and Spatial_Advection_1D::operator()().
fd2
SHarmonic1D Spatial_Advection_1D::fd2 private
Definition at line 31 of file vlasov.h.
Referenced by Spatial_Advection_1D::es1d(), and Spatial_Advection_1D::operator()().
fin [1/2]
valarray<double> self_f00_implicit_collisions::fin private
Definition at line 90 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop().
fin [2/2]
valarray<double> self_f00_explicit_collisions::fin private
Definition at line 203 of file collisions.h.
Referenced by self_f00_explicit_collisions::loop().
fin1
valarray<double> interspecies_f00_explicit_collisions::fin1 private
Definition at line 115 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_collisions::rkloop().
fin2
valarray<double> interspecies_f00_explicit_collisions::fin2 private
Definition at line 115 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_collisions::rkloop().
FLM
SHarmonic1D Magnetic_Field_1D::FLM private
Definition at line 104 of file vlasov.h.
Referenced by Magnetic_Field_1D::f1only(), and Magnetic_Field_1D::operator()().
formulary
Formulary interspecies_f00_explicit_step::formulary private
Definition at line 46 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::takestep().
formulas [1/4]
Formulary self_f00_implicit_step::formulas private
Definition at line 51 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), self_f00_implicit_step::takestep(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
formulas [2/4]
Formulary self_f00_explicit_step::formulas private
Definition at line 140 of file collisions.h.
Referenced by self_f00_explicit_step::takestep().
formulas [3/4]
Formulary interspecies_flm_implicit_step::formulas private
Definition at line 165 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::reset_coeff().
formulas [4/4]
Formulary self_flm_implicit_step::formulas private
Definition at line 264 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff().
fout
valarray<double> self_f00_implicit_collisions::fout private
Definition at line 90 of file collisions.h.
fslope
valarray<double> interspecies_f00_explicit_step::fslope private
Definition at line 43 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::takestep(), and interspecies_f00_RKfunctor::~interspecies_f00_RKfunctor().
G
SHarmonic1D Electric_Field_1D::G private
Definition at line 70 of file vlasov.h.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ex(), Electric_Field_1D::Implicit_Ex_f1only(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D::Implicit_Ez(), Electric_Field_1D::Implicit_Ez_f1only(), Electric_Field_1D::MakeG00(), Electric_Field_1D::MakeGH(), and Electric_Field_1D::operator()().
Gamma12
double interspecies_f00_explicit_step::Gamma12 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::takestep().
H
SHarmonic1D Electric_Field_1D::H private
Definition at line 70 of file vlasov.h.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ex(), Electric_Field_1D::Implicit_Ex_f1only(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ey_f1only(), Electric_Field_1D::Implicit_Ez(), Electric_Field_1D::Implicit_Ez_f1only(), Electric_Field_1D::MakeGH(), and Electric_Field_1D::operator()().
h [1/2]
double interspecies_f00_explicit_collisions::h private
Definition at line 120 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_collisions::interspecies_f00_explicit_collisions().
h [2/2]
double self_f00_explicit_collisions::h private
Definition at line 215 of file collisions.h.
Referenced by self_f00_explicit_collisions::loop(), and self_f00_explicit_collisions::self_f00_explicit_collisions().
heatingprofile
valarray<double> self_f00_implicit_collisions::heatingprofile private
Definition at line 99 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop().
Hp0
valarray< complex<double> > Electric_Field_1D::Hp0 private
Definition at line 78 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), and Electric_Field_1D::MakeGH().
I0 [1/2]
valarray<double> interspecies_flm_implicit_step::I0 private
Definition at line 152 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::reset_coeff().
I0 [2/2]
valarray<double> self_flm_implicit_step::I0 private
Definition at line 249 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff().
I0_density [1/2]
double interspecies_flm_implicit_step::I0_density private
Definition at line 163 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::reset_coeff().
I0_density [2/2]
double self_flm_implicit_step::I0_density private
Definition at line 261 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff().
I2 [1/3]
valarray<double> self_f00_explicit_step::I2 private
Definition at line 135 of file collisions.h.
Referenced by self_f00_explicit_step::takestep().
I2 [2/3]
valarray<double> interspecies_flm_implicit_step::I2 private
Definition at line 152 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::reset_coeff().
I2 [3/3]
valarray<double> self_flm_implicit_step::I2 private
Definition at line 249 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff().
I2_s1
valarray<double> interspecies_f00_explicit_step::I2_s1 private
Definition at line 61 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::remapintegrals(), and interspecies_f00_explicit_step::takestep().
I2_s2
valarray<double> interspecies_f00_explicit_step::I2_s2 private
Definition at line 58 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::remapintegrals().
I2_temperature [1/2]
double interspecies_flm_implicit_step::I2_temperature private
Definition at line 163 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::reset_coeff().
I2_temperature [2/2]
double self_flm_implicit_step::I2_temperature private
Definition at line 261 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff().
I4
valarray<double> self_f00_explicit_step::I4 private
Definition at line 135 of file collisions.h.
Referenced by self_f00_explicit_step::takestep().
I4_Lnee
double self_f00_implicit_step::I4_Lnee private
Definition at line 42 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), self_f00_implicit_step::takestep(), self_f00_implicit_step::update_C_Rosenbluth(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
I4_s1
valarray<double> interspecies_f00_explicit_step::I4_s1 private
Definition at line 61 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::remapintegrals(), and interspecies_f00_explicit_step::takestep().
I4_s2
valarray<double> interspecies_f00_explicit_step::I4_s2 private
Definition at line 58 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::remapintegrals().
ib [1/2]
bool self_f00_implicit_step::ib private
Definition at line 29 of file collisions.h.
Referenced by self_f00_implicit_step::getleftside(), and self_f00_implicit_step::takestep().
ib [2/2]
bool self_f00_implicit_collisions::ib private
Definition at line 92 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop().
IB_heating
bool self_f00_implicit_collisions::IB_heating private
Switches for inverse bremsstrahlung and maxwellian cooling.
Definition at line 96 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop().
idx [1/2]
complex<double> Faraday_1D::idx private
Definition at line 146 of file vlasov.h.
Referenced by Faraday_1D::Faraday_1D(), and Faraday_1D::operator()().
idx [2/2]
complex<double> Ampere_1D::idx private
Definition at line 164 of file vlasov.h.
Referenced by Ampere_1D::Ampere_1D(), and Ampere_1D::operator()().
if_tridiagonal [1/2]
bool interspecies_flm_implicit_step::if_tridiagonal private
Definition at line 160 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance().
if_tridiagonal [2/2]
bool self_flm_implicit_step::if_tridiagonal private
Definition at line 257 of file collisions.h.
Referenced by self_flm_implicit_step::advance().
implicit_step [1/2]
interspecies_flm_implicit_step interspecies_flm_implicit_collisions::implicit_step private
The object that is responsible for performing the algebra required for the integrals.
Definition at line 218 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advancef1(), and interspecies_flm_implicit_collisions::advanceflm().
implicit_step [2/2]
self_flm_implicit_step self_flm_implicit_collisions::implicit_step private
The object that is responsible for performing the algebra required for the integrals.
Definition at line 318 of file collisions.h.
Referenced by self_flm_implicit_collisions::advancef1(), and self_flm_implicit_collisions::advanceflm().
interspecies_f00_collisions
vector<interspecies_f00_explicit_collisions> interspecies_collisions::interspecies_f00_collisions private
Definition at line 243 of file interspeciescollisions.h.
invpr
valarray< complex<double> > Electric_Field_1D::invpr private
Definition at line 78 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), and Electric_Field_1D::MakeGH().
J1
valarray<double> self_f00_explicit_step::J1 private
The integrals.
Definition at line 135 of file collisions.h.
Referenced by self_f00_explicit_step::G(), and self_f00_explicit_step::takestep().
J1_s1
valarray<double> interspecies_f00_explicit_step::J1_s1 private
The integrals.
Definition at line 61 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::remapintegrals(), and interspecies_f00_explicit_step::takestep().
J1_s2
valarray<double> interspecies_f00_explicit_step::J1_s2 private
The integrals.
Definition at line 58 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::remapintegrals().
J1m [1/2]
valarray<double> interspecies_flm_implicit_step::J1m private
Definition at line 152 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::reset_coeff().
J1m [2/2]
valarray<double> self_flm_implicit_step::J1m private
Definition at line 249 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff().
Jx
Field1D Current_1D::Jx private
Definition at line 128 of file vlasov.h.
Referenced by Current_1D::es1d(), and Current_1D::operator()().
Jy
Field1D Current_1D::Jy private
Definition at line 128 of file vlasov.h.
Referenced by Current_1D::operator()().
Jz
Field1D Current_1D::Jz private
Definition at line 128 of file vlasov.h.
Referenced by Current_1D::operator()().
kpre [1/3]
double interspecies_f00_explicit_step::kpre private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step(), and interspecies_f00_explicit_step::takestep().
kpre [2/3]
double interspecies_flm_implicit_step::kpre private
Definition at line 164 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
kpre [3/3]
double self_flm_implicit_step::kpre private
Definition at line 262 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
l0 [1/2]
size_t interspecies_flm_implicit_collisions::l0 private
Number of m harmonics.
Definition at line 211 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advanceflm().
l0 [2/2]
size_t self_flm_implicit_collisions::l0 private
Number of m harmonics.
Definition at line 311 of file collisions.h.
Referenced by self_flm_implicit_collisions::advanceflm().
laser_Inv_Uav6
valarray<double> self_f00_implicit_step::laser_Inv_Uav6 private
Definition at line 38 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
m0 [1/2]
size_t interspecies_flm_implicit_collisions::m0 private
Number of m harmonics.
Definition at line 212 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advanceflm().
m0 [2/2]
size_t self_flm_implicit_collisions::m0 private
Number of m harmonics.
Definition at line 312 of file collisions.h.
Referenced by self_flm_implicit_collisions::advanceflm(), and self_flm_implicit_collisions::self_flm_implicit_collisions().
m1
double interspecies_f00_explicit_step::m1 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), interspecies_f00_explicit_step::interspecies_f00_explicit_step(), and interspecies_f00_explicit_step::takestep().
m2
double interspecies_f00_explicit_step::m2 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), interspecies_f00_explicit_step::interspecies_f00_explicit_step(), and interspecies_f00_explicit_step::takestep().
mass [1/3]
double self_f00_implicit_step::mass private
Definition at line 27 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step().
mass [2/3]
double self_f00_explicit_step::mass private
Array output by getslope.
Definition at line 127 of file collisions.h.
mass [3/3]
double self_flm_implicit_step::mass private
Definition at line 258 of file collisions.h.
Referenced by self_flm_implicit_step::self_flm_implicit_step().
MX_cooling
bool self_f00_implicit_collisions::MX_cooling private
Definition at line 97 of file collisions.h.
n1
double interspecies_f00_explicit_step::n1 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::takestep().
n2
double interspecies_f00_explicit_step::n2 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::takestep().
NB
int self_f00_explicit_step::NB private
Definition at line 139 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
Nbc [1/6]
int interspecies_f00_explicit_step::Nbc private
Number of boundary cells in each direction.
Definition at line 63 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step().
Nbc [2/6]
int self_f00_implicit_collisions::Nbc private
Number of boundary cells in each direction.
Definition at line 103 of file collisions.h.
Referenced by self_f00_implicit_collisions::self_f00_implicit_collisions().
Nbc [3/6]
int interspecies_f00_explicit_collisions::Nbc private
Number of boundary cells in each direction.
Definition at line 122 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_collisions::interspecies_f00_explicit_collisions(), and interspecies_f00_explicit_collisions::rkloop().
Nbc [4/6]
int interspecies_flm_implicit_collisions::Nbc private
Number of boundary cells in each direction.
Definition at line 208 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advancef1(), interspecies_flm_implicit_collisions::advanceflm(), and interspecies_flm_implicit_collisions::interspecies_flm_implicit_collisions().
Nbc [5/6]
int self_f00_explicit_collisions::Nbc private
Number of boundary cells in each direction.
Definition at line 217 of file collisions.h.
Referenced by self_f00_explicit_collisions::self_f00_explicit_collisions().
Nbc [6/6]
int self_flm_implicit_collisions::Nbc private
Number of boundary cells in each direction.
Definition at line 307 of file collisions.h.
Referenced by self_flm_implicit_collisions::self_flm_implicit_collisions().
num_h [1/2]
size_t interspecies_f00_explicit_collisions::num_h private
Definition at line 119 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_collisions::interspecies_f00_explicit_collisions(), and interspecies_f00_explicit_collisions::rkloop().
num_h [2/2]
size_t self_f00_explicit_collisions::num_h private
Definition at line 214 of file collisions.h.
Referenced by self_f00_explicit_collisions::loop(), and self_f00_explicit_collisions::self_f00_explicit_collisions().
numx [1/2]
size_t Faraday_1D::numx private
Definition at line 147 of file vlasov.h.
numx [2/2]
size_t Ampere_1D::numx private
Definition at line 165 of file vlasov.h.
p2dp
valarray<double> self_f00_implicit_step::p2dp private
Various coefficients for the integrals.
Definition at line 38 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step().
p2dpm1
valarray<double> self_f00_implicit_step::p2dpm1 private
Definition at line 38 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step().
p4dp
valarray<double> self_f00_implicit_step::p4dp private
Definition at line 38 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step(), and self_f00_implicit_step::update_C_Rosenbluth().
pgrid_s1
valarray<double> interspecies_f00_explicit_step::pgrid_s1 private
Definition at line 53 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), interspecies_f00_explicit_step::remapintegrals(), and interspecies_f00_explicit_step::takestep().
pgrid_s2
valarray<double> interspecies_f00_explicit_step::pgrid_s2 private
Definition at line 53 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step(), and interspecies_f00_explicit_step::remapintegrals().
phdp
valarray<double> self_f00_implicit_step::phdp private
Definition at line 38 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step().
phdpm1
valarray<double> self_f00_implicit_step::phdpm1 private
Definition at line 38 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step().
Pn [1/2]
valarray<double> interspecies_f00_explicit_step::Pn private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step().
Pn [2/2]
valarray<double> self_f00_explicit_step::Pn private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
pr
valarray< complex<double> > Electric_Field_1D::pr private
Definition at line 78 of file vlasov.h.
Referenced by Electric_Field_1D::Electric_Field_1D(), Electric_Field_1D::MakeG00(), and Electric_Field_1D::MakeGH().
Qn [1/2]
valarray<double> interspecies_f00_explicit_step::Qn private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step().
Qn [2/2]
valarray<double> self_f00_explicit_step::Qn private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
RK
Algorithms::RK4<valarray<double> > self_f00_explicit_collisions::RK private
This object contains the RK4 algorithm that advances the collision operator. Inside of it is the Collide object that contains all the relevant collision integral algebra.
Definition at line 210 of file collisions.h.
Referenced by self_f00_explicit_collisions::loop().
RK4
Algorithms::RK4<valarray<double> > interspecies_f00_explicit_collisions::RK4 private
Definition at line 116 of file interspeciescollisions.h.
rkf00 [1/2]
interspecies_f00_RKfunctor interspecies_f00_explicit_collisions::rkf00 private
Definition at line 114 of file interspeciescollisions.h.
rkf00 [2/2]
self_f00_RKfunctor self_f00_explicit_collisions::rkf00 private
Definition at line 212 of file collisions.h.
Referenced by self_f00_explicit_collisions::loop().
Scattering_Term [1/2]
valarray<double> interspecies_flm_implicit_step::Scattering_Term private
Definition at line 158 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), and interspecies_flm_implicit_step::reset_coeff().
Scattering_Term [2/2]
valarray<double> self_flm_implicit_step::Scattering_Term private
Definition at line 255 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), and self_flm_implicit_step::reset_coeff().
self_coll
vector<self_collisions> collisions::self_coll private
Definition at line 373 of file collisions.h.
Referenced by collisions::advancef0(), collisions::advancef1(), collisions::advanceflm(), collisions::collisions(), and collisions::self().
self_f00_exp_collisions
self_f00_explicit_collisions self_collisions::self_f00_exp_collisions private
Definition at line 343 of file collisions.h.
Referenced by self_collisions::advancef00().
self_f00_imp_collisions
self_f00_implicit_collisions self_collisions::self_f00_imp_collisions private
Definition at line 344 of file collisions.h.
Referenced by self_collisions::advancef00().
self_flm_collisions
self_flm_implicit_collisions self_collisions::self_flm_collisions private
Definition at line 345 of file collisions.h.
Referenced by self_collisions::advancef1(), and self_collisions::advanceflm().
small
double Current_1D::small private
Definition at line 129 of file vlasov.h.
Referenced by Current_1D::Current_1D().
szx [1/6]
int interspecies_f00_explicit_step::szx private
Total cells including boundary cells in x-direction.
Definition at line 64 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step().
szx [2/6]
int self_f00_implicit_collisions::szx private
Total cells including boundary cells in x-direction.
Definition at line 104 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop(), and self_f00_implicit_collisions::self_f00_implicit_collisions().
szx [3/6]
int interspecies_f00_explicit_collisions::szx private
Total cells including boundary cells in x-direction.
Definition at line 123 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_collisions::interspecies_f00_explicit_collisions(), and interspecies_f00_explicit_collisions::rkloop().
szx [4/6]
int interspecies_flm_implicit_collisions::szx private
Total cells including boundary cells in x-direction.
Definition at line 209 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_collisions::advancef1(), interspecies_flm_implicit_collisions::advanceflm(), and interspecies_flm_implicit_collisions::interspecies_flm_implicit_collisions().
szx [5/6]
int self_f00_explicit_collisions::szx private
Total cells including boundary cells in x-direction.
Definition at line 218 of file collisions.h.
Referenced by self_f00_explicit_collisions::loop(), and self_f00_explicit_collisions::self_f00_explicit_collisions().
szx [6/6]
int self_flm_implicit_collisions::szx private
Total cells including boundary cells in x-direction.
Definition at line 308 of file collisions.h.
Referenced by self_flm_implicit_collisions::advancef1(), self_flm_implicit_collisions::advanceflm(), and self_flm_implicit_collisions::self_flm_implicit_collisions().
T1
double interspecies_f00_explicit_step::T1 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::takestep().
T2
double interspecies_f00_explicit_step::T2 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::takestep().
TMP
SHarmonic1D Electric_Field_1D::TMP private
Definition at line 70 of file vlasov.h.
Referenced by Electric_Field_1D::es1d(), Electric_Field_1D::f1only(), Electric_Field_1D::Implicit_Ey(), Electric_Field_1D::Implicit_Ez(), and Electric_Field_1D::operator()().
tmpB
Field1D Ampere_1D::tmpB private
Definition at line 163 of file vlasov.h.
Referenced by Ampere_1D::operator()().
tmpE
Field1D Faraday_1D::tmpE private
Definition at line 145 of file vlasov.h.
Referenced by Faraday_1D::operator()().
U1 [1/4]
valarray<double> interspecies_f00_explicit_step::U1 private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::interspecies_f00_explicit_step().
U1 [2/4]
valarray<double> self_f00_explicit_step::U1 private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
U1 [3/4]
valarray<double> interspecies_flm_implicit_step::U1 private
Definition at line 149 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
U1 [4/4]
valarray<double> self_flm_implicit_step::U1 private
Definition at line 246 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
U1m1 [1/4]
valarray<double> interspecies_f00_explicit_step::U1m1 private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::interspecies_f00_explicit_step().
U1m1 [2/4]
valarray<double> self_f00_explicit_step::U1m1 private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
U1m1 [3/4]
valarray<double> interspecies_flm_implicit_step::U1m1 private
Definition at line 149 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
U1m1 [4/4]
valarray<double> self_flm_implicit_step::U1m1 private
Definition at line 246 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
U2 [1/4]
valarray<double> interspecies_f00_explicit_step::U2 private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::interspecies_f00_explicit_step().
U2 [2/4]
valarray<double> self_f00_explicit_step::U2 private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
U2 [3/4]
valarray<double> interspecies_flm_implicit_step::U2 private
Definition at line 149 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
U2 [4/4]
valarray<double> self_flm_implicit_step::U2 private
Definition at line 246 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
U2m1 [1/4]
valarray<double> interspecies_f00_explicit_step::U2m1 private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::interspecies_f00_explicit_step().
U2m1 [2/4]
valarray<double> self_f00_explicit_step::U2m1 private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
U2m1 [3/4]
valarray<double> interspecies_flm_implicit_step::U2m1 private
Definition at line 149 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
U2m1 [4/4]
valarray<double> self_flm_implicit_step::U2m1 private
Definition at line 246 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
U3 [1/2]
valarray<double> interspecies_f00_explicit_step::U3 private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step().
U3 [2/2]
valarray<double> self_f00_explicit_step::U3 private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
U4 [1/4]
valarray<double> interspecies_f00_explicit_step::U4 private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::interspecies_f00_explicit_step().
U4 [2/4]
valarray<double> self_f00_explicit_step::U4 private
Various coefficients for the integrals.
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
U4 [3/4]
valarray<double> interspecies_flm_implicit_step::U4 private
Definition at line 149 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
U4 [4/4]
valarray<double> self_flm_implicit_step::U4 private
Definition at line 246 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
U4m1 [1/4]
valarray<double> interspecies_f00_explicit_step::U4m1 private
Definition at line 55 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), and interspecies_f00_explicit_step::interspecies_f00_explicit_step().
U4m1 [2/4]
valarray<double> self_f00_explicit_step::U4m1 private
Definition at line 132 of file collisions.h.
Referenced by self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
U4m1 [3/4]
valarray<double> interspecies_flm_implicit_step::U4m1 private
Definition at line 149 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
U4m1 [4/4]
valarray<double> self_flm_implicit_step::U4m1 private
Definition at line 246 of file collisions.h.
Referenced by self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
vr [1/5]
valarray<double> self_f00_implicit_step::vr private
Define the velocity axis.
Definition at line 31 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step(), self_f00_implicit_step::update_C_Rosenbluth(), self_f00_implicit_step::update_D_inversebremsstrahlung(), and self_f00_implicit_step::update_D_Rosenbluth().
vr [2/5]
valarray< complex<double> > Spatial_Advection_1D::vr private
Definition at line 34 of file vlasov.h.
Referenced by Spatial_Advection_1D::es1d(), Spatial_Advection_1D::f1only(), Spatial_Advection_1D::operator()(), and Spatial_Advection_1D::Spatial_Advection_1D().
vr [3/5]
valarray<double> self_f00_explicit_step::vr private
Define the velocity axis.
Definition at line 129 of file collisions.h.
Referenced by self_f00_explicit_step::G(), self_f00_explicit_step::self_f00_explicit_step(), and self_f00_explicit_step::takestep().
vr [4/5]
valarray<double> interspecies_flm_implicit_step::vr private
Definition at line 146 of file interspeciescollisions.h.
Referenced by interspecies_flm_implicit_step::advance(), interspecies_flm_implicit_step::interspecies_flm_implicit_step(), and interspecies_flm_implicit_step::reset_coeff().
vr [5/5]
valarray<double> self_flm_implicit_step::vr private
Definition at line 243 of file collisions.h.
Referenced by self_flm_implicit_step::advance(), self_flm_implicit_step::reset_coeff(), and self_flm_implicit_step::self_flm_implicit_step().
vrh
valarray<double> self_f00_implicit_step::vrh private
Definition at line 33 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step().
vw_coeff_cube
double self_f00_implicit_step::vw_coeff_cube private
Definition at line 49 of file collisions.h.
Referenced by self_f00_implicit_step::self_f00_implicit_step(), and self_f00_implicit_step::update_D_inversebremsstrahlung().
xgrid
valarray<double> self_f00_implicit_collisions::xgrid private
Definition at line 91 of file collisions.h.
Referenced by self_f00_implicit_collisions::loop().
Yh
State1D collisions::Yh private
Definition at line 372 of file collisions.h.
Referenced by collisions::advance().
z1
double interspecies_f00_explicit_step::z1 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step(), and interspecies_f00_explicit_step::takestep().
z2
double interspecies_f00_explicit_step::z2 private
Definition at line 51 of file interspeciescollisions.h.
Referenced by interspecies_f00_explicit_step::interspecies_f00_explicit_step(), and interspecies_f00_explicit_step::takestep().