OSHUN: Electric_Field_Methods::Current_xyz Class Reference
Electric_Field_Methods::Current_xyz Class Reference
#include <implicitE.h>
Public Member Functions
Current_xyz (EMF1D &emf)
Field1D & J (int component)
void calculate_J (State1D &Yin)
Field1D & Jx ()
Field1D & Jy ()
Field1D & Jz ()
Private Attributes
Field1D jayx
Field1D jayy
Field1D jayz
complex< double > fourpioverthree
valarray< complex< double > > tempx
valarray< complex< double > > tempy
valarray< complex< double > > tempz
size_t Nbc
size_t szx
Detailed Description
Definition at line 28 of file implicitE.h.
Constructor & Destructor Documentation
Current_xyz()
Electric_Field_Methods::Current_xyz::Current_xyz (EMF1D & emf)
Definition at line 53 of file implicitE.cpp.
References Input::Input_List::BoundaryCells, Input::List(), Nbc, Input::Input_List::NxLocal, and szx.
        : jayx(emf.Ex()),
          jayy(emf.Ex()),
          jayz(emf.Ex()),
          // p3og(Algorithms::MakeAxis(
          //    static_cast< complex<double> >(Input::List().pmin),
          //    static_cast< complex<double> >(Input::List().pmaxs[0]),
          //    Input::List().ps[0])),
          // Delta_p(static_cast< complex<double> >((Input::List().pmaxs[0]-Input::List().pmin)/Input::List().ps[0])),
          // small(static_cast< complex<double> >(Input::List().pmin)),
          tempx(0.0,emf.Ex().numx()),
          tempy(0.0,emf.Ex().numx()),
          tempz(0.0,emf.Ex().numx()),
          fourpioverthree(4.0*M_PI/3.0,0.0)
          {
             Nbc = Input::List().BoundaryCells;
             szx = Input::List().NxLocal[0];
             // for (size_t s(0); s<Yin.Species();++s)
             // {
             //  for (size_t i(0); i<p3og.size(); ++i) { // calculate p^3/g
             //     p3og[i] = (p3og[i]*p3og[i])*(p3og[i]/sqrt(1.0+p3og[i]*p3og[i]));
             //  }
             //     p3ogv.push_back(p3og);
             // }
             //  small *= small; small *= small; small *= Input::List().pmin;
             //  small *= 0.2; small *= 1.0/(Input::List().pmin+Delta_p);
     }
Member Function Documentation
calculate_J()
void Electric_Field_Methods::Current_xyz::calculate_J (State1D & Yin)
Definition at line 135 of file implicitE.cpp.
References State1D::DF(), State1D::EMF(), EMF1D::Ex(), DistFunc1D::getcurrent(), jayx, jayy, jayz, Field1D::numx(), and State1D::Species().
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), and Jz().
{
 //--------------------------------------------------------------
 //  Update the total current
 //--------------------------------------------------------------
         complex<double> c01(0.0,1.0);
         complex<double> pmin, pmax;
         size_t nump;
         Array2D<double> current(3,Yin.EMF().Ex().numx());
         // jayx=0.0;jayy=0.0;jayz=0.0;
         jayx = static_cast<complex<double> >(0.0);
         jayy = static_cast<complex<double> >(0.0);
         jayz = static_cast<complex<double> >(0.0);
         for (size_t s(0); s < Yin.Species(); ++s){
             current = Yin.DF(s).getcurrent();
             for (size_t ix(0); ix < Yin.EMF().Ex().numx(); ++ix)
             {
                 jayx(ix) +=   static_cast<complex<double>>(current(0,ix));
                 jayy(ix) +=   static_cast<complex<double>>(current(1,ix));
                 jayz(ix) +=   static_cast<complex<double>>(current(2,ix));
             }
             // jayx.array() += static_cast<complex<double>>(Yin.DF(s).getcurrent(0));
             // jayy.array() += static_cast<complex<double>>(Yin.DF(s).getcurrent(1));
             // jayz.array() += static_cast<complex<double>>(Yin.DF(s).getcurrent(2));
         }
 }
J()
Field1D & Electric_Field_Methods::Current_xyz::J (int component)
Definition at line 86 of file implicitE.cpp.
References Jx(), Jy(), and Jz().
{
 //--------------------------------------------------------------
 //  Return the current component 1 --> x, 2 --> y, 3 --> z
 //--------------------------------------------------------------
     switch (component) {
         case 1: {
             return Jx();
             break;
         }
         case 2: {
             return Jy();
             break;
         }
         case 3: {
             return Jz();
             break;
         }
         default: {
                 cout << "There is no such component for the current!" << endl;
                 exit(1);
                 break;
         }
     }
     return Jx();
 }
Jx()
Field1D & Electric_Field_Methods::Current_xyz::Jx ()
Definition at line 115 of file implicitE.cpp.
References jayx.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), and J().
{
        return jayx;
     }
Jy()
Field1D & Electric_Field_Methods::Current_xyz::Jy ()
Definition at line 121 of file implicitE.cpp.
References jayy.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), Electric_Field_Methods::Implicit_E_Field::Ampere(), and J().
{
         return jayy;
     }
Jz()
Field1D & Electric_Field_Methods::Current_xyz::Jz ()
Definition at line 127 of file implicitE.cpp.
References calculate_J(), and jayz.
Referenced by Electric_Field_Methods::Implicit_E_Field::advance(), Electric_Field_Methods::Implicit_E_Field::Ampere(), and J().
{
         return jayz;
     }
Field Documentation
fourpioverthree
complex<double> Electric_Field_Methods::Current_xyz::fourpioverthree private
Definition at line 53 of file implicitE.h.
jayx
Field1D Electric_Field_Methods::Current_xyz::jayx private
Definition at line 50 of file implicitE.h.
Referenced by calculate_J(), and Jx().
jayy
Field1D Electric_Field_Methods::Current_xyz::jayy private
Definition at line 50 of file implicitE.h.
Referenced by calculate_J(), and Jy().
jayz
Field1D Electric_Field_Methods::Current_xyz::jayz private
Definition at line 50 of file implicitE.h.
Referenced by calculate_J(), and Jz().
Nbc
size_t Electric_Field_Methods::Current_xyz::Nbc private
Definition at line 61 of file implicitE.h.
Referenced by Current_xyz().
szx
size_t Electric_Field_Methods::Current_xyz::szx private
Definition at line 61 of file implicitE.h.
Referenced by Current_xyz().
tempx
valarray< complex<double> > Electric_Field_Methods::Current_xyz::tempx private
Definition at line 57 of file implicitE.h.
tempy
valarray< complex<double> > Electric_Field_Methods::Current_xyz::tempy private
Definition at line 58 of file implicitE.h.
tempz
valarray< complex<double> > Electric_Field_Methods::Current_xyz::tempz private
Definition at line 59 of file implicitE.h.
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/implicitE.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/implicitE.cpp