OSHUN: Algorithms Namespace Reference
Algorithms Namespace Reference
Data Structures
class AbstFunctor
class Axis
class AxisBundle
class CAxis
class LEAPs
class LEAPv
class PEFRL
class RK2
class RK3
class RK4
Functions
template<typename T >
valarray< T > MakeAxis (const T min, const T max, const size_t N)
template<typename T >
valarray< T > MakeCAxis (const T min, const T max, const size_t N)
template<class T >
valarray< T > Legendre (const T x, const size_t Nl)
template<class T >
Array2D< T > Legendre (const T x, const size_t Nl, const size_t Nm)
template<class T >
T moment (const vector< T > q, const vector< T > x, const int p)
template<class T >
T moment (const vector< T > q, const valarray< T > x, const int p)
template<class T >
T moment (const valarray< T > q, const valarray< T > x, const int p)
template<class T >
T relativistic_invg_moment (const vector< T > q, const valarray< T > x, const int p)
template<class T >
T relativistic_invg_moment (const valarray< T > q, const valarray< T > x, const int p)
template<class T >
T relativistic_gamma_moment (const valarray< T > q, const valarray< T > x, const int p)
Function Documentation
Legendre() [1/2]
template<class T > valarray<T> Algorithms::Legendre (const T x, const size_t Nl)
Definition at line 227 of file lib-algorithms.h.
Referenced by Output_Data::PLegendre1D::PLegendre1D(), and Output_Data::PLegendre2D::PLegendre2D().
                                                     { // where Nl is to denote l0+1
         valarray<T> P_Legendre(0.0, Nl);
         if ( abs(x) > 1 ) return P_Legendre;
         T r1, sqrtx = sqrt(1.0-x*x);
 //      Initialization
         P_Legendre[0] = 1.0;
         P_Legendre[1] = x;
         for (size_t l(1); l < Nl - 1; ++l){
             r1 = 1.0 / double(l + 1);
             P_Legendre[l+1] = P_Legendre[l] * (x*(2.0*l+1.0) * r1) -
                               P_Legendre[l-1]*(double(l) * r1);
         }
         return P_Legendre;
     }
Legendre() [2/2]
template<class T > Array2D<T> Algorithms::Legendre (const T x, const size_t Nl, const size_t Nm)
Definition at line 249 of file lib-algorithms.h.
{
 //      Local variables
         if (Nl < Nm) {
             cout << "ERROR: " << "l0+1 = " << Nl << " < " << Nm << " = m0+1\n";
             exit(1);
         }
         Array2D<T> P_Legendre(Nl+1,Nm+1);
         if ( abs(x) > 1 ) {
 //             cout << "ERROR: " << "|" << x << "| > 1 is not a valid cosine\n";
 //      cout << "setting values to 0.0";
             P_Legendre = 0.0;
         }
         else
         {
             T r1, sqrtx = sqrt(1.0-x*x), fact = 1.0;
             //      Initialization
             P_Legendre = 0.0;
             P_Legendre(0,0) = 1.0;
             for (size_t l = 1; l < Nm+1; ++l){
                 // std::cout << "\n l=" << l;
                 P_Legendre(l,l) = - P_Legendre(l-1,l-1)*(fact*sqrtx);
                 fact += 2.0;
             }
             // std::cout << "\n ";
             for (size_t l = 0; l < ((Nm < Nl) ? Nm+1 : Nl+1); ++l){
                 // std::cout << "\n l=" << l;
                 P_Legendre(l+1,l) = P_Legendre(l,l)*(x*(2.0*l+1.0));
             }
             // std::cout << "\n ";
             for (size_t m = 0; m < Nm+1; ++m){
                 for (size_t l = m+1; l < Nl ; ++l){
                     // std::cout << "\n l=" << l << ", m=" << m;
                     r1 = 1.0 / double(l - m + 1);
                     P_Legendre(l+1,m) = P_Legendre(l,m) * (x*(2.0*l+1.0) * r1) -
                                         P_Legendre(l-1,m)*(double(l+m) * r1);
                 }
             }
         }
         return P_Legendre;
     }
MakeAxis()
template<typename T > valarray<T> Algorithms::MakeAxis (const T min, const T max, const size_t N)
Definition at line 25 of file lib-algorithms.h.
Referenced by Algorithms::Axis< T >::Axis(), Output_Data::p2p1x1_1D::p2p1x1_1D(), Output_Data::PLegendre1D::PLegendre1D(), and Output_Data::PLegendre2D::PLegendre2D().
{
         valarray<T> v(N);
         for (size_t i(0); i < N; ++i) {
             v[i] = static_cast<T>(i);
         }
         v *= (max-min)/(static_cast<T>(N-1));
         v += min;
         return v;
     }
MakeCAxis()
template<typename T > valarray<T> Algorithms::MakeCAxis (const T min, const T max, const size_t N)
Definition at line 36 of file lib-algorithms.h.
Referenced by Export_Files::Header::axis(), Algorithms::CAxis< T >::CAxis(), DistFunc1D::getcurrent(), DistFunc1D::getdensity(), DistFunc1D::getpressure(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Output_Data::Output_Preprocessor_1D::n(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::Qz(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), and Output_Data::Output_Preprocessor_1D::vNz().
{
         valarray<T> v(N);
         for (size_t i(0); i < N; ++i) {
             v[i] = static_cast<T>(i);
         }
         v *= (max-min)/(static_cast<T>(N));
         v += min+0.5*(max-min)/(static_cast<T>(N));
         return v;
     }
moment() [1/3]
template<class T > T Algorithms::moment (const vector< T > q, const vector< T > x, const int p)
Definition at line 305 of file lib-algorithms.h.
Referenced by interspecies_f00_explicit_step::calculateintegrals(), DistFunc1D::getdensity(), DistFunc1D::getpressure(), Output_Data::Output_Preprocessor_1D::Jx(), Output_Data::Output_Preprocessor_1D::Jy(), Output_Data::Output_Preprocessor_1D::Jz(), Output_Data::Output_Preprocessor_1D::n(), Output_Data::Output_Preprocessor_1D::Qx(), Output_Data::Output_Preprocessor_1D::Qy(), Output_Data::Output_Preprocessor_1D::Qz(), Output_Data::Output_Preprocessor_1D::T(), Output_Data::Output_Preprocessor_1D::vNx(), Output_Data::Output_Preprocessor_1D::vNy(), and Output_Data::Output_Preprocessor_1D::vNz().
{
         T integral(0.0);
 // TODO:   Integral values up to the zeroth cell and above the last cell
 //       integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
 //                   * (x[1]-x[0]);
 //       for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
 //           integral += q[i] * pow(x[i], p)
 //                       * (x[i+1] - x[i-1]);
 //       }
 //       integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
 //                       * (x[q.size()-1]-x[q.size()-2]);
 //       return integral*0.5;
         integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
                     * (x[1]-x[0]);
         for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
             integral += q[i] * pow(x[i], p)
                         * 0.5*(x[i+1] - x[i-1]);
         }
         integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
                     * (x[q.size()-1]-x[q.size()-2]);
         return integral;
     }
moment() [2/3]
template<class T > T Algorithms::moment (const vector< T > q, const valarray< T > x, const int p)
Definition at line 331 of file lib-algorithms.h.
{
         T integral(0.0);
 // TODO:   Integral values up to the zeroth cell and above the last cell
 //       integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
 //                   * (x[1]-x[0]);
 //       for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
 //           integral += q[i] * pow(x[i], p)
 //                       * (x[i+1] - x[i-1]);
 //       }
 //       integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
 //                       * (x[q.size()-1]-x[q.size()-2]);
 //       return integral*0.5;
         integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
                     * (x[1]-x[0]);
         for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
             integral += q[i] * pow(x[i], p)
                         * 0.5*(x[i+1] - x[i-1]);
         }
         integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
                     * (x[q.size()-1]-x[q.size()-2]);
         return integral;
     }
moment() [3/3]
template<class T > T Algorithms::moment (const valarray< T > q, const valarray< T > x, const int p)
Definition at line 355 of file lib-algorithms.h.
{
         T integral(0.0);
 // TODO:   Integral values up to the zeroth cell and above the last cell
 //       integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
 //                   * (x[1]-x[0]);
 //       for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
 //           integral += q[i] * pow(x[i], p)
 //                       * (x[i+1] - x[i-1]);
 //       }
 //       integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
 //                       * (x[q.size()-1]-x[q.size()-2]);
 //       return integral*0.5;
         integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
                     * (x[1]-x[0]);
         for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
             integral += q[i] * pow(x[i], p)
                         * 0.5*(x[i+1] - x[i-1]);
         }
         integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
                     * (x[q.size()-1]-x[q.size()-2]);
         return integral;
     }
relativistic_gamma_moment()
template<class T > T Algorithms::relativistic_gamma_moment (const valarray< T > q, const valarray< T > x, const int p)
Definition at line 445 of file lib-algorithms.h.
{
         T integral(0.0);
 // TODO:   Integral values up to the zeroth cell and above the last cell
 //       integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
 //                   * (x[1]-x[0])
 //                   * sqrt(1.0+x[0]*x[0]);
 //       for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
 //           integral += q[i] * pow(x[i], p)
 //                       * (x[i+1] - x[i-1])
 //                       * sqrt(1.0+x[i]*x[i]);
 //       }
 //       integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
 //                       * (x[q.size()-1]-x[q.size()-2])
 //                       * sqrt(1.0+x[q.size-1]*x[q.size-1]);
 //       return integral*0.5;
         integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
                     * (x[1]-x[0])
                     * sqrt(1.0+x[0]*x[0]);
         for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
             integral += q[i] * pow(x[i], p)
                         * 0.5*(x[i+1] - x[i-1])
                         * sqrt(1.0+x[i]*x[i]);
         }
         integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
                     * (x[q.size()-1]-x[q.size()-2])
                     * sqrt(1.0+x[q.size-1]*x[q.size-1]);
         return integral;
     }
relativistic_invg_moment() [1/2]
template<class T > T Algorithms::relativistic_invg_moment (const vector< T > q, const valarray< T > x, const int p)
Definition at line 382 of file lib-algorithms.h.
Referenced by DistFunc1D::getcurrent().
{
         T integral(0.0);
 // TODO:   Integral values up to the zeroth cell and above the last cell
       // integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
       //             * (x[1]-x[0])
       //             / sqrt(1.0+x[0]*x[0]);
       // for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
       //     integral += q[i] * pow(x[i], p)
       //                 * (x[i+1] - x[i-1])
       //                 / sqrt(1.0+x[i]*x[i]);
       // }
       // integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
       //                 * (x[q.size()-1]-x[q.size()-2])
       //                 / sqrt(1.0+x[q.size()-1]*x[q.size()-1]);
       // return integral*0.5;
         integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
                     * (x[1]-x[0])
                     / sqrt(1.0+x[0]*x[0]);
         for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
             integral += q[i] * pow(x[i], p)
                         * 0.5*(x[i+1] - x[i-1])
                         / sqrt(1.0+x[i]*x[i]);
         }
         integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
                     * (x[q.size()-1]-x[q.size()-2])
                     / sqrt(1.0+x[q.size()-1]*x[q.size()-1]);
         return integral;
     }
relativistic_invg_moment() [2/2]
template<class T > T Algorithms::relativistic_invg_moment (const valarray< T > q, const valarray< T > x, const int p)
Definition at line 414 of file lib-algorithms.h.
{
         T integral(0.0);
 // TODO:   Integral values up to the zeroth cell and above the last cell
       // integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
       //             * (x[1]-x[0])
       //             / sqrt(1.0+x[0]*x[0]);
       // for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
       //     integral += q[i] * pow(x[i], p)
       //                 * (x[i+1] - x[i-1])
       //                 / sqrt(1.0+x[i]*x[i]);
       // }
       // integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
       //                 * (x[q.size()-1]-x[q.size()-2])
       //                 / sqrt(1.0+x[q.size-1]*x[q.size-1]);
       // return integral*0.5;
         integral += q[0] * pow(x[0], p)                   // += Q_0*x_0^p * (x_1-x_0)
                     * (x[1]-x[0])
                     / sqrt(1.0+x[0]*x[0]);
         for (size_t i(1); i < q.size()-1; ++i){           // += Q_i*x_i^p * (x_{i+1}-x_{i-1})
             integral += q[i] * pow(x[i], p)
                         * 0.5*(x[i+1] - x[i-1])
                         / sqrt(1.0+x[i]*x[i]);
         }
         integral += q[q.size()-1] * pow(x[q.size()-1], p) // += Q_n*x_n^p * (x_{n}-x_{n-1})
                     * (x[q.size()-1]-x[q.size()-2])
                     / sqrt(1.0+x[q.size-1]*x[q.size-1]);
         return integral;
     }