OSHUN: Array2D< T > Class Template Reference
Array2D< T > Class Template Reference
#include <lib-array.h>
Public Member Functions
Array2D (size_t x, size_t y)
Array2D (const Array2D &other)
~Array2D ()
size_t dim () const
size_t dim1 () const
size_t dim2 () const
valarray< T > & array () const
T & operator() (size_t i, size_t j)
T operator() (size_t i, size_t j) const
T & operator() (size_t i)
T operator() (size_t i) const
vector< T > d2c (size_t j)
GSlice_iter< T > d1c (size_t b, size_t e)
GSlice_iter< T > d2c (size_t b, size_t e)
GSlice_iter< T > SubArray2D (size_t st, size_t nx, size_t ny)
CGSlice_iter< T > d2c (size_t b, size_t e) const
CGSlice_iter< T > d1c (size_t b, size_t e) const
CGSlice_iter< T > SubArray2D (size_t st, size_t nx, size_t ny) const
Array2D & operator= (const T &d)
Array2D & operator= (const Array2D &other)
Array2D & operator*= (const T &d)
Array2D & operator*= (const Array2D &vmulti)
Array2D & operator+= (const T &d)
Array2D & operator+= (const Array2D &vadd)
Array2D & operator-= (const T &d)
Array2D & operator-= (const Array2D &vmin)
Array2D & multid1 (const valarray< T > &vmulti)
Array2D & multid2 (const valarray< T > &vmulti)
Array2D & Dd1 ()
Array2D & Dd2 ()
Array2D & Filterd1 (size_t N)
Private Attributes
valarray< T > * v
size_t d1
size_t d2
Detailed Description
template<class T>
class Array2D< T >
Definition at line 273 of file lib-array.h.
Constructor & Destructor Documentation
Array2D() [1/2]
template<class T > Array2D< T >::Array2D (size_t x, size_t y)
Definition at line 337 of file lib-array.h.
                                                         : d1(x), d2(y) {
     v = new valarray<T>(d1*d2);
 }
Array2D() [2/2]
template<class T > Array2D< T >::Array2D (const Array2D< T > & other)
Definition at line 341 of file lib-array.h.
{
     d1  = other.dim1();
     d2  = other.dim2();
     v = new valarray<T>(d1*d2);
     (*v) = other.array();
 }
~Array2D()
template<class T > Array2D< T >::~Array2D ()
Definition at line 348 of file lib-array.h.
{
     delete v;
 }
Member Function Documentation
array()
template<class T> valarray<T>& Array2D< T >::array () const inline
Definition at line 291 of file lib-array.h.
Referenced by Array2D< complex< double > >::Array2D(), Export_Files::Xport::Export_h5(), Array3D< complex< double > >::multid2d3(), Array3D_cmplx< T >::multid2d3(), Array2D< complex< double > >::operator*=(), Array2D_cmplx< T >::operator*=(), Array2D< complex< double > >::operator+=(), Array2D_cmplx< T >::operator+=(), Array2D< complex< double > >::operator-=(), Array2D_cmplx< T >::operator-=(), Array2D< complex< double > >::operator=(), and Array2D_cmplx< T >::operator=().
 {return *v;}
d1c() [1/2]
template<class T > GSlice_iter< T > Array2D< T >::d1c (size_t b, size_t e) inline
Definition at line 384 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     valarray<size_t> sz(2), str(2);
     str[1] = d1; str[0] = 1;
     sz[1]  = d2;  sz[0] = e-b+1;
     return GSlice_iter<T>(v,gslice(b,sz,str));
 }
d1c() [2/2]
template<class T > CGSlice_iter< T > Array2D< T >::d1c (size_t b, size_t e) const inline
Definition at line 392 of file lib-array.h.
{
     valarray<size_t> sz(2), str(2);
     str[1] = d1; str[0] = 1;
     sz[1]  = d2;  sz[0] = e-b+1;
     return CGSlice_iter<T>(v,gslice(b,sz,str));
 }
d2c() [1/3]
template<class T > vector< T > Array2D< T >::d2c (size_t j)
Definition at line 372 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     vector<T> d1vec(d1);
     for (size_t i(0); i < d1; ++i ){
         d1vec[i] = (*v)[i+j*d1];
     }
     return d1vec;
 }
d2c() [2/3]
template<class T > GSlice_iter< T > Array2D< T >::d2c (size_t b, size_t e) inline
Definition at line 400 of file lib-array.h.
{
     valarray<size_t> sz(1), str(1);     // sz --> size, str --> stride
     str[0] = 1; sz[0]  = (e-b+1)*d1;
     return GSlice_iter<T>(v,gslice(b*d1,sz,str));
 }
d2c() [3/3]
template<class T > CGSlice_iter< T > Array2D< T >::d2c (size_t b, size_t e) const inline
Definition at line 407 of file lib-array.h.
{
     valarray<size_t> sz(1), str(1);     // sz --> size, str --> stride
     str[0] = 1; sz[0]  = (e-b+1)*d1;
     return CGSlice_iter<T>(v,gslice(b*d1,sz,str));
 }
Dd1()
template<class T > Array2D< T > & Array2D< T >::Dd1 ()
Definition at line 507 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array(), and SHarmonic1D::Dp().
{
     for(long i(0); i< long(d1*d2)-2; ++i) {
         (*v)[i] -= (*v)[i+2];
     }
     for(long i(d1*d2-3); i>-1; --i) {
         (*v)[i+1] = (*v)[i];
     }
    //  Array2D<T> temp(*this);
    //  for (long i2(0); i2<long(d2);++i2){
    //      /// Second Order
    //      temp(0,i2) = 2.0*((*this)(0,i2)-(*this)(1,i2));
    //      // temp(i1,1) = 1.0/12.0*((*this)(i1,4)-6.0*(*this)(i1,3)+18.0*(*this)(i1,2)-10.0*(*this)(i1,1)-3.0*(*this)(i1,0));
    //      for (long i1(1); i1<long(d1)-1;++i1){
    //          // temp(i1,i2) = 1.0/12.0*(-(*this)(i1,i2+2)+8.0*(*this)(i1,i2+1)-8.0*(*this)(i1,i2-1)+(*this)(i1,i2-2));
    //          /// Second Order
    //          temp(i1,i2) = (*this)(i1-1,i2) - (*this)(i1+1,i2);
    //      }
    //      // temp(i1,long(d2)-2) = 1.0/12.0*(3.0*(*this)(i1,long(d2)-1)+10.0*(*this)(i1,long(d2)-2)-18.0*(*this)(i1,long(d2)-3)+6.0*(*this)(i1,long(d2)-4)-(*this)(i1,long(d2)-5));
    //      // temp(i1,long(d2)-1) = (*this)(i1,long(d2)-1)-(*this)(i1,long(d2)-2);
    //      /// Second Order
    //      temp(long(d1)-1,i2) = 2.0*((*this)(long(d1)-2,i2)-(*this)(long(d1)-1,i2));
    // }
    // *this = temp;
     return *this;
 }
Dd2()
template<class T > Array2D< T > & Array2D< T >::Dd2 ()
Has boundary errors unless boundary cells increased for each RK level
Definition at line 556 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array(), SHarmonic1D::Dx(), and SHarmonic2D::Dx().
{
    //  Array2D<T> temp(*this);
    //  for (long i1(0); i1<long(d1);++i1){
    //      /// Second Order
    //      temp(i1,0) = 2.0*((*this)(i1,0)-(*this)(i1,1));
    //      // std::cout << "this(" << i1 << ")" << (*this)(i1,0) << "\n";
    //      // std::cout << "temp(" << i1 << ")" << temp(i1,0) << "\n";
    //      // temp(i1,1) = 1.0/12.0*((*this)(i1,4)-6.0*(*this)(i1,3)+18.0*(*this)(i1,2)-10.0*(*this)(i1,1)-3.0*(*this)(i1,0));
    //      for (long i2(1); i2<long(d2)-1;++i2){
    //          // temp(i1,i2) = 1.0/12.0*(-(*this)(i1,i2+2)+8.0*(*this)(i1,i2+1)-8.0*(*this)(i1,i2-1)+(*this)(i1,i2-2));
    //          /// Second Order
    //          temp(i1,i2) = (*this)(i1,i2-1) - (*this)(i1,i2+1);
    //          // std::cout << "this(" << i1 << "," << i2 << ")" << (*this)(i1,i2) << "\n";
    //      }
    //      // temp(i1,long(d2)-2) = 1.0/12.0*(3.0*(*this)(i1,long(d2)-1)+10.0*(*this)(i1,long(d2)-2)-18.0*(*this)(i1,long(d2)-3)+6.0*(*this)(i1,long(d2)-4)-(*this)(i1,long(d2)-5));
    //      // temp(i1,long(d2)-1) = (*this)(i1,long(d2)-1)-(*this)(i1,long(d2)-2);
    //      /// Second Order
    //      temp(i1,long(d2)-1) = 2.0*((*this)(i1,long(d2)-2)-(*this)(i1,long(d2)-1));
    //      // std::cout << "this(" << i1 << "," << long(d2)-1 << ")" << (*this)(i1,long(d2)-1) << "\n";
    // }
    // *this = temp;
    //  return *this;
    // std::cout << "\n d1*d2-twod1 = " << long(d1*d2)-2*d1 << "\n";
    long twod1(2*d1);
     for(long i(0); i< long(d1*d2)-twod1; ++i) {
         // std::cout << "v[" << i << "] = " << (*v)[i]
         // <<  ", v[" << i+twod1 << "] = " << (*v)[i+twod1] << "\n";
         (*v)[i] -= (*v)[i+twod1];
     }
     for(long i(d1*d2-twod1-1); i>-1; --i) {
         (*v)[i+d1] = (*v)[i];
     }
     return *this;
 }
dim()
template<class T> size_t Array2D< T >::dim () const inline
Definition at line 288 of file lib-array.h.
 {return d1*d2;}
dim1()
template<class T> size_t Array2D< T >::dim1 () const inline
Definition at line 289 of file lib-array.h.
Referenced by interspecies_flm_implicit_step::advance(), self_flm_implicit_step::advance(), Array2D< complex< double > >::Array2D(), Export_Files::Xport::Export_h5(), Gauss_Seidel(), Array2D< complex< double > >::SubArray2D(), and Thomas_Tridiagonal().
 {return d1;}
dim2()
template<class T> size_t Array2D< T >::dim2 () const inline
Definition at line 290 of file lib-array.h.
Referenced by interspecies_flm_implicit_step::advance(), self_flm_implicit_step::advance(), Array2D< complex< double > >::Array2D(), Export_Files::Xport::Export_h5(), Gauss_Seidel(), and Thomas_Tridiagonal().
 {return d2;}
Filterd1()
template<class T > Array2D< T > & Array2D< T >::Filterd1 (size_t N)
Definition at line 604 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array(), SHarmonic1D::Filterp(), and SHarmonic2D::Filterp().
{
     for (size_t j(0); j < d2; ++j ){
         for (size_t i(j*d1); i< j*d1+N; ++i ){
             (*v)[i] = 0.0;
         }
     }
     return *this;
 }
multid1()
template<class T> Array2D< T > & Array2D< T >::multid1 (const valarray< T > & vmulti)
Definition at line 480 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     for (size_t j(0); j< d1*d2; j+=d1 ){
         for (size_t i(0); i< d1; ++i ){
             (*v)[i+j] *= vmulti[i];
         }
     }
     return *this;
 }
multid2()
template<class T> Array2D< T > & Array2D< T >::multid2 (const valarray< T > & vmulti)
Definition at line 490 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     for (size_t j(0); j< d2; ++j ){
         for (size_t i(j*d1); i< (j+1)*d1; ++i ){
             (*v)[i] *= vmulti[j];
         }
     }
     return *this;
 }
operator()() [1/4]
template<class T > T & Array2D< T >::operator() (size_t i, size_t j) inline
Definition at line 356 of file lib-array.h.
{
     return (*v)[i+j*d1];
 }
operator()() [2/4]
template<class T > T Array2D< T >::operator() (size_t i, size_t j) const inline
Definition at line 360 of file lib-array.h.
{
     return (*v)[i+j*d1];
 }
operator()() [3/4]
template<class T > T & Array2D< T >::operator() (size_t i) inline
Definition at line 364 of file lib-array.h.
{
     return (*v)[i];
 }
operator()() [4/4]
template<class T > T Array2D< T >::operator() (size_t i) const inline
Definition at line 368 of file lib-array.h.
{
     return (*v)[i];
 }
operator*=() [1/2]
template<class T> Array2D< T > & Array2D< T >::operator*= (const T & d)
Definition at line 447 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     (*v) *=d;
     return *this;
 }
operator*=() [2/2]
template<class T> Array2D< T > & Array2D< T >::operator*= (const Array2D< T > & vmulti)
Definition at line 451 of file lib-array.h.
{
     (*v) *= vmulti.array();
     return *this;
 }
operator+=() [1/2]
template<class T> Array2D< T > & Array2D< T >::operator+= (const T & d)
Definition at line 457 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     (*v) +=d;
     return *this;
 }
operator+=() [2/2]
template<class T> Array2D< T > & Array2D< T >::operator+= (const Array2D< T > & vadd)
Definition at line 461 of file lib-array.h.
{
     (*v) += vadd.array();
     return *this;
 }
operator-=() [1/2]
template<class T> Array2D< T > & Array2D< T >::operator-= (const T & d)
Definition at line 467 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     (*v) -=d;
     return *this;
 }
operator-=() [2/2]
template<class T> Array2D< T > & Array2D< T >::operator-= (const Array2D< T > & vmin)
Definition at line 471 of file lib-array.h.
{
     (*v) -= vmin.array();
     return *this;
 }
operator=() [1/2]
template<class T> Array2D< T > & Array2D< T >::operator= (const T & d)
Definition at line 435 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     (*v) = d;
     return *this;
 }
operator=() [2/2]
template<class T> Array2D< T > & Array2D< T >::operator= (const Array2D< T > & other)
Definition at line 439 of file lib-array.h.
{
     if (this != &other) {   //self-assignment
         (*v) = other.array();
     }
     return *this;
 }
SubArray2D() [1/2]
template<class T > GSlice_iter< T > Array2D< T >::SubArray2D (size_t st, size_t nx, size_t ny) inline
Definition at line 416 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array().
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1;  str[0] = dim1();
     sz[1]  = nx;  sz[0] = ny;
     return GSlice_iter<T>(v,gslice(st,sz,str));
 }
SubArray2D() [2/2]
template<class T > CGSlice_iter< T > Array2D< T >::SubArray2D (size_t st, size_t nx, size_t ny) const inline
Definition at line 424 of file lib-array.h.
{
     valarray<size_t> sz(2), str(2);
     str[1] = 1;  str[0] = dim1();
     sz[1]  = nx;  sz[0] = ny;
     return CGSlice_iter<T>(v,gslice(st,sz,str));
 }
Field Documentation
d1
template<class T> size_t Array2D< T >::d1 private
Definition at line 279 of file lib-array.h.
Referenced by Array2D< complex< double > >::Array2D(), Array2D< complex< double > >::d1c(), Array2D< complex< double > >::d2c(), Array2D< complex< double > >::Dd1(), Array2D< complex< double > >::Dd2(), Array2D_cmplx< T >::dim1(), Array2D< complex< double > >::Filterd1(), Array2D< complex< double > >::multid1(), Array2D< complex< double > >::multid2(), and Array2D< complex< double > >::operator()().
d2
template<class T> size_t Array2D< T >::d2 private
Definition at line 279 of file lib-array.h.
Referenced by Array2D< complex< double > >::Array2D(), Array2D< complex< double > >::d1c(), Array2D< complex< double > >::Dd1(), Array2D< complex< double > >::Dd2(), Array2D_cmplx< T >::dim(), Array2D_cmplx< T >::dim2(), Array2D< complex< double > >::Filterd1(), Array2D< complex< double > >::multid1(), and Array2D< complex< double > >::multid2().
v
template<class T> valarray<T>* Array2D< T >::v private
Definition at line 278 of file lib-array.h.
Referenced by Array2D_cmplx< T >::array(), Array2D< complex< double > >::Array2D(), Array2D< complex< double > >::d1c(), Array2D< complex< double > >::d2c(), Array2D< complex< double > >::operator()(), Array2D< complex< double > >::SubArray2D(), and Array2D< complex< double > >::~Array2D().
The documentation for this class was generated from the following file:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/lib-array.h