OSHUN: Export_Files::Header Class Reference
Export_Files::Header Class Reference
#include <export.h>
Public Member Functions
Header ()
Header (oAxis _x, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
Header (oAxis _x, oAxis _y, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
Header (oAxis _x, oAxis _y, oAxis _z, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
Header (vector< oAxis > _xyz, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
size_t dim ()
valarray< float > axis (const size_t i)
string label (const size_t i)
string units (const size_t i)
float conv (const size_t i)
float min (const size_t i)
float max (const size_t i)
string Title_label ()
float Title_conv ()
string Time_label ()
float Time_conv ()
string Directory ()
Private Attributes
vector< oAxis > xyz_axis
string title
string time
string timeU
float titleC
float timeC
string oDir
Detailed Description
Definition at line 134 of file export.h.
Constructor & Destructor Documentation
Header() [1/5]
Export_Files::Header::Header () inline
Definition at line 138 of file export.h.
Referenced by Export_Files::Xport::Xport().
 { };
Header() [2/5]
Export_Files::Header::Header (oAxis _x, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
Definition at line 459 of file export.cpp.
References xyz_axis.
         : title(_Ql), titleC(_Qc),
           time(_tl),  timeU(_tu),  timeC(_tc),
           oDir(_oD) {
     xyz_axis.push_back(_x);
 }
Header() [3/5]
Export_Files::Header::Header (oAxis _x, oAxis _y, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
Definition at line 470 of file export.cpp.
References xyz_axis.
         : title(_Ql),  time(_tl), timeU(_tu),
           titleC(_Qc), timeC(_tc),
           oDir(_oD) {
     xyz_axis.push_back(_x);
     xyz_axis.push_back(_y);
 }
Header() [4/5]
Export_Files::Header::Header (oAxis _x, oAxis _y, oAxis _z, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
Definition at line 482 of file export.cpp.
References xyz_axis.
         : title(_Ql), time(_tl), timeU(_tu),
           titleC(_Qc), timeC(_tc),
           oDir(_oD) {
     xyz_axis.push_back(_x);
     xyz_axis.push_back(_y);
     xyz_axis.push_back(_z);
 }
Header() [5/5]
Export_Files::Header::Header (vector< oAxis > _xyz, string _Ql, float _Qc, string _tl, string _tu, float _tc, string _oD)
Definition at line 495 of file export.cpp.
         : xyz_axis(_xyz), title(_Ql), time(_tl), timeU(_tu),
           titleC(_Qc), timeC(_tc),
           oDir(_oD) {}
Member Function Documentation
axis()
valarray< float > Export_Files::Header::axis (const size_t i)
Definition at line 509 of file export.cpp.
References Algorithms::MakeCAxis(), max(), min(), and xyz_axis.
{
 //    return Algorithms::MakeAxis(xyz_axis[i].min, xyz_axis[i].max, xyz_axis[i].sz);
     return Algorithms::MakeCAxis(xyz_axis[i].min, xyz_axis[i].max, xyz_axis[i].sz);
 }
conv()
float Export_Files::Header::conv (const size_t i)
dim()
size_t Export_Files::Header::dim ()
Definition at line 504 of file export.cpp.
References xyz_axis.
Referenced by Export_Files::Xport::Export_h5().
{
     return xyz_axis.size();
 }
Directory()
string Export_Files::Header::Directory ()
Definition at line 524 of file export.cpp.
References oDir.
Referenced by Export_Files::Xport::Export_h5().
 { return oDir; }
label()
string Export_Files::Header::label (const size_t i)
Definition at line 513 of file export.cpp.
References xyz_axis.
Referenced by Export_Files::Xport::Xport().
{
     return xyz_axis[i].label;
 }
max()
float Export_Files::Header::max (const size_t i) inline
Definition at line 155 of file export.h.
Referenced by axis(), and Export_Files::Xport::Export_h5().
 {return(xyz_axis[i].max);}
min()
float Export_Files::Header::min (const size_t i) inline
Definition at line 154 of file export.h.
Referenced by axis(), and Export_Files::Xport::Export_h5().
 {return(xyz_axis[i].min);}
Time_conv()
float Export_Files::Header::Time_conv ()
Definition at line 523 of file export.cpp.
References timeC.
 { return timeC; }
Time_label()
string Export_Files::Header::Time_label ()
Definition at line 522 of file export.cpp.
References time.
 { return time; }
Title_conv()
float Export_Files::Header::Title_conv ()
Definition at line 521 of file export.cpp.
References titleC.
 { return titleC; }
Title_label()
string Export_Files::Header::Title_label ()
Definition at line 520 of file export.cpp.
References title.
 { return title; }
units()
string Export_Files::Header::units (const size_t i)
Definition at line 516 of file export.cpp.
References xyz_axis.
{
     return xyz_axis[i].units;
 }
Field Documentation
oDir
string Export_Files::Header::oDir private
Definition at line 167 of file export.h.
Referenced by Directory().
time
string Export_Files::Header::time private
Definition at line 165 of file export.h.
Referenced by Export_Files::Xport::hinit_attr(), Export_Files::Xport::hinit_attr2(), and Time_label().
timeC
float Export_Files::Header::timeC private
Definition at line 166 of file export.h.
Referenced by Time_conv().
timeU
string Export_Files::Header::timeU private
Definition at line 165 of file export.h.
title
string Export_Files::Header::title private
Definition at line 165 of file export.h.
Referenced by Title_label().
titleC
float Export_Files::Header::titleC private
Definition at line 166 of file export.h.
Referenced by Title_conv().
xyz_axis
vector< oAxis > Export_Files::Header::xyz_axis private
Definition at line 164 of file export.h.
Referenced by axis(), dim(), Header(), label(), and units().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/export.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/export.cpp