OSHUN: Spatial_Advection_1D_f1 Class Reference
Spatial_Advection_1D_f1 Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov_f1.h>
Public Member Functions
Spatial_Advection_1D_f1 (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
void operator() (const DistFunc1D &Din, DistFunc1D &Dh)
Private Attributes
SHarmonic1D fd1
valarray< complex< double > > vr
complex< double > A00
complex< double > A10
complex< double > A20
Detailed Description
Definition at line 20 of file vlasov_f1.h.
Constructor & Destructor Documentation
Spatial_Advection_1D_f1()
Spatial_Advection_1D_f1::Spatial_Advection_1D_f1 (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
Definition at line 573 of file vlasov_f1.cpp.
References A00, A10, A20, and vr.
Referenced by VlasovFunctor1D_f1_explicitE::VlasovFunctor1D_f1_explicitE(), VlasovFunctor1D_f1_explicitEB::VlasovFunctor1D_f1_explicitEB(), VlasovFunctor1D_f1_implicitE_p1::VlasovFunctor1D_f1_implicitE_p1(), and VlasovFunctor1D_f1_implicitEB_p1::VlasovFunctor1D_f1_implicitEB_p1().
         : fd1(Np,Nx),
           vr(Algorithms::MakeAxis(static_cast<complex<double> >(pmin),
                                   static_cast<complex<double> >(pmax),
                                   Np)) {
 //      - - - - - - - - - - - - - - - - - - - - - - - - - - -
     complex<double> lc, mc;
     for (size_t i(0); i < vr.size(); ++i) {
         vr[i] = vr[i]/(sqrt(1.0+vr[i]*vr[i]));
     }
          double idx = (-1.0) / (2.0*(xmax-xmin)/double(Nx)); // -1/(2dx)
 //       Calculate the "A1, A2" parameters
         A00 = static_cast<complex<double>>(idx);
         A10 = static_cast<complex<double>>(idx/3.0);
         A20 = static_cast<complex<double>>(idx*2.0/5.0);
 }
Member Function Documentation
operator()()
void Spatial_Advection_1D_f1::operator() (const DistFunc1D & Din, DistFunc1D & Dh)
Definition at line 603 of file vlasov_f1.cpp.
References A00, A10, A20, SHarmonic1D::Dx(), fd1, DistFunc1D::mass(), SHarmonic1D::mpaxis(), and vr.
Referenced by VlasovFunctor1D_f1_explicitE::~VlasovFunctor1D_f1_explicitE(), VlasovFunctor1D_f1_explicitEB::~VlasovFunctor1D_f1_explicitEB(), VlasovFunctor1D_f1_implicitE_p1::~VlasovFunctor1D_f1_implicitE_p1(), VlasovFunctor1D_f1_implicitE_p2::~VlasovFunctor1D_f1_implicitE_p2(), and VlasovFunctor1D_f1_implicitEB_p1::~VlasovFunctor1D_f1_implicitEB_p1().
{
 //--------------------------------------------------------------
     valarray<complex<double> > vt(vr); vt *= 1.0/Din.mass();
     fd1 = Din(0,0);
     fd1 = fd1.Dx();     vt *= A00;
     Dh(1,0)+=(fd1.mpaxis(vt));
     fd1 = Din(1,0);
     fd1 = fd1.Dx();     vt *= A10/A00;
     Dh(0,0)+=(fd1.mpaxis(vt));
     fd1 = Din(0,0);     fd1 *= static_cast<complex<double>>(1.0/3.0);
     fd1 = fd1.Dx();     vt *= A20/A10;
     Dh(1,0)+=(fd1.mpaxis(vt));
 }
Field Documentation
A00
complex<double> Spatial_Advection_1D_f1::A00 private
Definition at line 34 of file vlasov_f1.h.
Referenced by operator()(), and Spatial_Advection_1D_f1().
A10
complex<double> Spatial_Advection_1D_f1::A10 private
Definition at line 34 of file vlasov_f1.h.
Referenced by operator()(), and Spatial_Advection_1D_f1().
A20
complex<double> Spatial_Advection_1D_f1::A20 private
Definition at line 34 of file vlasov_f1.h.
Referenced by operator()(), and Spatial_Advection_1D_f1().
fd1
SHarmonic1D Spatial_Advection_1D_f1::fd1 private
Definition at line 31 of file vlasov_f1.h.
Referenced by operator()().
vr
valarray< complex<double> > Spatial_Advection_1D_f1::vr private
Definition at line 33 of file vlasov_f1.h.
Referenced by operator()(), and Spatial_Advection_1D_f1().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.cpp