OSHUN: Magnetic_Field_1D_f1 Class Reference
Magnetic_Field_1D_f1 Class Reference
Vlasov-Fokker-Planck operators in 1D
#include <vlasov_f1.h>
Public Member Functions
Magnetic_Field_1D_f1 (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
void operator() (const DistFunc1D &Din, const Field1D &FBx, const Field1D &FBy, const Field1D &FBz, DistFunc1D &Dh)
void implicit (DistFunc1D &Din, const Field1D &FBx, const Field1D &FBy, const Field1D &FBz, double dt)
Private Attributes
SHarmonic1D FLM
valarray< complex< double > > A1
valarray< complex< double > > B1
Array2D< complex< double > > A2
complex< double > A3
Detailed Description
Definition at line 75 of file vlasov_f1.h.
Constructor & Destructor Documentation
Magnetic_Field_1D_f1()
Magnetic_Field_1D_f1::Magnetic_Field_1D_f1 (size_t Nl, size_t Nm, double pmin, double pmax, size_t Np, double xmin, double xmax, size_t Nx)
Definition at line 298 of file vlasov_f1.cpp.
References A1, A3, and B1.
         : A1(Nm+1), B1(Nl+1), A2(Nl+1,Nm+1), A3(0.5),
           FLM(Np,Nx)
 {
 //      - - - - - - - - - - - - - - - - - - - - - - - - - - -
     complex<double> lc, mc;
     complex<double> c01(0.0,1.0);
 //       Calculate the "A1" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t m(0); m < Nm+1; ++m){
         mc = static_cast< complex<double> >(m);
         A1[m] = (-1.0)*c01*mc;
     }
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "A2" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     // for (size_t l(1); l < Nl+1; ++l)
     //     for (size_t m=0; m<((Nm<l)?Nm:l)+1; ++m){
     //         lc = static_cast< complex<double> >(l);
     //         mc = static_cast< complex<double> >(m);
     //         A2(l,m) = (-0.5)*(lc+1.0-mc)*(lc+mc);
     //     }
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "A3" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     A3 = 0.5;
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //       Calculate the "B1" parameters
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
     for (size_t l(0); l < Nl+1; ++l){
         lc = static_cast< complex<double> >(l);
         B1[l] = (-1.0)*lc*(lc+1.0);
     }
 //       - - - - - - - - - - - - - - - - - - - - - - - - - - -
 }
Member Function Documentation
implicit()
void Magnetic_Field_1D_f1::implicit (DistFunc1D & Din, const Field1D & FBx, const Field1D & FBy, const Field1D & FBz, double dt)
Distribution function vector. 1 Nmx1 vector per momentum cell
Multiply Right Side to create right side vector
Unpack
Definition at line 422 of file vlasov_f1.cpp.
References Field1D::array(), DistFunc1D::q(), and Thomas_Tridiagonal().
{
 //--------------------------------------------------------------
 //  This is the core calculation for the magnetic field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Bx(FBx.array());
     valarray<complex<double> > Bm(FBy.array());
     Bm *= (-1.0)*ii;
     Bm += FBz.array();
     valarray<complex<double> > Bp(FBy.array());
     Bp *= ii;
     Bp += FBz.array();
     Bx *= Din.q();//Din.mass();
     Bm *= Din.q();//Din.mass();
     Bp *= Din.q();//Din.mass();
     size_t l0(1);
     size_t m0(1);
     int Nm(0);
     size_t ind(0);
     size_t indp(0);
     complex<double> temp(0.0,0.0);
     for (size_t i(0); i<Din(0,0).numx(); ++i)
     {
         for (size_t l(1); l < l0+1; ++l)
         {
             Nm = (l<m0?l:m0);
             valarray<complex<double>> fin((0.0,0.0),2*Nm+1);
             valarray<complex<double>> RHSv((0.0,0.0),2*Nm+1);
             Array2D<complex<double>>  LHS(2*Nm+1,2*Nm+1);
             Array2D<complex<double>>  RHS(2*Nm+1,2*Nm+1);
             //* The matrices corresponding to RHS and LHS are computed
             //  They apply to the vector
             //  [ f_l^m  ]          -> 0 index but applies to Nm th harmonic
             //     ...
             //  [ f_l^2  ]
             //  [ f_l^1  ]
             //  [ f_l^0  ]          -> Nm index but applies to 0th harmonic
             //  [ f_l^-1 ]
             //  [ f_l^-2 ]
             //     ...
             //  [ f_l^-m ]          *//
             RHS(0,0)           = 1.0-ii*double(Nm)*dt/2.0*Bx[i];
             LHS(0,0)           = conj(RHS(0,0));
             RHS(0,1)           =  0.25*dt*Bp[i];
             LHS(0,1)           = -0.25*dt*Bp[i];
             for (int m(Nm-1);m>0;--m)
             {
                 ind = Nm-m;
                 RHS(ind,ind)   = 1.0-ii*double(m)*dt/2.0*Bx[i];
                 LHS(ind,ind)   = conj(RHS(ind,ind));
                 RHS(ind,ind+1) =  0.25*dt*Bp[i];
                 LHS(ind,ind+1) = -0.25*dt*Bp[i];
                 RHS(ind,ind-1) = -0.25*dt*(l-m)*(l+m+1)*Bm[i];
                 LHS(ind,ind-1) =  0.25*dt*(l-m)*(l+m+1)*Bm[i];
             }
             RHS(Nm,Nm)         = 1.0;
             LHS(Nm,Nm)         = 1.0;
             RHS(Nm,Nm-1)       = -0.25*dt*(l)*(l+1)*Bm[i];
             LHS(Nm,Nm-1)       =  0.25*dt*(l)*(l+1)*Bm[i];
             //* Fill in bottom half which is a series of reflections and complex conjugates
             RHS(Nm,Nm+1)       = conj(RHS(Nm,Nm-1));
             LHS(Nm,Nm+1)       = conj(LHS(Nm,Nm-1));
             for (int m(-1);m>-Nm;--m)
             {
                 ind  = Nm-m;
                 indp = Nm-abs(m);
                 RHS(ind,ind)   = conj(RHS(indp,indp));
                 LHS(ind,ind)   = conj(LHS(indp,indp));
                 RHS(ind,ind+1) = conj(RHS(indp,indp-1));
                 LHS(ind,ind+1) = conj(LHS(indp,indp-1));
                 RHS(ind,ind-1) = conj(RHS(indp,indp+1));
                 LHS(ind,ind-1) = conj(LHS(indp,indp+1));
             }
             RHS(2*Nm,2*Nm)     = conj(RHS(0,0));
             LHS(2*Nm,2*Nm)     = conj(LHS(0,0));
             RHS(2*Nm,2*Nm-1)   = conj(RHS(0,1));
             LHS(2*Nm,2*Nm-1)   = conj(LHS(0,1));
             for (size_t k(0); k < Din(0,0).nump(); ++k) {
                 fin[0] = Din(l, Nm)(k, i);
                 for (int m(Nm - 1); m > 1; --m) {
                     ind = Nm - m;
                     fin[ind] = Din(l, m)(k, i);
                 }
                 fin[Nm] = Din(l, 0)(k, i);
                 for (int m(-1); m > -Nm; --m) {
                     ind = Nm - m;
                     fin[ind] = conj(Din(l, abs(m))(k, i));
                 }
                 fin[2 * Nm] = conj(Din(l, Nm)(k, i));
                 RHSv[0] = fin[0] * RHS(0, 0) + fin[1] * RHS(0, 1);
                 for (size_t mm(1); mm < 2 * Nm; ++mm) {
                     RHSv[mm] = fin[mm - 1] * RHS(mm, mm - 1) + fin[mm] * RHS(mm, mm) + fin[mm + 1] * RHS(mm, mm + 1);
                 }
                 RHSv[2 * Nm] = fin[2 * Nm - 1] * RHS(2 * Nm, 2 * Nm - 1) + fin[2 * Nm] * RHS(2 * Nm, 2 * Nm);
 //                std::cout << "\n\n LHS = \n";
 //                for (size_t i(0); i < LHS.dim1(); ++i) {
 //                    std::cout << "i = " << i << " :::: ";
 //                    for (size_t j(0); j < LHS.dim2(); ++j) {
 //                        std::cout << LHS(i, j) << "   ";
 //                    }
 //                    std::cout << "\n";
 //                }
                 Thomas_Tridiagonal(LHS,RHSv,fin);
                 Din(l,Nm)(k,i)     = fin[0];
                 for (int m(Nm-1);m>1;--m)
                 {
                     ind = Nm-m;
                     Din(l,m)(k,i)  = fin[ind];
                 }
                 Din(l,0)(k,i)     = fin[Nm];
             }
         }
     }
 }
operator()()
void Magnetic_Field_1D_f1::operator() (const DistFunc1D & Din, const Field1D & FBx, const Field1D & FBy, const Field1D & FBz, DistFunc1D & Dh)
Definition at line 347 of file vlasov_f1.cpp.
References A1, A3, Field1D::array(), B1, FLM, SHarmonic1D::mxaxis(), DistFunc1D::q(), and SHarmonic1D::Re().
{
 //--------------------------------------------------------------
 //  This is the core calculation for the magnetic field
 //--------------------------------------------------------------
     complex<double> ii(0.0,1.0);
     valarray<complex<double> > Bx(FBx.array());
     valarray<complex<double> > Bm(FBy.array());
     Bm *= (-1.0)*ii;
     Bm += FBz.array();
     valarray<complex<double> > Bp(FBy.array());
     Bp *= ii;
     Bp += FBz.array();
     Bx *= Din.q();
     Bm *= Din.q();
     Bp *= Din.q();
     size_t l0(B1.size()-1);
     size_t m0(A1.size()-1);
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 0, 1 < l < l0+1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     Bp *= A3;
     for (size_t l(1); l < l0+1; ++l){
         FLM = Din(l,0);      Dh(l,1) += FLM.mxaxis(Bp);
     }
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //      m = 1, l = 1
 // - - - - - - - - - - - - - - - - - - - - - - - - - - -
     FLM = Din(1,1); Bx *= A1[1];                           Dh(1,1) += FLM.mxaxis(Bx);
     FLM = Din(1,1); Bm *= B1[1]; FLM = FLM.mxaxis(Bm);     Dh(1,0) += FLM.Re();
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // //      m = 1, l > 1
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     for (size_t l(2); l < l0+1; ++l){
 //         FLM = Din(l,1);                                                Dh(l,2) += FLM.mxaxis(Bp);
 //         FLM = Din(l,1);                                                Dh(l,1) += FLM.mxaxis(Bx);
 //         FLM = Din(l,1); Bm *= B1[l]/B1[l-1]; FLM = FLM.mxaxis(Bm); Dh(l,0) += FLM.Re();
 //     }
 //     Bm *= 1.0/B1[l0];
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // //      m > 1, l = m
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     for (size_t m(2); m < m0; ++m){
 //         FLM = Din(m,m); Bx *= A1[m]/A1[m-1];                   Dh(m,m  ) += FLM.mxaxis(Bx);
 //         FLM = Din(m,m); Bm *= A2(m,m);                         Dh(m,m-1) += FLM.mxaxis(Bm);
 //         for (size_t l(m+1); l < l0+1; ++l){
 //             FLM = Din(l,m);                                    Dh(l,m+1) += FLM.mxaxis(Bp);
 //             FLM = Din(l,m);                                    Dh(l,m  ) += FLM.mxaxis(Bx);
 //             FLM = Din(l,m); Bm *= A2(l,m)/A2(l-1,m);           Dh(l,m-1) += FLM.mxaxis(Bm);
 //         }
 //         Bm *= 1.0/A2(l0,m);
 //     }
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // //      m = m0, l >= m0
 // // - - - - - - - - - - - - - - - - - - - - - - - - - - -
 //     FLM = Din(m0,m0); Bx *= A1[m0]/A1[m0-1];                   Dh(m0,m0)   += FLM.mxaxis(Bx);
 //     FLM = Din(m0,m0); Bm *= A2(m0,m0)/*/A2(l0,m0-1)*/;             Dh(m0,m0-1) += FLM.mxaxis(Bm);
 //     for (size_t l(m0+1); l < l0+1; ++l){
 //         FLM = Din(l,m0);                                     Dh(l,m0  )  += FLM.mxaxis(Bx);
 //         FLM = Din(l,m0); Bm *= A2(l,m0)/A2(l-1,m0);          Dh(l,m0-1)  += FLM.mxaxis(Bm);
 //     }
 }
Field Documentation
A1
valarray< complex<double> > Magnetic_Field_1D_f1::A1 private
Definition at line 94 of file vlasov_f1.h.
Referenced by Magnetic_Field_1D_f1(), and operator()().
A2
Array2D< complex<double> > Magnetic_Field_1D_f1::A2 private
Definition at line 95 of file vlasov_f1.h.
A3
complex<double> Magnetic_Field_1D_f1::A3 private
Definition at line 96 of file vlasov_f1.h.
Referenced by Magnetic_Field_1D_f1(), and operator()().
B1
valarray< complex<double> > Magnetic_Field_1D_f1::B1 private
Definition at line 94 of file vlasov_f1.h.
Referenced by Magnetic_Field_1D_f1(), and operator()().
FLM
SHarmonic1D Magnetic_Field_1D_f1::FLM private
Definition at line 92 of file vlasov_f1.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.h
/Users/archis/Dropbox/work/dev/oshun/oshun-OS/OSHUN/1d_cpp/source/vlasov_f1.cpp